### PR TITLE
Fix renaming extension key name in Database Settings

### LINKED ISSUE #11353: Renaming browser extension keys removes "Created" datetime
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

image

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Pick a key and rename it
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Only name changes (maybe "hidden" "updated at" metadata gets updates)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

"Created" datetime gets cleared

## Context
[NOTE]: # ( Give us any additional information you may have. )

I would expect that times are stored in a _unified format_ and they are rendered per-system. It seems that each X writes timestamps differently

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.6 LTS
CPU architecture: x86_64
Kernel: linux 5.15.0-122-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
When renaming a stored connection key for Browser Integration in Database Settings the key for _Created_ timestamp is not renamed. This causes an empty value to be shown for the renamed key. Also removes the _Created_ key when deleting stored key.

Introduces a static method `CustomData::getKeyWithPrefix()` instead of different concatenations in various classes.

Fixes #11353

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -611,7 +611,7 @@ QString BrowserService::storeKey(const QString& key)
 
     hideWindow();
     db->metadata()->customData()->set(CustomData::BrowserKeyPrefix + id, key);
-    db->metadata()->customData()->set(QString("%1_%2").arg(CustomData::Created, id),
+    db->metadata()->customData()->set(QString("%1%2").arg(CustomData::Created, id),
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp]: This is re-implementing `getKeyWithPrefix`, any way to use that function or make that more "central"? I almost think that should be a static function of  `CustomData`.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/browser/BrowserService.cpp (hunk 1 above)
Comment (varjolintu) [reply src/browser/BrowserService.cpp]: I was thinking about that too. Let me check if we use similar kind of prefix inserting elsewhere too.

**Comment by varjolintu** [comment]
Fixed.

**Review by droidmonkey — APPROVED** [review]
