### PR TITLE
Move socket into separate directory

### LINKED ISSUE #8018: Move socket into separate directory for sandbox friendliness
I'm trying to set up the browser plugin to talk to a locally running KeePassXC instance. I run the browser in a local sandbox so that it doesn't have unrestricted access to the entire system using Firejail (though the topic described here probably affects any sandboxing mechanism).

From what I understand, communication happens via a socket named `org.keepassxc.KeePassXC.BrowserServer` placed directly in `$XDG_RUNTIME_DIR`.

If I configure the browser's sandbox to have access to this file, it will only work if the file exists _before_ the browser is started. If the file does not exist when the browser is started, there is nothing to mount inside its filesystem namespace. Exposing individual files to sandboxes is tricky, and especially sockets. Usually, sockets are placed inside a dedicated directory, since exposing _that_ directory to the sandbox is less problematic.

A common workaround seems to have been to grant the browser access to the entirety of `$XDG_RUNTIME_DIR`, but this exposes a huge attack surface to the browser, granting it access to lot of very sensitive sockets.

## Expected Behavior

I can configure a sandboxed browser to talk to KeePassXC.

## Current Behavior

There's no obvious way to connect the browser plugin to keepass while keeping the browser sandboxed.

## Possible Solution

Move the socket into `$XDG_RUNTIME_DIR/org.keepassxc.KeePassXC.BrowserServer/sock`. This means that the `$XDG_RUNTIME_DIR/org.keepassxc.KeePassXC.BrowserServer/` directory can be exposed to browser sandboxes, and the plugin would be able to talk to keepass regardless of the order in which applications were started.

This directory can be created by either `keepass-proxy` itself, or by the sandbox running the browser (e.g.: Firejail, Flatpak); it doesn't matter which. That's what makes the change work; whichever of both processes run first can create the directory.

## Steps to Reproduce (for bugs)

Run Firefox with Firejail and try to set up the extension.

## Debug info

KeePassXC 2.71.
KeePassXC-Browser 1.7.12
Operating system: Linux
Browser: Firefox (but probably affects all browsers)

### PR DESCRIPTION
**Pull request by WhyNotHugo**
This is mostly to ease setup and configuration with sandboxed browsers.

The socket currently existing in `$XDG_RUNTIME_DIR`. When sandboxing a
browser, it would be unsafe to mount this directory inside the sandbox.
Mounting the socket into the sandbox's filesystem is also not possible
in cases where KeePassXC is [re]started after the browser has started.

This commit moves the socket into its own isolated subdirectory, which
can be safely mounted into sandboxes. Sandbox engines can create the
directory themselves (in case the browser starts before KeePassXC). Both
Flatpak and Firejail support this configuration.

A symlink is also created, linking the previous location to the new
location. This is meant for backwards compatibility and should
eventually be dropped.

The directory can't be named `org.keepassxc.KeePassXC.BrowserServer`,
since that would collide with the symlink. Instead, the directory has
been created to match the format used for Flatpak builds, which make it
a bit less of a snowflake build, while following accepted conventions.

Fixes: https://github.com/keepassxreboot/keepassxc/issues/8018

### Backwards compatibility

Try using browser integration on an existing, working, setup. It should all work without any issues.

### For sandboxed applications

See https://github.com/keepassxreboot/keepassxc/discussions/6741#discussioncomment-1154242, without tampering with `keepassxc.local`.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ New feature (change that adds functionality)

## Notes

It might make sense to drop this bit, since now it matches the default behaviour: https://github.com/keepassxreboot/keepassxc/blob/736517f4553b443a74a420ef421b7c62695e6462/src/browser/BrowserShared.cpp#L35-L37

Not sure if it's fine to do this on the PR of it it's best to do that separately.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Nice!

**Comment by WhyNotHugo** [comment]
Squashed follow-up commits. Formatting issues are all fixed. Ready for review/feedback.

**Comment by droidmonkey** [comment]
Interesting, our code format check seems to be broken @phoerious. We shouldn't be passing when there are if statements without { } blocks.

File: src/browser/BrowserShared.cpp [hunk 1]
```diff
@@ -35,10 +36,25 @@ namespace BrowserShared
...
                + serverName;
 #elif defined(Q_OS_UNIX) && !defined(Q_OS_MACOS)
-        // Use XDG_RUNTIME_DIR instead of /tmp if it's available
-        QString path = QStandardPaths::writableLocation(QStandardPaths::RuntimeLocation);
-        return path.isEmpty() ? QStandardPaths::writableLocation(QStandardPaths::TempLocation) + serverName
-                              : path + serverName;
+        // Use XDG_RUNTIME_DIR if available, else use /tmp.
+        QString xdgRuntimePath = QStandardPaths::writableLocation(QStandardPaths::RuntimeLocation);
+        if (xdgRuntimePath.isEmpty())
+            return QStandardPaths::writableLocation(QStandardPaths::TempLocation) + serverName;
```
Comment (droidmonkey) [inline src/browser/BrowserShared.cpp]: Besides wrapping this in { }, we should prefer the dedicated directory within the temp dir as well. Actually this would probably be better written as:
```
if (xdgRuntimePath.isEmpty()) {
    xdgRuntimePath = QStandardPaths::writableLocation(QStandardPaths::TempLocation);
}
```
Then let the rest of the function proceed as normal.

File: src/browser/BrowserShared.cpp [hunk 2]
```diff
@@ -35,10 +36,25 @@ namespace BrowserShared
...
+
+        QDir xdgRuntimeDir = QDir(xdgRuntimePath);
+
+        // Put the socket in a dedicated directory.
+        // This directory will be easily mountable by sandbox containers.
+        QDir socketDir = xdgRuntimeDir.filePath("app/org.keepassxc.KeePassXC");
```
Comment (droidmonkey) [inline src/browser/BrowserShared.cpp]: is the "app" directory a standard? Why not just use the fully qualified reverse domain?

File: src/browser/BrowserShared.cpp [hunk 3]
```diff
@@ -35,10 +36,25 @@ namespace BrowserShared
...
-        // Use XDG_RUNTIME_DIR instead of /tmp if it's available
-        QString path = QStandardPaths::writableLocation(QStandardPaths::RuntimeLocation);
-        return path.isEmpty() ? QStandardPaths::writableLocation(QStandardPaths::TempLocation) + serverName
-                              : path + serverName;
+        // Use XDG_RUNTIME_DIR if available, else use /tmp.
+        QString xdgRuntimePath = QStandardPaths::writableLocation(QStandardPaths::RuntimeLocation);
+        if (xdgRuntimePath.isEmpty())
+            return QStandardPaths::writableLocation(QStandardPaths::TempLocation) + serverName;
+
+        QDir xdgRuntimeDir = QDir(xdgRuntimePath);
```
Comment (droidmonkey) [inline src/browser/BrowserShared.cpp]: You don't need this variable. Just create the socketDir variable directly using `QDir(xdgRuntimePath + "/app/org.keepassxc.KeePassXC")`

File: src/browser/BrowserShared.cpp [hunk 4]
```diff
@@ -35,10 +36,25 @@ namespace BrowserShared
...
+
+        // Put the socket in a dedicated directory.
+        // This directory will be easily mountable by sandbox containers.
+        QDir socketDir = xdgRuntimeDir.filePath("app/org.keepassxc.KeePassXC");
+        if (!socketDir.exists())
+            xdgRuntimeDir.mkpath("app/org.keepassxc.KeePassXC");
```
Comment (droidmonkey) [inline src/browser/BrowserShared.cpp]: same, use `socketDir.mkPath({})`. No need to check for existence, the function does that for you and returns true if it exists.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/browser/BrowserShared.cpp (hunk 2 above)
Comment (WhyNotHugo) [reply src/browser/BrowserShared.cpp]: I noticed that Flatpak used it, and it seemed sensible to align with it. But I don't think it's actually a "standard" thing outside of Flatpak. I can drop `app/` if you wan't; I'm fine either way.

Comment (droidmonkey) [reply src/browser/BrowserShared.cpp]: good point, in fact we can get rid of the flatpak special case with this change, perhaps wrap the symlink part with a #ifndef KEEPASSXC_DIST_FLATPAK

**Comment by WhyNotHugo** [comment]
Looking at the [logs for the build](https://ci.keepassxc.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=212571&_focus=1247), I noticed this:

> [13:52:59][Step 3/4] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-keepassxc'

It turns out that [if `XDG_RUNTIME_DIR` is unset, then `QStandardsPaths::RuntimeLocation` returns fallback a path in `/tmp`](https://github.com/qt/qtbase/blob/ce0d7477a91d73a642bf1f3b34eb7e89f4dfab9e/src/corelib/io/qstandardpaths_unix.cpp#L256-L277). This implies that it only returns empty if a path inside `/tmp` was unusable, so the fallback code that's already present in `src/browser/BrowserShared.cpp` is wrong, since it'll try to use `/tmp` in cases when `/tmp` is unusable.

The fallback should be dropped. It's clear that nobody is relying on this fallback for the extension tho, because, unless I'm missing something, it cannot work.

Edit: implemented in https://github.com/keepassxreboot/keepassxc/pull/8030/commits/a455ee49bd4663d0f041a25dcd676fe0479f9b2b

---

That aside, I've no idea why the Ubuntu build is failing. Is this a fluke? I'll try to re-trigger CI and see if it passes.

Edit: it passed.

**Comment by droidmonkey** [comment]
Agree the fallback is silly. Perhaps we can issue a warning to the console if the socket cannot be created.

**Comment by WhyNotHugo** [comment]
> Agree the fallback is silly. Perhaps we can issue a warning to the console if the socket cannot be created.

Can we address it separately? I'm not really sure how to do that, and I think this PR is ready as-is.

**Comment by droidmonkey** [comment]
Yah no worries

File: src/browser/BrowserShared.cpp (hunk 1 above)
Comment (WhyNotHugo) [reply src/browser/BrowserShared.cpp]: Done in afe8f5bed971469bc609428817453226e8bf3d9e.

File: src/browser/BrowserShared.cpp (hunk 2 above)
Comment (WhyNotHugo) [reply src/browser/BrowserShared.cpp]: Also done. Not sure if the formatting is correct for nested `#elif`... seems a bit ambiguous. Lemme know if it needs to be different.

File: src/browser/BrowserShared.cpp (hunk 3 above)
Comment (WhyNotHugo) [reply src/browser/BrowserShared.cpp]: Done.

**Comment by droidmonkey** [comment]
I'll be looking at prs later this week

File: src/browser/BrowserShared.cpp [hunk 5]
```diff
@@ -31,14 +32,22 @@ namespace BrowserShared
         const auto serverName = QStringLiteral("/org.keepassxc.KeePassXC.BrowserServer");
 #if defined(KEEPASSXC_DIST_SNAP)
         return QProcessEnvironment::systemEnvironment().value("SNAP_USER_COMMON") + serverName;
-#elif defined(KEEPASSXC_DIST_FLATPAK)
-        return QStandardPaths::writableLocation(QStandardPaths::RuntimeLocation) + "/app/" + "org.keepassxc.KeePassXC"
-               + serverName;
 #elif defined(Q_OS_UNIX) && !defined(Q_OS_MACOS)
-        // Use XDG_RUNTIME_DIR instead of /tmp if it's available
+        // This returns XDG_RUNTIME_DIR or else a temporary subdirectory.
         QString path = QStandardPaths::writableLocation(QStandardPaths::RuntimeLocation);
```
Comment (droidmonkey) [inline src/browser/BrowserShared.cpp:37]: Need to append a '/' to this variable otherwise the symlink will fail.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/browser/BrowserShared.cpp [hunk 6]
```diff
@@ -31,14 +32,22 @@ namespace BrowserShared
...
-        return path.isEmpty() ? QStandardPaths::writableLocation(QStandardPaths::TempLocation) + serverName
-                              : path + serverName;
+
+        // Put the socket in a dedicated directory.
+        // This directory will be easily mountable by sandbox containers.
+        QString subPath = path + "/app/org.keepassxc.KeePassXC/";
```
Comment (droidmonkey) [inline src/browser/BrowserShared.cpp:41]: Once you append the trailing slash above, you can drop it from the start of this string.

File: src/browser/BrowserShared.cpp (hunk 5 above)
Comment (WhyNotHugo) [reply src/browser/BrowserShared.cpp:37]: When creating the symlink `path` is concatenated to `serverName`, and `serverName` has a leading slash.

File: src/browser/BrowserShared.cpp (hunk 6 above)
Comment (WhyNotHugo) [reply src/browser/BrowserShared.cpp:41]: Given that `serverName` has a leading slash, I followed suit here and did the same. Otherwise all the concatenations get muddier.

File: src/browser/BrowserShared.cpp (hunk 5 above)
Comment (droidmonkey) [reply src/browser/BrowserShared.cpp:37]: It sure does! I hang my head in the deepest shame

**Review by droidmonkey — APPROVED** [review]

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by WhyNotHugo** [comment]
Hmmm, the directory is created with permission 755, but keepass refuses to create the socket due to directory permissions (requires them to be 700).

I'm not that familiar with Qt, can we change `mkdir` so that is uses 0700, or should I just add a `chmod`?

**Comment by droidmonkey** [comment]
Use https://doc.qt.io/qt-5/qfileinfo.html#permission

**Comment by WhyNotHugo** [comment]
Oh, never mind. I was running in a sandbox and the permissions of `$XDG_RUNTIME_DIR` were wrong. Nothing to be fixed here, my bad.
