### PR TITLE
Both slots on Yubikey are now polled for challenge/response

### LINKED ISSUE #1045: Only 1 slot is detected for Yubikey challenge-response
## Expected Behavior

Two or more slots are configured for HMAC Challenge-Response. Those slots are shown in the drop down selection in the unlock database dialog.

## Current Behavior

One slot is randomly shown.

## Possible Solution

Reimplement how the YubiKey::detect() function works.

## Steps to Reproduce (for bugs)

1. Configure a yubikey with more than 1 slot as HMAC Challenge-Response
2. Attempt to use this yubikey in KeePassXC

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

Fixes #1045 

The previous implementation bailed after finding the first slot that was configured for challenge/response. In order to overcome some threading interchanges and Yubikey limitations the implementation was expanded to be far more robust.

Also, yubikey signals are disconnected from all the unlock widgets when they are hidden. The previous behavior caused all created unlock widgets (about 4-5 per open database) to be updated when the yubikey was polled.

## How has this been tested?

Manually with Yubikey Neo

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/DatabaseOpenWidget.cpp [hunk 1]
```diff
@@ -296,6 +303,14 @@ void DatabaseOpenWidget::yubikeyDetected(int slot, bool blocking)
     }
 }
 
+void DatabaseOpenWidget::yubikeyDetectComplete()
```
Comment (louib) [inline src/gui/DatabaseOpenWidget.cpp]: @droidmonkey just a nitpick : why not `yubikeyDetectionCompleted`? Would be coherent with the style of the other event handlers.

File: src/keys/drivers/YubiKey.cpp [hunk 2]
```diff
@@ -112,23 +113,36 @@ bool YubiKey::deinit()
...
-        for (int i = 1; i < 3; i++) {
-            YubiKey::ChallengeResult result;
-            QByteArray rand = randomGen()->randomArray(1);
-            QByteArray resp;
+        YubiKey::ChallengeResult result;
+        QByteArray rand = randomGen()->randomArray(1);
+        QByteArray resp;
 
+        // Check slot 1 and 2 for Challenge-Response HMAC capability
+        for (int i=1; i <= 2; ++ i) {
```
Comment (louib) [inline src/keys/drivers/YubiKey.cpp]: @droidmonkey spaces around `=`, and no spaces after `++`

Comment (droidmonkey) [reply src/keys/drivers/YubiKey.cpp]: This was clearly done by an amateur with questionable spacebar control. I'll fix it right quick :wink:
