### PR TITLE
CLI Cleanup and Improvements

### LINKED ISSUE #6001: CLI Add/Edit commands define -n twice
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The first definition is for added/editing notes, the second definition is for using numbers in the password generator. Recommend moving notes to just `--notes`.

### LINKED ISSUE #6119: `keepassxc-cli clip` problem pasting specific character
# version

5.10.15-arch1-1 x86_64 GNU/Linux
keepassxc 2.6.4-1
xclip 0.13-3

# problem

for any entry containing the pound sign **£** (hexa-decimal: A3), pasting from clipboard after having used `keepassxc-cli clip` outputs binary data instead of plain text.

# notes

- in the GUI, selecting the entry and pressing <Ctrl+C> does not produce the same issue
- autotype does not have any problem with **£**
- there might be other characters behaving similarly, I apologize if I haven't tried to find them

### LINKED ISSUE #6128: Set default timeout of keepassxc-cli 'clip' to 10 seconds
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
keepassxc-cli: 'clip' is not automatically cleared after N seconds

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. keepassxc-cli open /tmp/testdb
2. clip "test entry"
3. Cmd->V see that Past Works.
4. wait 15sec or more
5. Cmd->V see that Past still Works.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
.After 15sec or more
Clipboard should be auto cleared like in the GUI.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I can past long after the 
clip "test entry"

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.2
CPU architecture: x86_64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

### PR DESCRIPTION
**Pull request by droidmonkey**
**Cleanup CLI includes across all components**
* Remove unused include files
* Move includes out of widely shared headers (reduced rebuild time)
* Consolidate code for Analyze command

**CLI Improvements**
* Fix #6001 - only use `--notes` in Add/Edit commands to prevent clash with password generator option `-n`.

* Fix #6119 - Send UTF-8 to clip command

* Fix #6128 - `clip` command will default to clearing the clipboard after 10 seconds. To disable clearing set timeout to 0.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ Refactor (significant modification to existing code)

### CODE REVIEW

File: src/cli/Clip.cpp [hunk 1]
```diff
@@ -65,13 +61,18 @@ int Clip::executeWithDatabase(QSharedPointer<Database> database, QSharedPointer<
     auto& err = Utils::STDERR;
 
     const QStringList args = parser->positionalArguments();
-    QString bestEntryPath;
 
-    QString timeout;
+    auto timeout = 10;
```
Comment (louib) [inline src/cli/Clip.cpp:65]: @droidmonkey might be worth it to extract that as a `DEFAULT_TIMEOUT` constant

File: src/cli/keepassxc-cli.cpp [hunk 2]
```diff
@@ -179,7 +172,7 @@ void enterInteractiveMode(const QStringList& arguments)
 int main(int argc, char** argv)
 {
     if (!Crypto::init()) {
-        qFatal("Fatal error while testing the cryptographic functions:\n%s", qPrintable(Crypto::errorString()));
+        qWarning("Fatal error while testing the cryptographic functions:\n%s", qPrintable(Crypto::errorString()));
```
Comment (louib) [inline src/cli/keepassxc-cli.cpp:175]: @droidmonkey why warning here? That seems to be at least an error to me.

File: tests/TestCli.cpp [hunk 3]
```diff
@@ -511,35 +505,31 @@ void TestCli::testClip()
...
-    setInput("a");
-    execCmd(clipCmd, {"clip", m_dbFile->fileName(), "--totp", "/Sample Entry", "0"});
-    QVERIFY(m_stderr->readAll().contains("Invalid timeout value 0.\n"));
-
     setInput("a");
     execCmd(clipCmd, {"clip", m_dbFile->fileName(), "--totp", "/Sample Entry", "bleuh"});
     QVERIFY(m_stderr->readAll().contains("Invalid timeout value bleuh.\n"));
 
     setInput("a");
-    execCmd(clipCmd, {"clip", m_dbFile2->fileName(), "--totp", "/Sample Entry"});
```
Comment (louib) [inline tests/TestCli.cpp:523]: @droidmonkey do we already have a unit test for the `clip` command and unicode in the password (characters with multiple graphemes)?

**Review by louib — COMMENTED** [review]
Nice cleanup! Added a few comments.

File: src/cli/keepassxc-cli.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/cli/keepassxc-cli.cpp:175]: We return fatal, qfatal causes an assert which blocks the return in debug builds.

File: tests/TestCli.cpp (hunk 3 above)
Comment (droidmonkey) [reply tests/TestCli.cpp:523]: Need to add that

Comment (droidmonkey) [reply tests/TestCli.cpp:523]: @louib troubling, but not surprising, on Windows clip.exe cannot take UTF-8 input....

Comment (louib) [reply tests/TestCli.cpp:523]: Maybe we could test it only on Linux and Mac

**Comment by droidmonkey** [comment]
Copying unicode to clipboard works great now!
image

File: src/cli/Clip.cpp [hunk 4]
```diff
@@ -15,18 +15,14 @@
...
-#include "cli/TextStream.h"
-#include "cli/Utils.h"
-#include "core/Database.h"
+#include "Utils.h"
 #include "core/Entry.h"
-#include "core/Global.h"
 #include "core/Group.h"
+#include "core/Tools.h"
+
+#define DEFAULT_TIMEOUT 10
```
Comment (louib) [inline src/cli/Clip.cpp:25]: @droidmonkey since this is going to be global, maybe we can give it a more explicit name, like `DEFAULT_CLIP_TIMEOUT`

File: src/cli/Clip.cpp [hunk 5]
```diff
@@ -56,7 +52,9 @@ Clip::Clip()
     positionalArguments.append(
         {QString("entry"), QObject::tr("Path of the entry to clip.", "clip = copy to clipboard"), QString("")});
     optionalArguments.append(
-        {QString("timeout"), QObject::tr("Timeout in seconds before clearing the clipboard."), QString("[timeout]")});
+        {QString("timeout"),
+         QObject::tr("Timeout before clearing the clipboard (default is 10 seconds, set to 0 for unlimited)."),
```
Comment (louib) [inline src/cli/Clip.cpp:56]: @droidmonkey can we use the const value for `10` here?

**Comment by droidmonkey** [comment]
@louib changes are complete, anything else before we merge?

**Comment by louib** [comment]
@droidmonkey any clue why the Windows tests are failing?

**Review by louib — APPROVED** [review]

**Comment by droidmonkey** [comment]
The windows CI machine is borked
