### PR TITLE
Fix theme issues on macOS

### LINKED ISSUE #5025: Edit entry dialog separator (bullet) is rendered as a box with stripes (Mojave)
## Overview

As requested in #4110 by @phoerious.

## Steps to Reproduce
1. Install KeePassXC on macOS Mojave
2. Open database
3. Edit entry

## Expected Behavior

A bullet point being rendered correctly.

## Actual Behavior

Screenshot 2020-07-11 at 10 56 08

## Context

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

### LINKED ISSUE #5307: User Interface Icons with Text - macOS
## Summary
When enabling Icons with Text in Settings (macOS) the text shows in white and icons are black.
This makes text very hard to see and read.

## Context
Difficult to see Text under Icons. It would be good to keep both Icons and Text black color.

### LINKED ISSUE #5347: Transparent login screen & symbol bar [macOS 10.13.6 / KeepassXC 2.6.1]
KeePassXC - 2.6.1
macOS High Sierra 10.13.6

**Bug**
When I start KeePassXC the DB login-screen is completely transparent. After selecting and logging into a database the symbol bar stays transparent. As soon as I resize the window the transparency vanishes and the black background for the symbol bar returns to normal.

**Comment**
I think its an OS Issue. On my macbook with the newest macOS Catalina everything works fine. 
Unfortunately I can't update my desktop computer because of NVIDIA drivers that It need for motion & 3D stuff ;)

**Screenshots**
I attached some screenshots that show the problem. I used a blueish background so you can see where the transparency is visible... The transparency is also saved when I screenshot the programm window on macOS.

keepass_transparent_01
keepass_transparent_02

Cheers

### PR DESCRIPTION
**Pull request by droidmonkey**
* Include new icons for toolbar overflow to ensure they are tinted correctly and fit in with the rest of the UI

* Fixes #5307 
* Fixes #5347 
* Fixes #5025 - use common bullet character in edit entry widget

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
See below comments

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows and macOS

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/styles/dark/DarkStyle.cpp [hunk 1]
```diff
@@ -89,6 +91,18 @@ QPalette DarkStyle::standardPalette() const
     return palette;
 }
 
+QIcon DarkStyle::standardIcon(StandardPixmap sp, const QStyleOption* opt, const QWidget* widget) const
+{
+    switch (sp) {
+    case SP_ToolBarHorizontalExtensionButton:
+        return resources()->icon("chevron-double-down");
+    case SP_ToolBarVerticalExtensionButton:
```
Comment (phoerious) [inline src/gui/styles/dark/DarkStyle.cpp:99]: If this is so embarrassingly simple, shouldn't we be also doing this for other standard icons such as the clear field icon? Right now those are custom actions, because the standard icons are useless.

File: src/gui/styles/dark/DarkStyle.cpp [hunk 2]
```diff
@@ -104,18 +118,11 @@ void DarkStyle::polish(QWidget* widget)
     if (qobject_cast<QMainWindow*>(widget) || qobject_cast<QDialog*>(widget) || qobject_cast<QMenuBar*>(widget)
         || qobject_cast<QToolBar*>(widget)) {
         auto palette = widget->palette();
-#if defined(Q_OS_MACOS)
-        if (osUtils->isDarkMode()) {
-            // Let the Cocoa platform plugin draw its own background
-            palette.setColor(QPalette::All, QPalette::Window, Qt::transparent);
```
Comment (phoerious) [inline src/gui/styles/dark/DarkStyle.cpp:110]: Removing this breaks native theming. You can see that in your screenshot. The gradient is gone and there is a line between window title bar and chrome body.

**Review by phoerious — DISMISSED** [review]

File: src/gui/styles/dark/DarkStyle.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/gui/styles/dark/DarkStyle.cpp:99]: Great point and yes

File: src/gui/styles/dark/DarkStyle.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/gui/styles/dark/DarkStyle.cpp:110]: Then we can only do transparent on Catalina and above

Comment (phoerious) [reply src/gui/styles/dark/DarkStyle.cpp:110]: The way we have it now is that it's transparent if the theme matches and not transparent otherwise. That should take care of older macOS versions, too. The native platform theme does the same trick to let the window chrome shine through. Perhaps they are doing something in addition to fix the flyout background.

Comment (droidmonkey) [reply src/gui/styles/dark/DarkStyle.cpp:110]: This causes the extended toolbar to be transparent and older mac versions to show black background. In general the previous implementation was not good.

**Comment by droidmonkey** [comment]
@phoerious take another look please

**Review by varjolintu — APPROVED** [review]

**Review by phoerious — COMMENTED** [review]
The classic theme will probably have resolution issues with the standard icons again, but I think it's worth it. This gets rid of so much unnecessary code.

The theming code is a bit redundant. Transparency should also work without dark mode available and we only need to check at all if the OS theme doesn't match to avoid a dark toolbar in light mode and vice versa. So isDarkMode and hasDarkMode can probably be merged into one.

**Comment by droidmonkey** [comment]
I just totally disagree with using Qt::transparent in general, but especially on macOS < 10.14. Splitting the isDarkMode and hasDarkMode is necessary to ensure Qt::transparent is not used ever on lower macOS versions.

**Comment by droidmonkey** [comment]
@phoerious I completely removed the transparent logic, there is absolutely no need for it. The colors defined blend perfectly with the title bar of the window. I cannot see any difference when using transparent versus the colors. Transparent brings a host of issues.

**Comment by droidmonkey** [comment]
image

image

**Comment by phoerious** [comment]
There is a seam, which you can see when you zoom in a little and the toolbar looks awkwardly flat.
