### PR TITLE
Cumulative updates to secret service integration

### LINKED ISSUE #4004: KeepassXC not providing Freedesktop.Secrets after lock/unlock of database.
Uppon first opening an applications that tries to access the Freedesktop.Secrets service the user is asked to unlock his database with the following screen:
Screenshot_10 12 19_13:59:15
Password are accesible and everything works, but if you close the application, close the database and reopen the application (Remmina in this case) you are not asked to unlock the database again. Even after manually unlocking the database Remmina will not find any of it's stored secrets, you have to kill keepassxc and start from scratch.

The same behaviour can also be observed with `secret-tool` or `python-keyring`

## Expected Behavior
Ask to unlock the keyring again/resume freedesktop.secrets service after locking/unlocking the database .

## Steps to Reproduce
```
secret-tool store --label='Test' username testuser password testpassword
Password: Testpassword

#Keepassxc asks to unlock the database

libsecret-Message: 16:06:06.692: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Error return with empty body:
secret-tool: Error return with empty body:

secret-tool store --label='Test' username testuser password testpassword
Password: Testpassword
# Works

secret-tool lookup username testuser
Testpassword
# Works

#Lock database

secret-tool lookup username testuser

#Not asked to unlock again
#Manually unlock database

 secret-tool lookup username testuser
# No secrets found...
```

## Context
I'm forced to leave my database constanly unlocked, can't even lock it when I close the session, gnome-keyring had no problem with locking the keyring and asking to reopen it.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.2-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

### PR DESCRIPTION
**Pull request by Aetf**
## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ Refactor (significant modification to existing code)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

This PR contains multiple fixes and refactor. I just think they're not worth separate PRs. But @droidmonkey, if you prefer, I can also do that.

- UI improvements (mostly refactor)
    - Use proper models for database and session in the settings page
    - Fix button text (unlock/lock) not changed according to the database locking status
    - Fix button icons not present on icon themes other than Breeze
    - Fix the disconnect button may get clipped when a new session opens
- Remove half created entries if the creation fails.
- Cleanup all connections when the database is replaced due to locking, fix #4004
- Fix when exposing groups, the root group is considered in recycle bin
- Fix service not registered if starting with the plugin enabled

__Update__: 

(Checking PID for existing services is saved for targeting 2.6.0 due to translation freeze).

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Test manually.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/fdosecrets/objects/Collection.cpp [hunk 1]
```diff
@@ -602,9 +625,10 @@ namespace FdoSecrets
 
     void Collection::cleanupConnections()
     {
-        if (m_exposedGroup) {
-            m_exposedGroup->disconnect(this);
+        while (!m_connections.isEmpty()) {
+            disconnect(m_connections.takeFirst());
         }
```
Comment (droidmonkey) [inline src/fdosecrets/objects/Collection.cpp]: Technically you can just call `disconnect()` to remove all connections to/from this QObject. It's rather robust and avoids having to track all the connections.

File: src/fdosecrets/objects/Service.cpp [hunk 2]
```diff
@@ -58,9 +58,11 @@ namespace FdoSecrets
     bool Service::initialize()
     {
         if (!QDBusConnection::sessionBus().registerService(QStringLiteral(DBUS_SERVICE_SECRET))) {
-            qDebug() << "Another secret service is running";
-            emit error(tr("Failed to register DBus service at %1: another secret service is running.")
-                           .arg(QLatin1Literal(DBUS_SERVICE_SECRET)));
+            auto otherService = m_plugin->runningServiceInfo();
+            emit error(tr("Failed to register DBus service at %1: another secret service is running.<br/>"
+                          "<i>%2</i><br/>"
```
Comment (droidmonkey) [inline src/fdosecrets/objects/Service.cpp]: Don't include this in translation

File: src/fdosecrets/objects/Service.cpp [hunk 3]
```diff
@@ -58,9 +58,11 @@ namespace FdoSecrets
...
+                          "Please stop/remove it before re-enabling the Secret Service Integration.")
```
Comment (droidmonkey) [inline src/fdosecrets/objects/Service.cpp]: Start a new `tr(...)` here

Comment (Aetf) [reply src/fdosecrets/objects/Service.cpp]: So I'm going to save the checking PID to 2.6.0 anyway. But I don't quite get it. Do you mean something like
```
tr("Failed to register DBus service at %1: another secret service is running.<br/>")
+ tr("<i>%2</i><br/>")
+ tr("Please stop/remove it before re-enabling the Secret Service Integration.")
```
What's the benefit over a single `tr(...)` call?

(I'm not objecting. I just want to learn about what's the caveat here)

File: src/fdosecrets/objects/Collection.cpp (hunk 1 above)
Comment (Aetf) [reply src/fdosecrets/objects/Collection.cpp]: In this case, only some of the incoming signals (from `Database`, `Metadata`, `Group`, but not `DatabaseWidget`) need to be disconnected, so I can't use the catch-all `disconnect`.

Without `m_connections`, it will be multiple `otherobject->disconnect(this)` calls with a recursive helper function to disconnect from groups. I find it easy to mismatch what's connected and what's disconnected.

But it's also easy to forget if tracking connections manually. :/ So I don't have a strong opinion on this.

Anyway, since you asked, I'll change to the multiple `otherobject->disconnect(this)` calls version, which at least feels more natural to me.

Comment (Aetf) [reply src/fdosecrets/objects/Collection.cpp]: Just found out `groupsResurcive`. I'll use that.

File: src/fdosecrets/objects/Service.cpp (hunk 3 above)
Comment (droidmonkey) [reply src/fdosecrets/objects/Service.cpp]: Remove the middle `tr(...)`. For this PR the benefit is the initial part of the message will still translate properly. We also want to avoid adding pure fill ins to translate.

Comment (Aetf) [reply src/fdosecrets/objects/Service.cpp]: I see. Thanks for the explanation.

**Comment by Aetf** [comment]
- Address comments
- Remove the checking PID for existing services from this PR. I'll have a separate PR for that targeting `develop`.

**Comment by Aetf** [comment]
Added two more small bug fixes.

**Comment by Aetf** [comment]
Rebased on latest `release/2.5.2`

File: src/fdosecrets/widgets/SettingsModels.cpp [hunk 4]
```diff
@@ -0,0 +1,396 @@
...
+        m_dbs.clear();
+
+        if (m_dbTabs) {
+            // Add existing database tabs
+            for (int idx = 0; idx != m_dbTabs->count(); ++idx) {
+                auto dbWidget = m_dbTabs->databaseWidgetFromIndex(idx);
+                databaseAdded(dbWidget, false);
+            }
+            // connect signals
+            connect(m_dbTabs, &DatabaseTabWidget::databaseOpened, this, [this](DatabaseWidget* db) {
```
Comment (droidmonkey) [inline src/fdosecrets/widgets/SettingsModels.cpp]: I do not like this because it is the exact opposite of how signal/slots should be used. The Settings Model should be created, then the signals connected from the parent. The settings model should have no knowledge of the db tab widget.

I keep it as-is for now, but this would be a good upgrade for 2.6.0 to break some hard dependencies.

Comment (Aetf) [reply src/fdosecrets/widgets/SettingsModels.cpp]: I'll keep that in mind. In general, I'm also thinking about removing dependencies on db tab widget.

(Or even better, don't depend on any GUI classes at all. But that's quite difficult for now, given the db widget is the only one keeping the filename and lock state).

**Comment by Aetf** [comment]
Thanks for reviewing!

File: src/fdosecrets/widgets/SettingsModels.cpp (hunk 4 above)
Comment (droidmonkey) [reply src/fdosecrets/widgets/SettingsModels.cpp]: The filename is located in the Database class. You can determine if its locked by checking to see if it has a key associated with it.

**Comment by Aetf** [comment]
Ah yes. But a locked db is basically a new object. The db widget is still
the one emiting db replaced signal that I need to catch to reconnect
signals on the db.

And btw since we are on the topic, the db tab widget is the only source of
truth about currently opened dbs, is that correct?

**Comment by droidmonkey** [comment]
Yes that is correct
