### PR TITLE
Make the purpose of the key file field clearer

### LINKED ISSUE #3678: HMAC Mismatch after updating from 2.4.3 to 2.5.0
## Expected Behavior
My database should unlock.

## Current Behavior
HMAC Mismatch.

image

## Steps to Reproduce
1. Update KeepassXC from 2.4.3 to 2.5.0
2. Attempt to open your database.

## Context
Updated immediately after starting my computer when the chrome extension told me to update.  
Upon doing so I can no longer log into my database.

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.19008

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

### PR DESCRIPTION
**Pull request by phoerious**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
The new unlock dialogue seems to confuse users as to what the purpose of the key file is. This
patch changes the generic "Select file..." affordance to the more explicit "Select key file (if any)..."
and prevents the user from using the KDBX file as a key file (since that would never work anyway).

The change breaks existing translations on purpose (instead of simply adjusting the en_US locale)
in order to force translators to update this string for their languages.

Resolves #3678

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manual

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/DatabaseOpenWidget.cpp [hunk 1]
```diff
@@ -148,7 +148,7 @@ void DatabaseOpenWidget::load(const QString& filename)
     m_filename = filename;
     m_ui->fileNameLabel->setRawText(m_filename);
 
-    m_ui->comboKeyFile->addItem(tr("Select file..."), -1);
+    m_ui->comboKeyFile->addItem(tr("Select key file (if any)..."), -1);
```
Comment (droidmonkey) [inline src/gui/DatabaseOpenWidget.cpp]: I don't like the (if any) part. It doesn't reduce confusion IMO

Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: Yeah, I don't really like it either, but I thought that writing only "Select key file..." will not be explicit enough and people will still try to put their KDBX in this field.

Comment (hifi) [reply src/gui/DatabaseOpenWidget.cpp]: Would it be too extreme to have all of this hidden behind an "Advanced" arrow that has its state immediately saved to settings file so it persists?

Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: Then just write (this is not your database file)

Comment (hifi) [reply src/gui/DatabaseOpenWidget.cpp]: Or actually because that's likely not a native UI element, a checkbox with "[ ] Use additional security tokens" which acts as a toggle to show/hide the fields?

Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: I don't want to make it too long. Too much text clutter the whole layout too much.

Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: The rejection of kdbx files is sufficient

Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: It's kinda after-the-fact, though. I prefer UIs which do not even tempt the user to do the wrong thing.

Comment (grenzor) [reply src/gui/DatabaseOpenWidget.cpp]: IMO it would be better for "Enter Additional Credentials" line to read "Enter Additional Credentials (Optional)" or "Enter Additional Credentials (if any)" so that it's clearer that both key files/hardware keys aren't required unless set by the user.

Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: Or (Advanced Users)

Comment (schlimmchen) [reply src/gui/DatabaseOpenWidget.cpp]: Adding "(Advanced Users)" is not encouraging inexperienced users to use good practices, i.e., use a keyfile. It puts them off. Even from thinking about using a key file ("I'll never be an advanced user anyways").

I don't like the whole line "Enter Additional Credentials" and I'd remove it completely. But that might be a very personal view and has not too much to do with the issue at hand.

How a about a tooltip-like box, which appears as soon as and while the cursor hovers or moves over the "Browse" button? It would have plenty space to convey to the inexperienced user whether or not a key file must be specified. It would not clutter the unlock dialog GUI layout. It will disrupt inexperienced, cautious users, which it should. Experienced users will soon learn to ignore the box, if they are not saving paths to recent databases and key files anyways, in which case they will hover the "Browse" button only once and (basically) never see the box again.
Screenshot from 2019-11-07 09-47-59

Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: I wouldn't add a tooltip to the browse button. It's too unreliable to trigger and too easily dismissed or overlooked.

I took a few of the suggestions in this thread and combined them into a slightly different solution:

image

TODO: create the key file FAQ entry that opens when the user clicks the help icon.

Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: Note: I did not title-case the (if any), because it looks too ugly.

Comment (hifi) [reply src/gui/DatabaseOpenWidget.cpp]: For reference I imagined a single checkbox that remembers state between startups to toggle the extra fields:

image

As discussed on IRC this is unlikely to be implemented but I wanted it to be part of this thread.
