### PR TITLE
Correct multiple issues with custom icons

### LINKED ISSUE #232: Custom icons duplicated
Custom icons for the same website are added multiple times.

## Expected Behavior
We should at least try to detect duplicates and not fetch the icon multiple times for the same website.

## Current Behavior
Custom icons for the same website are added multiple times.

screen shot 2017-01-27 at 1 09 20 pm

## Steps to Reproduce (for bugs)

1. Add entry with a website
2. Click `Download favicon` multiple times.

## Context
I was trying to reproduce https://github.com/keepassxreboot/keepassxc/issues/225

## Your Environment
* KeePassXC version/commit used: 6409661a9f164cf32a46c5cfc2bf877b97e23512
* Qt version: Qt 5.7.1 
* Operating System and version: MacOS 10.11.16

### LINKED ISSUE #403: crash when switching to favicon
## Expected Behavior
Download favicon, apply it to the entry.

## Current Behavior
Crash when clicking OK.

## Steps to Reproduce (for bugs)
1. Right-click a key entry, select View/Edit, select Icon.
2. Click Download Favicon
3. Click OK.

Do NOT click once on the favicon to select it after it's downloaded.

## Context
KPXC 2.1.3 on Mac OS X 10.12.3. I just started using it today.
The DB is shared via Dropbox.
The DB was made last night, on Windows, using KPXC 2.1.3, from an imported v1 DB made with the old KeePassX (not sure which version, but probably really old, like maybe 0.4). I have not made edits to this DB yet on KPXC. It started with default icons everywhere.

So I've relaunched KPXC, went again into the Icon menu, actually clicked once on the downloaded favicon to select it, clicked OK, and it was fine.

## Your Environment

* KeePassXC version/commit used: 2.1.3
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): no idea, I've installed it from the binary installer
* Operating System and version: Mac OS X 10.12.3

### LINKED ISSUE #904: Increase the dimensions of custom icons from 16x16 to 128x128
What do you guys think about that? [KeePass does it by default](https://github.com/dlech/KeePass2.x/blob/2b20dccd497ccc4c0b5fb83553cac4886c11a076/KeePassLib/PwCustomIcon.cs#L43-L45). `16x16` icons look pixelated when viewing the database on [KeePass2Android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android):

screenshot_20170829-012816

The first and penultimate icons are `16x16`, while all the others are `128x128`.

Thank you.

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

Provides multiple fixes to reported bugs against custom icon loading.

* Fixes #904, icons are saved at or below 128x128 resolution
* Fixes #403, crash occurs due to dialog displayed while not on GUI thread
* Fixes #232, icon hashes are calculated on database load and compared against new downloads

The way I implemented the unique icon hashing ensures that existing databases with multiple unique icons already are not impacted.

## How has this been tested?

Manually with several websites.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/core/Metadata.cpp [hunk 1]
```diff
@@ -415,6 +419,11 @@ void Metadata::removeCustomIcon(const Uuid& uuid)
     Q_ASSERT(!uuid.isNull());
     Q_ASSERT(m_customIcons.contains(uuid));
 
+    // Remove hash record only if this is the same uuid
+    QByteArray hash = hashImage(m_customIcons[uuid]);
+    if (m_customIconsHashes.contains(hash) && m_customIconsHashes[hash] == uuid)
+        m_customIconsHashes.remove(hash);
```
Comment (louib) [inline src/core/Metadata.cpp]: @droidmonkey no braces?

Comment (droidmonkey) [reply src/core/Metadata.cpp]: Noted.

File: src/gui/EditWidgetIcons.cpp [hunk 2]
```diff
@@ -278,22 +272,39 @@ void EditWidgetIcons::addCustomIcon()
...
 }
 
+void EditWidgetIcons::addCustomIcon(const QImage &icon)
+{
+    if (m_database) {
+        Uuid uuid = m_database->metadata()->findCustomIcon(icon);
+        if (uuid.isNull()) {
+            uuid = Uuid::random();
+            // Don't add an icon larger than 128x128, but retain original size if smaller
+            if (icon.width() > 128 || icon.height() > 128)
```
Comment (TheZ3ro) [inline src/gui/EditWidgetIcons.cpp]: Insert bracket
