### PR TITLE
Several UI/UX Fixes

### LINKED ISSUE #9190: Password preview text is partially cut off
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When I unhide a password in the preview pane, the top of the text is cut off.

image

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry with a password
2. In the "General" section of preview pane for that entry, press the eye icon to unhide the password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The password is shown without some portion of the top hidden.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The bottom of the password text is shown without the top of the text.

## Context
[NOTE]: # ( Give us any additional information you may have. )

### System Info
```
OS: Manjaro Linux x86_64 
Kernel: 6.1.12-1-MANJARO 
DE: Xfce 4.18 
WM: Xfwm4 
WM Theme: Matcha-dark-azul 
Theme: Matcha-dark-azul [GTK2/3] 
Icons: Papirus-Maia [GTK2], Adwaita [GTK3] 
```

### KeePassXC Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 6.1.12-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

### Environment Overview
[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

## Thanks Devs & Other Contributors!

I'm quite happy to have such a robust FOSS password storage solution. Thanks to everyone who has put effort into the project!

### LINKED ISSUE #9545: Copy TOTP value in preview pane on double click
## Sum
keepassxc

Add a copy button that allow quickly copy TOTP from this menu

## Examples
image

Add a button here

## Context

It's more clear where to get and copy TOTP code

### LINKED ISSUE #9569: Navigation Panel Resizing at shared Folders
## Overview
If you export (or Import) a .share file and the path for this file is longer than the space for the filepath, the navigation panel gets resized and is not able to be resized to a bigger value.
grafik
grafik
grafik

If you switch to the export folder with long filepath, it resizes to a small navigation panel.
If you switch to the not exported folder, it resizes back to your setting.
If you switch to the export folder with short filepath, it remains correctly sized.

## Steps to Reproduce
1. create a database
2. create a folder to export (long file path)
3. create a folder without export
4. navigate between those two folders

## Expected Behavior
It would be nice, if the width of the navigation panel would stay the same size and the file path is visible as tooltip.
This only seems to be an issue with long file paths.

## Actual Behavior
Keepass resizes the navigation panel, the full path is never readable.

## Context
This happens on switch between exported and not exported folders (i guess it is related to the size of the text-field

KeePassXC - Version 2.7.5
Revision: 9d0537b
Betriebssystem: Windows 11 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22621

### PR DESCRIPTION
**Pull request by droidmonkey**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
* Fixes #9190
* Fixes #9569
* Closes #9545
* Increase fixed font point size on Windows
  * Consolas runs smaller then the default system font. Increasing by 1 point size makes them look equal.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
Example of before/after password preview fix:
image

Example of Consolas +1 point size fix:
image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows and Linux

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/EntryPreviewWidget.cpp [hunk 1]
```diff
@@ -109,6 +113,16 @@ EntryPreviewWidget::EntryPreviewWidget(QWidget* parent)
 
 EntryPreviewWidget::~EntryPreviewWidget() = default;
 
+bool EntryPreviewWidget::eventFilter(QObject* object, QEvent* event)
+{
+    if (object == m_ui->entryTotpLabel && event->type() == QEvent::MouseButtonDblClick) {
+        clipboard()->setText(m_ui->entryTotpLabel->text().remove(" "));
```
Comment (phoerious) [inline src/gui/EntryPreviewWidget.cpp]: I don't like this. There is always the risk of reading in rubbish when you read back stuff from UI elements (famous KDE example where they would randomly add & accelerators everywhere). I suppose the risk is manageable here, but I'd prefer you use the original data source.

Comment (phoerious) [reply src/gui/EntryPreviewWidget.cpp]: Also, what's going on with the Linux CI?

Comment (droidmonkey) [reply src/gui/EntryPreviewWidget.cpp]: Good point, will fix to use entry data directly.

**Review by varjolintu — APPROVED** [review]
