### PR TITLE
Grey out Apply button when there are no changes

### LINKED ISSUE #1181: Unsaved changes in the entry view silently get discarded if escape is pressed
Pressing escape in an entry view after changing the entry or viewing a newly created (unsaved) entry silently discards all changes instead of asking the user weather they want to save the information.

## Expected Behavior
Keepassxc asks if the user wants to discard the unsaved changes.

## Current Behavior
Pressing escape simply closes the entry view thus discarding all changes if apply was not clicked before.

## Possible Solution
I think a simple Discard/Safe/Cancel dialogue would do the trick.

## Steps to Reproduce (for bugs)
1. Open an existing database or new one
2. Create a new entry or edit an existing one
3. Press escape
4. Changes are discarded without any further prompt

## Context
I've lost several new entries and changes to existing entries by pressing escape before clicking apply. 

## Debug 
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.13.11-1-ARCH

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### LINKED ISSUE #1313: Grey out Apply button once clicked by user
## Expected Behavior

Once the apply button is clicked it should be greyed out. Only when the user has made a change and not clicked apply yet should it be clickable.

## Current Behavior

Once the apply button is clicked it is still clickable which can be confusing to the user whether or not applied changes have taken effect.

### PR DESCRIPTION
**Pull request by dwilches**
When the user clicks on the Apply button, it will get disabled. When changes are made, it's enabled again.

## Description

* Whenever the Apply button is pressed, and if the save was successful, then the Apply button is disabled.
* Each subwidget used by EditEntryWidget has now a signal called `widgetUpdated` that is emitted when the widgets' internal content changes. The EditEntryWidget subscribes to that signal to know when to enable the Apply button (by calling `entryUpdated()`).
* There are some views that are not isolated in their own widgets (`m_advancedUi`, for example) so in those cases I invoked `entryUpdated()` directly whenever I detected an update:
  * some updates occur directly in a Qt widget like when editing the text of a QLineItem, so in that case I connected the widget's signals directly to the `entryUpdated()` slot.
  * some updates occur in EditEntryWidget, so in those cases the invocation to `entryUpdated()` is made as soon as the change is detected (for example when the user has confirmed an action in a dialog).

## Motivation and context
Resolves #1313
Resolves #1181

## How has this been tested?
I tested it manually, not sure if I need to write an automated test.

## Types of changes
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
This needs to be combined with #1181.

**Comment by phoerious** [comment]
You can block signals for trivial updates. The button shouldn't be enabled for non-modifying changes.

**Comment by dwilches** [comment]
@droidmonkey What do you mean by "porting functionality"? Should I create a merge commit between my branch and frostasm's branch `request-confirmation-to-discard-unsaved-changes` and then make my PR include that merge commit?
Or should I copy&paste code from frostasm's branch into a new commmit in my PR?

**Comment by droidmonkey** [comment]
You could copy paste the relevant dialog code or implement your own variant. Definitely don't merge the branches.

**Comment by dwilches** [comment]
@droidmonkey @phoerious Changes implemented. This PR is now composed of 3 commits:
1. Solves #1313 but missing signal blocking
2. Implement signal blocking
3. Shows confirmation dialog before closing unsaved entries (#1181)

Let me know what you think!

**Comment by dwilches** [comment]
BTW: Amended the commits to change to my personal email.

File: src/gui/EditWidgetIcons.cpp [hunk 1]
```diff
@@ -66,6 +66,15 @@ EditWidgetIcons::EditWidgetIcons(QWidget* parent)
     connect(m_ui->deleteButton, SIGNAL(clicked()), SLOT(removeCustomIcon()));
     connect(m_ui->faviconButton, SIGNAL(clicked()), SLOT(downloadFavicon()));
 
+    connect(m_ui->defaultIconsRadio, SIGNAL(toggled(bool)), this, SIGNAL(widgetUpdated()));
+    connect(m_ui->defaultIconsRadio, SIGNAL(toggled(bool)), this, SIGNAL(widgetUpdated()));
+    connect(m_ui->defaultIconsView->selectionModel(),
+            SIGNAL(selectionChanged(const QItemSelection &, const QItemSelection &)),
```
Comment (phoerious) [inline src/gui/EditWidgetIcons.cpp]: No space before (please change that everywhere)

File: src/gui/entry/EditEntryWidget.cpp [hunk 2]
```diff
@@ -227,6 +228,60 @@ void EditEntryWidget::setupHistory()
...
+    connect(m_autoTypeUi->sequenceEdit, SIGNAL(textChanged(const QString &)), this, SLOT(setUnsavedChanges()));
+    connect(m_autoTypeUi->windowTitleCombo, SIGNAL(currentIndexChanged(int)), this, SLOT(setUnsavedChanges()));
+    connect(m_autoTypeUi->windowTitleCombo, SIGNAL(editTextChanged(const QString &)), this, SLOT(setUnsavedChanges()));
+
+    // Properties and History tabs don't need extra connections
+
+#ifdef WITH_XC_SSHAGENT
+    // SSH Agent tab
+    if (config()->get("SSHAgent", false).toBool())
+    {
```
Comment (phoerious) [inline src/gui/entry/EditEntryWidget.cpp]: No space before {

File: src/gui/entry/EditEntryWidget.cpp [hunk 3]
```diff
@@ -856,6 +913,20 @@ void EditEntryWidget::cancel()
         m_entry->setIcon(Entry::DefaultIconNumber);
     }
 
+    if (!m_saved)
+    {
```
Comment (phoerious) [inline src/gui/entry/EditEntryWidget.cpp]: Same

File: src/gui/entry/EditEntryWidget.cpp [hunk 4]
```diff
@@ -1214,5 +1296,12 @@ void EditEntryWidget::pickColor()
     QColor newColor = colorDialog.getColor(oldColor);
     if (newColor.isValid()) {
         setupColorButton(isForeground, newColor);
+        setUnsavedChanges(true);
     }
 }
+
+void EditEntryWidget::setUnsavedChanges(bool anyUnsaved)
```
Comment (phoerious) [inline src/gui/entry/EditEntryWidget.cpp]: I would call the parameter `hasUnsaved`

**Comment by phoerious** [comment]
I think ultimately we should change the button state based on the actual entry data, not based on widget edits. But for now it's okay IMHO.

**Comment by phoerious** [comment]
Hmm. The changes seem to hang the GUI tests. Please check what's wrong there. I would assume it's not finishing, because it can't click the button or so.

**Comment by phoerious** [comment]
I restarted the builds. Second rounds seems to go through, but it's quite slow.

File: src/gui/EditWidgetIcons.cpp (hunk 1 above)
Comment (dwilches) [reply src/gui/EditWidgetIcons.cpp]: You mean the newline? So should it be like:
```
    connect(m_ui->defaultIconsView->selectionModel(), SIGNAL(selectionChanged(const QItemSelection &, const QItemSelection &)),
            this, SIGNAL(widgetUpdated()));
```
or like this:
```
    connect(m_ui->defaultIconsView->selectionModel(), SIGNAL(selectionChanged(const QItemSelection &, const QItemSelection &)), this, SIGNAL(widgetUpdated()));
```

**Comment by dwilches** [comment]
@phoerious Pushed the format and space changes (and added a comment as I'm not sure I got one of your comments right). About the tests, I could run `make test` with no issue. The compilation is slow though when using `-DWITH_ASAN`, but could the changes on this PR be affecting something related to test/compilation speed?

**Comment by dwilches** [comment]
Just pushed another commit for a problem I noticed a moment ago. Do you use squash&merge or you want me to squash my commits in my branch before merging the PR?

**Comment by droidmonkey** [comment]
I would do a merge commit for this since there are multiple fixes.

**Comment by dwilches** [comment]
Ok, if it's ok for you, I'd like to squash some of the commits to clean a bit the story of the repository, instead of 5 commits I can leave 2 commits, one per fix.

**Comment by droidmonkey** [comment]
Yah you can squash the intermediate ones

**Comment by dwilches** [comment]
Done :+1:

File: src/gui/EditWidgetIcons.cpp (hunk 1 above)
Comment (phoerious) [reply src/gui/EditWidgetIcons.cpp]: I meant no space before &amp;. Github swallowed my ubeacaoed ampersand.

**Comment by phoerious** [comment]
Run with -DWITH_GUI_TESTS=ON. The don't finish.

**Comment by dwilches** [comment]
I found two problems:
1. Some times the "Entry has been modified" dialog popups up and hangs the test because it keeps waiting for input. I'll solve that one in a moment. It's strange it only fails some times, will look into that.
2. I found another test that fails every time, but it also fails with a fresh clone in the `master` branch:
```
FAIL!  : TestGui::testDeleteEntry() Compared values are not the same
   Actual   (entryView->selectionModel()->selectedRows().size()): 1
   Expected (2)                                                 : 2
   Loc: [/home/dwilches/Repos/tmp/keepassxc/tests/gui/TestGui.cpp(807)]
```
Not sure if it fails for you too or it's because I'm in Ubuntu+KDE Plasma (the test fails when clicking an entry, and then pressing Ctrl + clicking another entry, then expects 2 entries to be selected, but finds only 1 is selected).

**Comment by droidmonkey** [comment]
master tests passed: https://ci.keepassxc.org/viewLog.html?buildId=9321&buildTypeId=KeepassXC_TeamCityCi

**Comment by dwilches** [comment]
Fixed test that had broken by the new functionality.
About the other test that fails, should be something in my machine then. If I follow by myself the same steps that the test case does, and they work as expected.

**Comment by phoerious** [comment]
I stopped the old tests. They were jamming the queue.

**Comment by dwilches** [comment]
Noticed this PR status says "Changes requested", but there is no pending change, so letting you know in case there is still something needed.

**Comment by phoerious** [comment]
No, you just need to rebase to the current branch head.

**Comment by dwilches** [comment]
@phoerious Done, rebased on top of the current `develop` branch.

**Comment by phoerious** [comment]
Thanks!

**Comment by haridsv** [comment]
Just checking... this change is not yet in the latest release, right?

**Comment by droidmonkey** [comment]
It is, but I think its broken because as soon as you open an entry it determines there are unsaved changes.

**Comment by haridsv** [comment]
Thanks @droidmonkey! I didn't realize there is a newer version until I saw your response. I got the new version via Brew and now I can see that the Apply button is working as expected. I don't see the erroneous behavior that you are describing. Perhaps it is a corner case bug? Is it happening for you for all entries?

**Comment by droidmonkey** [comment]
The case I am describing is if you try to lock the database with the entry edit view open, it asks if you want to save the entry before closing instead of properly determining if it is "dirty" or not.
