### PR TITLE
Final push for 2.6.2

### LINKED ISSUE #4083: "Entry updated successfully" shows up even when you don't change anything
## Expected Behavior
The message saying "**Entry updated successfully.**", shouldn't appear if the user didn't actually update an entry.

## Current Behavior
Message shows up even when you didn't change an entry. But it requires specific steps to reproduce it, see below.

## Steps to Reproduce
1. Pick an already existing entry to edit
2. Open it, go to **Auto-Type**, click **Use custom Auto-Type sequence**
3. Put the following in the auto-type field: `{DELAY=100}`
4. Click **Apply**, a popup message will appear, asking you: "**This Auto-Type command contains very slow key presses. Do you really want to proceed?**"
5. Click **No** or close the dialog
6. A message saying "**Entry updated successfully.**" will pop up, but the entry itself won't get updated. Plus the **Apply** button will be grayed out (I guess it shouldn't)

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.14.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.7-zen1-1-zen

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

### LINKED ISSUE #4151: Always On Top [Windows 10]
## Summary
On the Windows 10 version (at least), there should be an optional feature called "Always on top", which would keep the KeepassXC window on top of all other windows until it's minimized. This will prevent having to click back and forth between applications to enter both the username and password when autofill doesn't work. 

Most Linux Desktop Environments handle the always on top feature pretty well independently. Unfortunately, Windows 10 does not and it makes using KeepassXC very inconvenient to use because it doesn't have the feature built in.

## Desired Behavior
User selects a feature called "Always on top". When activated, all KeepassXC related windows will remain on top of all other windows on the screen until it's minimized.

## Possible Solution
Add a check box that says "Always on top", in Tools > Settings > General > General. In Qt, I'm pretty sure the line would be something like: `@setWindowFlags(Qt::WindowStaysOnTopHint);@` 

## Context
It matters to me because I'm forced to use Windows 10 for certain applications and not having an always on top feature makes using KeepassXC (which I use frequently for multiple VPNs, VMs, Web apps, websites, etc) very annoying. I'm having to swap between windows twice for many apps where autofill doesn't work.

### LINKED ISSUE #4182: Viewing entry with multiple auto-type window associations evokes unsaved changes.
**Expected Behavior**

Should be able to fully view windows associations of an entry without making any changes and not be prompted about "unsaved changes" when leaving the entry.

**Current Behavior**
If you view the window associations by clicking on them, you can't leave that entry without getting the warning about unsaved changes (with nothing being changed).

**Steps to Reproduce**
1. Open an entry with multiple Auto-Type Window Associations.
2. Click Auto-Type
3. The first Association will be highlighted in grey. Select the second one.
4. Press Cancel

**Context**
Just normal use. Work with a new database with just a single entry.

**Debug Info**
Version: 2.5.2 64-bit on Windows 10.10.19536

Remarks:
[#3013](https://github.com/keepassxreboot/keepassxc/issues/3013) is quite similar, except that the fix for that one obviously did not solve this one.

For some reason, I did not get the bug-reporting template when creating this issue. I have therefore tried to mimic the template.

### LINKED ISSUE #4463: Password placeholder is not masked out in cmd confirmation message box
When a new or modified cmd:// url is added to an item, a message box pops up displaying the full command line and prompting the user if they wish to execute it. The password is shown in plain text and should be *******.

### LINKED ISSUE #4895: Crash on open - keeshare does not support folder removal
Hello,

Keeshare does not support folder removal. If a keeshare group is removed in a synchronised database, then the whole database can be remotely corrupted. Some details below :

## Steps to Reproduce
Create a database with several shared folder using keeshare. 
For example :
Database1.kdbx contains 2 groups :
keeshareGroup1 -> sync with C:/temp/keeshare1.kdbx.share
keeshareGroup2 -> sync with C:/temp/keeshare2.kdbx.share
Close Database1.kdbx

Copy Database1.kdbx to Database1-copy.kdbx and in that second database remove one group and empty trash.
Then the opening of first Database1.kdbx will fail with error : 
"The Instruction at 0x0000000000A572020 referenced memory at 0x0000000000000000. The memory could not be read."

## Expected Behavior
The Database1.kdbx still opens correctly and synchronisations with the keeshare files are made.

## Actual Behavior
The keepassXC is unable to open the Database1.kdbx

## Additionnal informations
Reproduced each time I tried it. 

KeePassXC - Version 2.5.4
Revision : c023bf9
Operating System : Windows 10 Version 1909
UC Arch : x86_64
Kernel : winnt 10.0.18363

I planned to deploy several shared database over several departments but I fear now than a single person who deletes a folder can make the whole departements stuck with no passwords access. Bad ...

Thanks for your support.

### LINKED ISSUE #4982: Hide Password - Remove tick not remembered in V 2.6.0
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Title says it all.  Unticking Hide Password is not now remembered between sessions.  It always has been for as long as I can remember

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to Header Bar
2. Right Click
3. Remove Tick against Hide Password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Previously the ability to **always** show passwords was remembered between sessions it certainly is in ver 2.5.4

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Show & Hide Passwords setting **is** remembered in the Preview panel
But not in the Main Panel

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

### LINKED ISSUE #5127: Snap helper script doesn't work on Fedora
From site i could see that to enable integration with browser if i install KeepassCX 2.6.0 using snap i need download script https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh

So i download it and try run

sh keepassxc-snap-helper.sh

but nothing happen while script code ii guess should output some message.

When i check script code i could see that it's try use this path /snap/bin/keepassxc.proxy but i don't have such file (and actually even /span folder). I install snapd only actually but this look as enough to run span: dnf install snapd

System is Fedora 32 with latest kernel.  BTW. Fedora do not yet update KeepassCX and release version is still 2.5.4

KeePassXC - Version 2.6.0
Revision: 0765954
Distro: Snap
Operating System: Fedora 32 64 bit
Desktop Env: Gnome
Windowing System: Wayland

So as result i still cannot integrate KeepassXC with Firefox.

### PR DESCRIPTION
**Pull request by droidmonkey**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
* Closes #4151 - implement windows always on top in view menu
* Fixes #4982 - Move hide usernames/passwords into view menu (cleans up code a bunch!)
* Fixes #4463 - Mask password placeholder in command execution dialog
* Fix #4083 - move auto-type checks early in the commit process to prevent half-saving an entry if there is a bail-out.
* Fix #4182 - prevent setting modified by just viewing auto-type window associations
* Fix #4895 - when KeeShare imports a database it performs a merge operation. If that share was deleted from another identical database (ie, same base group UUID), then the group would be deleted in the middle of reinit causing a crash. This fix moves the group into a QPointer catching the delete operation.
* Fix #5127 - use `which keepassxc.proxy` to find the path of the snap proxy. Warn the user if the snap proxy was not found and bail out early.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image

image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows and Linux

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: utils/keepassxc-snap-helper.sh [hunk 1]
```diff
@@ -16,15 +16,17 @@
...
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-set -e
-
-DEBUG=false
+JSON_OUT=""
+BASE_DIR="."
+INSTALL_DIR=""
+INSTALL_FILE="org.keepassxc.keepassxc_browser.json"
+PROXY_PATH=$(which keepassxc.proxy)
```
Comment (phoerious) [inline utils/keepassxc-snap-helper.sh:23]: `which` is non-standard. You should use `command` instead.

**Review by phoerious — APPROVED** [review]
One nitpick, rest looks okay to me.

**Comment by droidmonkey** [comment]
Switched from `which` to `command`
