### PR TITLE
Fix layout and alignment of Entry and Group edit views

### LINKED ISSUE #4852: Tabbing into notes on Entry Edit is broken
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Tab sequencing for editing an entry is slightly broken. Cannot tab into the notes field.

### LINKED ISSUE #5300: Scrollbar shows up in middle of edit/details screens
keepass-details-scrollbar-issue

## Overview
I just upgraded from 2.5.4 to 2.6.1 today and I'm seeing vertical scrollbars floating over the middle of the edit panel.

## Steps to Reproduce
Whenever I edit a folder, or the first time I edit a particular password's entry.  If I open the same password entry it doesn't happen, but it always happens when editing a folder's entry.

## Expected Behavior
Scrollbar shouldn't be floating in the middle of the window.

## My system info
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Let me know if there's anything else I can provide to help debug this issue.

### LINKED ISSUE #5321: inconsistent text alignment
username and notes text is slightly out of alignment with title, password and URL

version 2.6.1 on Debian. Interface text (in Gnome tweak tool) is size 12 with scaling 0.90 (to offset a recent increase in shell theme font size). Screen is HiDPI with scaling 200%.

misaligned_text

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #5321 - Text alignment in the general tab of the entry and group edit views is fixed
* Fixes #5300 - Errant scrollbar in the general tab is fixed
* Fixes #4852 - Tabbing into notes field works as expected. To tab out, currently only Shift+Tab works.

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
**BEFORE:**
image

**AFTER:**
image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows and Ubuntu 16.04

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
I guess the expired text also needs to be aligned now too

**Comment by 648643579** [comment]
the same problem: https://github.com/keepassxreboot/keepassxc/issues/5300

https://i.imgur.com/92UcZBK.png

```
KeePassXC - Verze 2.6.1

Revize: 9a35bba

Qt 5.15.0
Ladící režim je vypnutý.

Operační systém: Windows 10 Version 1809
Architektura procesoru: x86_64
Jádro systému: winnt 10.0.17763

Zapnutá rozšíření:
- Automatické vyplňování
- Napojení na webový prohlížeč
- SSH agent
- KeeShare (podepsané a nepodepsané sdílení)
- YubiKey

Kryptografické knihovny:
 libgcrypt 1.8.5
```

File: src/gui/entry/EditEntryWidget.cpp [hunk 1]
```diff
@@ -178,6 +178,9 @@ void EditEntryWidget::setupMain()
 
     m_mainUi->expirePresets->setMenu(createPresetsMenu());
     connect(m_mainUi->expirePresets->menu(), SIGNAL(triggered(QAction*)), this, SLOT(useExpiryPreset(QAction*)));
+
+    // HACK: Align username text with other line edits. Qt does not let you do this with an application stylesheet.
+    m_mainUi->usernameComboBox->lineEdit()->setStyleSheet("padding-left: 8px;");
```
Comment (phoerious) [inline src/gui/entry/EditEntryWidget.cpp:183]: I don't think this is an appropriate fix. The problem seems to be that one is a LineEdit and the other a ComboBox. Inconsistencies between these widget types should be fixed in the QStyle directly.

File: src/gui/styles/base/basestyle.qss [hunk 2]
```diff
@@ -64,3 +64,8 @@ DatabaseWidget #SearchBanner, DatabaseWidget #KeeShareBanner {
     border: 1px solid palette(dark);
     padding: 2px;
 }
+
+QPlainTextEdit, QTextEdit {
+    background-color: palette(base);
+    padding-left: 4px;
+}
```
Comment (phoerious) [inline src/gui/styles/base/basestyle.qss:71]: See above.

**Review by phoerious — CHANGES_REQUESTED** [review]

File: src/gui/entry/EditEntryWidget.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/gui/entry/EditEntryWidget.cpp:183]: I spent a long time trying to figure out exactly where the problem was. I dived into the BaseStyle and added padding in there and looked at all the exceptions. The problem is that QComboBox implements it's own QLineEdit and ignores ALL styling of QLineEdit applied. The only way to fix it is to override the style sheet post-construction. This was observed by many others in the Qt universe.

File: src/gui/styles/base/basestyle.qss (hunk 2 above)
Comment (droidmonkey) [reply src/gui/styles/base/basestyle.qss:71]: This is also a hack, technically. I looked at the Qt source code for TextEdit and it is a shim on top of a QScrollArea. Qt is entirely unconcerned with alignment styling and box model, even though they profess their support in the docs. It is literally impossible to add interior padding to the QTextEdit, this padding is actually added to the interior of the QScrollArea...

**Comment by droidmonkey** [comment]
For the record, I looked into aligning the QDateTime widget and that too is a hacked widget with no ability to even access the lineEdit() control like QComboBox because they made it a protected function.

**Comment by phoerious** [comment]
I am fine with merging this for 2.6.2, but we should find a better solution for aligning the fields.

**Comment by droidmonkey** [comment]
I'm fine with that

**Comment by shrinedrift4553** [comment]
This bug still persists for me, on 2.6.1 
Screenshot 2020-10-21 035453
