### PR TITLE
Ask for save location when creating new database

### LINKED ISSUE #285: Choose database path as part of New Database
Currently, when you create a database, it doesn't have a location. This leads to a bug where the "Automatically save after every change" setting gets ignored if you haven't already saved the database once.

## Expected Behavior
As part of the "New Database" interface, include a location field with a suitable default. When the user hits "OK," attempt to save an empty database to that location. If saving the database fails, prompt the user to choose another location before continuing.

## Current Behavior
Location is not set until user selects "Save" for the first time.

## Steps to Reproduce (for bugs)
1. Go to Tools > Settings > General and check the "Automatically save after every change" box.
2. Select New Database, set a password, and click OK.
3. Add a password to the database.
4. Notice that the title bar still has a "*" indicating that the database is not yet saved.

## Context
I'm trying to provide advice about password managers to non-technical users. In #279, I propose that "automatically save after every change" should become the default. This would make the auto-save experience nicer and less error-prone.

## Your Environment
* KeePassXC version: 2.1.1

### PR DESCRIPTION
**Pull request by phoerious**
This PR resolves #285.

## Description

When the user clicks the button to create a new database, they are asked immediately where to save the database. This resolves issues with the autosave feature in combination with unnamed databases. It also avoids general confusion when users are not aware that their database exists solely in memory until they explicitly save it.

When saving to a location fails, the save dialog is shown again, so the user can choose a different location. When the user clicks the "Cancel" button, the whole database creation process is canceled.

I also changed the default database file name to "Passwords.kdbx" to make it easier to understand for novice users.

## How Has This Been Tested?

I tested to save to multiple different locations (writable and non-writable) on Arch Linux.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by louib** [comment]
Tested with MacOS, works great. One comment: Now that the database is created before setting the password, the cancel button on the set password screen will leave the database without a password, without warning the user. Maybe the Cancel button could be removed when initially setting the password, so that the user would have to confirm the empty password on database creation.

File: src/gui/DatabaseTabWidget.cpp [hunk 1]
```diff
@@ -353,80 +361,78 @@ bool DatabaseTabWidget::saveDatabase(Database* db)
...
-    if (!fileName.isEmpty()) {
-        QFileInfo fileInfo(fileName);
-        QString lockFilePath;
-        if (fileInfo.exists()) {
-            // returns empty string when file doesn't exist
-            lockFilePath = fileInfo.canonicalPath();
-        }
-        else {
-            lockFilePath = fileInfo.absolutePath();
+    while (true) {
```
Comment (droidmonkey) [inline src/gui/DatabaseTabWidget.cpp]: I am not a fan of an infinite loop with such a complicated inner structure. There are not clear exit points.

Comment (phoerious) [inline src/gui/DatabaseTabWidget.cpp]: How would you solve it? return saveDatabaseAs(db) instead of continue only gobbles up the stack unnecessarily.
As an alternative approach I could move all the code into a separate method and then only put the method call into an endless loop.

Comment (droidmonkey) [inline src/gui/DatabaseTabWidget.cpp]: After review I find this to acceptable.

**Comment by TheZ3ro** [comment]
This is still not fixed:

> One comment: Now that the database is created before setting the password, the cancel button on the set password screen will leave the database without a password, without warning the user. Maybe the Cancel button could be removed when initially setting the password, so that the user would have to confirm the empty password on database creation.

**Comment by phoerious** [comment]
I'll make a new PR for that.
