### PR TITLE
Select password locking if an empty password is entered

### LINKED ISSUE #570: Empty master password is wrong until a wrong password is entered
## Context
This is a substitute for #569.
I dug a little into the issue and found a more generic scenario:

whenever a DB is saved and its master password is empty, in order to unlock it is needed to provide a wrong password first.

Describing the original issue I was misleaded into thinking this had to do with "saved as" DBs only as I had used a lot of empty passwords in the past and never had any trouble.

So I am suspecting this is something related to fresh code.

## Steps to Reproduce (for bugs)

1. Create a new Database with empty password
2. (optional) add an entry to the database
3. Save the database
4. Lock
5. Try to unlock with empty password, this will throw an error
6. Entry a wrong password
7. Try to unlock with empty password, this time you unlock sucessfully

## Your Environment

* KeePassXC version/commit used: 2.1.4
* Qt version (e.g. Qt 5.3): 5.5.1

### PR DESCRIPTION
**Pull request by seatedscribe**
Resolve #570 dilemma

## Description

Automatically check the password checkbox if no selection is made from user at all.
Basically validates the scenario of unlocking a DB locked with an empty password.

## Motivation and context

Coherence with the fact that a DB with empty password is legal.
Until now an error message is issued telling the user that the password is wrong (it isn't).

## How has this been tested?

Manually.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/DatabaseOpenWidget.cpp [hunk 1]
```diff
@@ -168,6 +167,10 @@ void DatabaseOpenWidget::enterKey(const QString& pw, const QString& keyFile)
 void DatabaseOpenWidget::openDatabase()
 {
     KeePass2Reader reader;
+    if ((m_ui->editPassword->text().isEmpty()) && (!m_ui->checkKeyFile->isChecked())) {
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp]: Does it make much sense to check if the key file is checked?

Comment (TheZ3ro) [reply src/gui/DatabaseOpenWidget.cpp]: What about removing this check and just call `activatePassword()`?

This code should be called only when a db file is selected for opening. (if I'm not wrong)
An the default is empty password and no keyfile.

If the `Remember last keyfile and security dongle` option is enabled keyfile will be autofilled but enforcing a password it's not bad afterall (I hope nobody uses a db with no password or keyfile-only)

What do you think?

Comment (seatedscribe) [reply src/gui/DatabaseOpenWidget.cpp]: Well, dude, you are right! Why not just check the Password checkbox by default? I will update this PR following that aim.

**Comment by seatedscribe** [comment]
Ping @*TheZ3ro*
*Thoughts?*


On 15 Feb 2018 12:32 am, "TheZ3ro" <notifications@github.com> wrote:

*@TheZ3ro* commented on this pull request.
------------------------------

In src/gui/DatabaseOpenWidget.cpp
<https://github.com/keepassxreboot/keepassxc/pull/1479#discussion_r168344856>
:

> @@ -168,6 +167,10 @@ void DatabaseOpenWidget::enterKey(const QString& pw, const QString& keyFile)
 void DatabaseOpenWidget::openDatabase()
 {
     KeePass2Reader reader;
+    if ((m_ui->editPassword->text().isEmpty()) &&
(!m_ui->checkKeyFile->isChecked())) {

What about removing this check and just call activatePassword()?

This code should be called only when a db file is selected for opening. (if
I'm not wrong)
An the default is empty password and no keyfile.

If the Remember last keyfile and security dongle option is enabled keyfile
will be autofilled but enforcing a password it's not bad afterall (I hope
nobody uses a db with no password or keyfile-only)

What do you think?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keepassxreboot/keepassxc/pull/1479#discussion_r168344856>,
or mute the thread

**Comment by TheZ3ro** [comment]
@seatedscribe can you rebase on top of develop?

@keepassxreboot/core-developers can someone review this or otherwise I will merge

**Comment by seatedscribe** [comment]
Sure, I will!

**Comment by seatedscribe** [comment]
@TheZ3ro at last I rebased, is it ok?

**Comment by droidmonkey** [comment]
Holy crap no, you pulled in a ton of ancillary commits.

**Comment by seatedscribe** [comment]
Gosh, sorry. I shouldn't have made it on a rush! Give me another day please

**Comment by seatedscribe** [comment]
Well if _you_ could shed some light on what _I_ have done wrong, provided that it is not trivial from _that_ distance, maybe I will learn something new today :)

**Comment by droidmonkey** [comment]
You rebased correctly but then merged in a series of commits from somewhere. I just did a hard reset onto your one and only commit that was involved in this PR.
