### PR TITLE
Forget keyfile path by honoring settings

### LINKED ISSUE #1151: Key file last position is remembered after session lock
KeepassXC remembers the exact position (directory) of the Key file after session is locked/unlocked, potentially reducing the security of the key file, even if "remember last key files and security dongles" option is disabled.

## Expected Behavior
After a session lock / lid closed KeepassXC should point to the user home directory (as for a new instance of KeepassXC) instead of bringing the user to the directory where the last used key file is/was positioned.

## Steps to Reproduce (for bugs)
While using a database with also a key file master key:
1. De-select "Remember last key files and security dongles"
2. Select "Lock databases when session is locked or lid is closed"
3. Lock session
4. Unlock session
5. Browse for the key file

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### PR DESCRIPTION
**Pull request by TheZ3ro**
Fix #1151 

## Motivation and context

Every successful open/save dialog in KeePassXC save the path in the `LastDir` configuration.
This is a useful feature if you have to open your DB or adding/saving attachment many times.
On the other hand, keeping the directory of the keyfile is not so nice if the user unset "Remember last keyfiles"

**Users should always make their keyfile unavailable to an attacker. 
Hiding the keyfile path is just security by obscurity**

---

## How has this been tested?

Manually

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/FileDialog.cpp [hunk 1]
```diff
@@ -42,11 +42,11 @@ QString FileDialog::getOpenFileName(QWidget* parent, const QString& caption, QSt
         if (parent) {
             parent->activateWindow();
         }
-
-        if (!result.isEmpty()) {
+        if (!result.isEmpty() && m_nextSaveLastDir) {
```
Comment (louib) [inline src/gui/FileDialog.cpp]: @TheZ3ro maybe that could go in a `saveLastDir` function, since that code is repeated 4 times?

File: src/gui/FileDialog.h [hunk 2]
```diff
@@ -36,6 +36,7 @@ class FileDialog
     QString getExistingDirectory(QWidget* parent = nullptr, const QString& caption = QString(),
                                  QString dir = QString(), QFileDialog::Options options = QFileDialog::ShowDirsOnly);
 
+    void setNextForgetDialog();
```
Comment (phoerious) [inline src/gui/FileDialog.h]: I would change this to a simple `setRememberLastDir()` setter and rename the member variable to `m_rememberLastDir`.

Comment (TheZ3ro) [reply src/gui/FileDialog.h]: The thing is that since it's a static instance it will need to reset the member variable anyway, otherwise once set all the future dialog will be set as well until it re-set

Comment (phoerious) [reply src/gui/FileDialog.h]: Then at least rename it to (m_)forgetLastDir and reverse the logic. The current name is a bit confusing.

**Comment by TheZ3ro** [comment]
@phoerious @louib fixed and rebased
