### PR TITLE
TOTP Setup Fixes

### LINKED ISSUE #773: Copy TOTP passwords by pressing CMD+c when it's visible
I need to hit the copy button now but I would like to be able to just use the system's shortcut for copy to copy it into the clipboard.

### LINKED ISSUE #3142: TOTP: OTP settings not updated if in invalid format [DATA LOSS]
## Expected Behavior
TOTP secrets are persistently stored.

## Current Behavior / Steps to Reproduce
1. Start KeePassXC
1. Unlock DB
1. Select record
1. Set up TOTP
1. Enter secret
1. Quit KeePassXC (only tested with autosave on every change enabled)
1. Repeat steps 1-4
1. TOTP secret is gone

## Context
This used to work just fine in the past, I don't know which version broke it.
I'm experiencing this both on windows and macos.
fwiw this totp secret has been in my db for a long time before it disappeared, surviving many saves and restarts.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ Refactor (significant modification to existing code)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Fix #3142 - Warn user when entering invalid TOTP secret key.
* Fix #773 - The TOTP dialog now listens for the copy shortcut without having to press the Copy button.

* Add ability to choose hash algorithm from the TOTP setup dialog
* Add upgrade to "otp" attribute when custom attributes are chosen to prevent data loss

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image

image

image

image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manual and unit testing

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by koutheir** [comment]
Oh great! Now we can specify the algorithm for TOTP! This makes SHA-512 TOTP way simpler. Thank you! I can't wait for a release version that includes this nice feature!

File: src/gui/TotpSetupDialog.cpp [hunk 1]
```diff
@@ -43,51 +45,92 @@ TotpSetupDialog::~TotpSetupDialog()
...
 void TotpSetupDialog::saveSettings()
 {
+    // Secret key sanity check
+    auto key = m_ui->seedEdit->text().toLatin1();
+    auto sanitizedKey = Base32::sanitizeInput(key);
+    if (sanitizedKey != key) {
+        MessageBox::information(this,
+                                "Invalid TOTP Secret",
+                                "You have entered an invalid secret key. The key must be in Base32 format.\n"
+                                "Example: JBSWY3DPEHPK3PXP");
```
Comment (phoerious) [inline src/gui/TotpSetupDialog.cpp]: Not translatable.

File: src/gui/TotpSetupDialog.cpp [hunk 2]
```diff
@@ -43,51 +45,92 @@ TotpSetupDialog::~TotpSetupDialog()
...
+        digits = m_ui->digitsSpinBox->value();
+    }
+
+    auto settings = m_entry->totpSettings();
+    if (settings) {
+        if (key.isEmpty()) {
+            auto answer = MessageBox::question(this,
+                                               "Confirm Remove TOTP Settings",
+                                               "Are you sure you want to delete TOTP settings for this entry?",
+                                               MessageBox::Delete | MessageBox::Cancel);
```
Comment (phoerious) [inline src/gui/TotpSetupDialog.cpp]: Same here.

File: src/gui/TotpSetupDialog.cpp [hunk 3]
```diff
@@ -43,51 +45,92 @@ TotpSetupDialog::~TotpSetupDialog()
...
+            if (answer == MessageBox::Cancel) {
+                return;
+            }
```
Comment (phoerious) [inline src/gui/TotpSetupDialog.cpp]: `if (answer != MessageBox::Delete) { ... }`

File: src/gui/TotpSetupDialog.cpp [hunk 4]
```diff
@@ -43,51 +45,92 @@ TotpSetupDialog::~TotpSetupDialog()
...
+
+        format = settings->format;
+        if (format == Totp::StorageFormat::LEGACY && m_ui->radioCustom->isChecked()) {
+            auto answer = MessageBox::question(
+                this,
+                "Upgrade TOTP Settings",
+                "You are currently using legacy TOTP settings which do not fully support custom settings.\n"
+                "Would you like to upgrade to the latest format?",
+                MessageBox::Yes | MessageBox::No,
+                MessageBox::No);
```
Comment (phoerious) [inline src/gui/TotpSetupDialog.cpp]: Not translatable either. I am also quite afraid that this might confuse and unsettle users again (like our "legacy key file" dialogue did). What could go wrong if we just upgrade silently? Why not simply create a history snapshot before saving the upgraded settings? And then if we still don't trust our own programming skills, we can show a purely informative message saying "hey there, your TOTP settings were upgraded. Please check that everything is in order, you can revert the changes in the history panel".

File: src/gui/TotpSetupDialog.ui [hunk 5]
```diff
@@ -6,10 +6,16 @@
    <rect>
     <x>0</x>
     <y>0</y>
-    <width>249</width>
-    <height>278</height>
+    <width>230</width>
+    <height>240</height>
```
Comment (phoerious) [inline src/gui/TotpSetupDialog.ui]: Remove explicit size?

File: src/gui/entry/EditEntryWidget.cpp [hunk 6]
```diff
@@ -862,7 +862,8 @@ void EditEntryWidget::setForms(Entry* entry, bool restore)
 
 #ifdef WITH_XC_BROWSER
     if (m_customData->contains(BrowserService::OPTION_SKIP_AUTO_SUBMIT)) {
-        m_browserUi->skipAutoSubmitCheckbox->setChecked(m_customData->value(BrowserService::OPTION_SKIP_AUTO_SUBMIT) == "true");
+        m_browserUi->skipAutoSubmitCheckbox->setChecked(m_customData->value(BrowserService::OPTION_SKIP_AUTO_SUBMIT)
+                                                        == "true");
```
Comment (phoerious) [inline src/gui/entry/EditEntryWidget.cpp]: The line break is pretty ugly.

File: src/gui/TotpSetupDialog.cpp (hunk 3 above)
Comment (droidmonkey) [reply src/gui/TotpSetupDialog.cpp]: No you want to early-out return here because you want to execute the rest of the function to actually delete the settings. Early out brings you back to the dialog which let's you undo or cancel your actions.

File: src/gui/TotpSetupDialog.cpp (hunk 4 above)
Comment (droidmonkey) [reply src/gui/TotpSetupDialog.cpp]: I removed the prompt, I had the same thoughts. Since we are thinking the same thing it is best to just implicitly "upgrade" and don't event bother the user. The only downfall is that legacy TOTP plugins *may* not recognize the OTP URL format. But if you are using custom TOTP settings it is likely they won't recognize those either.

File: src/gui/TotpSetupDialog.ui (hunk 5 above)
Comment (droidmonkey) [reply src/gui/TotpSetupDialog.ui]: The dialog sizes to contents on open, this is just an artifact of using Qt Designer.

Comment (phoerious) [reply src/gui/TotpSetupDialog.ui]: I know. I just like to keep these files as clean as possible.

File: src/gui/TotpSetupDialog.cpp (hunk 3 above)
Comment (droidmonkey) [reply src/gui/TotpSetupDialog.cpp]: Gotcha!

**Comment by droidmonkey** [comment]
Final changes made
