### PR TITLE
Capture original regex in non-matching group when an exact match is r…

### LINKED ISSUE #7776: Secret service attribute search containing a '|' (vertical bar) returns all entries
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
A `secret-tool` search containing a vertical bar returns every secret from the database.
The vertical bar needs to be at the begging or end of the query, otherwise the bug doesn't happen. 
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a database with two secrets. One with an attribute `attr`=1, and the other one with `attr`=2.
2. Enable secret service integration.
3. Run `secret-tool search --all attr "abc|"`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
`secret-tool` should return nothing, since there is no secret with `attr` equal to `abc|`. That's what gnome-keyring does in the same case.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
`secret-tool` returns there two secrets.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

### PR DESCRIPTION
**Pull request by libklein**
Fixes #7776.

Tools::convetToRegex pre-/appends "^"/"<span>$</span>" to the built regex if an exact match is requested. This breaks expressions such as "v|", which, instead of matching v or the empty string, matches v or the end of line after substitution: "^v|<span>$</span>" is parsed as "^(v|<span>$</span>)".

Surrounding the original regex with an non-capturing group fixes this error.

See https://pcre.org/pcre.txt Sections "Vertical Bar" and "Subpatterns".

## Testing strategy
Added test to TestFdoSecrets and TestTools.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: tests/TestFdoSecrets.cpp [hunk 1]
```diff
@@ -82,6 +82,11 @@ void TestFdoSecrets::testSpecialCharsInAttributeValue()
         QCOMPARE(res.count(), 1);
         QCOMPARE(res[0]->title(), QStringLiteral("titleB"));
     }
+    {
+        const auto term = Collection::attributeToTerm("testAttribute", "v|");
```
Comment (michaelk83) [inline tests/TestFdoSecrets.cpp:86]: May want to test the `|v` case as well.

Comment (libklein) [reply tests/TestFdoSecrets.cpp:86]: I agree that more tests are need, but i think we should implement these in TestTools. The regex builder tests need some refactoring as well. Right now they just check if the regex built matches some expected regex, but not if they actually behave correctly.

**Comment by droidmonkey** [comment]
Was thinking this was where the error was, great change!

**Comment by Aetf** [comment]
Why not use [`QRegularExpression::escape`](https://doc.qt.io/qt-5/qregularexpression.html#escape-1) to escape the string
if exact match is requested? The current fix breaks on inputs like `)v|(?:`

In some sense this is pretty similar to protecting against SQL injection...

Edit: there's also [`QRegularExpression::wildcardToRegularExpression`](https://doc.qt.io/qt-5/qregularexpression.html#wildcardToRegularExpression).
But then I noticed both functions are only available in Qt 5.15...

**Comment by droidmonkey** [comment]
That is why lol, not available yet for our minimum distros. Does the Qt function choke on these "malicious" type strings as well?

**Comment by Aetf** [comment]
I haven't tried but I don't think so.

Here's the implementation, we should do something similar

https://code.woboq.org/qt5/qtbase/src/corelib/text/qregularexpression.cpp.html#1899

https://code.woboq.org/qt5/qtbase/src/corelib/text/qregularexpression.cpp.html#1818

**Comment by droidmonkey** [comment]
I think I prefer just copying the 5.15 source code into our tools with attribution.

**Comment by libklein** [comment]
I agree and will work on that and some further tests later tonight to hopefully make 2.7.1.

**Comment by libklein** [comment]
> That is why lol, not available yet for our minimum distros. Does the Qt function choke on these "malicious" type strings as well?

Actually, the QT implementation of exact matches (https://doc.qt.io/qt-5/qregularexpression.html#anchoredPattern) does exactly the same thing were doing right now. The "malicious string" is malicious only because it is not a proper regular expression, which is something Tools::convertToRegex should require.

As we'd need the copy the existing implementation (https://github.com/qt/qtbase/blob/2eb7a92aa373f10f4e6828dad640b393279637a3/src/corelib/text/qregularexpression.cpp#L2053, available > qt 5.12) into our source anyway, i'd just leave the function as is.

I'd still implement QRegularExpression::escape (and expose it), simply because it allows us to granularize tests. See the latest commit. I'll add further tests if you agree with the approach. 

Also, does someone know if the attribution is correct?

**Comment by droidmonkey** [comment]
Should invoke the GPL 3 statements from their license block at the top of the qregularexpression.cpp.

**Comment by libklein** [comment]
I've fixed some more bugs with overlapping flag values, added some further tests, and the QT license header. 

After spending some time browsing through the codebase i'd suggest splitting convertToRegex into createWildcardRegex and createRegex (perhaps even get rid of the latter one) as these are orthogonal anyway.

File: src/core/Tools.cpp [hunk 2]
```diff
@@ -1,7 +1,10 @@
 /*
  *  Copyright (C) 2012 Felix Geyer <debfx@fobos.de>
  *  Copyright (C) 2017 Lennart Glauer <mail@lennart-glauer.de>
- *  Copyright (C) 2021 KeePassXC Team <team@keepassxc.org>
+ *  Copyright (C) 2020 Giuseppe D'Angelo <dangelog@gmail.com>.
+ *  Copyright (C) 2020 Klarälvdalens Datakonsult AB, a KDAB Group company, info@kdab.com, author Giuseppe D'Angelo
+ * <giuseppe.dangelo@kdab.com> Copyright (C) 2021 The Qt Company Ltd. Copyright (C) 2021 KeePassXC Team
```
Comment (Aetf) [inline src/core/Tools.cpp]: line endings seem to be messed up

File: src/core/Tools.cpp [hunk 3]
```diff
@@ -296,16 +299,80 @@ namespace Tools
...
+     * and conditions see https://www.qt.io/terms-conditions. For further
+     * information use the contact form at https://www.qt.io/contact-us.
+     *
+     * GNU Lesser General Public License Usage
+     * Alternatively, this file may be used under the terms of the GNU Lesser
+     * General Public License version 3 as published by the Free Software
+     * Foundation and appearing in the file LICENSE.LGPL3 included in the
+     * packaging of this file. Please review the following information to
+     * ensure the GNU Lesser General Public License version 3 requirements
+     * will be met: https://www.gnu.org/licenses/lgpl-3.0.html.
```
Comment (Aetf) [inline src/core/Tools.cpp]: These two shouldn't be necessary as we choose to use the GPL license?

File: src/core/Tools.cpp [hunk 4]
```diff
@@ -296,16 +299,80 @@ namespace Tools
...
+     *
+     * GNU General Public License Usage
+     * Alternatively, this file may be used under the terms of the GNU
```
Comment (Aetf) [inline src/core/Tools.cpp]:
```suggestion
     * Alternatively, this file may be used under the terms of the GNU
```
```suggestion
     * This function may be used under the terms of the GNU
```

Overall this can be confusing. What about leaving the license text, and just mentioning here copyright lines and the fact that this was adapted from Qt source.

Then in the `COPYING` file, add a new block linking to this?

File: src/core/Tools.cpp (hunk 3 above)
Comment (libklein) [reply src/core/Tools.cpp]: According to "https://opensource.org/faq#preserve-copyright-notices", it's best to leave the copyright as is. Im not sure if it applies to this specific situation, but i don't think it'll hurt to include everything.

Comment (droidmonkey) [reply src/core/Tools.cpp]: I removed the other licenses except GPL 3.

**Review by droidmonkey — APPROVED** [review]
