### PR TITLE
Fix occasional crash when favicon progress dialog is closed

### LINKED ISSUE #1936: Cancelling favicon download causes a crash
## Expected Behavior

While editing an entry clicking 'Download favicon' (always was and still) should download the favicon of the indicated URL.

## Current Behavior

The download starts and the icon gets added to the custom icons field. But there are 1-3 download progress windows/pop ups in the foreground which are stuck at 100%. Their 'Cancel' button is not working. So pressing the window's close-window-x on one those leads to a segfault of the whole application.

## Possible Solution

Meta: A `--verbose` or `--debug` command would help to track it down; I couldn't find such an option for keepassxc. Right now that issue could be a packaging problem within my distribution too, but there's not really a way for me to know that.

## Steps to Reproduce (for bugs)

1. Go to or add new entry.
2. Add URL to entry. (I think full domain incl https is necessary)
3. Change to 'Icon' tab and click 'Download favicon'.

## Context

What I would be afraid of is: When adding a new entry incl. generated password and being still in the process of editing, this segfault could lead to corrupt data and maybe inaccessible accounts.
## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.16.7-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

Fix #1936 

Also removes some unnecessary code and changes the progress to a true percentage.

## Motivation and context

Crashes are bad, mm'kay.

## How has this been tested?

Manually

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/EditWidgetIcons.cpp [hunk 1]
```diff
@@ -45,16 +45,13 @@ UrlFetchProgressDialog::UrlFetchProgressDialog(const QUrl &url, QWidget *parent)
...
-    setMinimumDuration(0);
+    setMinimumDuration(2000);
     setMinimumSize(QSize(400, 75));
 }
 
 void UrlFetchProgressDialog::networkReplyProgress(qint64 bytesRead, qint64 totalBytes)
 {
-    setMaximum(totalBytes);
-    setValue(bytesRead);
+    setValue(static_cast<int>(bytesRead/totalBytes));
```
Comment (phoerious) [inline src/gui/EditWidgetIcons.cpp]: Space around operators
