### PR TITLE
Prevent interface lockups during startup with multiple tabs

### LINKED ISSUE #11870: Touch Yubikey blue bar message doesn't show when using quick unlock
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

Starting with the recent update 2.7.10 when when attempting to unlock a previously locked database with saved Quick Unlock credentials and Challenge Response Yubikey, the application freezes and fails to show the blue bar prompting to touch the security key.

Error results: Error while reading the database: Unable to calculate database key: USB: Hardware key timed out waiting for user interaction.

### Steps to Reproduce

1. Open database using password, challenge/response security key and save use TouchID to save credentials.
2. Lock database
3. Click Unlock Database, tap for Windows touchID credentials.
4. No prompt appears to touch security key.
5. Database fails to re-open.

### Expected Versus Actual Behavior

When clicking to unlock the database using saved TouchID credentials and security key, the application should prompt for both the TouchID and pressing of the security key.

It currently only prompts for the security key challenge response.

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.7.10
Revision: b342be4

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```

### Operating System

Windows

### Linux Desktop Environment

None

### Linux Windowing System

None

### LINKED ISSUE #11998: KeePassXC becomes unresponsive shortly after launch if a YubiKey is plugged in
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

KeePassXC becomes unresponsive after launch for a couple of seconds if multiple database files are opened and a YubiKey is plugged in.
This freeze doesn't happen if no YubiKey is plugged in.

The time the app is unresponsive scales with the number of automatically opened database files. With four empty test databases, the program becomes unresponsive for about 4 seconds. My actual database files make KeePassXC freeze for about 10 seconds.

I've bisected the problem to 0b32cf348d66032534f520986df1a6c903196d93.
In particular, commenting out the lock in [`src/keys/drivers/YubiKey.cpp:109`](https://github.com/keepassxreboot/keepassxc/commit/0b32cf348d66032534f520986df1a6c903196d93#diff-6531af7f3a5bdeadd10751661b6e104ddf58a88268fe7b95c65f35d88dfa5bd9R109) makes the problem go away.
Unfortunately, I don't know enough about KeePassXC's code base to provide a patch. Simply removing the lock likely isn't an option.

This problem might be related to keepassxreboot/keepassxc#11852. I tried searching for other related issues but didn't find any. I'm sorry if this particular bug is already tracked somewhere.

### Steps to Reproduce

1. Launch KeePassXC with 0b32cf348d66032534f520986df1a6c903196d93 applied.
2. Open four or more different database files (you don't have to unlock them).
3. Quit KeePassXC.
4. Ensure a YubiKey is plugged in.
5. Launch KeePassXC again. This time, the UI freezes for a couple of seconds.

### Expected Versus Actual Behavior

Expected behaviour: KeePassXC doesn't freeze.\
Observed behaviour: KeePassXC becomes unresponsive for a couple of seconds.

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.7.9-snapshot
Build Type: Snapshot
Revision: 0b32cf3

Qt 5.15.16
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.13.5-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.7.1
```

### Operating System

Linux

### Linux Desktop Environment

Gnome

### Linux Windowing System

Wayland

### LINKED ISSUE #12148: Using Multiple Yubikeys Is Unstable At Best
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

There are multiple issues using KeePassXC when more than one YubiKey (with touch required) is inserted into the system, especially when trying to unlock a previously open kdbx. Among the issues are:

1) No keys are presented when trying to open a kdbx file. Or, not all keys are presented, A scan for keys usually only identifies one key, not all keys present.

2) Any key(s) that are found are often not usable, throwing the error shown in the attachment. 

Image

When this error occurs, the key is plugged into the system. When it occurs on a save, the key has not been removed from the system, yet KeePassXC does not find it despite its previous use. Unplugging the key and plugging it back in does not fix this problem most of the time.

3) When problem 2 occurs, multiple retries MAY eventually get the key to work.

4) Sometimes the above error is thrown when trying to save after editing an entry. This apparently leaves the kdbx in an unknown state, and there is no simple way to retry the save, as KeePassXC seems to think the kdbx file has been saved. If you try to close the kdbx file, you are not prompted to touch they key.

5) WORSE, sometimes when problem 4 occurs, the data is actually saved and other times it is not.

The only way to successfully correct the above issues is to close KeePassXC, remove all YubiKeys and reinsert them, then restart KeePassXC. This is problematic, as other apps which are using the SmartCard feature of one of the YubiKeys quits (for valid security reasons) if their YubiKey is removed.

### Steps to Reproduce

The most consistent way to reproduce this problem is to:
1) Insert two YubiKeys configured with Challenge-Response and required Touch. 
2) Open a kdbx file which requires one of the keys.
3) Switch user to a different user (which automatically closes the kdbx file).
4) Switch user back to the original user.
5) Attempt to reopen the kdbx file.

### Expected Versus Actual Behavior

Expected: 
To correctly automatically recognize all YubiKeys present and have those keys function properly without having to unplug them and plug them back in.

Actual: 
Doesn't find any YubiKeys.
Scan doesn't find all YubiKeys.
YubiKeys found are often not functional. Keys may work with retries, or they may not. Retries are often not easily performed, especially on 'save' operations.
When a YubiKey error occurs on save, the kdbx file may or may not have been actually saved.

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.7.10
Revision: b342be4

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.7
CPU architecture: arm64
Kernel: darwin 23.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```

### Operating System

macOS

### Linux Desktop Environment

None

### Linux Windowing System

None

### PR DESCRIPTION
**Pull request by droidmonkey**
Fixes #11998
Fixes #11870 

Avoids UI lockups by removing several unnecessary mutex blocks  and avoiding redundant key detection calls.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and include helpful comments. )
Tested on windows with a Yubikey

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by xboxones1** [comment]
It also fixes this https://github.com/keepassxreboot/keepassxc/issues/11471 and I think too https://github.com/keepassxreboot/keepassxc/issues/11870

**Comment by droidmonkey** [comment]
If it does than great! I didn't test those scenarios yet. On the surface those appear to be the same problem.

File: src/keys/drivers/YubiKey.h [hunk 1]
```diff
@@ -84,14 +84,14 @@ class YubiKey : public QObject
...
-    void findValidKeys(const QMutexLocker& locker);
-
     static YubiKey* m_instance;
 
     QTimer m_interactionTimer;
     bool m_initialized = false;
+    bool m_findingKeys = false;
     QString m_error;
 
+    // Prevents multiple simultaneous operations on hardware keys
```
Comment (w15eacre) [inline src/keys/drivers/YubiKey.h:95]: From what I can see, the class operates in a multithreaded context, but internal fields aren't properly synchronized. I originally assumed the existing mutex covers this, but it looks like we may need a separate mutex for internal state.
Please correct me if I'm mistaken.

Comment (droidmonkey) [reply src/keys/drivers/YubiKey.h:95]: I don't understand your comment, can you elaborate? The problem this PR solves is temporary deadlocks caused by "protecting" data that is actually not accessed from any other thread besides the main one. Preventing access to the data while a hardware key operation is still in progress isn't required or desired. This is because when the hardware operation is done, a signal is emitted informing the original caller to check the data value.

Comment (w15eacre) [reply src/keys/drivers/YubiKey.h:95]: You didn’t understand my question, but you gave me an answer anyway))

It’s interesting that the class members don’t require protection because they are only used from the main thread. However, the code doesn’t guarantee this. Maybe consider adding a check or a comment, since it’s not immediately obvious.

Why do we need this static mutex here if the class is a singleton.
By the way, isn’t the instance() function thread-safe?

Comment (droidmonkey) [reply src/keys/drivers/YubiKey.h:95]: So have to look at this a couple ways, what are we trying to protect against? In this case its multiple threads trying to access a single physical asset, the hardware key. The mutex currently does that, exclusively, through this PR.

Do we need to protect read-access to `m_usbKeys`, `m_pcscKeys`, and `m_connectedKeys`? There certainly is an argument that you could get inconsistent data in between a couple of those data copy calls. However, accessing those values are generally done after the complete signal is issued.

I also introduced a block for duplicative async calls so that slightly offset search requests don't end up clearing and setting these values back to back. That was actually the big problem here in that opening 2+ tabs at once would cause this to happen and each tab would have inconsistent findings.

A workaround to having to mutex block these values is to include them as part of the complete signal. So instead of just a boolean you would actually return the unified key set and the number of connected keys.

Comment (w15eacre) [reply src/keys/drivers/YubiKey.h:95]: You mentioned an implicit contract that these members should only be read after the signal is emitted. However, a consumer of this code may not be aware of that. I suggest adding documentation or providing a clear guarantee to enforce this behavior. That would make the code more maintainable.

Comment (droidmonkey) [reply src/keys/drivers/YubiKey.h:95]: After further review, I think this is good as it stands.

**Comment by droidmonkey** [comment]
I have another change i want to make

File: src/gui/osutils/winutils/DeviceListenerWin.cpp [hunk 2]
```diff
@@ -56,7 +56,6 @@ void DeviceListenerWin::registerHotplugCallback(bool arrived,
             regex += QString("PID_%1&").arg(productId, 0, 16).toUpper();
         }
     }
-    regex += QString(".*$"); // Qt won't match otherwise
```
Comment (phoerious) [inline src/gui/osutils/winutils/DeviceListenerWin.cpp:59]: Why was this needed? Is this a left-over of QRegExp? I can't really find any info about changes in the anchoring behaviours.

Comment (droidmonkey) [reply src/gui/osutils/winutils/DeviceListenerWin.cpp:59]: I added that before _in error_ thinking this was a qt problem. Instead it was an string over read due to incorrectly using the size parameter (code in other function). We were pulling in junk data (and somehow not causing a crash 🤯) and regexing junk. That no longer happens.

**Review by phoerious — APPROVED** [review]
