### PR TITLE
Passkeys: Fix ordering of clientDataJSON

### LINKED ISSUE #12116: Fix ordering of passkey clientDataJSON
We currently send the clientDataJSON payload in the following order: 

`{“challenge":"<base64url>",<clientDataFields>,"type":"webauthn.get"}`

this causes issues with clients that are following the limited parsing rules. Those rules prescribe a strict order of: 

`{"type":"webauthn.get","challenge":"<base64url>", <clientDataFields>}`

We need to reorder our fields _prior to signing_ the payload and sending it off.

Reference: https://w3c.github.io/webauthn/#clientdatajson-serialization
Original Thread: https://xcancel.com/slovaye/status/1925394819272384860

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
`clientDataJSON` which is returned with the response object when registering or authenticating a passkey sorts the JSON with keys. The JSON must be written in a certain order: https://w3c.github.io/webauthn/#clientdatajson-serialization.

Qt's JSON implementation always sorts the object. by key The fix is using a plain QString -> QByteArray conversion to keep the order intact.

Fixes #12116.

## Screenshots
[NOTE]: # ( Do not include screenshots of your actual database! )
[TIP]:  # ( Use View -> Allow Screen Capture )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and include helpful comments. )
Manually. To actually verify this, breakpoints must be set to the extension side:
https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/content/passkeys.js#L39
https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/content/passkeys.js#L51

Then convert the Uint8Array to a textual form the verify the JSON order has not been changed.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/browser/PasskeyUtils.cpp [hunk 1]
```diff
@@ -352,15 +352,11 @@ ExtensionResult PasskeyUtils::buildExtensionData(QJsonObject& extensionObject) c
...
 {
-    QJsonObject clientData;
-    clientData["challenge"] = publicKey["challenge"];
-    clientData["crossOrigin"] = false;
-    clientData["origin"] = origin;
-    clientData["type"] = get ? QString("webauthn.get") : QString("webauthn.create");
-
-    return clientData;
+    return QString("{\"type\":\"%1\",\"challenge\":\"%2\",\"origin\":\"%3\",\"crossOrigin\":false}")
+        .arg((get ? QString("webauthn.get") : QString("webauthn.create")), publicKey["challenge"].toString(), origin);
```
Comment (phoerious) [inline src/browser/PasskeyUtils.cpp:359]: Since the values that can go in here are very limited, this is probably fine, but it feels icky to do it this way. Couldn't we implement a custom serialisation implementation similar to the ECMAScript example in the JCS spec? https://www.rfc-editor.org/rfc/rfc8785#name-ecmascript-sample-canonical

Comment (droidmonkey) [reply src/browser/PasskeyUtils.cpp:359]: I think this is good enough for what we want to do. If we need to do this anywhere else than we can introduce a serializer.

**Review by droidmonkey — APPROVED** [review]

File: src/browser/PasskeyUtils.cpp (hunk 1 above)
Comment (phoerious) [reply src/browser/PasskeyUtils.cpp:359]: I suppose challenge is base64, so it won't ever contain any invalid characters, right? What about origin?

Comment (droidmonkey) [reply src/browser/PasskeyUtils.cpp:359]: Origin is a url like `https://webauthn.io`

**Comment by droidmonkey** [comment]
Tested with the original site reporting the issue (https://metri.xyz) and it works flawlessly. Tested previous sites as well, works.

For some reason I still cannot get bestbuy.com to work with passkeys. I can register a passkey but cannot authenticate with it.
