### PR TITLE
Fix crash on screen lock or computer sleep

### LINKED ISSUE #10415: Random Crashes Upon Database Unlocks on Wayland, Specifically
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When running KeePassXC under Wayland, specifically (for some reason), submitting passwords to unlock a database may randomly crash KeePassXC.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Run a KDE Plasma Wayland session (Doesn't matter if Plasma 5 or 6; they both suffer from this issue.)
2. Launch KeePassXC (can either be via terminal or via `.desktop` file, but DO NOT run with `gdb (which keepassxc)`
3. Optionally attach GDB: `# gdb --pid=(pidof keepassxc)` and run `continue` once GDB is stalled shortly afterwards
4. Open KeePassXC from the task tray, if not already open
5. Attempt to authenticate an existing database and click Unlock
6. The crash _**may or may not occur upon this attempt;**_ these crashes are random but usually frequent

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC is expected to not crash upon authentication submission.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC crashes upon authentication submission.

## Context
[NOTE]: # ( Give us any additional information you may have. )

- All of the packages on my system are built with debug symbols, so if anything is missing in the GDB output, I have no idea why.
- Most of the system is built with `-O3`
- Compile flags for KeePassXC were:
```bash
CFLAGS="-march=znver2 -pipe -O2 -fno-plt -fexceptions -ftrivial-auto-var-init=pattern -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -Werror=array-bounds -fstack-clash-protection -fstack-protector-strong -fcf-protection -fPIC -ggdb3"
CXXFLAGS="-march=znver2 -pipe -O2 -fno-plt -fexceptions -ftrivial-auto-var-init=pattern -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -Werror=array-bounds -fstack-clash-protection -fstack-protector-strong -fcf-protection -fPIC -ggdb3"
LDFLAGS="-Wl,-O2,--sort-common,--as-needed,-z,relro,-z,now"
```
- System Toolchain: Clang17+LLVM17 with libc++ (Also occurs with Clang/LLVM/libc++ 16)

GDB Log: https://pastebin.com/QZg4xLXL

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.12
Debugging mode is disabled.

Operating system: Gentoo Linux
CPU architecture: x86_64
Kernel: linux 6.7.1-tkg-pds-gentoo-llvm-zen2 (https://github.com/frogging-family/linux-tkg)

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
- Botan 3.2.0
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Gentoo Linux (LLVM17)
Desktop Env: KDE
Windowing System: Wayland

### LINKED ISSUE #10432: Segfault when locking GNOME/Wayland desktop with database open
## Overview

KeePassXC crashes when locking the desktop.  New regression as of 2.7.7.

## Steps to Reproduce
1. Enable the security option `Lock databases when session is locked or lid is closed`.
2. Unlock the database.
3. Lock the GNOME desktop

## Expected Behavior
Before 2.7.7, KPXC behaved as expected.  Was still running with database locked upon session unlock.

## Actual Behavior
KPXC receives SIGSEGV before the database is locked (at least window still displays unlocked content)

## Additional information
Fedora 39/GNOME/Wayland.  KPXC build is [from the Fedora testing repo](https://bodhi.fedoraproject.org/updates/FEDORA-2024-81c843b00e).

### Debug info

```
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.12
Debugging mode is disabled.

Operating system: Fedora Linux 39 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.7.9-200.fc39.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

### backtrace

```
Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
0x00005555556b78cd in Database::transformedDatabaseKey (this=<optimized out>) at /usr/include/qt5/QtCore/qscopedpointer.h:116
Downloading source file /usr/include/qt5/QtCore/qscopedpointer.h
116         T *operator->() const noexcept                                                                                                                                                                             
(gdb) bt
#0  0x00005555556b78cd in Database::transformedDatabaseKey (this=<optimized out>) at /usr/include/qt5/QtCore/qscopedpointer.h:116
#1  0x00005555556f1dcf in Kdbx4Reader::readDatabaseImpl (this=0x55555612d390, device=0x7fffffffd040, headerData=..., key=..., db=<optimized out>)
    at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/format/Kdbx4Reader.cpp:61
#2  0x00005555556ee6df in KdbxReader::readDatabase (db=0x5555572afb40, key=..., device=0x7fffffffd040, this=<optimized out>) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/format/KdbxReader.cpp:95
#3  KeePass2Reader::readDatabase (this=<optimized out>, device=0x7fffffffd040, key=..., db=0x5555572afb40) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/format/KeePass2Reader.cpp:97
#4  0x00005555556b7bfb in Database::open (this=0x5555572afb40, filePath=..., key=..., error=0x7fffffffd108) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/core/Database.cpp:149
#5  0x000055555571d301 in DatabaseOpenWidget::clearForms (this=this@entry=0x555556e66bd0) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/gui/DatabaseOpenWidget.cpp:275
#6  0x000055555571e7f3 in DatabaseOpenWidget::load (this=0x555556e66bd0, filename=...) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/gui/DatabaseOpenWidget.cpp:241
#7  0x000055555573025f in DatabaseWidget::switchToOpenDatabase (this=0x5555563a8100, filePath=...) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/gui/DatabaseWidget.cpp:1355
#8  0x0000555555736d8d in DatabaseWidget::lock (this=0x5555563a8100) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/gui/DatabaseWidget.cpp:1790
#9  0x00005555557200ee in DatabaseTabWidget::lockDatabases (this=0x555555dc4f60) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/gui/DatabaseTabWidget.cpp:666
#10 0x00007ffff64e92d8 in doActivate<false> (sender=0x555556052c90, signal_index=3, argv=0x7fffffffd380) at kernel/qobject.cpp:3937
#11 0x00007ffff64e92d8 in doActivate<false> (sender=0x555556052ba0, signal_index=3, argv=0x7fffffffd450) at kernel/qobject.cpp:3937
#12 0x00005555556abd20 in ScreenLockListenerDBus::qt_metacall (this=0x555556052ba0, _c=QMetaObject::InvokeMetaMethod, _id=3, _a=0x7fffffffd5a0)
    at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/redhat-linux-build/src/keepassx_core_autogen/FUIKO5VHUE/moc_ScreenLockListenerDBus.cpp:141
#13 0x00007ffff759438b in QDBusConnectionPrivate::deliverCall (this=<optimized out>, object=<optimized out>, msg=..., metaTypes=..., slotIdx=<optimized out>) at qdbusintegrator.cpp:1001
#14 0x00007ffff64df9fb in QObject::event (this=0x555556052ba0, e=0x7fffe001a010) at kernel/qobject.cpp:1347
#15 0x00007ffff77aeb95 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x555556052ba0, e=0x7fffe001a010) at kernel/qapplication.cpp:3640
#16 0x00007ffff64b4e78 in QCoreApplication::notifyInternal2 (receiver=0x555556052ba0, event=0x7fffe001a010) at kernel/qcoreapplication.cpp:1064
#17 0x00007ffff64b5092 in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>) at kernel/qcoreapplication.cpp:1462
#18 0x00007ffff64b8325 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x555555b68570) at kernel/qcoreapplication.cpp:1821
#19 0x00007ffff64b85dd in QCoreApplication::sendPostedEvents (receiver=<optimized out>, event_type=<optimized out>) at kernel/qcoreapplication.cpp:1680
#20 0x00007ffff65078cf in postEventSourceDispatch (s=0x555555d149e0) at kernel/qeventdispatcher_glib.cpp:277
#21 0x00007ffff4b11e5c in g_main_dispatch (context=0x7fffe0000ec0) at ../glib/gmain.c:3476
#22 g_main_context_dispatch_unlocked (context=0x7fffe0000ec0) at ../glib/gmain.c:4284
#23 0x00007ffff4b6cf18 in g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7fffe0000ec0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4349
#24 0x00007ffff4b0fad3 in g_main_context_iteration (context=0x7fffe0000ec0, may_block=1) at ../glib/gmain.c:4414
#25 0x00007ffff65073b9 in QEventDispatcherGlib::processEvents (this=0x555555d017e0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#26 0x00007ffff64b383b in QEventLoop::exec (this=this@entry=0x7fffffffda80, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#27 0x00007ffff64bbacb in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#28 0x00007ffff6960efd in QGuiApplication::exec () at kernel/qguiapplication.cpp:1863
#29 0x00007ffff77aeb09 in QApplication::exec () at kernel/qapplication.cpp:2832
#30 0x000055555563d3a5 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/main.cpp:215
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

### LINKED ISSUE #10455: Crash on Windows after PC wakes up since 2.7.7
## Overview

Since the update from 2.7.6 to 2.7.7 I occasionally get crashes when the PC wakes up and I get this shown on the unlock screen.

Screenshot 2024-03-12 082145

It happened four times this week and never before that in the last year.

## Steps to Reproduce

I haven't figured out a way to reproduce, I only know this:

1) Have KeepassXC running
2) Put the PC to sleep
3) Wake up the PC

## Expected Behavior

No crash

## Actual Behavior

Crash

## Context

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #10455
* Fixes #10432
* Fixes #10415

Prevent setting critical key components to nullptr when database data is cleared. This can result in a crash due to race condition between threads.

Added a bunch of asserts to detect this problem and if guards to prevent actual crashes.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by zGadli** [comment]
How did you properly mention issues in the PR? Usually, I write #xxxx where x are the numbers. If you could teach me how to properly mention an issue like you I would be grateful. :)

**Comment by carun** [comment]
I can help test this if there's a build available as I'm able to reproduce the issue consistently.

**Comment by old-pigeon** [comment]
Also able to reproduce 100%, let me know when I can test.

**Comment by dimitris-personal** [comment]
Tried this patch on top of 2.7.7 and still got the crash on session lock, steps/environment same as #10432.

**Comment by droidmonkey** [comment]
You got the same stack trace? That wouldn't be possible.

**Comment by dimitris-personal** [comment]
Hmm, the stack trace looks the same?

```
Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
0x0000555971c278cd in Database::transformedDatabaseKey (this=<optimized out>) at /usr/include/qt5/QtCore/qscopedpointer.h:116
warning: 116	/usr/include/qt5/QtCore/qscopedpointer.h: No such file or directory
(gdb) bt
#0  0x0000555971c278cd in Database::transformedDatabaseKey (this=<optimized out>) at /usr/include/qt5/QtCore/qscopedpointer.h:116
#1  0x0000555971c61dcf in Kdbx4Reader::readDatabaseImpl (this=0x55597342a070, device=0x7ffcf2b000c0, headerData=..., key=..., db=<optimized out>)
    at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/format/Kdbx4Reader.cpp:61
#2  0x0000555971c5e6df in KdbxReader::readDatabase (db=0x555973fca910, key=..., device=0x7ffcf2b000c0, this=<optimized out>) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/format/KdbxReader.cpp:95
#3  KeePass2Reader::readDatabase (this=<optimized out>, device=0x7ffcf2b000c0, key=..., db=0x555973fca910) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/format/KeePass2Reader.cpp:97
#4  0x0000555971c27bfb in Database::open (this=0x555973fca910, filePath=..., key=..., error=0x7ffcf2b00188) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/core/Database.cpp:149
#5  0x0000555971c8d301 in DatabaseOpenWidget::clearForms (this=this@entry=0x555973a89040) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/gui/DatabaseOpenWidget.cpp:275
#6  0x0000555971c8e7f3 in DatabaseOpenWidget::load (this=0x555973a89040, filename=...) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/gui/DatabaseOpenWidget.cpp:241
#7  0x0000555971ca025f in DatabaseWidget::switchToOpenDatabase (this=0x555972fb4bc0, filePath=...) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/gui/DatabaseWidget.cpp:1355
#8  0x0000555971ca6d8d in DatabaseWidget::lock (this=0x555972fb4bc0) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/gui/DatabaseWidget.cpp:1790
#9  0x0000555971c900ee in DatabaseTabWidget::lockDatabases (this=0x5559729d2c90) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/gui/DatabaseTabWidget.cpp:666
#10 0x00007f4789ce92d8 in void doActivate<false>(QObject*, int, void**) () from /lib64/libQt5Core.so.5
#11 0x00007f4789ce92d8 in void doActivate<false>(QObject*, int, void**) () from /lib64/libQt5Core.so.5
#12 0x0000555971c1bd20 in ScreenLockListenerDBus::qt_metacall (this=0x555972c21fc0, _c=QMetaObject::InvokeMetaMethod, _id=3, _a=0x7ffcf2b00620)
    at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/redhat-linux-build/src/keepassx_core_autogen/FUIKO5VHUE/moc_ScreenLockListenerDBus.cpp:141
#13 0x00007f478b65438b in QDBusConnectionPrivate::deliverCall(QObject*, int, QDBusMessage const&, QVector<int> const&, int) () from /lib64/libQt5DBus.so.5
#14 0x00007f4789cdf9fb in QObject::event(QEvent*) () from /lib64/libQt5Core.so.5
#15 0x00007f478afaeb95 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#16 0x00007f4789cb4e78 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#17 0x00007f4789cb8325 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib64/libQt5Core.so.5
#18 0x00007f4789d078cf in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /lib64/libQt5Core.so.5
#19 0x00007f4788511e5c in g_main_context_dispatch_unlocked.lto_priv () from /lib64/libglib-2.0.so.0
#20 0x00007f478856cf18 in g_main_context_iterate_unlocked.isra () from /lib64/libglib-2.0.so.0
#21 0x00007f478850fad3 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#22 0x00007f4789d073b9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#23 0x00007f4789cb383b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#24 0x00007f4789cbbacb in QCoreApplication::exec() () from /lib64/libQt5Core.so.5
#25 0x0000555971bad3a5 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/keepassxc-2.7.7-2.fc39.x86_64/src/main.cpp:215
```

I built on Fedora using `fedpkg mockbuild` after adding this PR's patch to the spec file...

**Comment by droidmonkey** [comment]
You aren't running the code from this PR then. I removed the line item that is #4 on the trace.

**Comment by dimitris-personal** [comment]
Yeah, the patch is not being applied in the build for some reason... I rebased it to 2.7.7 but still get that `Database::open()` frame.

**Comment by dimitris-personal** [comment]
Yup, circled back to this and I was indeed missing the patch application in the spec file.  Built 2.7.7 plus this PR's patch and can no longer reproduce #10432.

I did have to disable tests in order for the rpm to build, probably what's also behind the CI failures here (no teamcity access on my end obviously).

**Comment by droidmonkey** [comment]
Yah I just fixed the test problems, needed to revert some code changes I made that went a little too far.

File: src/core/Database.h [hunk 1]
```diff
@@ -188,30 +188,33 @@ public slots:
...
+            transformedDatabaseKey.reset(new PasswordKey());
+            challengeResponseKey.reset(new PasswordKey());
 
             key.reset();
-            kdf.reset();
 
-            publicCustomData.clear();
+            // Default to AES KDF, KDBX4 databases overwrite this
+            kdf.reset(new AesKdf(true));
+            kdf->randomizeSeed();
```
Comment (phoerious) [inline src/core/Database.h:217]: Is this a good idea? Shouldn't be default to something more secure?

**Review by phoerious — APPROVED** [review]

File: src/core/Database.h (hunk 1 above)
Comment (droidmonkey) [reply src/core/Database.h:217]: I tried to fix this, but we would have to recode a bunch of places that make assumptions on kdf settings. This is specifically so for kdbx3 reader and the encryption settings widget. Note the original code set this as well, but it did so only once and did not properly reset these settings when the database object was reset.

**Comment by benediktwerner** [comment]
Any chance we could get a release with this fix? The constant crashes are kinda annoying, so I was hoping we'd get an update soon.

**Comment by droidmonkey** [comment]
Yes 2.7.8, but use https://snapshot.keepassxc.org for now if you like
