### PR TITLE
Fix problems with the hide/restore functionality on the tray icon (issue #1595) (redone)

### LINKED ISSUE #1595: KeePassXC  immediately minimizes to tray when restoring from tray icon
When starting KeePassXC with "Minimize window at application startup" and "Hide window system tray when minimizes" immediately minimizes to tray when restoring from tray icon for the first time.
This happens with XFCE with or without composite manager (xfwm4 or compton), didn't try with other desktop environment.

## Expected Behavior

Main window should minimized when restored from system tray

## Current Behavior

Window always minimizes immediately when restored for the first time
[Issue video demo](https://gfycat.com/FaroffAppropriateBufeo)

## Steps to Reproduce (for bugs)

1. Go to Tools > Settings
2. Enable "Minimize window at application startup" and "Hide window system tray when minimizes"
3. Restart KeePassXC

## Debug Info

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.14.22-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

XFCE4 - 4.12

### PR DESCRIPTION
**Pull request by joanbm**
**Opening another PR since PR #1700 had the wrong source branch. Sorry for the annoyance...**

Fix/work around tray issues on some Linux systems such as Arch Linux, and Windows. Fixes all cases explained in issue #1595.

## Description
Basically there are two separate issues at play there:
* **The Linux issue:** Sometimes instead of restoring, the KeePassXC window just flickers when restoring the window from the tray. This mostly happens if both the "minimize to tray" and "minimize at startup" options are enabled, and only on the first restore, though sometimes it's enough to set the  "minimize to tray" option is enough and the flicker happens once per every restore, thus the tray having a flicker-restore-hide cycle instead of a restore-hide cycle. I'm not sure why it only happens on Arch but not on Ubuntu, and why it only happens sometimes, but I have found what seems to be the trigger of the issue: If one both minimizes and hides the window by code (or minimizes the window without showing it at all), it seems that a spurious changeEvent with isMinimized()=true is received sometimes when the main window is restored, which causes the bug. I imagine that, internally on the Qt Linux implementation, hiding the window causes further events to be enqueued or something similar, and when restoring the window some events from when the window was minimized are notified.

This can happen both on start (this is the case of the original bug report), if `minimizeOnStartup=true` and `minimizeToTray=true`, then the window is minimized but not shown:

```
    // start minimized if configured
    bool minimizeOnStartup = config()->get("GUI/MinimizeOnStartup").toBool();
    bool minimizeToTray    = config()->get("GUI/MinimizeToTray").toBool();
    if (minimizeOnStartup) {
        mainWindow.setWindowState(Qt::WindowMinimized); // --> MINIMIZE
    }
    if (!(minimizeOnStartup && minimizeToTray)) {
        mainWindow.show(); // --> NO SHOW
}
```

Or when clicking on the tray icon to hide the window, the window is both minimized and hidden by code on `hideWindow()` (this is what is causing my flicker-restore-minimize cycle sometimes):

```
void MainWindow::hideWindow()
{
    saveWindowInformation();
#ifndef Q_OS_MAC
    setWindowState(windowState() | Qt::WindowMinimized); // --> MINIMIZE
#endif
    QTimer::singleShot(0, this, SLOT(hide())); // --> HIDE

    if (config()->get("security/lockdatabaseminimize").toBool()) {
        m_ui->tabWidget->lockDatabases();
    }
}
```

* **The Windows issue:** This is a completely separate issue. The flicker on restore issue explained previously doesn't happen on Windows, but on the other hand it seems impossible to hide the window by clicking on the tray icon on Windows. On `toggleWindow()`, there's a `QApplication::activeWindow() == this` check:

```
void MainWindow::toggleWindow()
{
    if ((QApplication::activeWindow() == this) && isVisible() && !isMinimized()) {
        hideWindow();
    } else {
```

On Windows, when clicking on the tray icon when the window is visible, `QApplication::activeWindow() = NULL`. I think this is due to differences in window focus behavior between Windows and Linux (I believe Windows removes the focus from the window when clicking on the tray).

## Motivation and context
This change is required in order to avoid issues when hiding and restoring the KeePassXC windows from tray. One of those issues happen on Windows, and the other in some Linux systems (what exactly causes some systems and desktop environments to be affected and some not to be affected is not known, though it probably depends on the Qt version, but must also depend on some environment condition since on my system the bug only happens sometimes).

For the Linux issue, I avoid both minimizing and hiding the window at the same time by code. It should suffice to only hide the window if the event is caused by a tray icon click.

For the Windows issue, I just removed the check for QApplication::activeWindow() == this, I think it is unreliable and the other checks in the same line (which were added later) should suffice alone.

Fixes #1595

## How has this been tested?

I set up some VMs for manual testing of the issue, and I found this:

* **Local Arch Linux + XFCE  (Updated):** I experience the flicker-restore-minimize cycle sometimes, and sometimes only the flicker on the first time like in the original report. No idea on what makes the difference. After applying the changes, the bug disappears and no regressions are found.

Environment details:

```
Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.7-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

* **Local Arch Linux + LXDE (Updated):** I experience the flicker like in the original report. After applying the changes, the bug disappears and no regressions are found.
* **VM Ubuntu 17.10 + Unity,KDE,LXDE (Updated clean install):** No bug experienced. After applying the changes, no regressions are found.
* **VM Arch Linux + LXDE (Updated clean install):** I experience the flicker like in the original report. After applying the changes, the bug disappears and no regressions are found.
* **Local Windows 10  (Updated):** No flicker on restore, but the window cannot be hidden by clicking on the tray icon. After applying the changes, the bug disappears and no regressions are found.
* **VM Windows 7 (Updated clean install):** No flicker on restore, but the window cannot be hidden by clicking on the tray icon.  After applying the changes, the bug disappears and no regressions are found.

I also ran all the automatic tests on my local Arch Linux system and they passed.

## Screenshots (if appropriate):
Windows issue: https://imgur.com/fJW62v7
Linux issue (flicker on first restore): https://imgur.com/cES8olj

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Builds are failing

**Comment by joanbm** [comment]
@droidmonkey They work on my Linux and Windows machines... not sure what's different in the CI environment.

**Comment by joanbm** [comment]
Fixed, looks like the CI environment has no tray and therefore the tray icon can't be tested there, so it is now skipped.

File: src/gui/MainWindow.cpp [hunk 1]
```diff
@@ -971,7 +971,10 @@ void MainWindow::trayIconTriggered(QSystemTrayIcon::ActivationReason reason)
 void MainWindow::hideWindow()
 {
     saveWindowInformation();
-#ifndef Q_OS_MAC
```
Comment (droidmonkey) [inline src/gui/MainWindow.cpp]: Why remove this guard for MacOS?

File: src/gui/MainWindow.cpp [hunk 2]
```diff
@@ -983,7 +986,7 @@ void MainWindow::hideWindow()
 
 void MainWindow::toggleWindow()
 {
-    if ((QApplication::activeWindow() == this) && isVisible() && !isMinimized()) {
```
Comment (droidmonkey) [inline src/gui/MainWindow.cpp]: I'm afraid this will cause undesirable effects on MacOS

Comment (joanbm) [reply src/gui/MainWindow.cpp]: @droidmonkey Can you elaborate? A priori I can't see it causing problems, since it looks like an old check (it was there before the other two conditions were implemented), it works on Windows and Linux, and it wasn't added specifically for Mac, though it would be nice for someone to check.

File: src/gui/MainWindow.cpp (hunk 1 above)
Comment (joanbm) [reply src/gui/MainWindow.cpp]: Good catch... @phoerious said in issue #1595 that isn't probably an ancient code from the time Mac didn't have a tray icon, and I remember doing a git blame, but it looks like I did it wrong, because it's rather the opposite... it was introduced in 8d6db27b3430543e6f262a566be0cbd0331a404e when the tray icon on Mac was **introduced**... I will add it again, along with a TODO asking for further comments.

File: src/gui/MainWindow.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/gui/MainWindow.cpp]: I'm just saying that we edited it and thoroughly tested on Linux and Windows but not Mac. What I meant to say is "this needs to be tested on Mac to ensure no undesirable effects"

Comment (weslly) [reply src/gui/MainWindow.cpp]: @droidmonkey I tested yesterday and saw no problems toggling the window from the tray icon on Mac.

**Comment by weslly** [comment]
I just noticed the "minimize on start" option doesn't work at all on macOS with or without this PR.

**Comment by TheZ3ro** [comment]
@weslly I think we can fix the mac minimize on start in a new PR

@joanbm please rebase

**Comment by joanbm** [comment]
@TheZ3ro Done, all commits in release/2.3.2 are not in my fork.

**Comment by TheZ3ro** [comment]
Thanks fot the contribution! :tada:
