### PR TITLE
FdoSecrets: do not share entry <-> item property by multiple unlock prompts

### LINKED ISSUE #7753: Crash in fdosecrets/objects/Prompt.cpp
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use vscode and configure secret service integration
2. open mutiple vscode windows, all requesting the same entry
3. acklowledge the first prompt
4. acklowledge the second prompt -> keepassxc crashes

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
No crash

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
crash

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION: 2.7.0
Revision: REVISION

I rebuilt keepassxc from source, attached gdb and get the following stacktrace during the crash:

```
QList<QDBusObjectPath>::node_construct (this=<optimized out>, n=0x564c715db850, t=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:465
465         if (QTypeInfo<T>::isLarge || QTypeInfo<T>::isStatic) n->v = new T(t);
(gdb) bt
#0  QList<QDBusObjectPath>::node_construct (this=<optimized out>, n=0x564c715db850, t=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:465
#1  QList<QDBusObjectPath>::append (t=..., this=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:634
#2  QList<QDBusObjectPath>::append (this=<optimized out>, t=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:620
#3  0x0000564c6f2ffbf1 in QList<QDBusObjectPath>::operator+= (t=..., this=0x7fcc80015d50) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:399
#4  FdoSecrets::UnlockPrompt::itemUnlockFinished (this=0x7fcc80015d10, decisions=..., forFutureEntries=<optimized out>)
    at /home/nic/projects/keepassxc/src/fdosecrets/objects/Prompt.cpp:343
#5  0x00007fcc94a63dfe in QtPrivate::QSlotObjectBase::call (a=0x7ffd162952a0, r=0x7fcc80015d10, this=0x564c740d5110)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#6  doActivate<false> (sender=0x7fcc800181b0, signal_index=10, argv=0x7ffd162952a0) at kernel/qobject.cpp:3886
#7  0x00007fcc94a5d1c7 in QMetaObject::activate (sender=sender@entry=0x7fcc800181b0, m=m@entry=0x564c6f5e9580 <AccessControlDialog::staticMetaObject>, 
    local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7ffd162952a0) at kernel/qobject.cpp:3946
#8  0x0000564c6f2bacb7 in AccessControlDialog::finished (this=this@entry=0x7fcc800181b0, _t1=..., _t2=<optimized out>, _t2@entry=AuthDecision::Undecided)
    at /home/nic/projects/build/keepassxc/src/fdosecrets/fdosecrets_autogen/IMAN36LHMA/moc_AccessControlDialog.cpp:156
#9  0x0000564c6f2cfb09 in AccessControlDialog::dialogFinished (this=0x7fcc800181b0, result=<optimized out>)
    at /home/nic/projects/keepassxc/src/fdosecrets/widgets/AccessControlDialog.cpp:198
#10 0x00007fcc94a63dfe in QtPrivate::QSlotObjectBase::call (a=0x7ffd16295490, r=0x7fcc800181b0, this=0x564c7409d1d0)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#11 doActivate<false> (sender=0x7fcc800181b0, signal_index=7, argv=0x7ffd16295490) at kernel/qobject.cpp:3886
#12 0x00007fcc957bff02 in QDialog::finished(int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007fcc94a63dfe in QtPrivate::QSlotObjectBase::call (a=0x7ffd162955b0, r=0x7fcc800181b0, this=0x564c740ead90)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#14 doActivate<false> (sender=0x564c740e6c80, signal_index=9, argv=0x7ffd162955b0) at kernel/qobject.cpp:3886
#15 0x00007fcc956ad3f6 in QAbstractButton::clicked(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007fcc956ad61e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fcc956aeaf3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007fcc956aecb5 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007fcc955f7d76 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007fcc95753893 in QPushButton::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007fcc955b4dc3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007fcc955bddc7 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007fcc94a2cd7a in QCoreApplication::notifyInternal2 (receiver=0x564c740e6c80, event=0x7ffd16295b70)
    at ../../include/QtCore/5.15.3/QtCore/private/../../../../../src/corelib/thread/qthread_p.h:332
#24 0x00007fcc955bd0c7 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007fcc95612f64 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007fcc95616284 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007fcc955b4dc3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007fcc955bdbd8 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007fcc94a2cd7a in QCoreApplication::notifyInternal2 (receiver=0x564c740f2ef0, event=0x7ffd16295ff0)
    at ../../include/QtCore/5.15.3/QtCore/private/../../../../../src/corelib/thread/qthread_p.h:332
#30 0x00007fcc94e10578 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#31 0x00007fcc94e11be5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#32 0x00007fcc94de97bc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#33 0x00007fcc908491ce in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#34 0x00007fcc92fd717d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007fcc92fd7400 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007fcc92fd74a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fcc94a87642 in QEventDispatcherGlib::processEvents (this=0x564c7113ee40, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#38 0x00007fcc94a2b87b in QEventLoop::exec (this=this@entry=0x7ffd16296390, flags=..., flags@entry=...)
``` 

It seems to be caused here:
``` 
#4  FdoSecrets::UnlockPrompt::itemUnlockFinished (this=0x7fcc80015d10, decisions=..., forFutureEntries=<optimized out>)
    at /home/nic/projects/keepassxc/src/fdosecrets/objects/Prompt.cpp:343
343                     m_unlocked += item->objectPath();
(gdb) p item
$1 = (FdoSecrets::Item *) 0x0
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

### PR DESCRIPTION
**Pull request by Aetf**
Fixes #7753

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested manually. Existing unit tests pass.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/fdosecrets/objects/Prompt.cpp [hunk 1]
```diff
@@ -303,9 +303,7 @@ namespace FdoSecrets
                     }
                     continue;
                 }
-                // attach a temporary property, so later we can get the item
-                // back from the dialog's result
-                entry->setProperty(FdoSecretsBackend, QVariant::fromValue(item.data()));
+                m_entry2items[entry] = item.data();
```
Comment (droidmonkey) [inline src/fdosecrets/objects/Prompt.cpp]: Prefer this to be named `m_entryToItems` and use entry->uuid() instead of a pointer since we don't actually need the entry pointer itself.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/fdosecrets/objects/Prompt.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/fdosecrets/objects/Prompt.cpp]: Never mind, I took care of it.

**Review by droidmonkey — APPROVED** [review]
