### PR TITLE
Browser: Fix cancel with database unlock dialog

### LINKED ISSUE #11430: Nothing happens if you click "reopen database" after closing the popup window the first time.
"Reopen database" doesn't work if you close the pop-up window and reopen it again.

## Expected Behavior
Pop-up to open database appears when you click "reopen database".

## Current Behavior
Nothing happens if you click "reopen database".

## Steps to Reproduce (for bugs)
1. Click the browser extension
2. Click "reopen database" when your database is in locked state
3. Close the pop-up window
4. Click "reopen database" again, nothing happens
5. Closing and reopening keepassxc app or successful unlocks will cause it to work again, but only once

## Debug info
KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.4
Operating system: Windows 10
Browser: Brave (Chromium) v1.71.121

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
If database unlock dialog is canceled, the window state is not handled correctly. The following fixes needed to be done:
- Listen for `databaseUnlockDialogFinished` signal in `BrowserService`.
- If the dialog was canceled, set `m_bringToFrontRequested` to `false` and hide the window, similar to database unlock.
- If the dialog was canceled, set browser integration specific boolean `m_databaseOpenInProgress` in `DatabaseTabWidget` to `false` as well, so emitting a new dialog request will succeed.

Fixes #11430

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually. Steps to verify (and reproduce the error without the fix):
- Click "Reopen Database"
- Cancel the database unlock popup
- Try clicking "Reopen Database" again

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -1678,6 +1682,17 @@ void BrowserService::activeDatabaseChanged(DatabaseWidget* dbWidget)
     m_currentDatabaseWidget = dbWidget;
 }
 
+void BrowserService::handleDatabaseUnlockDialogFinished(bool accepted, DatabaseWidget* dbWidget)
+{
+    // User canceled the database open dialog
+    if (dbWidget && !accepted && m_bringToFrontRequested) {
+        if (m_bringToFrontRequested) {
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp]: You already test for this condition in the line above

File: src/gui/DatabaseTabWidget.cpp [hunk 2]
```diff
@@ -821,6 +821,11 @@ void DatabaseTabWidget::handleDatabaseUnlockDialogFinished(bool accepted, Databa
         m_dbWidgetPendingLock = dbWidget;
     }
 
+    // If browser extension requested the unlock make sure cancel is handled
+    if (intent == DatabaseOpenDialog::Intent::Browser && !accepted && m_databaseOpenInProgress) {
+        m_databaseOpenInProgress = false;
```
Comment (droidmonkey) [inline src/gui/DatabaseTabWidget.cpp]: I'd think we would always want to set this to false

**Review by droidmonkey — CHANGES_REQUESTED** [review]

**Review by droidmonkey — APPROVED** [review]

**Review by droidmonkey — APPROVED** [review]
