### PR TITLE
Fix clearing clipboad on Gnome

### LINKED ISSUE #4126: Keyboard clipboard is *not* cleared after timeout
The clipboard is not cleared according to the relevant security setting.

## Steps to Reproduce

1. In KeePassXC go to Tools → Settings → Security
2. Tick "Clear clipboard after" and set the timeout to "10 sec"
3. Open a password database
4. Highlight an entry with a password and press <kbd>Ctrl-c</kbd>
5. Wait for more than 10 seconds
6. Focus another window and paste **using the keyboard** (<kbd>Ctrl-v</kbd> or <kbd>Ctrl-Shift-v</kbd>, depending on the application)

## Expected Behavior

Nothing should be pasted.

## Current Behavior

The password is pasted!

## Context

The mouse clipboard *is* cleared.

I'm running vanilla Ubuntu 19.10 (with GNOME) with the latest updates. I'm not running any custom clipboard managers as far as I know.

This *did* work on every other KeePassXC version + OS + WM combination I've ever tried before.

## Debug Info

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-24-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Prefer clearing clipboard by explicitly setting the clipboard
to an empty string. Qt's QClipboard::clear() method is unreliable
under X11 environment.

* Fixes #4126

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Gnome and Windows 10.

Needs to be tested on:
- [x] KDE
- [x] XFCE
- [x] macOS

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

File: src/gui/Clipboard.cpp [hunk 1]
```diff
@@ -44,28 +44,26 @@ Clipboard::Clipboard(QObject* parent)
...
 #ifdef Q_OS_MACOS
     mime->setText(text);
     mime->setData("application/x-nspasteboard-concealed-type", text.toUtf8());
     clipboard->setMimeData(mime, QClipboard::Clipboard);
 #else
-    const QString secretStr = "secret";
-    QByteArray secretBa = secretStr.toUtf8();
     mime->setText(text);
-    mime->setData("x-kde-passwordManagerHint", secretBa);
+    mime->setData("x-kde-passwordManagerHint", QString("secret").toUtf8());
```
Comment (phoerious) [inline src/gui/Clipboard.cpp]: This should be `QByteArrayLiteral("secret")`.

Comment (droidmonkey) [reply src/gui/Clipboard.cpp]: done, I also added a nullptr check of clipboard in the setText function.
