### PR TITLE
Passkeys: Fix default timeout on authentication

### LINKED ISSUE #10148: 0 timeout on passkey authentication
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When authenticating with a passkey at login.wordpress.org, which does not specify a `timeout` when attempting to authenticate, the KeePassXC popup has a timeout of zero and closes almost immediately.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an account on wordpress.org and add a passkey.
2. In a separate browser or incognito window, visit login.wordpress.org to log in.
3. (When I try it, the page for the passkey initially doesn't trigger KeePassXC at all, going straight to Firefox's built-in hardware dialog. Cancelling that and clicking "Retry" makes KeePassXC prompt.)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A passkey confirmation dialog with a reasonable timeout value.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The dialog has a timeout of zero, and closes itself almost immediately.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Perhaps the code at https://github.com/keepassxreboot/keepassxc/blob/a8cfefe6c8a4c10f4a215a003a98148b56840474/src/browser/BrowserService.cpp#L712 should do like https://github.com/keepassxreboot/keepassxc/blob/a8cfefe6c8a4c10f4a215a003a98148b56840474/src/browser/BrowserService.cpp#L648 ?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: cc0530b

Qt 5.15.10
Debugging mode is disabled.

Operating system: Debian GNU/Linux trixie/sid
CPU architecture: x86_64
Kernel: linux 6.6.8-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Window Maker
Windowing System: X11
Browser: Firefox 121.0

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
If server has not set a timeout during Passkeys authentication, it should be set to a default value.

Fixes #10148.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually, by setting timeout to zero from the extension side.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -709,7 +709,7 @@ QJsonObject BrowserService::showPasskeysAuthenticationPrompt(const QJsonObject&
         return getPublicKeyCredentialFromEntry(entries.first(), publicKey, origin);
     }
 
-    const auto timeout = publicKey["timeout"].toInt();
+    const auto timeout = browserPasskeys()->getTimeout(userVerification, publicKey["timeout"].toInt());
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp:712]: This function is rather opaque. Is it just checking for 0 and returning X? Why not just do that?

Comment (varjolintu) [reply src/browser/BrowserService.cpp:712]: IIRC there are different default timeout values, depenging on the `userVerification`.

Comment (droidmonkey) [reply src/browser/BrowserService.cpp:712]: You are right, looks good

**Review by droidmonkey — APPROVED** [review]
