### PR TITLE
Request screen reader permission for AutoType

### LINKED ISSUE #3270: macOS: keepassxc-cli libquazip error
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Launch `keepassxc-cli` without an error, e.g.:

<details>
  <summary><code>$ keepassxc-cli -h</code></summary>

```console
Usage: keepassxc-cli [options] command
KeePassXC command line interface.

Available commands:
add            Add a new entry to a database.
clip           Copy an entry's password to the clipboard.
create         Create a new database.
diceware       Generate a new random diceware passphrase.
edit           Edit an entry.
estimate       Estimate the entropy of a password.
extract        Extract and print the content of a database.
generate       Generate a new random password.
locate         Find entries quickly.
ls             List database entries.
merge          Merge two databases.
rm             Remove an entry from the database.
show           Show an entry's information.


Options:
  --debug-info   Displays debugging information.
  -h, --help     Displays this help.
  -v, --version  Displays version information.

Arguments:
  command        Name of the command to execute.
```

</details>

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
```console
$ keepassxc-cli -h
dyld: Library not loaded: /usr/local/opt/quazip/lib/libquazip.1.dylib
  Referenced from: /usr/local/bin/keepassxc-cli
  Reason: image not found
Abort trap: 6
```

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Possibly related to #3088?

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install 2.4.3 for macOS
2. run `keepassxc-cli`

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I have verified that I can successfully run keepassxc-cli with versions 2.4.0 and 2.4.1. I have only seen this error appear with 2.4.3.

## Debug Info
```
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4
```

### LINKED ISSUE #3578: Duplicate key in macOS entitlements.
There is a duplicate key in the entitlements. It is set to conflicting values. There is constant error spam in the syslog if you have the browser extension installed with the proxy.

## Possible Solution
Remove the duplicate key and decide on the correct value.

### LINKED ISSUE #3609: macOS 10.15: Auto-type requires screen reader permission
## Expected Behavior
I am using the shortcut ALT+SHIFT+A as my auto-type. Whenever I press that combination I expect the auto-type to start either by inputting the credentials or by showing a dialog with credential options for that website/application

## Current Behavior
After updating to macOS Catalina auto-type stopped working. My shortcut starts something but for every website/application I get the error message saying:
"Couldn't find an entry that matches the window title: passwords.kdbx - KeePassXC"
When I check the auto-type settings for that website I also notice that the "Window title:" dropdown does not get populated with possible windows titles that are currently open.

## Steps to Reproduce
1. Update to macOS Catalina
2. Open browser
3. Open KeePassXC
4. Browse to website where auto-type is setup
5. Use shortcut to start auto-type
6. The error message should appear

## Context
We use KeePassXC at work with passwords that are all generated through KeePassXC so I personally don't remember any of the passwords. Currently I manually copy and paste the credentials which is more annoying but it works for now.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Fix #3609 - Request screen reader permission by faking a 1px screenshot. Thanks to MacPass for this idea.
* Fix #3578 - Remove duplicate sandbox entitlement
* Fix #3270 - Use executable path reference for libquazip

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on macOS 10.15

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

File: src/gui/macutils/AppKitImpl.mm [hunk 1]
```diff
@@ -144,6 +144,13 @@ - (void) removeGlobalMonitor:(id) monitor
 //
 - (bool) enableAccessibility
 {
+    CGImageRef screenshot = CGWindowListCreateImage(
+            CGRectMake(0, 0, 1, 1),
+            kCGWindowListOptionOnScreenOnly,
+            kCGNullWindowID,
+            kCGWindowImageDefault);
+    CFRelease(screenshot);
+
```
Comment (phoerious) [inline src/gui/macutils/AppKitImpl.mm]: Update: Actually, please add a comment as to what this does and why it is needed.

Comment (droidmonkey) [reply src/gui/macutils/AppKitImpl.mm]: Done
