### PR TITLE
FDO Secrets: Fix double free on exit

### LINKED ISSUE #4877: Crash in QtSharedPointer::CustomDeleter in some cases
## Overview
When I was testing #4848, I found that in some cases KeePassXC crashes at exit. See Steps to Reproduce for details.

I use "Release Preview Bug report" as I don't get a crash with the same steps on 2.5.4.

## Steps to Reproduce
(Steps 1 and 2 are not needed if there are no recent databases)
1. Database -> Recent Databases -> Clear History
2. Restart KeePassXC
3. Tools -> Settings
4. Change nothing and hit Cancel
5. Hit Ctrl+Q to leave KeePassXC

## Expected Behavior
KeePassXC exits cleanly

## Actual Behavior
Segmentation fault. Backtrace from gdb:
```
#0  0x0000555555618f3f in QtSharedPointer::CustomDeleter<ISettingsPage, QtSharedPointer::NormalDeleter>::execute() (this=0x555556901b20)
    at /usr/include/qt/QtCore/qsharedpointer_impl.h:186
#1  0x0000555555618ced in QtSharedPointer::ExternalRefCountWithCustomDeleter<ISettingsPage, QtSharedPointer::NormalDeleter>::deleter(QtSharedPointer::ExternalRefCountData*) (self=0x555556901b10) at /usr/include/qt/QtCore/qsharedpointer_impl.h:204                                              
#2  0x00005555555db6f5 in QtSharedPointer::ExternalRefCountData::destroy() (this=0x555556901b10)
    at /usr/include/qt/QtCore/qsharedpointer_impl.h:148
#3  0x0000555555618dee in QSharedPointer<ISettingsPage>::deref(QtSharedPointer::ExternalRefCountData*) (dd=0x555556901b10)
    at /usr/include/qt/QtCore/qsharedpointer_impl.h:456
#4  0x0000555555618a44 in QSharedPointer<ISettingsPage>::deref() (this=0x555556901b30) at /usr/include/qt/QtCore/qsharedpointer_impl.h:451
#5  0x00005555556186ec in QSharedPointer<ISettingsPage>::~QSharedPointer() (this=0x555556901b30, __in_chrg=<optimized out>)
    at /usr/include/qt/QtCore/qsharedpointer_impl.h:309
#6  0x00005555556185fa in ApplicationSettingsWidget::ExtraPage::~ExtraPage() (this=0x555556901b30, __in_chrg=<optimized out>)
    at /build/keepassxc-git/src/keepassxc/src/gui/ApplicationSettingsWidget.cpp:35
#7  0x0000555555618e5c in QList<ApplicationSettingsWidget::ExtraPage>::node_destruct(QList<ApplicationSettingsWidget::ExtraPage>::Node*, QList<ApplicationSettingsWidget::ExtraPage>::Node*) (this=0x55555618c738, from=0x55555687cb10, to=0x55555687cb28) at /usr/include/qt/QtCore/qlist.h:524    
#8  0x0000555555618af3 in QList<ApplicationSettingsWidget::ExtraPage>::dealloc(QListData::Data*) (this=0x55555618c738, data=0x55555687cb00)
    at /usr/include/qt/QtCore/qlist.h:921
#9  0x00005555556187dc in QList<ApplicationSettingsWidget::ExtraPage>::~QList() (this=0x55555618c738, __in_chrg=<optimized out>)
    at /usr/include/qt/QtCore/qlist.h:874
#10 0x000055555560c846 in ApplicationSettingsWidget::~ApplicationSettingsWidget() (this=0x55555618c6d0, __in_chrg=<optimized out>)
    at /build/keepassxc-git/src/keepassxc/src/gui/ApplicationSettingsWidget.cpp:157
#11 0x000055555560c894 in ApplicationSettingsWidget::~ApplicationSettingsWidget() (this=0x55555618c6d0, __in_chrg=<optimized out>)
    at /build/keepassxc-git/src/keepassxc/src/gui/ApplicationSettingsWidget.cpp:159
#12 0x00007ffff6c8ac3e in QObjectPrivate::deleteChildren() () at /usr/lib/libQt5Core.so.5
#13 0x00007ffff78271de in QWidget::~QWidget() () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff782755a in QWidget::~QWidget() () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff6c8ac3e in QObjectPrivate::deleteChildren() () at /usr/lib/libQt5Core.so.5
#16 0x00007ffff78271de in QWidget::~QWidget() () at /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff799b06a in QStackedWidget::~QStackedWidget() () at /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff6c8ac3e in QObjectPrivate::deleteChildren() () at /usr/lib/libQt5Core.so.5
#19 0x00007ffff78271de in QWidget::~QWidget() () at /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff782755a in QWidget::~QWidget() () at /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff6c8ac3e in QObjectPrivate::deleteChildren() () at /usr/lib/libQt5Core.so.5
#22 0x00007ffff78271de in QWidget::~QWidget() () at /usr/lib/libQt5Widgets.so.5
#23 0x00005555555ebe8e in MainWindow::~MainWindow() (this=0x7fffffffdd00, __in_chrg=<optimized out>)
    at /build/keepassxc-git/src/keepassxc/src/gui/MainWindow.cpp:574
#24 0x00005555555c58e5 in main(int, char**) (argc=1, argv=0x7fffffffdf78) at /build/keepassxc-git/src/keepassxc/src/main.cpp:132
```

## Context

KeePassXC - Version 2.6.0-snapshot
Build Type: Snapshot
Revision: c68f487

(actually c68f487 with patch #4848)

Qt 5.15.0
Debugging mode is enabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.7.2-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Arch Linux
Desktop Env: LXQt
Windowing System: X11

I use PKGBUILD modified from the AUR one to integrate patch #4848 and enable debugging. Here is the full PKGBUILD.
```
# Maintainer: Daniel Landau <daniel@landau.fi>
# Contributor: Maxqia <contrib@maxqia.com>

# The following people have contributed to keepassx-git package
# Contributor: Lev Lybin <aur@devtrue.net>
# Contributor: Jamie Macdonald <jamie.alban@gmail.com>
# Contributor: Alucryd <alucryd at gmail dot com>
# Contributor: Paolo Stivanin <admin at polslinux dot it>

pkgname=keepassxc-git
_gitname=keepassxc
pkgver=2.6.0.beta1.r3.gc68f4872
pkgrel=1
pkgdesc="Cross-platform community-driven port of KeePass Password Safe"
arch=('i686' 'x86_64')
url="https://github.com/keepassxreboot/keepassxc"
license=('GPL2')
depends=('qt5-base' 'qt5-x11extras' 'qt5-translations' 'qt5-imageformats'
         'libxtst' 'shared-mime-info' 'hicolor-icon-theme' 'desktop-file-utils'
         'yubikey-personalization' 'qt5-svg' 'qrencode' 'quazip'
         'libsodium' 'libgcrypt' 'argon2' 'zlib')
#install=keepassxc.install
makedepends=('git' 'intltool' 'cmake' 'qt5-tools')
provides=(org.freedesktop.secrets)
conflicts=('keepassxc')
replaces=('keepassx-http' 'keepassx-reboot-git')
options=(!emptydirs !buildflags !strip)
source=(git+https://github.com/keepassxreboot/keepassxc.git#branch=release/2.6.0
        keepassxc-issue4835.patch::https://github.com/keepassxreboot/keepassxc/pull/4848.patch)
md5sums=('SKIP'
         'f2ec0878cd2b58a5e838752a116fd6a0')

pkgver() {
    cd "${_gitname}"
    git describe --long | sed 's/^FOO-//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

prepare() {
    cd "${_gitname}"
    patch -Np1 -i ../keepassxc-issue4835.patch
    mkdir -p build
    sed -i'' -e 's:/usr/local/share/man/:${CMAKE_INSTALL_MANDIR}/:' src/cli/CMakeLists.txt
}

build() {
    cd "${_gitname}/build"
    export CXXFLAGS="$CXXFLAGS -Wno-unused-result"
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_BINDIR=/usr/bin \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DCMAKE_VERBOSE_MAKEFILE=OFF \
        -DWITH_GUI_TESTS=ON \
        -DWITH_XC_ALL=ON \
        -DWITH_XC_KEESHARE_SECURE=ON \
        -DCMAKE_BUILD_TYPE=Debug ..
    make VERBOSE=1
}

#check() {
#    cd "${_gitname}/build"
#    make test
#}

package() {
    cd "${_gitname}/build"
    make DESTDIR="${pkgdir}" install
}
```

[1] https://aur.archlinux.org/packages/keepassxc-git

### PR DESCRIPTION
**Pull request by droidmonkey**
* Prevent double free due to QObject cleanup happening before/after the ExtraPage  storing the QSharedPointer to FdoSecretsPlugin is deleted.
* Fixes #4877

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/fdosecrets/FdoSecretsPlugin.cpp [hunk 1]
```diff
@@ -30,13 +30,20 @@
...
 FdoSecretsPlugin::FdoSecretsPlugin(DatabaseTabWidget* tabWidget)
-    : QObject(tabWidget)
-    , m_dbTabs(tabWidget)
+    : m_dbTabs(tabWidget)
 {
+    g_fdoSecretsPlugin = this;
     FdoSecrets::registerDBusTypes();
 }
 
+FdoSecretsPlugin* FdoSecretsPlugin::getPlugin() {
```
Comment (phoerious) [inline src/fdosecrets/FdoSecretsPlugin.cpp:43]: Formatting.

Comment (droidmonkey) [reply src/fdosecrets/FdoSecretsPlugin.cpp:43]: oops

**Comment by Aetf** [comment]
I'm a little bit late to this :sweat_smile:

I think there really should be a comment at the `FdoSecretsPlugin` constructor to remind future readers (especially myself :P). I initially got this correct. The parenting to `tabWidget` was added when I was later skimming through the code and thought the plugin object was not owned by anyone. The `addSettingsPage` manages the page object using a shared pointer is IMHO quite an uncommon interface semantic. Usually, I would expect the ownership to be managed by the QObject's parent mechanism if the object is passed in as a raw pointer.

**Comment by droidmonkey** [comment]
The whole plugin will be redone for 2.6.1. Generally speaking the ISettingsPage should never have been a QObject to begin with.
