### PR TITLE
Correct multiple issues with Yubikey integration

### LINKED ISSUE #531: Saving Database fails with Yubikey 2FA Challenge-Response
I have a database with Yubikey 2FA Challenge-Response enabled.
If I remove the yubikey from the USB port and re-insert it, then saving the database fails with
> Writing the database failed.
> Unable to issue challenge-response.

This error also occurs, after the OS woke up from the suspend-to-ram state.

## Expected Behavior
Database is always saved 

## Current Behavior
Database is only saved, when Yubikey has never been removed before.

## Possible Solution
Scan for Yubikey before Saving Database

## Steps to Reproduce (for bugs)
1. Create a database and enable Challenge-Response with Yubikey inserted
2. Add entry
3. Save database --> success
4. Remove Yubikey from USB port
5. Add entry
6. Re-Insert Yubikey to USB port
7. Save database

Result: Error 
> Writing the database failed.
> Unable to issue challenge-response.

## Workaround
1. ...
2. ...
3. ...
4. ...
5. ...
6. Re-Insert Yubikey to USB port
7. Open "Change master key" dialog
8. Activate "Challenge Response" checkbox
9. Cancel "Change master key" dialog
10. Save database

## Context
Build: `-DWITH_XC_YUBIKEY=ON`

## Your Environment
Debian Linux Jessie
KeePassXC - Version 2.1.4
Revision: ad79162061c19decdd122784ff8adc4f18d6ce9b

Libraries:
- Qt 5.3.2
- libgcrypt 1.6.3

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### LINKED ISSUE #712: Yubikey is not re-detected after replugging.
When using the Challenge/Response mode with a Yubikey, if you unplug the key and replug it, the key is no longer detected or able to do the challenge / response authentication.

This leads to being unable to save the database after any changes.

Error message states:
Writing the database failed. Unable to issue challenge-response.

## Expected Behavior
Key should be redetected on replug - or only accessed when the functionality is needed.

## Current Behavior
1) Open a challenge / response secured database
2) Remove the yubikey
3) Make a change to something
4) Plug in the Yubikey
5) Try to save the database.

## Possible Solution
Should only access the Yubikey when a challenge is required. Once the challenge is complete, the key should be released.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.7

Operating system: Fedora 26 (Twenty Six)
CPU architecture: x86_64
Kernel: linux 4.11.6-301.fc26.x86_64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

* Fixed database not showing modified after failed save (auto save after change never marks dirty)
* Fixed Yubikey not being redetected after replug (fixes #712)
* Fixed single shot challenge resulting in failed saves (bumped it to try twice, results in 90% success rate) (fixes #531)

## How has this been tested?

Manually using a Yubikey Neo

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by bullet64** [comment]
Hello,

i have tested this pull and all work's fine for me. I will do some more tests.
**Keep up the good work!**


```
KeePassXC - Version 2.2.0
Revision: dfbf50d3454f8ad5b44e9c5b8f1cbcb1c40600dd

Bibliotheken:
- Qt 5.5.1
- libgcrypt 1.6.5

Betriebssystem: Linux Mint 18.2
CPU-Architektur: x86_64
Kernel: linux 4.11.0-14-generic

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey
```

**Comment by cjustin88** [comment]
Hi,

What is the time-frame for the release that this pull request is targeting? The bug that this pull request fixes is particularly severe in that it can cause database corruption and interrupts database saving.

Thanks,
Justin

**Comment by phoerious** [comment]
Target milestone is 2.2.1.

**Comment by droidmonkey** [comment]
Basically I'd want to release shortly after this is merged.

**Comment by droidmonkey** [comment]
@keepassxreboot/core-developers ready to merge this?

File: src/gui/DatabaseTabWidget.cpp [hunk 1]
```diff
@@ -363,6 +363,8 @@ bool DatabaseTabWidget::saveDatabase(Database* db)
             emit messageDismissTab();
             return true;
         } else {
+            dbStruct.modified = true;
```
Comment (louib) [inline src/gui/DatabaseTabWidget.cpp]: @droidmonkey the only problem I have with that is that if the database file was not modified but the user tried to save manually, and the save fails, the db will be marked as dirty even though no changes have been made. You can try for example by removing write permission to the db file after opening it in keepassxc. Of course you could argue that it's not gonna happen often.

What about marking the database dirty before calling autosave in `DatabaseTabWidget::modified()`:
```
diff --git a/src/gui/DatabaseTabWidget.cpp b/src/gui/DatabaseTabWidget.cpp
--- a/src/gui/DatabaseTabWidget.cpp
+++ b/src/gui/DatabaseTabWidget.cpp
@@ -780,16 +780,17 @@ void DatabaseTabWidget::modified()
     Database* db = static_cast<Database*>(sender());
     DatabaseManagerStruct& dbStruct = m_dbList[db];
 
-    if (config()->get("AutoSaveAfterEveryChange").toBool() && dbStruct.saveToFilename) {
-        saveDatabase(db);
-        return;
-    }
-
     if (!dbStruct.modified) {
         dbStruct.modified = true;
         dbStruct.dbWidget->databaseModified();
         updateTabName(db);
     }
+
+    if (config()->get("AutoSaveAfterEveryChange").toBool() && dbStruct.saveToFilename) {
+        saveDatabase(db);
+    }
+
 }
```

Comment (droidmonkey) [reply src/gui/DatabaseTabWidget.cpp]: The whole saving structure needs to be redone. I suggest moving this improvement edge case to then.

Comment (louib) [reply src/gui/DatabaseTabWidget.cpp]: @droidmonkey as you wish, but I thought the above diff was solving both problems.

Comment (droidmonkey) [reply src/gui/DatabaseTabWidget.cpp]: I will need to think about that a little bit. The case I am trying to solve with my fix is the user requested a save and it failed to save so I am marking the database as dirty because I do not know if the state can be trusted. This incidentally fixes the issue when an auto save fails and never marks the database dirty (ie. the database != save file).

Comment (TheZ3ro) [reply src/gui/DatabaseTabWidget.cpp]: Is this ready to be merged?

Comment (droidmonkey) [reply src/gui/DatabaseTabWidget.cpp]: Yes. I will be refactoring the code above with my database pointer fixes and will address it there for 2.3
