### PR TITLE
Change `--pw-stdin` to use `getPassword()`

### LINKED ISSUE #1673: Using `--pw-stdin` echoes password back
This is related to the issue I opened the other day #1636.
While most of it was fixed in `2.3.1` the password is still echoed back, at least on Ubuntu.

The culprit seems to be [readline()](https://github.com/keepassxreboot/keepassxc/blob/aa6327716f523329c95134228027d47750087945/src/main.cpp#L151)

## Expected Behavior
The database password should be kept hidden

## Current Behavior
The database password is echoed back

## Possible Solution
Using bash and pinentry something like this could be done
```
echo $(echo -e "SETPROMPT Database password\nGETPIN\nBYE" | pinentry | sed -n '/^D .*/s/^D //p') | keepassxc --pw-stdin Passwords2.kdbx
```
But a solution that disables echo altogether would be better. Something can be found [here](https://stackoverflow.com/questions/1413445/reading-a-password-from-stdcin)

## Steps to Reproduce (for bugs)
1. run `keepassxc --pw-stdin Passwords.kdbx`
2. wait for the unpainted windows to appear
3. type in the database password and see it being echoed back

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-25-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### PR DESCRIPTION
**Pull request by a-dma**
Make `--pw-stdin` use `getPassword()` instead of `readLine()`

## Description
A minor change to use the `getPassword()` function from CLI.
I've also updated the translation files and I'd like a thumbs up on that.

## Motivation and context
Fixes #1673

## How has this been tested?
Manual testing plus `make test`

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: share/translations/keepassx_ar.ts [hunk 1]
```diff
@@ -4094,5 +4094,9 @@ Please unlock the selected database or choose another one which is unlocked.</so
         <source>Parent window handle</source>
         <translation>زر النافذة الأم</translation>
     </message>
+    <message>
```
Comment (phoerious) [inline share/translations/keepassx_ar.ts]: > I've also updated the translation files and I'd like a thumbs up on that.

Please revert that. We will update translations before the release. There is no point in pulling them in now. They just convolute the PR.

File: src/main.cpp [hunk 2]
```diff
@@ -148,7 +150,9 @@ int main(int argc, char** argv)
             // we always need consume a line of STDIN if --pw-stdin is set to clear out the
             // buffer for native messaging, even if the specified file does not exist
             static QTextStream in(stdin, QIODevice::ReadOnly);
-            password = in.readLine();
+            static QTextStream out(stdout, QIODevice::WriteOnly);
+            out << QCoreApplication::translate("Main", "Database password") << QString(": ") << flush;
```
Comment (phoerious) [inline src/main.cpp]: The colon should be part of the translation string.

**Comment by phoerious** [comment]
Also please rebase against release/2.3.2.

**Comment by a-dma** [comment]
Updated and rebased
