### PR TITLE
Auto-Type: Increase max inter-type delay to 500 ms

### LINKED ISSUE #6398: [Auto-Type] Increase max inter-key delay to 300 ms
## Overview
The new functionality has many advantages due to the fact that almost every bank in Poland uses these terrible single letters passwords. In any case, several banks introduce delays between each letter being entered.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download the KeePassXC 2.7.0-snapshot (805574c)
2. Create a new sequence from pickchars, e.g. {DELAY 2000}{DELAY=100}{PICKCHARS}{ENTER}
3. The bank in protection against bots introduces a delay between each letter of the password. The 100ms delay is way too fast. Login failed.

## Expected Behavior
Entering characters slowly.

## Actual Behavior
Very fast typing of characters, preventing proper logging in.

## Solution
Functionality {PICKCHARSDELAY = 500} for adding extra delay.
or
If the user has {DELAY = 1000} and {PICKCHARS}, only pickchars are affected.

## System
KeePassXC - 2.7.0-snapshot
Revision: 805574c
Operating System: Windows 10.0.19042 Build 19042
Desktop Env: Windows NT X64

### PR DESCRIPTION
**Pull request by droidmonkey**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
* Fix #6398 

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by hifi — APPROVED** [review]

File: src/autotype/AutoType.cpp [hunk 1]
```diff
@@ -514,7 +514,7 @@ AutoType::parseSequence(const QString& entrySequence, const Entry* entry, QStrin
         return {};
     }
 
-    const int maxTypeDelay = 100;
+    const int maxTypeDelay = 500;
```
Comment (aartiukh) [inline src/autotype/AutoType.cpp:517]: IMHO these constants might be `static`

Comment (droidmonkey) [reply src/autotype/AutoType.cpp:517]: not a big deal
