### PR TITLE
Unlock previously opened databases with --pw-stdin

### LINKED ISSUE #590: --pw-stdin stopped working
I have used --pw-stdin in a script to open and unlock KeePassXC upon login, but it stopped working when I updated keepassxc to version 2.1.4.

## Expected Behavior
This command should work fine to start and unlock KeePassXC:
keepassxc --keyfile ~/folder/keyfile.key --pw-stdin ~/anotherFolder/database.kdbx <<< password

## Current Behavior
KeePassXC starts, but is still in a locked state. I have to open it up from the tray, and input the password to unlock it.

## Steps to Reproduce (for bugs)
1. Launch KeePassXC with the command above

## Your Environment
* KeePassXC version/commit used: 2.1.4.r396.ga75746c7
* Qt version: 5.8.0
* Compiler: 4.0.0
* Operating System and version: Arch Linux with 4.11.2-1-zen kernel.

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

Fixes #590 by passing the provided password (via stdin) to a database that was already opened due to "open previously open databases"

## How has this been tested?

Manually

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/DatabaseTabWidget.cpp [hunk 1]
```diff
@@ -129,7 +129,12 @@ void DatabaseTabWidget::openDatabase(const QString& fileName, const QString& pw,
     while (i.hasNext()) {
         i.next();
         if (i.value().canonicalFilePath == canonicalFilePath) {
-            setCurrentIndex(databaseIndex(i.key()));
+            if (!i.value().dbWidget->dbHasKey() && (!pw.isNull() || !keyFile.isEmpty())) {
```
Comment (phoerious) [inline src/gui/DatabaseTabWidget.cpp]: I would prefer the logically equivalent `!(pw.isNull() && keyFile.isEmpty())`, which is more intuitive to understand.

Comment (droidmonkey) [reply src/gui/DatabaseTabWidget.cpp]: This logic sequence is used 15 lines below as well.

Comment (phoerious) [reply src/gui/DatabaseTabWidget.cpp]: Change it there, too. ;-)

**Comment by droidmonkey** [comment]
PR updated, request final review and merge @phoerious
