### PR TITLE
Last round of fixes for 2.5.2

### LINKED ISSUE #1917: macOS Sierra: Password text box font size, at "View/Edit entry" window,  is too small
(Issue noted on macOS Sierra - 10.12.6 and KeePassXC - Version 2.3.1) The font size for the password text at the "View/Edit entry" window, is much smaller than the username text's font size. There is no way to adjust the Password's font size in preference settings. The reason may be related to different font type on username text box and password text box.

## Expected Behavior

There should be a way to change password's font size for "View/Edit entry" window.

## Current Behavior

Currently there is no way to change password's text box font size. Although there is a workaround, which is setting the environment variable QT_SCALE_FACTOR to 1.25 on .bash_profile (export QT_SCALE_FACTOR=1.25), it only works if the user calls the app from the terminal (/Applications/KeePassXC.app/Contents/MacOS/KeePassXC) and QT_SCALE_FACTOR changes the font size on every text related to any control at each and every single application's window.

## Possible Solution

Allow the user to set, specifically,  the password's text box font size in preference settings.

## Context

Making the password text box content more legible.

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating System: macOS Sierra - 10.12.6
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### LINKED ISSUE #3707: macOS and Windows shouldn't talk about snaps
https://github.com/keepassxreboot/keepassxc/blob/bef1b94d71aa0478145673884a310d56956bfef1/src/browser/BrowserOptionDialog.ui#L65

## Expected Behavior
Snaps are a linux packaging model, apps when run on macOS (and Windows) shouldn't talk about it.

## Current Behavior
`Browsers installed as snaps are currently not supported.`

## Possible Solution
Add a branch which hides this field for non Linux platforms.

## Steps to Reproduce
1. Open KeePassXC
1. Open Preferences...
1. Go to Browser Integration (with `Enable browser integration` unchecked)

## Context
macOS (user cares about terminology)

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

### LINKED ISSUE #3931: AutoOpen only works if password is not empty
When using AutoOpen, a password must be present to open another database.

[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
AutoOpen would work just with an `url` (the database), or `url` + `username` (the keyfile).

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
If no password is present, AutoOpen will not work.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Remove the ` || entry->password().isEmpty()` or change it to ` || (entry->password().isEmpty() && entry->username().isEmpty())`. The first solution would work for databases without password and keyfile, the second enabled just keyfile without password AutoOpen.
https://github.com/keepassxreboot/keepassxc/blob/0fd883686c05c7689bf8f074b02dcfff3a705a97/src/gui/DatabaseWidget.cpp#L1746-L1749

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Add folder `/AutoOpen` (directly under root)
2. Add entry with an `url` and `username` but without a `password`
3. Save database
4. Lock database
5. Unlock database

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836
Distribution: AppImage

Qt 5.12.3
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 5.2.0-0.bpo.3-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

### LINKED ISSUE #3999: OPVault importer uses legacy attribute for TOTP secrets
## Expected Behavior
TOTP secrets (i.e. "otpauth" URIs) in 1Password/OPVault items should be converted to the "otp" attribute in KeePass format, that e.g. KeePassXC's own TOTP setup dialog uses.

## Current Behavior
TOTP secrets are converted to the legacy(?) "TOTP Settings" attribute.

## Possible Solution
Change the OPVault import code to use the "otp" attribute for otpauth URIs.

## Steps to Reproduce
1. Import OPVault data with TOTP secrets.
2. Inspect attributes of imported entries with TOTP secrets.

## Context
The legacy "TOTP Settings" attribute appears to be enough for KeePassXC to generate TOTP codes, but the Strongbox iOS app would not – I believe it also expects a "TOTP Seed" attribute in this case, which the importer doesn't add. The problem was resolved by simply renaming the attribute to "otp".

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
Last bit of 2.5.2 bug fixes:

* Fix compiler issues with Qt 5.14
  * Remove deprecation warnings when not doing a DEV_BUILD. Qt 5.14 introduced several deprecation flags on basic function calls in QList and QSet that would require several #pragma ignores. Assuming this was in preparation to Qt 6.0.
  * Remove unnecessary assert in PasswordEditWidget that was hit in macOS debug builds.

* Choose a better monospace font on macOS (Fixes #1917)

* Hide snap browser warning label on non-Linux OS (Fixes #3707)

* Fix AutoOpen with key file only databases (Fixes #3931)

* Use new TOTP structure when importing 1Password Vault (Fixes #3999)

* Fix TOTP Dialog not closing on lock

* Improve GUI test reliability
  * Explicitly resize the window to improve testing on High DPI displays
  * Add additional bootstrap calls to mimic the actual application

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Ran all tests locally and on macOS

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

File: tests/gui/TestGui.cpp [hunk 1]
```diff
@@ -91,11 +95,12 @@ void TestGui::initTestCase()
...
     config()->set("UpdateCheckMessageShown", true);
 
-    m_mainWindow.reset(new MainWindow());
-    Bootstrap::restoreMainWindowState(*m_mainWindow);
     Bootstrap::bootstrapApplication();
+
+    m_mainWindow.reset(new MainWindow());
     m_tabWidget = m_mainWindow->findChild<DatabaseTabWidget*>("tabWidget");
     m_mainWindow->show();
+    m_mainWindow->resize(1024, 768);
```
Comment (phoerious) [inline tests/gui/TestGui.cpp]: 🥴

Comment (droidmonkey) [reply tests/gui/TestGui.cpp]: There really is no good way around this, we do require a minimum screen size of 1024x768 (not a high bar!). The reason for this is when testing on Hi-DPI screens the window is so small as to prevent clicking some entries in the entry list causing the tests to fail.

Comment (phoerious) [reply tests/gui/TestGui.cpp]: I know, I know. :shrug:
