### PR TITLE
Passkeys improvements

### LINKED ISSUE #10287: Security, privacy and other issues with WebAuthn/passkeys support
## Overview

Following on from #10269, I've checked the `develop` branches of the KeePassXC implementation (the app itself and the browser extension) against parts of the WebAuthn Level 1 spec and it looks like there are a few serious security issues:

- KeePassXC does not perform domain and RP ID validation correctly, which I think cause privacy and security issues:
    - Privacy example: I'm pretty sure that it would be possible for one *.github.io site to gather information about what credentials a user has for other *.github.io sites.
    - Security example: If `bank.com` uses passkeys, an attacker could create a phishing site at `fakebank.com` and use an RP ID of `bank.com` and I think KeePassXC would provide the user's `bank.com` assertion, which the attacker could then use to sign into the user's bank account.
    - Fixing this would involve changes to the browser extension to implement the correct logic.
- KeePassXC does not correctly determine when it is required to perform user presence tests
    - This is a security issue, as while it's not obvious, WebAuthn always requires either user presence or user verification to be performed (and user verification implies user presence), so this violates the assumptions that RPs can make about authenticated users.
    - I think this might be chained together with the RP ID validation issue and the user presence requirement being ignored so that an attacker could get KeePassXC to provide a user's bank account assertion without any interaction with or visibility to the user.
    - Fixing this would involve changes in the browser extension.
- KeePassXC does not correctly determine when it is required to perform user verification
    - This is a security issue, as user verification is what makes passkeys capable of 2FA, and knowing when the RP requires user validation to be performed is a prerequisite to performing it when it's needed (unless you always perform it, but KeePassXC doesn't).
    - Fixing this would involve changes in the browser extension.
- KeePassXC ignores any user presence requirement when the RP has supplied allowed credentials and there is only one matching entry. In that case, it does not perform the user presence test but tells the RP that it did.
    - This is a security issue, as I've mentioned above.
    - Fixing this would involve changes in KeePassXC.
- KeePassXC never performs user verification (even if the RP requires it), but if the RP did not explicitly discourage user verification, KeePassXC tells the RP that user verification was performed
    - This is a security issue as it means that while an RP might think that 2FA has been performed, it's actually only been 1FA, and that might not be good enough in relatively high-risk situations (especially given that it looks like an attacker could phish that single factor).
    - Fixing this would involve changes in KeePassXC.
    - One approach might be to update `BrowserPasskeysConfirmationDialog` to prompt for and validate database unlock credentials when user verification is required, though I don't know if KeePassXC can already do that kind of thing without locking the database (which could be a bit annoying if you're also using it for other things).

If my understanding is correct, then I think it would be dangerous to users to include KeePassXC's passkey support in a stable release in its current state.

I think that there are also some other potential issues or areas for improvement:

- Some operations that should be performed in the client (the browser extension) are being performed in the authenticator (KeePassXC), which might be a security issue if either of them can find themselves talking to untrusted code instead. Otherwise it's not an issue itself, but the discrepancies may hide other issues.
    - Improving on this would involve changes to the payloads sent between the browser extension and KeePassXC, so it would be good to clean those interfaces up before passkey support is released, at which point it becomes a breaking change.
- There are a variety of other discrepancies that I don't think impact privacy or security but may impact UX and compatibility.
    - I think these are relatively low priority and shouldn't impact any decision to release passkey support.

While I checked against the Level 1 spec, I did then compare Level 1 against Level 2 and I don't think the differences have meaningful privacy or security impacts. It would be good to be compliant with Level 2 for compatibility reasons (e.g. `AuthenticatorAttestationResponse.getTransports()` isn't implemented by the browser extension), but I think initially targeting Level 1 is reasonable. I didn't compare against Level 3.

Finally, it's not spec-related, but the property name `KPEX_PASSKEY_GENERATED_USER_ID` is misleadingly inaccurate, `KPEX_PASSKEY_CREDENTIAL_ID` would be more appropriate.
- It's confusing because the WebAuthn spec isn't consistent about the field names for the user handle: sometimes it's `userHandle` and sometimes it's `id`, and KeePassXC also has a `PKEX_PASSKEY_USER_HANDLE` property, so it looks like KeePassXC is storing two different user handles when that's not actually what's happening.

The following is a breakdown of the discrepancies I've noticed while going through the spec and the code.

#### In the client

https://www.w3.org/TR/2019/REC-webauthn-1-20190304/#createCredential

This is supposed to be implemented in the client, so I've been looking through keepassxc-browser and occasionally going into keepassxc to see if some checks were put there instead.

Discrepancies are:

- Step 4 - timeout is not checked, corrected or set to a client-specific default
- Step 5 - caller origin is not checked to see if it's opaque
- Step 6 - Effective domain is not checked
- Step 7 - Effective domain / RP ID check is not performed correctly, the browser plugin only checks - if the current hostname ends with the RP ID
- Step 9 - Unsupported credential types are not filtered out
- Step 10 - Check for presence of only unsupported credential types is not performed
- Step 12 - The extensions list is not checked
- Step 13 - collectedClientData is not built, though something that's supposed to be it is built - much later in BrowserPasskeys::buildClientDataJson()
- Step 14 - clientDataJSON is not created
- Step 15 - clientDataJSON is not hashed
- Step 16 - signal is not checked
- Step 17 - no set of authenticator requests, it's just one authenticator (though there is the - native implementation fallback), so probably not really an issue
- Step 18 - no set of authenticators, but again probably not really an issue
- Step 20
    - If lifetimeTimer expires - no lifetime timer
    - If the user exercises a user agent user-interface option to cancel the process - it doesn't  look like the browser extension offers such an option, so this may not be relevant
    - If the options.signal is present and its aborted flag is set to true - signal is not checked
    - If an authenticator becomes available on this client device
        - Step 1 - authenticatorAttachment and requireResidentKey isn't checked. userVerification is checked but not as described
        - Step 2 - userVerification is not set as described
        - Step 3 - userPresence is not set
        - Step 6 - the data sent to the authenticator is not as described
    - If an authenticator ceases to be available on this client device - doesn't seem to be handled, may not be relevant?
    - If any authenticator returns a status indicating that the user cancelled the operation - there is error handling, seems sufficient since there's only one authenticator
    - If any authenticator returns an error status equivalent to "InvalidStateError" - it doesn't look like the exception is raised
    - If any authenticator returns an error status not equivalent to "InvalidStateError" - this is different to the above to avoid leaking information, but the extension doesn't seem to report any such errors anyway
    - If any authenticator indicates success
        - Step 2 - the struct is not created as described, the only inputs come from the authenticator, which is probably technically a security issue (though because the browser extension and KeePassXC have the same authors they can trust each other in practice)
        - Step 3.1 - attestationConveyancePreferenceOption is not checked
        - Step 3.4 - the object created doesn't quite look like a PublicKeyCredential, it's missing id, type and the internal slots aren't represented in any way (aside from [[identifier]], which is covered by rawId)
        - Step 4 - not really relevant as there's only one authenticator
- Step 21 - No exception thrown, seems like information is leaked due to that

Of these issues, I think the effective domain and RP ID checks represent privacy and possibly security issues, and the handling of data returned by the authenticator may be a security issue if it's possible that it's not KeePassXC that the browser extension is talking to. The rest seem to be more about UX and compatibility than security or privacy.

#### In the authenticator

https://www.w3.org/TR/2019/REC-webauthn-1-20190304/#authenticatormakecredential

These steps are supposed to happen in the authenticator, so I've been looking through KeePassXC's code for them.

Before the procedure starts, the spec notes that:

> Before performing this operation, all other operations in progress in the authenticator session MUST be aborted by running the authenticatorCancel operation.

That doesn't seem to happen, which might have security implications (e.g. if a site can coordinate actions to happen at the same time and so get KeePassXC into a confused state where it performs the wrong operations on the wrong data).

- Step 1 - There are a couple of validation checks, but not to the level described. Could be an issue if KeePassXC could be contacted by anything other than the official browser extension.
- Step 2 - this validation isn't performed, instead it looks like if KeePassXC doesn't support one of the algorithms requested then it'll just used ES256, which is theoretically a compatibility issue (I've only seen RS256 and ES256 in the wild) but I don't think it's a security issue.
- Step 3 - The descriptor ID is looked up, but the RP ID and type don't get checked and there is no user consent check done
- Step 4 - Not relevant, KeePassXC can store resident keys
- Step 5 - Not relevant because KeePassXC can perform user verification (but doesn't, though that's a later issue)
- Step 6 - The user consent dialog doesn't display the RP name or user display name, but these only SHOULD be displayed, and they're less important than what does get displayed, so that's fine. However, the dialog does not perform user verification if it is required. This is a security issue as it downgrades 2FA to 1FA without the RP's knowledge, and so weakens the security of the user's online account.
- Step 7.3 - credentialSource is built without the type, but that's always public-key so not really an issue
- Step 7.4 - KeePassXC doesn't have a credentials map in the way that is described, but the functionality seems to be equivalent
- Step 8 - Error handling isn't clear, particularly if generating a key pair fails, as looks like it'll just silently store an empty key?
- Step 11 - The credential ID length is hardcoded to be 16 bytes, which is fine, but it would be better to get this from the credential ID that gets passed into BrowserPasskeys::buildAttestationObject().

The handling of step 3 might be a privacy risk, but I'm not confident about that. However, the user consent dialog in step 6 not performing user verification when required is definitely a security issue. The rest of the discrepancies seem like minor issues.

#### In the client

https://www.w3.org/TR/2019/REC-webauthn-1-20190304/#getAssertion

Steps 1 to 6 are the same as for passkey create, and have the same discrepancies.

- Step 7 - RP ID is set to the hostname, which isn't necessarily the effective domain, and if already set RP ID is not validated correctly.
- Step 8,9 - there doesn't seem to be any extensions handling, which is fine but it would be good to have a comment or no-op function signalling that it's intentional.
- Step 10 - collectedClientData is not built
- Step 11 - collectedClientData is not serialised as JSON
- Step 12 - clientDataJSON is not hashed
- Step 13 - no signal handling
- Step 16 - not really relevant since there's just one authenticator
- Step 17 - no timer
- Step 18
    - If lifetimeTimer expires - no lifetime timer
    - If the user exercises a user agent user-interface option to cancel the process - it doesn't look like the browser extension offers such an option, so this may not be relevant
    - If the signal is present and its aborted flag is set to true - signal is not checked
    - If issuedRequests is empty, options.allowCredentials is not empty, and no authenticator will become available for any public key credentials therein - doesn't seem to be handled, but I guess that the functionality wouldn't get this far if the connection with KeePassXC was broken?
    - If an authenticator becomes available on this client device
        - Step 1 - userVerification is checked but not as described, though KeePassXC is capable of user verification so this would always pass.
        - Step 2 - userVerification is not set as described
        - Step 3 - userPresence is not set
        - Step 4.1 to 4.5 - The logic for allowCredentials not being empty is handled differently, because no functionality has been built to query KeePassXC for a list of matching credentials. 
        - Step 4.6,4.7 - The transports handling is different, but that's due to the above discrepancy. Given that all credentials in KeePassXC will have the same transports, I don't think it's significant. The parameters passed to the authenticator don't match what is described.
    - If an authenticator ceases to be available on this client device - doesn't seem to be handled, may not be relevant?
    - If any authenticator returns a status indicating that the user cancelled the operation - there is error handling, seems sufficient since there's only one authenticator
    - If any authenticator returns an error status - there is error handling, seems sufficient since there's only one authenticator
    - If any authenticator indicates success
        - Step 2 - the struct is not created as described, the only inputs come from the authenticator, which is probably technically a security issue (though because the browser extension and KeePassXC have the same authors they can trust each other in practice)
        - Step 3 - the object created doesn't quite look like a PublicKeyCredential, it's missing id, type, getClientExtensionResults and the internal slots aren't represented in any way (aside from [[identifier]], which is covered by rawId)
        - Step 4 - not really relevant as there's only one authenticator

Step 7's discrepancy seems likely to cause privacy/security issues, and the handling of data returned by the authenticator may be a security issue if it's possible that it's not KeePassXC that the browser extension is talking to. The rest seem to be more about UX and compatibility than security or privacy.

#### In the authenticator

https://www.w3.org/TR/2019/REC-webauthn-1-20190304/#authenticatorgetassertion

This starts with the same note about cancelling operations as when creating a passkey, so the same concerns apply here.

- Step 1 - There are a couple of validation checks, but not to the level described. Could be an issue if KeePassXC could be contacted by anything other than the official browser extension.
- Step 3 - the implementation also falls back to allowing entries which have a user handle set, which isn't relevant (this might be because the filtering happens even if the allowed credentials list is empty?). It also filters credentials by RP ID, which again doesn't happen yet (though that's in step 5)
- Step 7 - The handling of user verification is wrong, and the dialog doesn't perform user verification but KeePassXC may set the UV bit later. This is a security issue as it secretly downgrades 2FA to 1FA. There's also a case where no user presence check performed even if it's required, but KeePassXC always sets the UP bit later.
- Step 8 - there doesn't seem to be any extensions handling, which is fine as no extensions are supported, but a comment or no-op function for it would be good.
- Step 10 - as mentioned, KeePassXC may essentially lie to RPs when it sets the flags in the attestation object
- Step 11 - the clientDataJSON is built and hashed here instead of in the client, which may be a security issue if the client could be untrusted. I'm not familiar with Botan's API so can't comment on whether it's used correctly, but I assume so given that RPs can verify signatures successfully.
- Step 12 - Error handling isn't clear, particularly if creating a signature fails, as then it'll just send an empty signature back?
- Step 13 - More data is returned to the client than required, and the signature ID is always sent, but those don't seem to be issues.

### Missing APIs

https://www.w3.org/TR/2019/REC-webauthn-1-20190304/#storeCredential
https://www.w3.org/TR/2019/REC-webauthn-1-20190304/#preventSilentAccessCredential

These look like nice-to-haves for compatibility.

It also seems like the browser plugin should be overriding `PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()` so that it returns true when KeePassXC is available.

https://www.w3.org/TR/2019/REC-webauthn-1-20190304/#op-lookup-credsource-by-credid

This one looks like the interface that should be implemented so that the browser extension can be updated to follow the specified steps for handling allowed credentials as part of the client get assertion procedure, as mentioned in the client get assertion section above.

https://www.w3.org/TR/2019/REC-webauthn-1-20190304/#op-cancel

As mentioned in both sections above, it looks like authenicatorCancel is important to have, but maybe it's not necessary with how KeePassXC and the browser extension communicate and operate together, I can't tell.

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Refactors the Passkey implementation to include more checks and a structure that is more aligned with the official specification.
Notable changes:
- _BrowserService_ no longer does the checks by itself. A new class _BrowserPasskeysClient_ constructs the relevant objects, acting as a client. _BrowserService_ only acts as a bridge between the client and _BrowserPasskeys_ (authenticator) and calls the relevant popups for user interaction.
- A new helper class _PasskeyUtils_ includes the actual checks and parses the objects.
- _BrowserPasskeys_ is pretty much intact, but some functions have been moved to PasskeyUtils.
- Fixes Ed25519 encoding in _BrowserCBOR_.
- Adds new error messages.
- User confirmation for Passkey retrieval is also asked even if `discouraged` is used. This goes against the specification, but currently there's no other way to verify the user.
- `cross-platform` is also accepted for compatibility. This could be removed if there's a potential issue with it.
- Extension data is now handled correctly during Authentication.
- Allowed and excluded credentials are now handled correctly.
- `KPEX_PASSKEY_GENERATED_USER_ID` is renamed to `KPEX_PASSKEY_CREDENTIAL_ID`
- Adds a new option "Allow localhost with Passkeys" to Browser Integration -> Advanced tab. By default it's not allowed to access HTTP sites, but `http://localhost` can be allowed for debugging and testing purposes for local servers.
- Add tag `passkey` to a Passkey entry, or an entry with an imported Passkey.

Corresponding KeePassXC-Browser side PR: https://github.com/keepassxreboot/keepassxc-browser/pull/2121

Fixes #10287.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Automatic tests added. Sites tested manually. I couldn't get the Microsoft Passkeys creation work anymore, even with the old implementation. The site always triggers OS/Browser level dialog that cannot be prevented.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Refactor (significant modification to existing code)

### CODE REVIEW

File: src/core/UrlTools.cpp [hunk 1]
```diff
@@ -171,3 +171,14 @@ bool UrlTools::isUrlValid(const QString& urlField) const
...
+
+bool UrlTools::domainHasIllegalCharacters(const QString& domain) const
+{
+    QRegularExpression re(R"([\s\^#|/:<>\?@\[\]\\])");
+    auto match = re.match(domain);
+    if (match.hasMatch()) {
+        return true;
+    }
+
+    return false;
```
Comment (phoerious) [inline src/core/UrlTools.cpp]:
```suggestion
    QRegularExpression re(R"([\s\^#|/:<>\?@\[\]\\])");
    return re.match(domain).hasMatch();
```
;-)

File: src/browser/BrowserAction.cpp [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /*
- *  Copyright (C) 2023 KeePassXC Team <team@keepassxc.org>
+ *  Copyright (C) 2024 KeePassXC Team <team@keepassxc.org>
```
Comment (Ortham) [inline src/browser/BrowserAction.cpp:2]: I can't comment on the actual lines since they weren't changed, but lines 544 and 577 check that the origin starts with `https://` but this is too restrictive as `http://localhost` also counts as a secure context. It's not a big deal but breaks locally testing a site.

File: src/browser/PasskeyUtils.cpp [hunk 3]
```diff
@@ -0,0 +1,329 @@
...
+{
+    if (!result) {
+        return ERROR_PASSKEYS_ORIGIN_NOT_ALLOWED;
+    }
+
+    if (origin.isEmpty()) {
+        return ERROR_PASSKEYS_ORIGIN_NOT_ALLOWED;
+    }
+
+    const auto effectiveDomain = QUrl::fromUserInput(origin).host();
```
Comment (Ortham) [inline src/browser/PasskeyUtils.cpp:97]: The origin can also be `"null"`, so it might be worth explicitly handling that case (which should cause an origin not allowed error).

File: src/browser/PasskeyUtils.cpp [hunk 4]
```diff
@@ -0,0 +1,329 @@
...
+    }
+
+    return true;
+}
+
+bool PasskeyUtils::isDomain(const QString& hostName) const
+{
+    const auto domain = QUrl::fromUserInput(hostName).host();
+    return !domain.isEmpty() && !domain.endsWith('.') && Tools::isAsciiString(domain)
+           && !urlTools()->domainHasIllegalCharacters(domain) && !urlTools()->isIpAddress(hostName);
```
Comment (Ortham) [inline src/browser/PasskeyUtils.cpp:255]: Does `isIpAddress()` handle IPv6 addresses that are enclosed in square brackets? In a hostname an IPv6 address will appear as e.g. `[::]`, not `::`, to separate it from any following port. `QHostAddress`'s docs only give examples of IPv6 addresses without the brackets.

Comment (Ortham) [inline src/browser/PasskeyUtils.cpp:255]: It might be better to use `QUrl::toAce()` to check if the domain is a valid hostname (i.e. check that its return value is not empty) than to rely on `isAsciiString()` and `domainHasIllegalCharacters()` as supporting IDNA looks very complicated and chances are that these checks aren't sufficient.

File: src/browser/PasskeyUtils.cpp [hunk 5]
```diff
@@ -0,0 +1,329 @@
...
+
+    if (origin.isEmpty()) {
+        return ERROR_PASSKEYS_ORIGIN_NOT_ALLOWED;
+    }
+
+    if (!isRegistrableDomainSuffix(rpId, origin)) {
+        return ERROR_PASSKEYS_DOMAIN_RPID_MISMATCH;
+    }
+
+    if (rpId.isEmpty() || rpId == origin) {
```
Comment (Ortham) [inline src/browser/PasskeyUtils.cpp]: If the RP ID is empty then it's not valid. The RP ID may be undefined (if you change the browser extension as I've suggested), in which case it should be set to the effective domain, but that's different from being defined as an empty string.

File: src/browser/PasskeyUtils.cpp [hunk 6]
```diff
@@ -0,0 +1,329 @@
...
+    const auto effectiveDomain = QUrl::fromUserInput(origin).host();
+    if (!isDomain(effectiveDomain)) {
+        return ERROR_PASSKEYS_DOMAIN_IS_NOT_VALID;
+    }
+
+    *result = effectiveDomain;
+    return 0;
+}
+
+int PasskeyUtils::validateRpId(const QString& rpId, const QString& origin, QString* result) const
```
Comment (Ortham) [inline src/browser/PasskeyUtils.cpp]: `origin` here is actually the effective domain, the name used here is misleading.

File: src/browser/PasskeyUtils.cpp (hunk 5 above)
Comment (Ortham) [reply src/browser/PasskeyUtils.cpp]: I also think this check should come before the `isRegistrableDomainSuffix()` check, as otherwise you'll fail that check if the RP ID is not set and do unnecessary work if it's equal to the origin.

File: src/browser/PasskeyUtils.cpp [hunk 7]
```diff
@@ -0,0 +1,329 @@
...
+    return true;
+}
+
+bool PasskeyUtils::isRegistrableDomainSuffix(const QString& hostSuffixString, const QString& originalHost) const
+{
+    if (hostSuffixString.isEmpty()) {
+        return false;
+    }
+
+    if (!isDomain(hostSuffixString) || !isDomain(originalHost)) {
```
Comment (Ortham) [inline src/browser/PasskeyUtils.cpp]: The first `isDomain()` check here should be against `hostSuffix`, not `hostSuffixString`.

File: src/browser/BrowserPasskeysClient.cpp [hunk 8]
```diff
@@ -0,0 +1,174 @@
...
+
+    // Check PublicKeyCredentialTypes
+    const auto pubKeyCredParams = passkeyUtils()->parseCredentialTypes(publicKeyOptions["pubKeyCredParams"].toArray());
+    if (pubKeyCredParams.isEmpty() && !publicKeyOptions["pubKeyCredParams"].toArray().isEmpty()) {
+        return ERROR_PASSKEYS_NO_SUPPORTED_ALGORITHMS;
+    }
+
+    // Check Attestation
+    const auto attestation = passkeyUtils()->parseAttestation(publicKeyOptions["attestation"].toString());
+    if (attestation.isEmpty()) {
```
Comment (Ortham) [inline src/browser/BrowserPasskeysClient.cpp]: `parseAttestation` returns an empty string if the given value was not `none` or `direct`, but that's not an error case, the spec says that if the given value is unknown it should be treated as if it does not exist and therefore default to `none`. To put it another way, if an PR asks for a certain type of attestation conveyance, it's not an error if the client can't provide it, it just does what it can.

My interpretation of https://www.w3.org/TR/webauthn-2/#enumdef-attestationconveyancepreference is that KeePassXC should treat `indirect` as `direct` (as it can't replace the attestation statement), and `enterprise` as `direct` (as it doesn't support enterprise attestation), but I think you could argue one or both should be treated as `none` instead.

File: src/browser/PasskeyUtils.cpp [hunk 9]
```diff
@@ -0,0 +1,329 @@
...
+        return false;
+    }
+
+    const auto requireResidentKey = authenticatorSelection["requireResidentKey"].toBool();
+    if (requireResidentKey && !BrowserPasskeys::SUPPORT_RESIDENT_KEYS) {
+        return false;
+    }
+
+    const auto residentKey = authenticatorSelection["residentKey"].toString();
+    if (residentKey.isEmpty() && requireResidentKey && !BrowserPasskeys::SUPPORT_RESIDENT_KEYS) {
```
Comment (Ortham) [inline src/browser/PasskeyUtils.cpp:195]: This check just repeats the check on line 181 above. It looks like you're missing a check for when `residentKey == "required"`, see my equivalent code [here](https://github.com/Ortham/passkeys-client/blob/main/src/page/webauthn.ts#L107-L114).

File: src/browser/BrowserPasskeysClient.cpp [hunk 10]
```diff
@@ -0,0 +1,174 @@
...
+
+    auto authenticatorAttachment = authenticatorSelection["authenticatorAttachment"].toString();
+    if (authenticatorAttachment.isEmpty()) {
+        authenticatorAttachment = BrowserPasskeys::ATTACHMENT_PLATFORM;
+    }
+
+    // Check validity of UserVerificationRequirement
+    const auto userVerification = authenticatorSelection["userVerification"].toString();
+    if (!passkeyUtils()->isUserVerificationValid(userVerification)) {
+        return ERROR_PASSKEYS_INVALID_USER_VERIFICATION;
```
Comment (Ortham) [inline src/browser/BrowserPasskeysClient.cpp]: This doesn't need to (shouldn't?) be an error, the spec says that if it's not a recognised value, the value should be ignored.

File: src/browser/PasskeyUtils.cpp [hunk 11]
```diff
@@ -0,0 +1,329 @@
...
+    return QStringList({BrowserPasskeys::REQUIREMENT_PREFERRED,
+                        BrowserPasskeys::REQUIREMENT_REQUIRED,
+                        BrowserPasskeys::REQUIREMENT_DISCOURAGED})
+        .contains(userVerification);
+}
+
+bool PasskeyUtils::isResidentKeyRequired(const QJsonObject& authenticatorSelection) const
+{
+    const auto residentKey = authenticatorSelection["residentKey"].toString();
+    if (residentKey == BrowserPasskeys::REQUIREMENT_REQUIRED || residentKey == BrowserPasskeys::REQUIREMENT_PREFERRED) {
```
Comment (Ortham) [inline src/browser/PasskeyUtils.cpp]: For consistency the preferred case should only return true if `BrowserPasskeys::SUPPORT_RESIDENT_KEYS` is true.

File: src/browser/BrowserService.cpp [hunk 12]
```diff
@@ -620,55 +622,48 @@ QJsonObject BrowserService::showPasskeysRegisterPrompt(const QJsonObject& public
...
-    const auto userVerification = authenticatorSelection["userVerification"].toString();
-    if (!browserPasskeys()->isUserVerificationValid(userVerification)) {
-        return getPasskeyError(ERROR_PASSKEYS_INVALID_USER_VERIFICATION);
-    }
+    const auto excludeCredentials = credentialCreationOptions["excludeCredentials"].toArray();
+    const auto rpId = publicKeyOptions["rp"]["id"].toString();
+    const auto timeout = publicKeyOptions["timeout"].toInt();
+    const auto username = credentialCreationOptions["user"].toObject()["name"].toString();
 
+    // Parse excludeCredentialDescriptorList
```
Comment (Ortham) [inline src/browser/BrowserService.cpp:637]: It looks like there's a step missing before this where a supported algorithm is selected, or an error occurs if no supported algorithm was provided, see https://www.w3.org/TR/webauthn-3/#sctn-op-make-cred step 2.

File: src/browser/BrowserService.cpp [hunk 13]
```diff
@@ -620,55 +622,48 @@ QJsonObject BrowserService::showPasskeysRegisterPrompt(const QJsonObject& public
...
     if (!excludeCredentials.isEmpty() && isPasskeyCredentialExcluded(excludeCredentials, origin, keyList)) {
```
Comment (Ortham) [inline src/browser/BrowserService.cpp]: Checking if a credential is excluded should filter credentials by RP ID, not origin.

File: src/browser/BrowserService.cpp [hunk 14]
```diff
@@ -620,55 +622,48 @@ QJsonObject BrowserService::showPasskeysRegisterPrompt(const QJsonObject& public
...
         return getPasskeyError(ERROR_PASSKEYS_CREDENTIAL_IS_EXCLUDED);
```
Comment (Ortham) [inline src/browser/BrowserService.cpp:639]: The error type should depend on whether the user has given consent for the authenticator to reveal that the passkey exists, see step 3 of <https://www.w3.org/TR/webauthn-3/#sctn-op-make-cred>.

File: src/browser/BrowserService.cpp [hunk 15]
```diff
@@ -620,55 +622,48 @@ QJsonObject BrowserService::showPasskeysRegisterPrompt(const QJsonObject& public
...
     }
-
     const auto existingEntries = getPasskeyEntries(rpId, keyList);
-    const auto timeout = browserPasskeys()->getTimeout(userVerification, timeoutValue);
 
     raiseWindow();
     BrowserPasskeysConfirmationDialog confirmDialog;
     confirmDialog.registerCredential(username, rpId, existingEntries, timeout);
```
Comment (Ortham) [inline src/browser/BrowserService.cpp:645]: Technically, I don't think this dialog counts as user verification, as it doesn't require the user to be verified each time it is invoked (it only needs the user to be pre-verified by way of unlocking the Keepass database before the WebAuthn flow started).

That said, some other password managers (e.g. 1Password, Bitwarden) take the same approach of only requiring the DB to already be unlocked and not requiring any per-request verification, so at least this approach is no worse than some very popular commercial options.

Aside from that, I'm OK with this approach because while it's weaker against an evil maid signing you up to (or into, elsewhere) a website, in practice if you're at risk of such an attack and you leave your DB unlocked and unattended, you've got bigger problems. 🤷

File: src/browser/BrowserPasskeys.cpp [hunk 16]
```diff
@@ -444,9 +396,9 @@ char BrowserPasskeys::setFlagsFromJson(const QJsonObject& flags) const
 }
 
 // Returns the first supported algorithm from the pubKeyCredParams list (only support ES256, RS256 and EdDSA for now)
-WebAuthnAlgorithms BrowserPasskeys::getAlgorithmFromPublicKey(const QJsonObject& publicKey) const
+WebAuthnAlgorithms BrowserPasskeys::getAlgorithmFromPublicKey(const QJsonObject& credentialCreationOptions) const
```
Comment (Ortham) [inline src/browser/BrowserPasskeys.cpp:421]: This function should not use ES256 if no supported algorithm is specified, an error should have already been thrown before the user presence dialog was displayed.

Also, this function doesn't correctly handle the case where the first element of `credTypesAndPubKeyAlgs` is an unsupported algorithm but a later algorithm is supported. E.g. an RP may prefer PS256 but accept RS256 as its second choice, and in that case KeePassXC should choose RS256 instead of erroring (or, as it currently does, using ES256 instead).

File: src/browser/BrowserPasskeys.cpp [hunk 17]
```diff
@@ -59,125 +66,91 @@ BrowserPasskeys* BrowserPasskeys::instance()
...
     // Use default flags
-    const auto flags =
-        setFlagsFromJson(QJsonObject({{"ED", !extensions.isEmpty()},
-                                      {"AT", true},
-                                      {"BS", false},
-                                      {"BE", false},
-                                      {"UV", publicKey["userVerification"].toString() != REQUIREMENT_DISCOURAGED},
-                                      {"UP", true}}));
+    const auto flags = setFlagsFromJson(QJsonObject(
+        {{"ED", !extensions.isEmpty()}, {"AT", true}, {"BS", false}, {"BE", false}, {"UV", true}, {"UP", true}}));
```
Comment (Ortham) [inline src/browser/BrowserPasskeys.cpp:165]: I'd argue that the BE flag should be true because it's easy to backup the passkey by backing up a copy of the Keepass DB, though you can't set the BS flag to true because you've got no way of knowing if the user has done so. I'm happy with it either way though.

File: src/browser/BrowserPasskeys.cpp [hunk 18]
```diff
@@ -197,8 +170,12 @@ PrivateKey BrowserPasskeys::buildAttestationObject(const QJsonObject& publicKey,
         QByteArray::Base64UrlEncoding));
 
     // Credential private key
-    const auto alg = getAlgorithmFromPublicKey(publicKey);
+    const auto alg = getAlgorithmFromPublicKey(credentialCreationOptions);
     const auto credentialPublicKey = buildCredentialPrivateKey(alg, testingVariables.first, testingVariables.second);
```
Comment (Ortham) [inline src/browser/BrowserPasskeys.cpp]: It's not wrong, but I think it's a code smell that the private key is generated inside the function that generates the data that is sent back to the client, it would be too easy for a code change to accidentally expose the private key.

Variable naming doesn't help, with the private key being in `credentialPublicKey.pem` while the public key is stored in `credentialPublicKey.cborEncoded` - if I didn't know what was going on I'd assume the two fields were different encodings of the same public key data.

I think it would be more safely maintainable for the key pair to be generated outside of this function and then the public key to be passed into this function.

Comment (Ortham) [inline src/browser/BrowserPasskeys.cpp]: I can't comment on the implementation of `buildCredentialPrivateKey()` since it hasn't changed, but the way its return value is constructed is very risky. It constructs a type of

```c++
struct PrivateKey
{
    QByteArray cborEncoded;
    QByteArray pem;
};
```

using `return {result, pem};`, so if a code change were to swap the order in which the `cborEncoded` and `pem` fields were declared, it would inadvertantly mean private keys would be exposed. If you're going to store the public and private key data using the same data type (and I'd recommend that best practice would be to create distinct wrapper types for them), at least construct the objects using the field names explicitly so that the declaration order is not significant.

Comment (Ortham) [inline src/browser/BrowserPasskeys.cpp]: Again, I can't comment on `buildCredentialPrivateKey()`, but it's again needlessly risky that when generating an EdDSA key it sets `secondPart` to be the private key data and then passes it into `cborEncodePublicKey()`. That function doesn't actually use the `secondPart` data, but it shouldn't be given private data in the first place: just leave it as an empty byte array.

File: src/browser/BrowserCbor.cpp [hunk 19]
```diff
@@ -96,8 +96,15 @@ QByteArray BrowserCbor::cborEncodePublicKey(int alg, const QByteArray& first, co
 
         writer.endMap();
     } else if (alg == WebAuthnAlgorithms::EDDSA) {
-        // https://www.rfc-editor.org/rfc/rfc8152#section-13.2
-        writer.startMap(3);
+        writer.startMap(4);
+
+        // Key type
+        writer.append(1);
+        writer.append(getCoseKeyType(alg));
```
Comment (Ortham) [inline src/browser/BrowserCbor.cpp]: I can't comment on the functions directly, but I think the default cases for `getCoseKeyType()` and `getCurveParameter()` should throw errors instead of returning `WebAuthnCoseKeyType::EC2` and  `WebAuthnCurveKey::P256` respectively, as it should be impossible to hit those default cases (as the algorithm is validated before those functions get called), so hitting the default case is a logical error that shouldn't be silently ignored.

File: src/browser/BrowserPasskeys.cpp [hunk 20]
```diff
@@ -59,125 +66,91 @@ BrowserPasskeys* BrowserPasskeys::instance()
...
-    clientData["crossOrigin"] = false;
-    clientData["origin"] = origin;
-    clientData["type"] = get ? QString("webauthn.get") : QString("webauthn.create");
-
-    return clientData;
-}
-
 // https://w3c.github.io/webauthn/#attestation-object
-PrivateKey BrowserPasskeys::buildAttestationObject(const QJsonObject& publicKey,
+PrivateKey BrowserPasskeys::buildAttestationObject(const QJsonObject& credentialCreationOptions,
```
Comment (Ortham) [inline src/browser/BrowserPasskeys.cpp]: Why does a function called `buildAttestationObject()` return data of type `PrivateKey`? As I've said in other comments, the data type name is misleading, and it's constructed in a way that risks a code change sending the private key to the RP instead of the attestation object. I don't think that's a security risk when creating a credential (since the private key you've just generated is useless to the RP on its own), but WebAuthn Level 3 adds the option to send an attestation object when using a passkey, so if that's supported at some point it would risk leaking a meaningful private key.

File: src/browser/BrowserPasskeysClient.cpp [hunk 21]
```diff
@@ -0,0 +1,174 @@
...
+    const auto extensionData = passkeyUtils()->buildExtensionData(extensionObject);
+    const auto extensions = browserMessageBuilder()->getBase64FromArray(extensionData);
+
+    // clientDataJson
+    const auto clientDataJson = passkeyUtils()->buildClientDataJson(publicKeyOptions, origin, true);
+
+    // Check validity of UserVerificationRequirement
+    const auto userVerification = publicKeyOptions["userVerification"].toString();
+    if (!passkeyUtils()->isUserVerificationValid(userVerification)) {
+        return ERROR_PASSKEYS_INVALID_USER_VERIFICATION;
```
Comment (Ortham) [inline src/browser/BrowserPasskeysClient.cpp]: Same as when creating a passkey, this doesn't need to (shouldn't?) be an error, the spec says that if it's not a recognised value, the value should be ignored.

File: src/browser/BrowserPasskeysClient.cpp [hunk 22]
```diff
@@ -0,0 +1,174 @@
...
+    const auto isUserVerificationRequired = passkeyUtils()->isUserVerificationRequired(publicKeyOptions);
+
+    QJsonObject assertionOptions;
+    assertionOptions["clientDataJson"] = clientDataJson;
+    assertionOptions["extensions"] = extensions;
+    assertionOptions["rpId"] = rpId;
+    assertionOptions["userPresence"] = !isUserVerificationRequired;
+    assertionOptions["userVerification"] = isUserVerificationRequired;
+
+    *result = assertionOptions;
```
Comment (Ortham) [inline src/browser/BrowserPasskeysClient.cpp:171]: This is missing `publicKeyOptions["allowCredentials"]`, which is used later in `PasskeyUtils::getAllowedCredentialsFromPublicKey()`.

File: src/browser/BrowserPasskeysClient.cpp [hunk 23]
```diff
@@ -0,0 +1,174 @@
...
+    if (!passkeyUtils()->isUserVerificationValid(userVerification)) {
+        return ERROR_PASSKEYS_INVALID_USER_VERIFICATION;
+    }
+    const auto isUserVerificationRequired = passkeyUtils()->isUserVerificationRequired(publicKeyOptions);
+
+    QJsonObject assertionOptions;
+    assertionOptions["clientDataJson"] = clientDataJson;
+    assertionOptions["extensions"] = extensions;
+    assertionOptions["rpId"] = rpId;
+    assertionOptions["userPresence"] = !isUserVerificationRequired;
```
Comment (Ortham) [inline src/browser/BrowserPasskeysClient.cpp]: It's best to omit `userPresence` as user presence is always required, and having it as the inverse of user verification (which it is in WebAuthn Level 1 only) is needlessly confusing IMHO and could lead to faulty logic where you check user presence but forget to check user verification and see that user presence is false so don't perform a user presence test. WebAuthn Level 2 and 3 treat it as a pseudo-parameter that's always `true`.

File: src/browser/BrowserService.cpp [hunk 24]
```diff
@@ -725,7 +717,21 @@ QJsonObject BrowserService::showPasskeysAuthenticationPrompt(const QJsonObject&
     if (dialogResult == QDialog::Accepted) {
         hideWindow();
         const auto selectedEntry = confirmDialog.getSelectedEntry();
-        return getPublicKeyCredentialFromEntry(selectedEntry, publicKey, origin);
+        if (!selectedEntry) {
+            return getPasskeyError(ERROR_PASSKEYS_UNKNOWN_ERROR);
+        }
+
+        const auto privateKeyPem = selectedEntry->attributes()->value(BrowserPasskeys::KPEX_PASSKEY_PRIVATE_KEY_PEM);
+        const auto credentialId = selectedEntry->attributes()->value(BrowserPasskeys::KPEX_PASSKEY_GENERATED_USER_ID);
```
Comment (Ortham) [inline src/browser/BrowserService.cpp]: I know I'm repeating myself, but `KPEX_PASSKEY_GENERATED_USER_ID` is a very confusing and misleading name, could you rename it to something like `KPEX_PASSKEY_CREDENTIAL_ID` instead?

File: src/browser/BrowserService.cpp [hunk 25]
```diff
@@ -1347,7 +1353,7 @@ QList<Entry*> BrowserService::getPasskeyAllowedEntries(const QJsonObject& public
                                                        const StringPairList& keyList)
 {
     QList<Entry*> entries;
-    const auto allowedCredentials = browserPasskeys()->getAllowedCredentialsFromPublicKey(publicKey);
+    const auto allowedCredentials = passkeyUtils()->getAllowedCredentialsFromPublicKey(publicKey);
```
Comment (Ortham) [inline src/browser/BrowserService.cpp]: If `publicKey["allowCredentials"]` is not empty but `allowedCredentials` is empty, that should cause the request to timeout, but the current implementation treats that case as if no allowed credentials were provided and will therefore match against credentials that the RP has chosen not to allow.

File: src/browser/BrowserPasskeys.cpp [hunk 26]
```diff
@@ -59,125 +66,91 @@ BrowserPasskeys* BrowserPasskeys::instance()
...
                                                          const QString& privateKeyPem)
 {
-    const auto authenticatorData = buildGetAttestationObject(publicKeyCredentialRequestOptions);
-    const auto clientData = buildClientDataJson(publicKeyCredentialRequestOptions, origin, true);
-    const auto clientDataArray = QJsonDocument(clientData).toJson(QJsonDocument::Compact);
+    if (!passkeyUtils()->checkCredentialAssertionOptions(assertionOptions)) {
+        return {};
+    }
+
+    const auto authenticatorData = buildGetAttestationObject(assertionOptions);
```
Comment (Ortham) [inline src/browser/BrowserPasskeys.cpp]: `buildGetAttestationObject()` is a misleading function name, it's only building the authenticator data. WebAuthn Level 3 adds the option to also return an attestation object, so it's easy to misunderstand what's going on.

File: src/browser/BrowserPasskeys.cpp [hunk 27]
```diff
@@ -218,13 +195,8 @@ QByteArray BrowserPasskeys::buildGetAttestationObject(const QJsonObject& publicK
...
 
-    const auto flags =
-        setFlagsFromJson(QJsonObject({{"ED", false},
-                                      {"AT", false},
-                                      {"BS", false},
-                                      {"BE", false},
-                                      {"UV", publicKey["userVerification"].toString() != REQUIREMENT_DISCOURAGED},
-                                      {"UP", true}}));
+    const auto flags = setFlagsFromJson(
+        QJsonObject({{"ED", false}, {"AT", false}, {"BS", false}, {"BE", false}, {"UV", true}, {"UP", true}}));
```
Comment (Ortham) [inline src/browser/BrowserPasskeys.cpp]: Same comment as before about the `BE` flag, but as in that comment this approach is fine.

File: src/browser/BrowserPasskeys.cpp (hunk 26 above)
Comment (Ortham) [inline src/browser/BrowserPasskeys.cpp]: Since I can't comment on the relevant code directly, is it intentional that `buildGetAttestationObject()` does not include any extensions data in its output?

I don't think I've seen any processing of extensions when getting a credential, but `BrowserPasskeysClient::getAssertionOptions()` does preserve the input data and creating a credential does support the `uvm` extension, which also applies to the get flow. Though saying that, while I've seen code saying it's supported, I don't recall seeing anything that actually processes the extension. Is that implemented?

**Review by Ortham — CHANGES_REQUESTED** [review]
Sorry about the flood of comments, but on a positive note I found the changed code much easier to follow than before, and thanks for addressing the issues I'd raised. 👍

File: src/browser/BrowserPasskeys.cpp (hunk 18 above)
Comment (droidmonkey) [reply src/browser/BrowserPasskeys.cpp]: Agreed, building a private key should return a distinct private key object that includes the public key. The object definitely shouldn't be named public key!

File: src/browser/BrowserAction.cpp (hunk 2 above)
Comment (varjolintu) [reply src/browser/BrowserAction.cpp:2]: I'll add an option for this that allows localhost for testing purposes.

File: src/browser/PasskeyUtils.cpp (hunk 4 above)
Comment (varjolintu) [reply src/browser/PasskeyUtils.cpp:255]: "This function was introduced in Qt 6.3." <- this is why I didn't include it.

File: src/browser/PasskeyUtils.cpp (hunk 3 above)
Comment (varjolintu) [reply src/browser/PasskeyUtils.cpp:97]: We always read the value as a string. If a `null` is passed to the API, it's same as empty origin, returning an error. Or are you saying the origin can be a string containing `"null"`?

Comment (Ortham) [reply src/browser/PasskeyUtils.cpp:97]: The latter, e.g. if you open `data:text/plain;base64,SGVsbG8sIFdvcmxkIQ==` in your web browser and check `window.origin`, the value is a string containing `null` (i.e. the letters, without double quotes). A screenshot from Edge's dev tools, to help avoid confusion:

image

File: src/browser/BrowserAction.cpp (hunk 2 above)
Comment (Ortham) [reply src/browser/BrowserAction.cpp:2]: The logic for deciding if something is a secure context is described [here](https://html.spec.whatwg.org/multipage/webappapis.html#secure-context). Ignoring the parts that aren't relevant because they're not allowed origins for WebAuthn, the origins that should be allowed are:

- `https://` followed by anything
- Any origin with a host that is `localhost` or `localhost.`
- Any origin with a host that ends with `.localhost` or `.localhost.`
- `file://` followed by anything

So it would be good if the logic allowed all of them.

This disregards origins that the browser might consider to be authenticated or trustworthy (the spec gives the example of browser extension pages' origins), but I don't think KeePassXC has any way of knowing what those would be and it seems like a niche case anyway.

File: src/browser/PasskeyUtils.cpp (hunk 4 above)
Comment (Ortham) [reply src/browser/PasskeyUtils.cpp:255]: Ah, right. Is that something that could be noted to swap in later as part of the update to Qt 6?

File: src/browser/PasskeyUtils.cpp (hunk 3 above)
Comment (varjolintu) [reply src/browser/PasskeyUtils.cpp:97]: Those values are treated as empty values in KeePassXC side.

File: src/browser/BrowserService.cpp (hunk 12 above)
Comment (varjolintu) [reply src/browser/BrowserService.cpp:637]: It's already checked in `BrowserPasskeysClient::getCredentialCreationOptions()`.

Comment (Ortham) [reply src/browser/BrowserService.cpp:637]: Where in that function? I see the call to `parseCredentialTypes()` but that doesn't choose a supported algorithm.

File: src/browser/BrowserAction.cpp [hunk 28]
```diff
@@ -541,7 +541,7 @@ QJsonObject BrowserAction::handlePasskeysGet(const QJsonObject& json, const QStr
     }
 
     const auto origin = browserRequest.getString("origin");
-    if (!origin.startsWith("https://")) {
+    if (!browserSettings()->allowLocalhostWithPasskeys() && !origin.startsWith("https://")) {
```
Comment (Ortham) [inline src/browser/BrowserAction.cpp]: This doesn't just allow localhost, it allows anything. Shouldn't there also be a check to see if the host is localhost?

File: src/browser/BrowserAction.cpp [hunk 29]
```diff
@@ -574,7 +574,7 @@ QJsonObject BrowserAction::handlePasskeysRegister(const QJsonObject& json, const
...
```
Comment (Ortham) [inline src/browser/BrowserAction.cpp]: Same as above, it looks like this should also check if the host is localhost.

File: src/browser/PasskeyUtils.cpp (hunk 5 above)
Comment (Ortham) [reply src/browser/PasskeyUtils.cpp]: I don't know why this was marked as resolved, the issues are still present.

File: src/browser/BrowserPasskeysClient.cpp (hunk 10 above)
Comment (Ortham) [reply src/browser/BrowserPasskeysClient.cpp]: I don't know why this was marked as resolved, the issue is still present.

File: src/browser/PasskeyUtils.cpp (hunk 11 above)
Comment (Ortham) [reply src/browser/PasskeyUtils.cpp]: I don't know why this was marked as resolved, the issue is still present.

File: src/browser/BrowserService.cpp (hunk 12 above)
Comment (varjolintu) [reply src/browser/BrowserService.cpp:637]: Where does it say to "choose" in the specification? The step 2 only points out that the supported algorithms should be checked. Although the three supported ones are not really checked here, so I'll add that.

File: src/browser/BrowserService.cpp (hunk 13 above)
Comment (Ortham) [reply src/browser/BrowserService.cpp]: I don't know why this was marked as resolved, the issue is still present.

File: src/browser/BrowserService.cpp (hunk 14 above)
Comment (varjolintu) [reply src/browser/BrowserService.cpp:639]: Could it harm if we just automatically choose not to consent?

File: src/browser/BrowserAction.cpp (hunk 28 above)
Comment (varjolintu) [reply src/browser/BrowserAction.cpp]: Yes :)

File: src/browser/BrowserService.cpp (hunk 12 above)
Comment (Ortham) [reply src/browser/BrowserService.cpp:637]: Sorry, I got the steps muddled up, the choosing doesn't happen until 7.1. What is missing here from step 2 is:

> Check if at least one of the specified combinations of [PublicKeyCredentialType](https://www.w3.org/TR/webauthn-3/#enumdef-publickeycredentialtype) **and cryptographic parameters** in credTypesAndPubKeyAlgs is supported.

Emphasis mine, `parseCredentialTypes()` checks the `type` values but not the `alg` values.

File: src/browser/BrowserService.cpp (hunk 14 above)
Comment (Ortham) [reply src/browser/BrowserService.cpp:639]: I don't think so, I didn't check how `ERROR_PASSKEYS_CREDENTIAL_IS_EXCLUDED` was being handled in the browser extension, but now that I have this seems fine.

File: src/browser/BrowserPasskeys.cpp (hunk 20 above)
Comment (varjolintu) [reply src/browser/BrowserPasskeys.cpp]: That's a good point. I'd rather create the key outside of that function, and just return the pure Attestation Object.

File: src/browser/PasskeyUtils.cpp (hunk 5 above)
Comment (varjolintu) [reply src/browser/PasskeyUtils.cpp]: I marked many of these solved before I actually pushed the changes.

File: src/browser/BrowserCbor.cpp [hunk 30]
```diff
@@ -230,7 +243,7 @@ unsigned int BrowserCbor::getCurveParameter(int alg) const
     case WebAuthnAlgorithms::EDDSA:
         return WebAuthnCurveKey::ED25519;
     default:
-        return WebAuthnCurveKey::P256;
+        return 0;
```
Comment (droidmonkey) [inline src/browser/BrowserCbor.cpp]: would prefer `WebAuthnCurveKey::Invalid` which equals 0, but is named

File: src/browser/BrowserCbor.cpp [hunk 31]
```diff
@@ -240,14 +253,15 @@ unsigned int BrowserCbor::getCoseKeyType(int alg) const
...
     case WebAuthnAlgorithms::ES512:
-        return WebAuthnCoseKeyType::EC2;
+        return 0;
     case WebAuthnAlgorithms::EDDSA:
         return WebAuthnCoseKeyType::OKP;
     case WebAuthnAlgorithms::RS256:
         return WebAuthnCoseKeyType::RSA;
     default:
-        return WebAuthnCoseKeyType::EC2;
+        return 0;
```
Comment (droidmonkey) [inline src/browser/BrowserCbor.cpp]: Same here, `WebAuthnCoseKeyType::Invalid` resolving to 0

File: src/browser/BrowserCbor.cpp [hunk 32]
```diff
@@ -240,14 +253,15 @@ unsigned int BrowserCbor::getCoseKeyType(int alg) const
 {
     switch (alg) {
     case WebAuthnAlgorithms::ES256:
+        return WebAuthnCoseKeyType::EC2;
     case WebAuthnAlgorithms::ES384:
     case WebAuthnAlgorithms::ES512:
-        return WebAuthnCoseKeyType::EC2;
+        return 0;
```
Comment (droidmonkey) [inline src/browser/BrowserCbor.cpp]: Same here, `WebAuthnCoseKeyType::Invalid` resolving to 0

File: src/browser/BrowserPasskeys.cpp [hunk 33]
```diff
@@ -59,125 +66,103 @@ BrowserPasskeys* BrowserPasskeys::instance()
...
     // Use default flags
-    const auto flags =
-        setFlagsFromJson(QJsonObject({{"ED", !extensions.isEmpty()},
-                                      {"AT", true},
-                                      {"BS", false},
-                                      {"BE", false},
-                                      {"UV", publicKey["userVerification"].toString() != REQUIREMENT_DISCOURAGED},
-                                      {"UP", true}}));
+    const auto flags = setFlagsFromJson(QJsonObject(
+        {{"ED", !extensions.isEmpty()}, {"AT", true}, {"BS", false}, {"BE", false}, {"UV", true}, {"UP", true}}));
```
Comment (droidmonkey) [inline src/browser/BrowserPasskeys.cpp:165]: Would be good to link drop the definition of the various flags, ED/AT/BS/BE/etc. https://www.w3.org/TR/webauthn-2/#flags or just define them in a comment:

```
// ED - Extension Data, AT - Attested Credential, BS - ???
// BE - ??? , UV - User Verified, UP - User Present
```

File: src/browser/BrowserPasskeys.cpp [hunk 34]
```diff
@@ -339,7 +329,7 @@ QByteArray BrowserPasskeys::buildSignature(const QByteArray& authenticatorData,
             rawSignature = signer.signature(*randomGen()->getRng());
         } else if (algName == "Ed25519") {
             Botan::Ed25519_PrivateKey privateKey(algId, privateKeyBytes);
-            Botan::PK_Signer signer(privateKey, *randomGen()->getRng(), "SHA-512");
+            Botan::PK_Signer signer(privateKey, *randomGen()->getRng(), "Pure");
```
Comment (droidmonkey) [inline src/browser/BrowserPasskeys.cpp:333]: Need a comment or link drop here on what "Pure" means in this context: https://botan.randombit.net/handbook/api_ref/pubkey.html#ed25519-variants

File: src/browser/BrowserPasskeysClient.cpp [hunk 35]
```diff
@@ -0,0 +1,171 @@
...
+    credentialCreationOptions["residentKey"] = isResidentKeyRequired;
+    credentialCreationOptions["rp"] = QJsonObject({{"id", rpId}, {"name", rpName}});
+    credentialCreationOptions["user"] = publicKeyOptions["user"];
+    credentialCreationOptions["userPresence"] = !isUserVerificationRequired;
+    credentialCreationOptions["userVerification"] = isUserVerificationRequired;
+
+    *result = credentialCreationOptions;
+    return 0;
+}
+#include <QJsonDocument>
```
Comment (droidmonkey) [inline src/browser/BrowserPasskeysClient.cpp]: should be at top of file

File: src/browser/PasskeyUtils.cpp [hunk 36]
```diff
@@ -0,0 +1,344 @@
...
+        return ERROR_PASSKEYS_ORIGIN_NOT_ALLOWED;
+    }
+
+    const auto effectiveDomain = QUrl::fromUserInput(origin).host();
+    if (!isDomain(effectiveDomain)) {
+        return ERROR_PASSKEYS_DOMAIN_IS_NOT_VALID;
+    }
+
+    *result = effectiveDomain;
+    return 0;
```
Comment (droidmonkey) [inline src/browser/PasskeyUtils.cpp]: Should define this as `PASSKEYS_SUCCESS` or similar

**Review by droidmonkey — APPROVED** [review]

File: src/browser/BrowserService.cpp [hunk 37]
```diff
@@ -699,24 +694,21 @@ QJsonObject BrowserService::showPasskeysAuthenticationPrompt(const QJsonObject&
...
 
-    // Parse "allowCredentials"
-    const auto rpId = publicKey["rpId"].toString();
-    const auto entries = getPasskeyAllowedEntries(publicKey, rpId, keyList);
+    // Get allowed entries from RP ID
+    const auto rpId = assertionOptions["rpId"].toString();
+    const auto entries = getPasskeyAllowedEntries(assertionOptions, rpId, keyList);
     if (entries.isEmpty()) {
-        return getPasskeyError(ERROR_KEEPASS_NO_LOGINS_FOUND);
+        return getPasskeyError(ERROR_PASSKEYS_WAIT_FOR_LIFETIMER);
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp]: I believe this is the wrong error message, should be NO_LOGINS_FOUND

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/browser/PasskeyUtils.cpp [hunk 38]
```diff
@@ -0,0 +1,344 @@
...
+    return QStringList({BrowserPasskeys::REQUIREMENT_PREFERRED,
+                        BrowserPasskeys::REQUIREMENT_REQUIRED,
+                        BrowserPasskeys::REQUIREMENT_DISCOURAGED})
+        .contains(userVerification);
+}
+
+bool PasskeyUtils::isOriginAllowedWithLocalhost(bool allowLocalhostWithPasskeys, const QString& origin) const
+{
+    return (!allowLocalhostWithPasskeys && origin.startsWith("https://"))
+           || (allowLocalhostWithPasskeys && (origin.startsWith("https://") || origin.startsWith("http://localhost")));
```
Comment (Ortham) [inline src/browser/PasskeyUtils.cpp]: This would allow an origin like `http://localhosting.com`, which would allow MITM to occur when a user isn't expecting it. How about logic like:

```c++
if (origin.startsWith("https://") || (allowLocalhostWithPasskeys && origin.startsWith("file://")) {
  return true;
}

if (!allowLocalhostWithPasskeys) {
  return false;
}

const auto host = QUrl::fromUserInput(origin).host();

return host == "localhost" 
  || host == "localhost."
  || host.endsWith(".localhost")
  || host.endsWith(".localhost.");
```

Comment (varjolintu) [reply src/browser/PasskeyUtils.cpp]: This could work.

**Review by droidmonkey — APPROVED** [review]

File: src/browser/BrowserPasskeys.cpp [hunk 39]
```diff
@@ -444,9 +418,9 @@ char BrowserPasskeys::setFlagsFromJson(const QJsonObject& flags) const
 }
 
 // Returns the first supported algorithm from the pubKeyCredParams list (only support ES256, RS256 and EdDSA for now)
-WebAuthnAlgorithms BrowserPasskeys::getAlgorithmFromPublicKey(const QJsonObject& publicKey) const
+WebAuthnAlgorithms BrowserPasskeys::getAlgorithmFromPublicKey(const QJsonObject& credentialCreationOptions) const
 {
-    const auto pubKeyCredParams = publicKey["pubKeyCredParams"].toArray();
+    const auto pubKeyCredParams = credentialCreationOptions["credTypesAndPubKeyAlgs"].toArray();
     if (!pubKeyCredParams.isEmpty()) {
         const auto alg = pubKeyCredParams.first()["alg"].toInt();
```
Comment (Ortham) [inline src/browser/BrowserPasskeys.cpp:425]: Copied from an earlier comment:

> This function doesn't correctly handle the case where the first element of credTypesAndPubKeyAlgs is an unsupported algorithm but a later algorithm is supported. E.g. an RP may prefer PS256 but accept RS256 as its second choice, and in that case KeePassXC should choose RS256 instead of using ES256.

I think this still applies.

Comment (droidmonkey) [reply src/browser/BrowserPasskeys.cpp:425]: I think you mean we should iterate through the array until we find a supported algorithm, instead of just picking the first element and bailing out if that doesn't work. I agree.

Comment (varjolintu) [reply src/browser/BrowserPasskeys.cpp:425]: Just to note, the array comes from here: https://github.com/keepassxreboot/keepassxc/pull/10318/files#diff-02fad338f30f066992b2231a0cf4f5a91592313a32a22defedc5574b4a0d6a55R141
So the first element is already from the supported list.
