### PR TITLE
Accept kdbx:// urls in Edit Entry view

### LINKED ISSUE #7220: URLs starting with a slash (e.g. kdbx:///path/to/db.kdbx) displayed as invalid
## Overview
If you enter an absolute path to a file on Linux, e.g. `kdbx:///path/to/db.kdbx) for AutoOpen, the entry field tells you "Invalid URL".

## Steps to Reproduce
1. add any absolute URL with three slashes
2. clicking on the URL still works as expected.

## Expected Behavior
The field shouldn't become red.

## Actual Behavior
URL field becomes red and tells you "invalid URL"

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9

Operating System: Linux
Desktop Env: KDE
Windowing System: X11/Wayland

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Fix displying URLs starting with `kdbx://` as invalid.

Fixes #7220.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/core/Tools.cpp [hunk 1]
```diff
@@ -242,6 +242,7 @@ namespace Tools
     bool checkUrlValid(const QString& urlField)
     {
         if (urlField.isEmpty() || urlField.startsWith("cmd://", Qt::CaseInsensitive)
+            || urlField.startsWith("kdbx://", Qt::CaseInsensitive)
```
Comment (droidmonkey) [inline src/core/Tools.cpp:273]: might as well toss file:// up here as well and then we can delete the exception for file down on line 257

**Review by droidmonkey — APPROVED** [review]

File: src/core/Tools.cpp (hunk 1 above)
Comment (varjolintu) [reply src/core/Tools.cpp:273]: Sure. Still, it looks file `file://` is also checked that it actually contains something. Maybe a similar check would be needed for `cmd://` and `kdbx://` as well.

Comment (droidmonkey) [reply src/core/Tools.cpp:273]: Agree

**Review by droidmonkey — APPROVED** [review]
