### PR TITLE
Fix various quirks with CSV import widget and parser

### LINKED ISSUE #7956: Import tags with CSV
### Discussed in https://github.com/keepassxreboot/keepassxc/discussions/7954

<div type='discussions-op-text'>

<sup>Originally posted by **MembershipExcel** April 25, 2022</sup>
Hi
Is there a way to import or add tag while importing from file (.csv for exemple)

My original CSV file as a "tag column" but it doesn't seem possible to put the information while creating/importing the DB so I need to modify them manually</div>

### LINKED ISSUE #11502: Text-/Comment-Qualifiers corrupt csv import data
## Overview
In KeypassXC 2.6.6 importing a CSV file a text qualifiers contained in a field breaks the line. Also the recognition of text qualifiers is greedy within the current csv-entry, i.e. it doesn't check wether it is a textqualifier directly followed by a separator or linebreak to close the field.

## Steps to Reproduce
1. Try import csv
2. Try importing a file with fields containing 3 textqualifiers among other random strings or ending a csv field early with a closing textqualfier.

## Expected Behavior
I'd have thought a textqualifier qualifies the entire csv-field as text. To parse this one would have to check for the opening qualifier directly after a linebreak or previous separator and the closing qualfier *directly* followed by either a linebreak or a separator.
Alternatively it should be possible to disable text/comment-qualifiers.

## Actual Behavior
The early closing of the text-qualifier in a csv-field acts similar to a linebreak.

KeePassXC - 2.6.6
Revision: 9c108b9

Operating System: Linux
Desktop Env: Cinnamon

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #11502 - correct improper handling of text qualifiers
* Closes #7956 - support importing tags from csv
* Improve layout of csv import widget
* Hide error messages when trying to import again

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and include helpful comments. )
Tested extensively with various CSV files

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/csvImport/CsvImportWidget.cpp [hunk 1]
```diff
@@ -254,14 +271,14 @@ QSharedPointer<Database> CsvImportWidget::buildDatabase()
 
         // Icon
         bool ok;
-        int icon = m_parserModel->data(m_parserModel->index(r, 7)).toInt(&ok);
+        int icon = m_parserModel->data(m_parserModel->index(r, 8)).toInt(&ok);
```
Comment (phoerious) [inline src/gui/csvImport/CsvImportWidget.cpp:274]: These magic numbers seem very fragile to me. Can we name or automatically derive them somehow?

Comment (droidmonkey) [reply src/gui/csvImport/CsvImportWidget.cpp:274]: Yah i agree they are very magical

**Review by phoerious — APPROVED** [review]

File: src/gui/csvImport/CsvImportWidget.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/gui/csvImport/CsvImportWidget.cpp:274]: We will fix these later, this is rather static anyway
