### PR TITLE
Fix AppRun path issue

### LINKED ISSUE #12612: PATH issue in AppRun.wrapped (AppImage)
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

Hi devs,
I found another issue in the bundled AppImages, tested with the current snapshots.
It looks like there is an issue with the `$PATH` in the `AppRun.wrapped` script, in an old commit, there was, although, a PATH export:

```
$ ./KeePassXC-2.8.0-snapshot-x86_64.AppImage 
/tmp/.mount_KeePasAs9sCV/AppRun.wrapped: line 11: exec: keepassxc: not found
$ RC = 127
```

Hope that helps, thank you!

### Steps to Reproduce

1. Download AppImage Snapshot
2. Execute on linux system

### Expected Versus Actual Behavior

_No response_

### KeePassXC Debug Information

```Text

```

### Operating System

Linux

### Linux Desktop Environment

Gnome

### Linux Windowing System

Wayland

### PR DESCRIPTION
**Pull request by phoerious**
Fix PATH issue in AppRun script.
Fixes #12612 

Changes not actually tested yet.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
I found that the browser integration also does not work anymore (at least with snap firefox). Same browser works with native install.

**Comment by phoerious** [comment]
Ok, maybe we need to add the library path back as well.

**Comment by droidmonkey** [comment]
Nah it's the Firefox Snap, it doesn't set the environment variable. Need to include the flatpak method here.

https://github.com/keepassxreboot/keepassxc/blob/develop/utils%2Fkeepassxc-flatpak-wrapper.sh#L26-L34

**Comment by phoerious** [comment]
But why? We haven't changed that part in years. Are there any other env cars we could check for?

**Comment by droidmonkey** [comment]
The fix I posted works with Snap Firefox now.

**Review by droidmonkey — APPROVED** [review]

**Comment by phoerious** [comment]
We should ensure we never set an empty : as a library path, otherwise we're back at the issue because of which I removed it in the first place.

**Comment by droidmonkey** [comment]
Oh take that out then,  it is not needed for the proxy

File: share/linux/appimage-apprun.sh [hunk 1]
```diff
@@ -1,12 +1,15 @@
...
+
 if [ "$1" == "cli" ] || [ "$(basename "$ARGV0")" == "keepassxc-cli" ] || [ "$(basename "$ARGV0")" == "keepassxc-cli.AppImage" ]; then
     [ "$1" == "cli" ] && shift
     exec keepassxc-cli "$@"
-elif  [ "$1" == "proxy" ] || [ "$(basename "$ARGV0")" == "keepassxc-proxy" ] || [ "$(basename "$ARGV0")" == "keepassxc-proxy.AppImage" ] \
-    || [ -v CHROME_WRAPPER ] || [ -v MOZ_LAUNCHED_CHILD ]; then
+elif  [ "$1" == "proxy" ] || [ "$(basename "$ARGV0")" == "keepassxc-proxy" ] || [ "$(basename "$ARGV0")" == "keepassxc-proxy.AppImage" ]; then
     [ "$1" == "proxy" ] && shift
     exec keepassxc-proxy "$@"
+elif [ -v CHROME_WRAPPER ] || [ -v MOZ_LAUNCHED_CHILD ] || [ "$2" == "keepassxc-browser@keepassxc.org" ]; then
```
Comment (phoerious) [inline share/linux/appimage-apprun.sh:11]: ```[ "$2" == "keepassxc-browser@keepassxc.org" ]```

In which case would this be true?

Comment (droidmonkey) [reply share/linux/appimage-apprun.sh:11]: When launched from snap'd firefox

Comment (phoerious) [reply share/linux/appimage-apprun.sh:11]: In $2? Interesting.
