### PR TITLE
Check for mismatched passwords BEFORE saving to prevent data loss

### LINKED ISSUE #909: "Repeat" field does not match? I'm just throwing away all your changes!
If password and repeat don't match, you can click `OK` but all your changes won't get saved.

## Expected Behavior

I can think of two possible fixes, but there may be better ways.

- `OK` could be disabled as long as some basic requirements are not met
- pushing `OK` could also just yield a warning message, that password/repeat don't match

## Current Behavior

Pushing OK will close the editor, but the changes are lost.

## Steps to Reproduce (for bugs)

1. have a database open
2. edit an existing entry's title
3. make sure password and repeat *do not match*
4. click `OK`
5. look at the list, the _old_ entry is still there. Your changes are lost

## Debug Info

KeePassXC - Version 2.2.0
Revision: 5e309feaebf37afa5278f424056e0bbc034a20a8

Bibliotheken:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Betriebssystem: Debian GNU/Linux 9 (stretch)
CPU-Architektur: x86_64
Kernel: linux 4.9.0-3-amd64

Aktivierte Erweiterungen:
- Auto-Type

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

Fixes #909. Password fields are checked prior to saving to prevent data loss.

_Note: Code is repeated due to the way the apply button works (directly calls the save function). This should be refactored in the future._

## How has this been tested?

Manually and unit tests.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/entry/EditEntryWidget.cpp [hunk 1]
```diff
@@ -446,6 +446,12 @@ void EditEntryWidget::saveEntry()
 
 void EditEntryWidget::acceptEntry()
 {
+    // Check if passwords are mismatched first to prevent saving
+    if (!passwordsEqual()) {
+        showMessage(tr("Different passwords supplied."), MessageWidget::Error);
+        return;
+    }
```
Comment (louib) [inline src/gui/entry/EditEntryWidget.cpp]: @droidmonkey do you think you can add a test to `TestGui::testEditEntry()` for that?

Comment (droidmonkey) [reply src/gui/entry/EditEntryWidget.cpp]: Good idea, on it

Comment (droidmonkey) [reply src/gui/entry/EditEntryWidget.cpp]: @louib ready for you
