### PR TITLE
Correct multiple issues with database saving

### LINKED ISSUE #3857: Crash on macOS when stored in cloud service
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Apply changes to entry settings after clicking apply.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC crashes.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Start KeePassXC and select existing entry
2. Add Auto-type window setting to any currently existing windo
3. press apply
4. change the window title to another existing
5. press apply
-> it crashes

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Well, changes don't get persisted which certainly is not good and interruptive.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS Mojave (10.14)
CPU-Architektur: x86_64
Kernel: darwin 18.7.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

<details>
  <summary>Click to expand!</summary>

```
Process:               KeePassXC [7413]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               2.5.1 (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [7413]
User ID:               1970745226

Date/Time:             2019-11-13 14:23:59.272 +0100
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Bridge OS Version:     3.6 (16P6571)
Anonymous UUID:        EF9B27C9-AC49-AB49-37C2-1F6446CE6FE7

Sleep/Wake UUID:       0E878DB3-73C8-4E6C-AD70-17A914DB06E1

Time Awake Since Boot: 13000 seconds
Time Since Wake:       660 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000100
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [7413]

VM Regions Near 0x100:
--> 
    __TEXT                 0000000105b44000-0000000105ed0000 [ 3632K] r-x/r-x SM=COW  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.keepassx.keepassxc        	0x0000000105b7903f 0x105b44000 + 217151
1   org.keepassx.keepassxc        	0x0000000105c60d7a 0x105b44000 + 1166714
2   org.keepassx.keepassxc        	0x0000000105b5cb55 0x105b44000 + 101205
3   org.qt-project.QtCore         	0x0000000106fff833 QMetaObject::activate(QObject*, int, int, void**) + 1843
4   org.qt-project.QtCore         	0x0000000106fff833 QMetaObject::activate(QObject*, int, int, void**) + 1843
5   org.qt-project.QtWidgets      	0x00000001063698b3 0x1061c8000 + 1710259
6   org.qt-project.QtCore         	0x0000000106fff833 QMetaObject::activate(QObject*, int, int, void**) + 1843
7   org.qt-project.QtWidgets      	0x00000001062bf84f 0x1061c8000 + 1013839
8   org.qt-project.QtWidgets      	0x00000001062bf6ec 0x1061c8000 + 1013484
9   org.qt-project.QtWidgets      	0x00000001062c081c QAbstractButton::mouseReleaseEvent(QMouseEvent*) + 268
10  org.qt-project.QtWidgets      	0x0000000106212be7 QWidget::event(QEvent*) + 439
11  org.qt-project.QtWidgets      	0x00000001061d8220 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
12  org.qt-project.QtWidgets      	0x00000001061db186 QApplication::notify(QObject*, QEvent*) + 7670
13  org.qt-project.QtCore         	0x0000000106fcf834 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
14  org.qt-project.QtWidgets      	0x00000001061d8b47 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 903
15  org.qt-project.QtWidgets      	0x0000000106231dff 0x1061c8000 + 433663
16  org.qt-project.QtWidgets      	0x0000000106230b4a 0x1061c8000 + 428874
17  org.qt-project.QtWidgets      	0x00000001061d8220 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
18  org.qt-project.QtWidgets      	0x00000001061d95d5 QApplication::notify(QObject*, QEvent*) + 581
19  org.qt-project.QtCore         	0x0000000106fcf834 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
20  org.qt-project.QtGui          	0x00000001068acff1 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 3441
21  org.qt-project.QtGui          	0x000000010689464b QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 219
22  libqcocoa.dylib               	0x0000000108f02828 0x108ece000 + 215080
23  com.apple.CoreFoundation      	0x00007fff537c0de3 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
24  com.apple.CoreFoundation      	0x00007fff537c0d89 __CFRunLoopDoSource0 + 108
25  com.apple.CoreFoundation      	0x00007fff537a474b __CFRunLoopDoSources0 + 195
26  com.apple.CoreFoundation      	0x00007fff537a3d15 __CFRunLoopRun + 1189
27  com.apple.CoreFoundation      	0x00007fff537a361e CFRunLoopRunSpecific + 455
28  com.apple.HIToolbox           	0x00007fff52a021ab RunCurrentEventLoopInMode + 292
29  com.apple.HIToolbox           	0x00007fff52a01ded ReceiveNextEventCommon + 355
30  com.apple.HIToolbox           	0x00007fff52a01c76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
31  com.apple.AppKit              	0x00007fff50d9a77d _DPSNextEvent + 1135
32  com.apple.AppKit              	0x00007fff50d9946b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
33  com.apple.AppKit              	0x00007fff50d93588 -[NSApplication run] + 699
34  libqcocoa.dylib               	0x0000000108f01698 0x108ece000 + 210584
35  org.qt-project.QtCore         	0x0000000106fcaddf QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
36  org.qt-project.QtCore         	0x0000000106fcfe82 QCoreApplication::exec() + 130
37  org.keepassx.keepassxc        	0x0000000105b4ddb0 0x105b44000 + 40368
38  libdyld.dylib                 	0x00007fff7f6fa3d5 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff7f8ed3f0 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff7f8ed3f0 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff7f8ed3f0 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff7f8ed3f0 start_wqthread + 0

Thread 5:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff7f83661a __select + 10
1   com.apple.CoreFoundation      	0x00007fff537d22d2 __CFSocketManager + 635
2   libsystem_pthread.dylib       	0x00007fff7f8ee2eb _pthread_body + 126
3   libsystem_pthread.dylib       	0x00007fff7f8f1249 _pthread_start + 66
4   libsystem_pthread.dylib       	0x00007fff7f8ed40d thread_start + 13

Thread 6:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff7f83286a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff7f8f156e _pthread_cond_wait + 722
2   org.qt-project.QtCore         	0x0000000106e14e80 0x106dec000 + 167552
3   org.qt-project.QtCore         	0x0000000106e14bde 0x106dec000 + 166878
4   org.qt-project.QtCore         	0x0000000106e14b54 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 100
5   org.qt-project.QtCore         	0x0000000106e14abb QWaitCondition::wait(QMutex*, unsigned long) + 59
6   org.qt-project.QtCore         	0x0000000106e116a7 0x106dec000 + 153255
7   org.qt-project.QtCore         	0x0000000106e0c8f3 0x106dec000 + 133363
8   libsystem_pthread.dylib       	0x00007fff7f8ee2eb _pthread_body + 126
9   libsystem_pthread.dylib       	0x00007fff7f8f1249 _pthread_start + 66
10  libsystem_pthread.dylib       	0x00007fff7f8ed40d thread_start + 13

Thread 7:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff7f83286a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff7f8f156e _pthread_cond_wait + 722
2   org.qt-project.QtCore         	0x0000000106e14e80 0x106dec000 + 167552
3   org.qt-project.QtCore         	0x0000000106e14bde 0x106dec000 + 166878
4   org.qt-project.QtCore         	0x0000000106e14b54 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 100
5   org.qt-project.QtCore         	0x0000000106e14abb QWaitCondition::wait(QMutex*, unsigned long) + 59
6   org.qt-project.QtCore         	0x0000000106e116a7 0x106dec000 + 153255
7   org.qt-project.QtCore         	0x0000000106e0c8f3 0x106dec000 + 133363
8   libsystem_pthread.dylib       	0x00007fff7f8ee2eb _pthread_body + 126
9   libsystem_pthread.dylib       	0x00007fff7f8f1249 _pthread_start + 66
10  libsystem_pthread.dylib       	0x00007fff7f8ed40d thread_start + 13

Thread 8:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff7f82f22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff7f82f76c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff537a494e __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff537a3ebc __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff537a361e CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff50da24a2 _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff7f8ee2eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff7f8f1249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff7f8ed40d thread_start + 13

Thread 9:
0   libsystem_pthread.dylib       	0x00007fff7f8ed3f0 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0a1c5e0a7ddc0056  rbx: 0x00007fc7d6246750  rcx: 0x0000000000000102  rdx: 0x00000000facb1128
  rdi: 0x00007ffeea0b9318  rsi: 0x0000600002c224e0  rbp: 0x00007ffeea0b93a0  rsp: 0x00007ffeea0b9390
   r8: 0x00000000000001ff   r9: 0x00000000000007fb  r10: 0x00000000000024e0  r11: 0x0000000000000020
  r12: 0x00007ffeea0b93d0  r13: 0x000060000204cd20  r14: 0x0000000000000000  r15: 0x00007ffeea0b93c0
  rip: 0x0000000105b7903f  rfl: 0x0000000000010206  cr2: 0x0000000000000100
  
Logical CPU:     4
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x105b44000 -        0x105ecfff7 +org.keepassx.keepassxc (2.5.1 - ???) <8572EB38-168E-3BE8-9126-B996EA914324> /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
       0x105f42000 -        0x105f76ff3 +org.qt-project.QtSvg (5.13 - 5.13.1) <5D40E191-F74A-3BAE-87B2-06A72185DCBE> /Applications/KeePassXC.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
       0x105f9d000 -        0x105fa3ff3 +libqrencode.4.dylib (0) <FE171507-64C1-3743-A10E-C27D02CEC9DE> /Applications/KeePassXC.app/Contents/Frameworks/libqrencode.4.dylib
       0x105fb0000 -        0x105fb4fff +org.qt-project.QtConcurrent (5.13 - 5.13.1) <A9E9B78E-0111-3148-AF77-2377BBB7FDC7> /Applications/KeePassXC.app/Contents/Frameworks/QtConcurrent.framework/Versions/5/QtConcurrent
       0x105fbf000 -        0x105ffeffb +libsodium.23.dylib (0) <850C6E32-6365-3521-9E65-6A0CBDDF743C> /Applications/KeePassXC.app/Contents/Frameworks/libsodium.23.dylib
       0x106014000 -        0x106015ff3 +libyubikey.0.dylib (0) <473DB6D1-02CA-3BE0-A610-F265E3E2FEC6> /Applications/KeePassXC.app/Contents/Frameworks/libyubikey.0.dylib
       0x106023000 -        0x10602bff3 +libykpers-1.1.dylib (0) <1D1608D3-D6BD-31DD-8B61-B73945361366> /Applications/KeePassXC.app/Contents/Frameworks/libykpers-1.1.dylib
       0x106037000 -        0x10603bff7 +libargon2.1.dylib (0) <4D79ABEC-E884-3A9F-B4A7-6A10CCE99A68> /Applications/KeePassXC.app/Contents/Frameworks/libargon2.1.dylib
       0x106045000 -        0x106059ff7 +libgpg-error.0.dylib (0) <1466B6B0-0884-3EC2-A01C-6600AADE1C3E> /Applications/KeePassXC.app/Contents/Frameworks/libgpg-error.0.dylib
       0x10606b000 -        0x106177ff7 +org.qt-project.QtNetwork (5.13 - 5.13.1) <03F53563-F9A8-3EB5-99FA-64755F473698> /Applications/KeePassXC.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x1061c8000 -        0x10660aff3 +org.qt-project.QtWidgets (5.13 - 5.13.1) <8BDB9E5D-311D-3341-8878-B06BB576C0C3> /Applications/KeePassXC.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10677d000 -        0x10680ffff +libgcrypt.20.dylib (0) <86BE0D44-0020-332E-95BB-736112C84F25> /Applications/KeePassXC.app/Contents/Frameworks/libgcrypt.20.dylib
       0x10682c000 -        0x10684dff7 +libquazip.1.dylib (0) <54DDCC03-2CB7-32D5-A270-58F30D194F37> /Applications/KeePassXC.app/Contents/Frameworks/libquazip.1.dylib
       0x106860000 -        0x106868fff +org.qt-project.QtMacExtras (5.13 - 5.13.1) <FE65A669-35FB-3B67-9FC1-EB6070A42B86> /Applications/KeePassXC.app/Contents/Frameworks/QtMacExtras.framework/Versions/5/QtMacExtras
       0x106877000 -        0x106cd1fe7 +org.qt-project.QtGui (5.13 - 5.13.1) <FD39F713-89A4-3288-9ABF-F1F358A0DB1D> /Applications/KeePassXC.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x106dec000 -        0x10730ffff +org.qt-project.QtCore (5.13 - 5.13.1) <0B3FF8A2-5042-3335-A1D7-2F6D99B08266> /Applications/KeePassXC.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x1073e0000 -        0x1073e7fff +libjson-c.4.dylib (0) <E9FF068D-6093-3763-BDD6-D1C229556E65> /Applications/KeePassXC.app/Contents/Frameworks/libjson-c.4.dylib
       0x108ece000 -        0x10902dfff +libqcocoa.dylib (0) <345EC8D4-53B3-391C-BFD3-5ABE706107D8> /Applications/KeePassXC.app/Contents/PlugIns/platforms/libqcocoa.dylib
       0x109082000 -        0x1090e0ffb +org.qt-project.QtDBus (5.13 - 5.13.1) <6BBA8F9F-3C83-3AD0-B036-02681FDE2D56> /Applications/KeePassXC.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x1090ff000 -        0x109128ffb +org.qt-project.QtPrintSupport (5.13 - 5.13.1) <419EB6E8-E917-3D57-B067-143101AE58D5> /Applications/KeePassXC.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x10babf000 -        0x10bae3fff +libqmacstyle.dylib (0) <52899D99-03F5-35FB-B10B-4B5E3AADF667> /Applications/KeePassXC.app/Contents/PlugIns/styles/libqmacstyle.dylib
       0x10bb70000 -        0x10bb76fff +libqgif.dylib (0) <8AC7F696-4492-3A2B-8B3D-76B516BF238D> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqgif.dylib
       0x10bb7f000 -        0x10bb86ff3 +libqicns.dylib (0) <6EB0C505-9FD0-31EE-BC74-1537C537C189> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqicns.dylib
       0x10bb90000 -        0x10bb95ff7 +libqico.dylib (0) <1218A0B9-9A47-3333-9D6F-FD7486677249> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqico.dylib
       0x10bb9e000 -        0x10bc01ffb +libqjpeg.dylib (0) <8168004B-3010-397A-AFD3-6ABC6E6324B1> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqjpeg.dylib
       0x10bc0c000 -        0x10bc11ff3 +libqmacheif.dylib (0) <81BF0AC7-9CD4-32F2-97E0-337A313D9B02> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqmacheif.dylib
       0x10bc1b000 -        0x10bc20ff3 +libqmacjp2.dylib (0) <7D8B45BF-2F9B-3F56-B114-A1678E05AD4B> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqmacjp2.dylib
       0x10bc2a000 -        0x10bc2eff3 +libqsvg.dylib (0) <48FCF279-B4FA-37D4-83EF-1C873AB6EE1F> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqsvg.dylib
       0x10bc37000 -        0x10bc3bfff +libqtga.dylib (0) <11E10B94-6A0E-3BC3-AA84-94C6AD8A2D94> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqtga.dylib
       0x10bc44000 -        0x10bca7ffb +libqtiff.dylib (0) <29BE9DB5-7B85-36D2-9E52-A65FE2C5FD2F> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqtiff.dylib
       0x10bcb5000 -        0x10bcb8ff7 +libqwbmp.dylib (0) <6E228FFD-F9BE-3BBD-A1EC-40C824EC6B7C> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqwbmp.dylib
       0x10bcc1000 -        0x10bd59ff3 +libqwebp.dylib (0) <AF3A41CA-2E11-355A-87CF-F22E04D44C5B> /Applications/KeePassXC.app/Contents/PlugIns/imageformats/libqwebp.dylib
       0x10c1be000 -        0x10c22870f  dyld (655.1.1) <DFC3C4AF-6F97-3B34-B18D-7DCB23F2A83A> /usr/lib/dyld
       0x10c289000 -        0x10c611fff +libkeepassx-autotype-cocoa.so (0) <64FC49D1-A03C-30D9-B7D8-C6A89C38EDF7> /Applications/KeePassXC.app/Contents/PlugIns/libkeepassx-autotype-cocoa.so
       0x10c726000 -        0x10c729047  libobjc-trampolines.dylib (756.2) <5795A048-3940-3801-90CE-33D1B1AF81F4> /usr/lib/libobjc-trampolines.dylib
       0x10cc50000 -        0x10cc66fff  com.apple.security.csparser (3.0 - 58286.270.3.0.1) <215095F3-2B6A-3F8D-A8AB-5E29C3A861F6> /System/Library/Frameworks/Security.framework/PlugIns/csparser.bundle/Contents/MacOS/csparser
       0x10cfe2000 -        0x10cfeffff  com.apple.iokit.IOHIDLib (2.0.0 - 2.0.0) <08CC730F-CFD2-328D-B338-43D4E801ED6B> /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib
    0x7fff47eca000 -     0x7fff48223fff  com.apple.RawCamera.bundle (8.15.0 - 1031.4.4) <AB6E8A8F-0BFE-37EE-A135-44ABA4FCB559> /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera
    0x7fff4cd0d000 -     0x7fff4d03ffff  com.apple.driver.AppleIntelKBLGraphicsMTLDriver (12.10.12 - 12.1.0) <F44A2087-008C-30CB-9E33-A94DFF197E68> /System/Library/Extensions/AppleIntelKBLGraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsMTLDriver
    0x7fff4f79d000 -     0x7fff4f7a1fff  com.apple.agl (3.3.2 - AGL-3.3.2) <03320890-819C-38A2-AD45-78F1473E693F> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff4fb4c000 -     0x7fff4fb4cfff  com.apple.Accelerate (1.11 - Accelerate 1.11) <762942CB-CFC9-3A0C-9645-A56523A06426> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff4fb4d000 -     0x7fff4fb63ff7  libCGInterfaces.dylib (506.22) <1B6C92D9-F4B8-37BA-9635-94C4A56098CE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff4fb64000 -     0x7fff501fdfef  com.apple.vImage (8.1 - ???) <53FA3611-894E-3158-A654-FBD2F70998FE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff501fe000 -     0x7fff50477ff3  libBLAS.dylib (1243.200.4) <417CA0FC-B6CB-3FB3-ACBC-8914E3F62D20> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff50478000 -     0x7fff504eaffb  libBNNS.dylib (38.250.1) <538D12A2-9B9D-3E22-9896-F90F6E69C06E> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff504eb000 -     0x7fff50894ff3  libLAPACK.dylib (1243.200.4) <92175DF4-863A-3780-909A-A3E5C410F2E9> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff50895000 -     0x7fff508aafeb  libLinearAlgebra.dylib (1243.200.4) <CB671EE6-DEA1-391C-9B2B-AA09A46B4D7A> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff508ab000 -     0x7fff508b0ff3  libQuadrature.dylib (3.200.2) <1BAE7E22-2862-379F-B334-A3756067730F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff508b1000 -     0x7fff5092dff3  libSparse.dylib (79.200.5) <E78B33D3-672A-3C53-B512-D3DDB2E9AC8D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff5092e000 -     0x7fff50941fe3  libSparseBLAS.dylib (1243.200.4) <E9243341-DB77-37C1-97C5-3DFA00DD70FA> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff50942000 -     0x7fff50b29ff7  libvDSP.dylib (671.250.4) <7B110627-A9C1-3FB7-A077-0C7741BA25D8> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff50b2a000 -     0x7fff50bddff7  libvMisc.dylib (671.250.4) <D5BA4812-BFFC-3CD0-B382-905CD8555DA6> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff50bde000 -     0x7fff50bdefff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <74288115-EF61-30B6-843F-0593B31D4929> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff50d80000 -     0x7fff51b35ffb  com.apple.AppKit (6.9 - 1671.60.109) <EFB74848-E23F-3FC3-B167-BA1F960996CC> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff51b87000 -     0x7fff51b87fff  com.apple.ApplicationServices (50.1 - 50.1) <84097DEB-E2FC-3901-8DD7-A670EA2274E0> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff51b88000 -     0x7fff51bf3fff  com.apple.ApplicationServices.ATS (377 - 453.11.2.2) <A258DA73-114B-3102-A056-4AAAD3CEB9DD> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff51c8c000 -     0x7fff51da3fff  libFontParser.dylib (228.6.2.3) <3602D55B-3B9E-3B3A-A814-08C1244A8AE4> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
    0x7fff51da4000 -     0x7fff51de6fff  libFontRegistry.dylib (228.12.2.3) <2A56347B-2809-3407-A8B4-2AB88E484062> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff51e40000 -     0x7fff51e72fff  libTrueTypeScaler.dylib (228.6.2.3) <7E4C5D9C-51AF-3EC1-8FA5-11CD4BEE477A> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib
    0x7fff51ed7000 -     0x7fff51edbff3  com.apple.ColorSyncLegacy (4.13.0 - 1) <C0D9E23C-ABA0-39DE-A4EB-5A41C5499056> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff51f76000 -     0x7fff51fc8ff7  com.apple.HIServices (1.22 - 628) <2BE461FF-80B9-30D3-A574-AED5724B1C1B> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff51fc9000 -     0x7fff51fd8fff  com.apple.LangAnalysis (1.7.0 - 1.7.0) <F5617A2A-FEA6-3832-B5BA-C2111B98786F> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff51fd9000 -     0x7fff52022ff7  com.apple.print.framework.PrintCore (14.2 - 503.8) <57C2FE32-0E74-3079-B626-C2D52F2D2717> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff52023000 -     0x7fff5205cff7  com.apple.QD (3.12 - 407.2) <28C7D39F-59C9-3314-BECC-67045487229C> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff5205d000 -     0x7fff52069fff  com.apple.speech.synthesis.framework (8.1.3 - 8.1.3) <5E7B9BD4-122B-3012-A044-3259C97E7509> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff5206a000 -     0x7fff522e1ff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <04F482F1-E1C1-3955-8A6C-8AA152AA06F3> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff522e3000 -     0x7fff522e3fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <ABC54269-002D-310D-9654-46CF960F863E> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff5263c000 -     0x7fff529ddfff  com.apple.CFNetwork (978.0.7 - 978.0.7) <B2133D0D-1399-3F17-80F0-313E3A241C89> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff529f2000 -     0x7fff529f2fff  com.apple.Carbon (158 - 158) <56AD06AA-7BB4-3F0B-AEF7-9768D0BC1C98> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff529f3000 -     0x7fff529f6ffb  com.apple.CommonPanels (1.2.6 - 98) <1CD6D56D-8EC7-3528-8CBC-FC69533519B5> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff529f7000 -     0x7fff52ceefff  com.apple.HIToolbox (2.1.1 - 918.7) <13F69D4C-D19F-3E09-9231-1978D783A556> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff52cef000 -     0x7fff52cf2ff3  com.apple.help (1.3.8 - 66) <A08517EB-8958-36C9-AEE0-1A8FEEACBE3F> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff52cf3000 -     0x7fff52cf8ff7  com.apple.ImageCapture (9.0 - 1534.2) <DB063E87-ED8F-3E4E-A7E2-A6B45FA73EF7> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff52cf9000 -     0x7fff52d8eff3  com.apple.ink.framework (10.9 - 225) <7C7E9483-2E91-3DD3-B1E0-C238F42CA0DD> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff52d8f000 -     0x7fff52da7ff7  com.apple.openscripting (1.7 - 179.1) <9B8C1ECC-5864-3E21-9149-863E884EA25C> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff52dc7000 -     0x7fff52dc8ff7  com.apple.print.framework.Print (14.2 - 267.4) <A7A9D2A0-D4E0-35EF-A0F7-50521F707C33> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff52dc9000 -     0x7fff52dcbff7  com.apple.securityhi (9.0 - 55006) <05717F77-7A7B-37E6-AB3E-03F063E9095B> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff52dcc000 -     0x7fff52dd2ff7  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <3CC050FB-EBCB-3087-8EA5-F378C8F99217> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff52f02000 -     0x7fff53051ff7  com.apple.ColorSync (4.13.0 - 3345.6) <31648BB6-7239-3D0E-81B1-BCF51FEF557F> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff531dd000 -     0x7fff53263fff  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <1E8E64E6-0E58-375A-97F7-07CB4EE181AC> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff532c7000 -     0x7fff532f1ffb  com.apple.CoreBluetooth (1.0 - 1) <A73F1709-DD18-3052-9F22-C0015278834B> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff532f2000 -     0x7fff53677fef  com.apple.CoreData (120 - 866.6) <132CB39B-8D58-30FA-B8AD-49BFFF34B293> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff53678000 -     0x7fff53768ff7  com.apple.CoreDisplay (101.3 - 110.18) <0EB2A997-FCAD-3D17-B140-9829961E5327> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff53769000 -     0x7fff53baeff7  com.apple.CoreFoundation (6.9 - 1575.22) <51040EEE-7C5D-3433-A271-86B47B0562BF> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff53bb0000 -     0x7fff5423ffff  com.apple.CoreGraphics (2.0 - 1265.9) <BC95B558-EF77-3A57-A0BC-11606C778991> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff54241000 -     0x7fff54561fff  com.apple.CoreImage (14.4.0 - 750.0.140) <11026E39-D2FF-3CF6-8ACE-7BA293F9853E> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff5485e000 -     0x7fff54962fff  com.apple.CoreMedia (1.0 - 2290.13) <A739B93D-23C2-3A34-8D61-6AC924B9634F> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff549bf000 -     0x7fff549bffff  com.apple.CoreServices (946 - 946) <2EB6117A-6389-311B-95A0-7DE32C5FCFE2> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff549c0000 -     0x7fff54a3cff7  com.apple.AE (773 - 773) <55AE7C9E-27C3-30E9-A047-3B92A6FD53B4> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff54a3d000 -     0x7fff54d14fff  com.apple.CoreServices.CarbonCore (1178.33 - 1178.33) <CB87F0C7-2CD6-3983-8E32-B6A2EC925352> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff54d15000 -     0x7fff54d5dff7  com.apple.DictionaryServices (1.2 - 284.16.4) <746EB200-DC51-30AE-9CBC-608A7B4CC8DA> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff54d5e000 -     0x7fff54d66ffb  com.apple.CoreServices.FSEvents (1239.200.12 - 1239.200.12) <8406D379-8D33-3611-861B-7ABD26DB50D2> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff54d67000 -     0x7fff54f18ff7  com.apple.LaunchServices (946 - 946) <A0C91634-9410-38E8-BC11-7A5A369E6BA5> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff54f19000 -     0x7fff54fb7ff7  com.apple.Metadata (10.7.0 - 1191.57) <BFFAED00-2560-318A-BB8F-4E7E5123EC61> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff54fb8000 -     0x7fff55002ff7  com.apple.CoreServices.OSServices (946 - 946) <20C4EEF8-D5AC-39A0-9B4A-78F88E3EFBCC> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff55003000 -     0x7fff5506aff7  com.apple.SearchKit (1.4.0 - 1.4.0) <DA08AA6F-A6F1-36C0-87F4-E26294E51A3A> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff5506b000 -     0x7fff5508cff3  com.apple.coreservices.SharedFileList (71.28 - 71.28) <487A8464-729E-305A-B5D1-E3FE8EB9CFC5> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff55397000 -     0x7fff554f9ff3  com.apple.CoreText (352.0 - 584.26.3.2) <59919B0C-CBD5-3877-8D6F-D6048F1E5F42> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff554fa000 -     0x7fff5553aff3  com.apple.CoreVideo (1.8 - 281.4) <10CF8E52-07E3-382B-8091-2CEEEFFA69B4> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff5553b000 -     0x7fff555cafff  com.apple.framework.CoreWLAN (13.0 - 1375.2) <BF4B29F7-FBC8-3299-98E8-C3F8C04B7C92> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff555cb000 -     0x7fff555fbff7  com.apple.CryptoTokenKit (1.0 - 1) <0D12EBBB-1B4C-3015-AE0F-30FA2E1B139D> /System/Library/Frameworks/CryptoTokenKit.framework/Versions/A/CryptoTokenKit
    0x7fff55821000 -     0x7fff55826ffb  com.apple.DiskArbitration (2.7 - 2.7) <F481F2C0-884E-3265-8111-ABBEC93F0920> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff559ec000 -     0x7fff55d99ffb  com.apple.Foundation (6.9 - 1575.22) <CDB9A3E1-41A5-36EC-A24E-94FBCC752D6A> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff55e08000 -     0x7fff55e37ffb  com.apple.GSS (4.0 - 2.0) <E2B90D08-3857-3155-9FCC-07D778988EC9> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff55f37000 -     0x7fff56041fff  com.apple.Bluetooth (6.0.14 - 6.0.14d3) <C2D1A774-2390-363D-8215-BF51FFCB6CCA> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff560a4000 -     0x7fff56133fff  com.apple.framework.IOKit (2.0.2 - 1483.260.4) <8A90F547-86EF-3DFB-92FE-0E2C0376DD84> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff56135000 -     0x7fff56144ffb  com.apple.IOSurface (255.6.1 - 255.6.1) <85F85EBB-EA59-3A8B-B3EB-7C20F3CC77AE> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff56198000 -     0x7fff56323fef  com.apple.ImageIO.framework (3.3.0 - 1850.2) <75E46A31-D87D-35CE-86A4-96A50971FDB2> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff56324000 -     0x7fff56328ffb  libGIF.dylib (1850.2) <4774EBDF-583B-3DDD-A0E1-9F427CB6A074> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff56329000 -     0x7fff56405fef  libJP2.dylib (1850.2) <697BB77F-A682-339F-8659-35432962432D> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff56406000 -     0x7fff5642bfeb  libJPEG.dylib (1850.2) <171A8AC4-AADA-376F-9F2C-B9C978DB1007> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff566ee000 -     0x7fff56714feb  libPng.dylib (1850.2) <FBCEE909-F573-3AD6-A45F-AF32612BF8A2> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff56715000 -     0x7fff56717ffb  libRadiance.dylib (1850.2) <56907025-D5CE-3A9E-ACCB-A376C2599853> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff56718000 -     0x7fff56765fe7  libTIFF.dylib (1850.2) <F59557C9-C761-3E6F-85D1-0FBFFD53ED5C> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff578d8000 -     0x7fff578f1fff  com.apple.Kerberos (3.0 - 1) <DB1E0679-37E1-3B93-9789-32F63D660C3B> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff57974000 -     0x7fff57992fff  com.apple.CoreAuthentication.SharedUtils (1.0 - 425.270.3) <DDEAC106-D051-385A-9F74-CD9BE230D336> /System/Library/Frameworks/LocalAuthentication.framework/Support/SharedUtils.framework/Versions/A/SharedUtils
    0x7fff57993000 -     0x7fff579a7fff  com.apple.LocalAuthentication (1.0 - 425.270.3) <23CD2E0C-5A3A-348D-986F-58F302E4FEA4> /System/Library/Frameworks/LocalAuthentication.framework/Versions/A/LocalAuthentication
    0x7fff57bab000 -     0x7fff57bb5fff  com.apple.MediaAccessibility (1.0 - 114.4) <76C449C5-DB45-3D7F-BFAD-3DACEF15DA21> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fff57c65000 -     0x7fff5830bfff  com.apple.MediaToolbox (1.0 - 2290.13) <71BB5D76-34CA-3A30-AECF-24BE29FCC275> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
    0x7fff5830d000 -     0x7fff583b5ff7  com.apple.Metal (162.2 - 162.2) <FFF7DFF3-7C4E-32C6-A0B5-C356079D3B7C> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff583d1000 -     0x7fff583f0ff7  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <44CE8362-E972-3697-AD6F-15BC863BAEB8> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff583f1000 -     0x7fff5846dfe7  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <EE8440DA-66DF-3923-ABBC-E0543211C069> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff5846e000 -     0x7fff58495fff  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <E64450DF-2B96-331E-B7F4-666E00571C70> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff58496000 -     0x7fff585c1ff7  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <F2CF26B6-73F1-3644-8FE9-CDB9B2C4501F> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff585c2000 -     0x7fff585dcfff  com.apple.MetalPerformanceShaders.MPSRayIntersector (1.0 - 1) <B33A35C3-0393-366B-ACFB-F4BB6A5F7B4A> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector
    0x7fff585dd000 -     0x7fff585deff7  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <69F14BCF-C5C5-3BF8-9C31-8F87D2D6130A> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff593d5000 -     0x7fff593e1ff7  com.apple.NetFS (6.0 - 4.0) <E917806F-0607-3292-B2D6-A15404D61B99> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff5be7f000 -     0x7fff5bed6ff7  com.apple.opencl (2.15.3 - 2.15.3) <056BAD8A-23BC-3F74-9E2C-3AC81E7DEA5A> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff5bed7000 -     0x7fff5bef2ff7  com.apple.CFOpenDirectory (10.14 - 207.200.4) <F03D84EB-49B2-3A00-9127-B9A269824026> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff5bef3000 -     0x7fff5befeffb  com.apple.OpenDirectory (10.14 - 207.200.4) <A8020CEE-5B78-3581-A735-EA2833683F31> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff5c84e000 -     0x7fff5c850fff  libCVMSPluginSupport.dylib (17.7.3) <8E051EA7-55B6-3DF1-9821-72C391DE953B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff5c851000 -     0x7fff5c856ff3  libCoreFSCache.dylib (166.2) <222C2A4F-7E32-30F6-8459-2FAB98073A3D> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff5c857000 -     0x7fff5c85bfff  libCoreVMClient.dylib (166.2) <6789ECD4-91DD-32EF-A1FD-F27D2344CD8B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff5c85c000 -     0x7fff5c864ff7  libGFXShared.dylib (17.7.3) <8C50BF27-B525-3B23-B86C-F444ADF97851> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff5c865000 -     0x7fff5c870fff  libGL.dylib (17.7.3) <2AC457EA-1BD3-3C8E-AFAB-7EA6234EB749> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff5c871000 -     0x7fff5c8abfef  libGLImage.dylib (17.7.3) <AA027AFA-C115-3861-89B2-0AE946838952> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff5ca1f000 -     0x7fff5ca5dfff  libGLU.dylib (17.7.3) <CB3B0579-D9A2-3CA5-8942-0C8344FAD054> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff5d3fa000 -     0x7fff5d409ffb  com.apple.opengl (17.7.3 - 17.7.3) <94B5CF34-5BD6-3652-9A8C-E9C56E0A9FB4> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff5e20c000 -     0x7fff5e463ff7  com.apple.QuartzCore (1.11 - 701.14) <33E846BE-1794-3186-9BF2-6ADF62C782A3> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff5ec99000 -     0x7fff5ef99fff  com.apple.security (7.0 - 58286.270.3.0.1) <DF7677A7-9765-3B6A-9D1C-3589145E4B65> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff5ef9a000 -     0x7fff5f026fff  com.apple.securityfoundation (6.0 - 55185.260.1) <1EE899E6-222A-3526-B505-B0D0B6FA042A> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff5f027000 -     0x7fff5f057ffb  com.apple.securityinterface (10.0 - 55109.200.8) <02B83641-2D21-3DB8-AAB8-6F8AAD0F6264> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff5f058000 -     0x7fff5f05cfff  com.apple.xpc.ServiceManagement (1.0 - 1) <FCF7BABA-DDDD-3770-8DAC-7069850203C2> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff5f3f5000 -     0x7fff5f462fff  com.apple.SystemConfiguration (1.17 - 1.17) <30C8327F-3EFF-3520-9C50-016F8B6B954F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff5f6c1000 -     0x7fff5fa22fff  com.apple.VideoToolbox (1.0 - 2290.13) <7FCB2FC0-EFB8-37C2-B0D3-60AE9FDFE230> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff6269e000 -     0x7fff62743feb  com.apple.APFS (1.0 - 1) <2D22485D-552D-3CB6-9FE1-38547597918F> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff63158000 -     0x7fff63159ff7  com.apple.AggregateDictionary (1.0 - 1) <A6AF8AC4-1F25-37C4-9157-A02E9C200926> /System/Library/PrivateFrameworks/AggregateDictionary.framework/Versions/A/AggregateDictionary
    0x7fff6375a000 -     0x7fff63786ff7  com.apple.framework.Apple80211 (13.0 - 1380.2) <16F093EF-370B-3B90-8DB4-E94624431D15> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff638ae000 -     0x7fff638bdfc7  com.apple.AppleFSCompression (96.200.3 - 1.0) <3CF60CE8-976E-3CB8-959D-DD0948C1C2DE> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff639b9000 -     0x7fff639c4fff  com.apple.AppleIDAuthSupport (1.0 - 1) <2E9D1398-DBE6-328B-ADDA-20FA5FAD7405> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff63a05000 -     0x7fff63a4eff3  com.apple.AppleJPEG (1.0 - 1) <4C1F426B-7D77-3980-9633-7DBD8C666B9A> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff63ca2000 -     0x7fff63cc4fff  com.apple.applesauce (1.0 - ???) <F49107C7-3C51-3024-8EF1-C57643BE4F3B> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff63d88000 -     0x7fff63dd8ff7  com.apple.AppleVAFramework (5.1.4 - 5.1.4) <3399D678-8741-3B70-B8D0-7C63C8ACF7DF> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fff63e23000 -     0x7fff63e37ffb  com.apple.AssertionServices (1.0 - 1) <456E507A-4561-3628-9FBE-173ACE7429D8> /System/Library/PrivateFrameworks/AssertionServices.framework/Versions/A/AssertionServices
    0x7fff64206000 -     0x7fff642f2ff7  com.apple.AuthKit (1.0 - 1) <2765ABE9-54F2-3E45-8A93-1261E251B90D> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff644b4000 -     0x7fff644bcfff  com.apple.coreservices.BackgroundTaskManagement (1.0 - 57.1) <2A396FC0-7B79-3088-9A82-FB93C1181A57> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff644bd000 -     0x7fff64552fff  com.apple.backup.framework (1.10.5 - ???) <4EEC51E2-AE4C-340A-B686-901810152C12> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fff64553000 -     0x7fff645c0ff3  com.apple.BaseBoard (360.28 - 360.28) <68FA8044-F3CD-3BC6-9DAB-27DACF52BFC0> /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard
    0x7fff6622b000 -     0x7fff66234ffb  com.apple.CommonAuth (4.0 - 2.0) <93335CB6-ABEB-3EC7-A040-8A667F40D5F3> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff666cd000 -     0x7fff66ab0fef  com.apple.CoreAUC (274.0.0 - 274.0.0) <C71F1581-E73B-3DA0-958B-E912C3FB3F23> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
    0x7fff66ab1000 -     0x7fff66adfff7  com.apple.CoreAVCHD (6.0.0 - 6000.4.1) <A04A99B8-DAC5-36FC-BAC7-7431600C1F89> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
    0x7fff66f0d000 -     0x7fff66f1eff7  com.apple.CoreEmoji (1.0 - 69.19.9) <228457B3-E191-356E-9A5B-3C0438D05FBA> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff674c8000 -     0x7fff6752eff7  com.apple.CoreNLP (1.0 - 130.15.22) <27877820-17D0-3B02-8557-4014E876CCC7> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
    0x7fff677db000 -     0x7fff677e3ff7  com.apple.CorePhoneNumbers (1.0 - 1) <11F97C7E-C183-305F-8E6C-9B374F50E26B> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff6795f000 -     0x7fff67990ff3  com.apple.CoreServicesInternal (358 - 358) <DD6EF60D-048F-3186-83DA-EB191EDF48AE> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff67d57000 -     0x7fff67ddbfff  com.apple.CoreSymbolication (10.2 - 64490.25.1) <28B2FF2D-3FDE-3A20-B343-341E5BD4E22F> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff67e6b000 -     0x7fff67f96ff7  com.apple.coreui (2.1 - 499.10) <A80F4B09-F940-346F-A9DF-4EFADD9220A8> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff67f97000 -     0x7fff68137fff  com.apple.CoreUtils (5.9 - 590.16) <66CC50F7-766D-33E2-A388-4DE22840ADFB> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff6818b000 -     0x7fff681eeff7  com.apple.framework.CoreWiFi (13.0 - 1375.2) <CA4B835A-27AC-3FAB-9F44-E48548EA2442> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fff681ef000 -     0x7fff68200ff7  com.apple.CrashReporterSupport (10.13 - 938.26) <E93D84A6-891D-38EE-BB4F-E9CD681189B7> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff68290000 -     0x7fff6829ffff  com.apple.framework.DFRFoundation (1.0 - 211.1) <E3F02F2A-2059-39CC-85DA-969676EB88EB> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff682a0000 -     0x7fff682a4ff7  com.apple.DSExternalDisplay (3.1 - 380) <787B9748-B120-3453-B8FE-61D9E363A9E0> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff68325000 -     0x7fff6839affb  com.apple.datadetectorscore (7.0 - 590.27) <06FB1A07-7AE6-3ADD-8E7E-41955FAB38E8> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff683e6000 -     0x7fff68423ff7  com.apple.DebugSymbols (190 - 190) <6F4FAACA-E06B-38AD-A0C2-14EA5408A231> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff68424000 -     0x7fff6855fff7  com.apple.desktopservices (1.13.5 - ???) <265C0E94-B8BF-3F58-8D68-EA001EEA0B15> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff694a6000 -     0x7fff698c1fff  com.apple.vision.FaceCore (3.3.4 - 3.3.4) <A576E2DA-BF6F-3B18-8FEB-324E5C5FA9BD> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff6d175000 -     0x7fff6d176fff  libmetal_timestamp.dylib (902.3.2) <05389463-AF2E-33E2-A14F-1416E4A30835> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/3902/Libraries/libmetal_timestamp.dylib
    0x7fff6e816000 -     0x7fff6e81bfff  com.apple.GPUWrangler (3.50.12 - 3.50.12) <6C820ED9-F306-3978-B5B8-432AD97BBDAF> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff6f627000 -     0x7fff6f636fff  com.apple.GraphVisualizer (1.0 - 5) <48D020B7-5938-3FAE-B468-E291AEE2C06F> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff6f79c000 -     0x7fff6f810ffb  com.apple.Heimdal (4.0 - 2.0) <D97FCF19-EAD6-3E2F-BE88-F817E45CAE96> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff70b16000 -     0x7fff70b1dffb  com.apple.IOAccelerator (404.14 - 404.14) <11A50171-C8AE-3BBC-9FB9-2A3313FFBD31> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff70b21000 -     0x7fff70b39fff  com.apple.IOPresentment (1.0 - 42.6) <6DFD9A6E-BF95-3A27-89E7-ACAA9E30D90A> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff70ee1000 -     0x7fff70f0eff7  com.apple.IconServices (379 - 379) <7BAD562D-4FA3-3E11-863C-1EEBE2406D2C> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff711a1000 -     0x7fff711b3ff3  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <30CFE05C-4108-3879-AFAA-5BB02CBE190B> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff711ce000 -     0x7fff712a9ff7  com.apple.LanguageModeling (1.0 - 159.15.15) <3DE3CE61-542B-37B7-883E-4B9717CAC65F> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff712aa000 -     0x7fff712e6ff7  com.apple.Lexicon-framework (1.0 - 33.15.10) <4B5E843E-2809-3E70-9560-9254E2656419> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff712ed000 -     0x7fff712f2fff  com.apple.LinguisticData (1.0 - 238.25) <F529B961-098C-3E4C-A3E9-9DA9BFA1B3F0> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff71b10000 -     0x7fff71b13fff  com.apple.Mangrove (1.0 - 25) <537A5B2E-4C30-3CFD-8BDC-79F9A04AC327> /System/Library/PrivateFrameworks/Mangrove.framework/Versions/A/Mangrove
    0x7fff71fe7000 -     0x7fff7200fff7  com.apple.spotlight.metadata.utilities (1.0 - 1191.57) <38BB1FB7-3336-384C-B71F-4D0D402EB606> /System/Library/PrivateFrameworks/MetadataUtilities.framework/Versions/A/MetadataUtilities
    0x7fff72010000 -     0x7fff7209dff7  com.apple.gpusw.MetalTools (1.0 - 1) <CBE2176A-8048-3A9C-AFE4-13973D44C704> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff720b4000 -     0x7fff720cdffb  com.apple.MobileAssets (1.0 - 437.250.3) <8BE5B3A0-8F3A-3FAE-9AFF-32836300183C> /System/Library/PrivateFrameworks/MobileAsset.framework/Versions/A/MobileAsset
    0x7fff72248000 -     0x7fff72263ffb  com.apple.MobileKeyBag (2.0 - 1.0) <C7C5DD21-66DE-31D1-92D9-BBEEAAE156FB> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff722ec000 -     0x7fff72316ffb  com.apple.MultitouchSupport.framework (2450.1 - 2450.1) <42A23EC9-64A7-31C7-BF33-DF4412ED8A3F> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff72552000 -     0x7fff7255cfff  com.apple.NetAuth (6.2 - 6.2) <0D01BBE5-0269-310D-B148-D19DAE143DEB> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff72dbd000 -     0x7fff72e0eff3  com.apple.OTSVG (1.0 - ???) <5BF1A9EB-2694-3267-9514-A4EB3BEF4081> /System/Library/PrivateFrameworks/OTSVG.framework/Versions/A/OTSVG
    0x7fff73fa6000 -     0x7fff73fb5ff7  com.apple.PerformanceAnalysis (1.218.2 - 218.2) <65F3DB3E-6D4E-33A0-B510-EF768D323DAB> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff75998000 -     0x7fff759bbffb  com.apple.pluginkit.framework (1.0 - 1) <910C3AFE-7C46-3C34-B000-4ED92336B9FD> /System/Library/PrivateFrameworks/PlugInKit.framework/Versions/A/PlugInKit
    0x7fff75e47000 -     0x7fff75e65ff7  com.apple.ProtocolBuffer (1 - 263.2) <907D6C95-D050-31DE-99CA-16A5135BC6F9> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff75ffd000 -     0x7fff7604dfff  com.apple.ROCKit (27.6 - 27.6) <756C2253-E8B1-3C48-9945-DE8D6AD24DE2> /System/Library/PrivateFrameworks/ROCKit.framework/Versions/A/ROCKit
    0x7fff761a7000 -     0x7fff761c9fff  com.apple.RemoteViewServices (2.0 - 128) <8FB0E4EB-DCBB-32E6-94C6-AA9BA9EE4CAC> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff779d3000 -     0x7fff77af1fff  com.apple.Sharing (1288.62 - 1288.62) <48B1F247-7910-3C16-814C-B99DE231F7F0> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff78905000 -     0x7fff78bb4fff  com.apple.SkyLight (1.600.0 - 340.54) <90EB1C2E-B264-3EC4-AF7F-CDE7E7585746> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff79357000 -     0x7fff79363fff  com.apple.SpeechRecognitionCore (5.0.21 - 5.0.21) <7A6A67DB-C813-328E-AAFB-D267A5B50B3D> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff79a02000 -     0x7fff79a3eff3  com.apple.StreamingZip (1.0 - 1) <046FAD5C-E0C5-3013-B1FE-24C018A0DDCF> /System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/StreamingZip
    0x7fff79ab4000 -     0x7fff79b3ffc7  com.apple.Symbolication (10.2 - 64490.38.1) <9FDCC98D-5B32-35AD-A9BF-94DF2B78507F> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fff7a027000 -     0x7fff7a033ffb  com.apple.TCC (1.0 - 1) <73CF6FA9-44CE-30C9-887F-235940976585> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff7a299000 -     0x7fff7a361ff3  com.apple.TextureIO (3.8.4 - 3.8.1) <7CEAC05A-D283-3D5A-B1E3-C849285FA0BF> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff7a41e000 -     0x7fff7a5d5ffb  com.apple.UIFoundation (1.0 - 551.2) <917480B5-14BE-30E0-ABE6-9702336CC35A> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff7b251000 -     0x7fff7b32afff  com.apple.ViewBridge (401.1 - 401.1) <18144EC1-5DEF-369C-8EBA-2826E7142784> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff7bb02000 -     0x7fff7bb05fff  com.apple.dt.XCTTargetBootstrap (1.0 - 14490.66) <7AE3457F-AF40-3508-93FB-1D9E31EB1C9D> /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/Versions/A/XCTTargetBootstrap
    0x7fff7bf06000 -     0x7fff7bf08ffb  com.apple.loginsupport (1.0 - 1) <3F8D6334-BCD6-36C1-BA20-CC8503A84375> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff7bf09000 -     0x7fff7bf1efff  com.apple.login (3.0 - 3.0) <E168F05D-A5DF-3848-8686-DF5015EA4BA4> /System/Library/PrivateFrameworks/login.framework/Versions/A/login
    0x7fff7c1d2000 -     0x7fff7c206fff  libCRFSuite.dylib (41.15.4) <406DAC06-0C77-3F90-878B-4D38F11F0256> /usr/lib/libCRFSuite.dylib
    0x7fff7c209000 -     0x7fff7c213ff7  libChineseTokenizer.dylib (28.15.3) <9B7F6109-3A5D-3641-9A7E-31D2239D73EE> /usr/lib/libChineseTokenizer.dylib
    0x7fff7c2a1000 -     0x7fff7c2a2ffb  libDiagnosticMessagesClient.dylib (107) <A14D0819-0970-34CD-8680-80E4D7FE8C2C> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff7c2d9000 -     0x7fff7c530ff3  libFosl_dynamic.dylib (18.3.4) <1B5DD4E2-8AE0-315E-829E-D5BFCD264EA8> /usr/lib/libFosl_dynamic.dylib
    0x7fff7c581000 -     0x7fff7c5a0fff  libMobileGestalt.dylib (645.270.1) <99A06C8A-97D6-383D-862C-F453BABB48A4> /usr/lib/libMobileGestalt.dylib
    0x7fff7c5a1000 -     0x7fff7c5a1fff  libOpenScriptingUtil.dylib (179.1) <4D603146-EDA5-3A74-9FF8-4F75D8BB9BC6> /usr/lib/libOpenScriptingUtil.dylib
    0x7fff7c6e1000 -     0x7fff7c6e2ffb  libSystem.B.dylib (1252.250.1) <B1006948-7AD0-3CA9-81E0-833F4DD6BFB4> /usr/lib/libSystem.B.dylib
    0x7fff7c75e000 -     0x7fff7c75ffff  libThaiTokenizer.dylib (2.15.1) <ADB37DC3-7D9B-3E73-A72A-BCC3433C937A> /usr/lib/libThaiTokenizer.dylib
    0x7fff7c771000 -     0x7fff7c787ffb  libapple_nghttp2.dylib (1.24.1) <6F04250A-6686-3FDC-9A8D-290C64B06502> /usr/lib/libapple_nghttp2.dylib
    0x7fff7c788000 -     0x7fff7c7b1ffb  libarchive.2.dylib (54.250.1) <47289946-8504-3966-9127-6CE39993DC2C> /usr/lib/libarchive.2.dylib
    0x7fff7c7b2000 -     0x7fff7c831fff  libate.dylib (1.13.8) <92B44EDB-369D-3EE8-AEC5-61F8B9313DBF> /usr/lib/libate.dylib
    0x7fff7c835000 -     0x7fff7c835ff3  libauto.dylib (187) <3E3780E1-96F3-3A22-91C5-92F9A5805518> /usr/lib/libauto.dylib
    0x7fff7c905000 -     0x7fff7c915ffb  libbsm.0.dylib (39.200.18) <CF381E0B-025B-364F-A83D-2527E03F1AA3> /usr/lib/libbsm.0.dylib
    0x7fff7c916000 -     0x7fff7c923fff  libbz2.1.0.dylib (38.200.3) <272953A1-8D36-329B-BDDB-E887B347710F> /usr/lib/libbz2.1.0.dylib
    0x7fff7c924000 -     0x7fff7c977ff7  libc++.1.dylib (400.9.4) <9A60A190-6C34-339F-BB3D-AACE942009A4> /usr/lib/libc++.1.dylib
    0x7fff7c978000 -     0x7fff7c98dff7  libc++abi.dylib (400.17) <38C09CED-9090-3719-90F3-04A2749F5428> /usr/lib/libc++abi.dylib
    0x7fff7c98e000 -     0x7fff7c98eff3  libcharset.1.dylib (51.200.6) <2A27E064-314C-359C-93FC-8A9B06206174> /usr/lib/libcharset.1.dylib
    0x7fff7c98f000 -     0x7fff7c99fffb  libcmph.dylib (6.15.1) <9C52B2FE-179F-32AC-B87E-2AFC49ABF817> /usr/lib/libcmph.dylib
    0x7fff7c9a0000 -     0x7fff7c9b8ffb  libcompression.dylib (52.250.2) <7F4BB18C-1FB4-3825-8D8B-6E6B168774C6> /usr/lib/libcompression.dylib
    0x7fff7cc2d000 -     0x7fff7cc43fff  libcoretls.dylib (155.220.1) <4C64BE3E-41E3-3020-8BB7-07E90C0C861C> /usr/lib/libcoretls.dylib
    0x7fff7cc44000 -     0x7fff7cc45ff3  libcoretls_cfhelpers.dylib (155.220.1) <0959B3E9-6643-3589-8BB3-21D52CDF0EF1> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff7d0f1000 -     0x7fff7d147ff3  libcups.2.dylib (462.12) <095619DC-9233-3937-9E50-5F10D917A40D> /usr/lib/libcups.2.dylib
    0x7fff7d27b000 -     0x7fff7d27bfff  libenergytrace.dylib (17.200.1) <80BB567A-FD18-3497-BF97-353F57D98CDD> /usr/lib/libenergytrace.dylib
    0x7fff7d2ad000 -     0x7fff7d2b2ff7  libgermantok.dylib (17.15.2) <E5F0F794-FF27-3D64-AE52-C78C6A84DD67> /usr/lib/libgermantok.dylib
    0x7fff7d2b3000 -     0x7fff7d2b8ff7  libheimdal-asn1.dylib (520.270.1) <73F60D6F-76F8-35EF-9C86-9A81225EE4BE> /usr/lib/libheimdal-asn1.dylib
    0x7fff7d2e3000 -     0x7fff7d3d3fff  libiconv.2.dylib (51.200.6) <2047C9B7-3F74-3A95-810D-2ED8F0475A99> /usr/lib/libiconv.2.dylib
    0x7fff7d3d4000 -     0x7fff7d635ffb  libicucore.A.dylib (62141.0.1) <A0D63918-76E9-3C1B-B255-46F4C1DA7FE8> /usr/lib/libicucore.A.dylib
    0x7fff7d682000 -     0x7fff7d683fff  liblangid.dylib (128.15.1) <22D05C4F-769B-3075-ABCF-44A0EBACE028> /usr/lib/liblangid.dylib
    0x7fff7d684000 -     0x7fff7d69cff3  liblzma.5.dylib (10.200.3) <E1F4FD60-1CE4-37B9-AD95-29D348AF1AC0> /usr/lib/liblzma.5.dylib
    0x7fff7d6b4000 -     0x7fff7d758ff7  libmecab.1.0.0.dylib (779.24.1) <A8D0379B-85FA-3B3D-89ED-5CF2C3826AB2> /usr/lib/libmecab.1.0.0.dylib
    0x7fff7d759000 -     0x7fff7d95dfff  libmecabra.dylib (779.24.1) <D71F71E0-30E2-3DB3-B636-7DE13D51FB4B> /usr/lib/libmecabra.dylib
    0x7fff7db35000 -     0x7fff7de86ff7  libnetwork.dylib (1229.250.15) <72C7E9E3-B2BE-3300-BE1B-64606222022C> /usr/lib/libnetwork.dylib
    0x7fff7df18000 -     0x7fff7e69dfdf  libobjc.A.dylib (756.2) <7C312627-43CB-3234-9324-4DEA92D59F50> /usr/lib/libobjc.A.dylib
    0x7fff7e6af000 -     0x7fff7e6b3ffb  libpam.2.dylib (22.200.1) <586CF87F-349C-393D-AEEB-FB75F94A5EB7> /usr/lib/libpam.2.dylib
    0x7fff7e6b6000 -     0x7fff7e6ebfff  libpcap.A.dylib (79.250.1) <C0893641-7DFF-3A33-BDAE-190FF54837E8> /usr/lib/libpcap.A.dylib
    0x7fff7e804000 -     0x7fff7e81cffb  libresolv.9.dylib (65.200.2) <893142A5-F153-3437-A22D-407EE542B5C5> /usr/lib/libresolv.9.dylib
    0x7fff7e86d000 -     0x7fff7e86eff7  libspindump.dylib (267.3) <A584E403-8C95-3841-9C16-E22664A5A63F> /usr/lib/libspindump.dylib
    0x7fff7e86f000 -     0x7fff7ea4cfff  libsqlite3.dylib (274.26) <6404BA3B-BCA4-301F-B2FE-8776105A2AA3> /usr/lib/libsqlite3.dylib
    0x7fff7ec65000 -     0x7fff7ec68ff7  libutil.dylib (51.200.4) <CE9B18C9-66ED-32D4-9D29-01F8FCB467B0> /usr/lib/libutil.dylib
    0x7fff7ec69000 -     0x7fff7ec76fff  libxar.1.dylib (417.1) <39CCF46B-C81A-34B1-92A1-58C4E5DA846E> /usr/lib/libxar.1.dylib
    0x7fff7ec7b000 -     0x7fff7ed5dff3  libxml2.2.dylib (32.10) <AA4E1B1F-0FDE-3274-9FA5-75446298D1AC> /usr/lib/libxml2.2.dylib
    0x7fff7ed5e000 -     0x7fff7ed86ff3  libxslt.1.dylib (16.5) <E330D3A2-E32B-378A-973E-A8D245C0F712> /usr/lib/libxslt.1.dylib
    0x7fff7ed87000 -     0x7fff7ed99ff7  libz.1.dylib (70.200.4) <B048FC1F-058F-3A08-A1FE-81D5308CB3E6> /usr/lib/libz.1.dylib
    0x7fff7f57d000 -     0x7fff7f581ff3  libcache.dylib (81) <1987D1E1-DB11-3291-B12A-EBD55848E02D> /usr/lib/system/libcache.dylib
    0x7fff7f582000 -     0x7fff7f58cff3  libcommonCrypto.dylib (60118.250.2) <1765BB6E-6784-3653-B16B-CB839721DC9A> /usr/lib/system/libcommonCrypto.dylib
    0x7fff7f58d000 -     0x7fff7f594ff7  libcompiler_rt.dylib (63.4) <5212BA7B-B7EA-37B4-AF6E-AC4F507EDFB8> /usr/lib/system/libcompiler_rt.dylib
    0x7fff7f595000 -     0x7fff7f59eff7  libcopyfile.dylib (146.250.1) <98CD00CD-9B91-3B5C-A9DB-842638050FA8> /usr/lib/system/libcopyfile.dylib
    0x7fff7f59f000 -     0x7fff7f623fc3  libcorecrypto.dylib (602.260.2) <01464D24-570C-3B83-9D18-467769E0FCDD> /usr/lib/system/libcorecrypto.dylib
    0x7fff7f6aa000 -     0x7fff7f6e3ff7  libdispatch.dylib (1008.270.1) <97273678-E94C-3C8C-89F6-2E2020F4B43B> /usr/lib/system/libdispatch.dylib
    0x7fff7f6e4000 -     0x7fff7f710ff7  libdyld.dylib (655.1.1) <002418CC-AD11-3D10-865B-015591D24E6C> /usr/lib/system/libdyld.dylib
    0x7fff7f711000 -     0x7fff7f711ffb  libkeymgr.dylib (30) <0D0F9CA2-8D5A-3273-8723-59987B5827F2> /usr/lib/system/libkeymgr.dylib
    0x7fff7f712000 -     0x7fff7f71eff3  libkxld.dylib (4903.271.2) <FBF128C8-D3F0-36B6-983A-A63B8A3E0E52> /usr/lib/system/libkxld.dylib
    0x7fff7f71f000 -     0x7fff7f71fff7  liblaunch.dylib (1336.261.2) <2B07E27E-D404-3E98-9D28-BCA641E5C479> /usr/lib/system/liblaunch.dylib
    0x7fff7f720000 -     0x7fff7f725fff  libmacho.dylib (927.0.3) <A377D608-77AB-3F6E-90F0-B4F251A5C12F> /usr/lib/system/libmacho.dylib
    0x7fff7f726000 -     0x7fff7f728ffb  libquarantine.dylib (86.220.1) <6D0BC770-7348-3608-9254-F7FFBD347634> /usr/lib/system/libquarantine.dylib
    0x7fff7f729000 -     0x7fff7f72aff7  libremovefile.dylib (45.200.2) <9FBEB2FF-EEBE-31BC-BCFC-C71F8D0E99B6> /usr/lib/system/libremovefile.dylib
    0x7fff7f72b000 -     0x7fff7f742ff3  libsystem_asl.dylib (356.200.4) <A62A7249-38B8-33FA-9875-F1852590796C> /usr/lib/system/libsystem_asl.dylib
    0x7fff7f743000 -     0x7fff7f743ff7  libsystem_blocks.dylib (73) <A453E8EE-860D-3CED-B5DC-BE54E9DB4348> /usr/lib/system/libsystem_blocks.dylib
    0x7fff7f744000 -     0x7fff7f7cbfff  libsystem_c.dylib (1272.250.1) <7EDACF78-2FA3-35B8-B051-D70475A35117> /usr/lib/system/libsystem_c.dylib
    0x7fff7f7cc000 -     0x7fff7f7cfffb  libsystem_configuration.dylib (963.270.3) <2B4A836D-68A4-33E6-8D48-CD4486B03387> /usr/lib/system/libsystem_configuration.dylib
    0x7fff7f7d0000 -     0x7fff7f7d3ff7  libsystem_coreservices.dylib (66) <719F75A4-74C5-3BA6-A09E-0C5A3E5889D7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff7f7d4000 -     0x7fff7f7dafff  libsystem_darwin.dylib (1272.250.1) <EC9B39A5-9592-3577-8997-7DC721D20D8C> /usr/lib/system/libsystem_darwin.dylib
    0x7fff7f7db000 -     0x7fff7f7e1ff7  libsystem_dnssd.dylib (878.270.2) <E9A5ACCF-E35F-3909-AF0A-2A37CD217276> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff7f7e2000 -     0x7fff7f82dffb  libsystem_info.dylib (517.200.9) <D09D5AE0-2FDC-3A6D-93EC-729F931B1457> /usr/lib/system/libsystem_info.dylib
    0x7fff7f82e000 -     0x7fff7f856ff7  libsystem_kernel.dylib (4903.271.2) <EA204E3C-870B-30DD-B4AF-D1BB66420D14> /usr/lib/system/libsystem_kernel.dylib
    0x7fff7f857000 -     0x7fff7f8a2ff7  libsystem_m.dylib (3158.200.7) <F19B6DB7-014F-3820-831F-389CCDA06EF6> /usr/lib/system/libsystem_m.dylib
    0x7fff7f8a3000 -     0x7fff7f8cdfff  libsystem_malloc.dylib (166.270.1) <011F3AD0-8E6A-3A89-AE64-6E5F6840F30A> /usr/lib/system/libsystem_malloc.dylib
    0x7fff7f8ce000 -     0x7fff7f8d8ff7  libsystem_networkextension.dylib (767.250.2) <FF06F13A-AEFE-3A27-A073-910EF78AEA36> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff7f8d9000 -     0x7fff7f8e0fff  libsystem_notify.dylib (172.200.21) <145B5CFC-CF73-33CE-BD3D-E8DDE268FFDE> /usr/lib/system/libsystem_notify.dylib
    0x7fff7f8e1000 -     0x7fff7f8eafef  libsystem_platform.dylib (177.270.1) <9D1FE5E4-EB7D-3B3F-A8D1-A96D9CF1348C> /usr/lib/system/libsystem_platform.dylib
    0x7fff7f8eb000 -     0x7fff7f8f5ff7  libsystem_pthread.dylib (330.250.2) <2D5C08FF-484F-3D59-9132-CE1DCB3F76D7> /usr/lib/system/libsystem_pthread.dylib
    0x7fff7f8f6000 -     0x7fff7f8f9ff7  libsystem_sandbox.dylib (851.270.1) <9494594B-5199-3186-82AB-5FF8BED6EE16> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff7f8fa000 -     0x7fff7f8fcff3  libsystem_secinit.dylib (30.260.2) <EF1EA47B-7B22-35E8-BD9B-F7003DCB96AE> /usr/lib/system/libsystem_secinit.dylib
    0x7fff7f8fd000 -     0x7fff7f904ff3  libsystem_symptoms.dylib (820.267.1) <03F1C2DD-0F5A-3D9D-88F6-B26C0F94EB52> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff7f905000 -     0x7fff7f91afff  libsystem_trace.dylib (906.260.1) <FC761C3B-5434-3A52-912D-F1B15FAA8EB2> /usr/lib/system/libsystem_trace.dylib
    0x7fff7f91c000 -     0x7fff7f921ffb  libunwind.dylib (35.4) <24A97A67-F017-3CFC-B0D0-6BD0224B1336> /usr/lib/system/libunwind.dylib
    0x7fff7f922000 -     0x7fff7f951fff  libxpc.dylib (1336.261.2) <7DEE2300-6D8E-3C00-9C63-E3E80D56B0C4> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 13062
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=424.4M resident=0K(0%) swapped_out_or_unallocated=424.4M(100%)
Writable regions: Total=690.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=690.1M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG backing stores                 1664K        5 
CG image                           236K       14 
CoreAnimation                       92K        8 
CoreGraphics                         8K        1 
CoreImage                           36K        5 
CoreUI image data                 1152K       15 
CoreUI image file                  416K        6 
Foundation                           4K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           417.4M       68 
MALLOC guard page                   32K        6 
MALLOC_NANO (reserved)           256.0M        1         reserved VM address space (unallocated)
Memory Tag 242                      12K        1 
Memory Tag 251                      12K        1 
STACK GUARD                       56.0M       10 
Stack                             12.6M       10 
VM_ALLOCATE                        216K       19 
__DATA                            26.8M      290 
__FONT_DATA                          4K        1 
__LINKEDIT                       227.8M       38 
__TEXT                           196.6M      289 
__UNICODE                          564K        1 
mapped file                       59.7M       28 
shared memory                      664K       19 
===========                     =======  ======= 
TOTAL                              1.2G      841 
TOTAL, minus reserved VM space     1.0G      841 

Model: MacBookPro15,2, BootROM 220.270.99.0.0 (iBridge: 16.16.6571.0.0,0), 4 processors, Intel Core i5, 2,4 GHz, 16 GB, SMC 
Graphics: kHW_IntelIrisGraphics655Item, Intel Iris Plus Graphics 655, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, Samsung, K4EBE304EC-EGCG
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, Samsung, K4EBE304EC-EGCG
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Mar 28 2019 19:17:52 version 9.137.9.0.32.6.34 FWID 01-36f56c94
Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: BillBoard Device
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: USB Keyboard
USB Device: Jabra EVOLVE LINK MS
USB Device: USB3.0 Hub
USB Device: USB3.0 Card Reader
USB Device: USB3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: iBridge Bus
USB Device: iBridge DFR brightness
USB Device: iBridge Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: iBridge ALS
USB Device: iBridge FaceTime HD Camera (Built-in)
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2
```
</details>

### LINKED ISSUE #3933: KeepassXC (Linux) crashing on Apply/OK/Cancel
## Expected Behavior
KeePassXC should save the data (or not in the case of cancel), and return to the database tree with all the entries

## Current Behavior
When editing an entry, upon hitting any of the below buttons, KeepassXC will crash without saving. This happens approximately every other time trying. In other words, I can open the database and save one entry, but the next one will crash it.
_Apply, Cancel, OK_
Edit: Cancel does appear to be working, so long as I "Close without saving"
Edit 2: Cancel works when I don't make a change. However, when I make a change using Apply, then hit Cancel to exit, it will crash. (In this situation, the change will be saved to the database with the Apply action)

## Possible Solution
None

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open database
2. Edit an entry
3. Save entry
4. Open another entry
5. Save entry

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
This makes using KeePassXC very frustrating. Windows does not appear to have this issue (and Linux hasn't in the past either)
I have tried disabling the browser extension, restoring settings to default, moving all entries to a new database, using the development version, and the current app package.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18 (Went from Ubuntu GNOME to KDE Kubuntu)
CPU architecture: x86_64
Kernel: linux 5.3.0-23-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

Libraries:
- LIBS

### LINKED ISSUE #3941: Merge popup randomly appears when kdbx file is on network share
I have, ever since i use KPXC, one of my databases on a network share in windows, assigned to a drive letter. Since v2.5.0 (Also on current 2.5.1) every now and then the "Merge" popup snaps into my view, doesn't matter which programm i have currently opened.

So it happens sometime that the popup distract my work in certain programs. I always press "Merge" or "Abort", it doesn't matter. The file hasn't changed, neither on KPXC side nor on the share.

The only thing i can imagine is that, for a short period, the network drive seems inactive/not available and as soon as it comes available again KPXC will detect this and pops up the merge window for whatever reason.

I cannot give a reproduction example here, as it doesn't happen when i try to reproduce it. It happen round about 5-10 times during 8 hours of activity.

This happen only on my files that are on a windows shared drive, it does not happen on local disk files.

Here is the codeline (i guess) for the popup that appears: https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/DatabaseWidget.cpp#L1449

Again, nothing has changed on network or local side in the KPXC database when it appear, but the Asterisk beside the database name in the tab indicates a change.

Let me know if i can provide any more information.

	KeePassXC - Version 2.5.1
	Revision: 0fd8836

	Qt 5.13.1
	Diagnosemodus ist deaktiviert.

	Betriebssystem: Windows 10 (10.0)
	CPU-Architektur: x86_64
	Kernel: winnt 10.0.17134

	Aktivierte Erweiterungen:
	- Auto-Type
	- Browser-Integration
	- SSH-Agent
	- KeeShare (bestätigtes und unbestätigtes Teilen)
	- YubiKey

	Kryptographische Bibliotheken:
	 libgcrypt 1.8.5

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Mark the database as clean after fully completing the file save operation INSTEAD of when merely writing the database to a file.

* Stop the modified timer when marking the database as clean, this prevents latent erroneous modified signals from being emitted.

* Do not restart the modified timer after a new change is detected while it is still running.

* Fix #3933 and  fix #3857. Interaction with entries and groups is disabled while the database is being reloaded or saved to prevent changes from occurring. Prevent the database from being reloading if an entry or group is currently being edited.

* Fix #3941 - Only notify components when the database file actually changes (determined by checksum). This prevents spurious merge requests when the file is merely touched by another service (e.g., DropBox).

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Currently testing on all platforms to confirm the above bugs are fixed.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

File: src/gui/DatabaseWidget.cpp [hunk 1]
```diff
@@ -1441,6 +1449,11 @@ void DatabaseWidget::reloadDatabaseFile()
         }
     }
 
+    // Lock out interactions
+    m_entryView->setDisabled(true);
+    m_groupView->setDisabled(true);
+    QApplication::processEvents();
```
Comment (phoerious) [inline src/gui/DatabaseWidget.cpp]: The clean way would be to actually to save in the background and queue any changes done in the meantime.

Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: That's a 2.6.0 change

**Comment by Bill-cpp** [comment]
When I upgraded KeePassXC from 2.4.3 to 2.5.1, I started encountering a strange problem upon saving my database into DropBox from Linux Mint: Although the database would be saved, I'd also get a pop-up window titled "File has changed", with message "The database file has changed. Do you want to load the changes?" I could type "yes" or "no". Either way, nothing remarkable happened. (This problem did not occur all the time, but nearly all the time.) Seeing this bug report, I figured my problem would be solved by this fix, so I recently upgraded to 2.5.3. Made no difference! I still get this gratuitous pop-up window. Is this part of the same problem, or what? I'm currently running Mint 19.3.

**Comment by droidmonkey** [comment]
Please create a new issue with your exact environment and replication steps
