### PR TITLE
Code quality updates for 2.4.0

### LINKED ISSUE #2684: [PRE-RELEASE] KeePassXC fails to resolve the entry reference if the referenced entry is in a different group
## Expected Behavior
Username and password should be inferred correctly, no matter in which group the entry currently belongs to.

## Current Behavior
KeePassXC fails to resolve the entry reference if the referenced entry is in a different group. Inferred username and password are empty. It's also not possible to copy neither the username nor the password. It works fine for cloned entries within the same group.
image
image
image
image

## Steps to Reproduce
1. Create a new group
2. Clone an entry with "Replace username and password with references" option
3. Move the cloned entry to a different group

## Context
Started to happen in the version 2.4.0-beta1. Works fine in 2.3.x

## Debug Info
KeePassXC - Version 2.4.0-beta1
Build Type: PreRelease
Revision: 42cfe01

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

### LINKED ISSUE #2697: [PRE-RELEASE] Shutdown keepassxc-proxy when receiving close message
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
This is for the Windows platform only. When receiving a WM_CLOSE or WM_QUERYENDSESSION / WM_ENDSESSION message the proxy application should exit.

https://docs.microsoft.com/en-us/windows/desktop/winmsg/wm-close

https://docs.microsoft.com/en-us/windows/desktop/shutdown/wm-queryendsession

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The application remains running.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Trying to gracefully close the proxy application from the MSI installer.

### LINKED ISSUE #2699: [PRE-RELEASE] Shutdown application when receiving close message
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When WM_CLOSE or WM_QUERYENDSESSION is issued to KeePassXC, the application should actually close instead of hiding to the system tray (if the setting is enabled).

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
If the system tray is enabled these messages cause the application to minimize to the tray.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Affects Windows only.

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
General quality of code improvements for 2.4.0. Also addressing a couple of issues:

* Gracefully close KeePassXC and KeePassXC-Browser when receiving end session notice on Windows
* Fix #2684 - entry references search the whole group tree instead of its current group on down
* Fix #2697 and fix #2699

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Used rmlogotest from the Windows 10 Developer Kit which simulates an actual shutdown/logoff sequence.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.

### CODE REVIEW

File: src/proxy/keepassxc-proxy.cpp [hunk 1]
```diff
@@ -55,13 +55,28 @@ void catchUnixSignals(std::initializer_list<int> quitSignals)
         sigaction(sig, &sa, nullptr);
     }
 }
+#else
+#include <windows.h>
```
Comment (phoerious) [inline src/proxy/keepassxc-proxy.cpp]: This should be at the beginning of the file.

File: src/proxy/keepassxc-proxy.cpp [hunk 2]
```diff
@@ -55,13 +55,28 @@ void catchUnixSignals(std::initializer_list<int> quitSignals)
...
+BOOL WINAPI ConsoleHandler(DWORD dwType)
+{
+    switch(dwType) {
```
Comment (phoerious) [inline src/proxy/keepassxc-proxy.cpp]: Space after switch

File: src/proxy/keepassxc-proxy.cpp [hunk 3]
```diff
@@ -55,13 +55,28 @@ void catchUnixSignals(std::initializer_list<int> quitSignals)
...
 #endif
 
 int main(int argc, char* argv[])
 {
     QCoreApplication a(argc, argv);
-#if defined(Q_OS_UNIX) || defined(Q_OS_LINUX)
+#ifndef Q_OS_WIN
     catchUnixSignals({SIGQUIT, SIGINT, SIGTERM, SIGHUP});
+#else
+    SetConsoleCtrlHandler(static_cast<PHANDLER_ROUTINE>(ConsoleHandler),TRUE);
```
Comment (varjolintu) [inline src/proxy/keepassxc-proxy.cpp]: Space after comma.

Nice and simple solution for the event handler. Good job.

File: src/proxy/keepassxc-proxy.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/proxy/keepassxc-proxy.cpp]: Technically it is. The top #ifdef block includes headers. I'll add a blank space after it though since that is against convention.
