### PR TITLE
Translate Cipher and KDF strings

### LINKED ISSUE #8952: Database encryption settings not translated
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

KeePassXC displays some translated strings in English.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Change KeePassXC's language to Polish (100% on Transifex).
2. Check out these strings:

Argon2d (KDBX 4 – recommended)

Restore Entry(s)

Twofish 256-bit

AES 256-bit

ChaCha20 256-bit

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The strings are translated on Transifex and should be in KeePassXC as well.

Argon2d (KDBX 4 – zalecany)

Przywróć wpisy

Twofish:  256-bitowy

AES 256-bitowy

ChaCha20 256-bitowy

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Strings mentioned above are hard-coded in English.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 22H2

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fix #8952 - move translations for Cipher and KDF strings into evaluated code instead of globally defined code. The strings were being baked prior to the language being set resulting in only english being displayed.

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested by setting alternate language and ensuring the translations showed.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/format/KeePass2.cpp [hunk 1]
```diff
@@ -133,3 +129,29 @@ KeePass2::ProtectedStreamAlgo KeePass2::idToProtectedStreamAlgo(quint32 id)
         return KeePass2::ProtectedStreamAlgo::InvalidProtectedStreamAlgo;
     }
 }
+
+QString KeePass2::cipherToString(QUuid cipherUuid)
+{
+    if (cipherUuid == KeePass2::CIPHER_AES256) {
```
Comment (dmaslenko) [inline src/format/KeePass2.cpp:135]: What about `CIPHER_AES128` which is defined on line 25? I know it was not mentioned in the original `CIPHERS` list but if it is still used it will be translated into the `Invalid Cipher`.

File: src/format/KeePass2.cpp [hunk 2]
```diff
@@ -133,3 +129,29 @@ KeePass2::ProtectedStreamAlgo KeePass2::idToProtectedStreamAlgo(quint32 id)
...
+        return QObject::tr("AES 256-bit");
+    } else if (cipherUuid == KeePass2::CIPHER_TWOFISH) {
+        return QObject::tr("Twofish 256-bit");
+    } else if (cipherUuid == KeePass2::CIPHER_CHACHA20) {
+        return QObject::tr("ChaCha20 256-bit");
+    }
+    return QObject::tr("Invalid Cipher");
```
Comment (dmaslenko) [inline src/format/KeePass2.cpp:142]: Optional: I would say `Unsupported Cipher`.

File: src/format/KeePass2.cpp [hunk 3]
```diff
@@ -133,3 +129,29 @@ KeePass2::ProtectedStreamAlgo KeePass2::idToProtectedStreamAlgo(quint32 id)
         return KeePass2::ProtectedStreamAlgo::InvalidProtectedStreamAlgo;
     }
 }
+
+QString KeePass2::cipherToString(QUuid cipherUuid)
```
Comment (dmaslenko) [inline src/format/KeePass2.cpp:133]: Does it make sense to cover these 2 new methods by unit tests?
BTW, I am a fan of unit testing and ready to help with this on the project. I saw 64% of total coverage, it can be improved.

File: src/format/KeePass2.cpp [hunk 4]
```diff
@@ -133,3 +129,29 @@ KeePass2::ProtectedStreamAlgo KeePass2::idToProtectedStreamAlgo(quint32 id)
...
+        return QObject::tr("AES 256-bit");
+    } else if (cipherUuid == KeePass2::CIPHER_TWOFISH) {
+        return QObject::tr("Twofish 256-bit");
+    } else if (cipherUuid == KeePass2::CIPHER_CHACHA20) {
+        return QObject::tr("ChaCha20 256-bit");
+    }
+    return QObject::tr("Invalid Cipher");
+}
+
+QString KeePass2::kdfToString(QUuid kdfUuid)
```
Comment (dmaslenko) [inline src/format/KeePass2.cpp:145]: Optional: we can rename the input argument from `kdfUuid` to just `uuid` because it is obvious for `kdfToString` method.

File: src/format/KeePass2.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/format/KeePass2.cpp:135]: This cipher is only used with KeePass1 databases and I think the AES KDF, the string isn't exposed anywhere.

File: src/format/KeePass2.cpp (hunk 3 above)
Comment (droidmonkey) [reply src/format/KeePass2.cpp:133]: Testing string output is not really a useful use of time to be honest. We have 100% coverage of critical code.

File: src/format/KeePass2.cpp (hunk 4 above)
Comment (droidmonkey) [reply src/format/KeePass2.cpp:145]: No we use uuids elsewhere

File: src/format/KeePass2.cpp (hunk 1 above)
Comment (dmaslenko) [reply src/format/KeePass2.cpp:135]: Got it.

File: src/format/KeePass2.cpp (hunk 3 above)
Comment (dmaslenko) [reply src/format/KeePass2.cpp:133]: I agree, sometimes very trivial logic can be tested indirectly.

File: src/format/KeePass2.cpp (hunk 4 above)
Comment (dmaslenko) [reply src/format/KeePass2.cpp:145]: I mean in scope of this method it is obvious the expected given uuid is kdf one and no other uuids in the method we have. But if you have a global `uuid` it may conflict, sure thing.
Anyway, it was just a cosmetic suggestion.

**Comment by droidmonkey** [comment]
@phoerious also this one
