### PR TITLE
Passkeys: Fix incorrect username fill

### LINKED ISSUE #10840: Username filling wrong value when passkey existed
## Overview

Take [NVIDIA](https://nvidia.com/en-us/account) and [Facebook](https://facebook.com/login) for example.

When creating an account with email, the email is treated as login username.
Therefore, when user is logging in their account, they are required to provide the email and password.

When user enable passkey, they are still required to give their email and password and passkey is used as multi-factor security.

## Expected Behavior

Username is filled into login form when passkey is enabled for the selected entry.

image

## Actual Behavior

The `KPEX_PASSKEY_USERNAME` attribute is filled into login form when passkey is enabled for the selected entry.

image

Update: When I capturing the screenshot, I found that as long as there is an attribute called `KPEX_PASSKEY_USERNAME`, the username will be overwritten.

## Possible Solution

I'm not sure where to fix this.
Maybe here https://github.com/keepassxreboot/keepassxc/blob/5de669eb7b3c2a56ee865960bb4b8002090ca1f5/src/browser/BrowserService.cpp#L1148-L1161
?

## Steps to Reproduce

1. Create an account on [NVIDIA](https://nvidia.com/en-us/account), [Facebook](https://facebook.com/login), or any other service which login username is different from passkey user name. (Update: Can be simplified as creating any account.)
2. Create an entry in KeepassXC.
3. Setup passkey with KeePassXC-Browser. (Update: Can be simplified as creating `KPEX_PASSKEY_USERNAME` attribute.)
4. Logout and login again.
5. Now KeePassXC-Browser auto fills `KPEX_PASSKEY_USERNAME` instead of username.

## Debug info

KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.0.5
Operating system: Win
Browser: Firefox

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Fix filling wrong username with a normal entry that has a passkey.
There are two possible situations with entries that has a passkey:
1) Entry only has a passkey. Username is set to `KPEX_PASSKEY_USERNAME`.
2) Entry has normal credentials and `KPEX_PASSKEY_USERNAME`.

In the second situation the normal username needs to be returned if entry has a passkey but `KPEX_PASSKEY_USERNAME` differs. The `KPEX_PASSKEY_USERNAME` attribute will be still used during authentication normally. The username only matters how the credential is displayed in the extension side, and during the Access Confirm Dialog.

Fixes #10840.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by droidmonkey — APPROVED** [review]

**Comment by varjolintu** [comment]
Some changes needed for this.

EDIT: Should be fixed. Please verify. There was a bug with entries without any passkeys. The username could be returned as empty.

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -1149,9 +1149,14 @@ QJsonObject BrowserService::prepareEntry(const Entry* entry)
...
     QJsonObject res;
 #ifdef WITH_XC_BROWSER_PASSKEYS
-    // Use Passkey's username instead if found
-    res["login"] = entry->hasPasskey() ? passkeyUtils()->getUsernameFromEntry(entry)
-                                       : entry->resolveMultiplePlaceholders(entry->username());
+    // If entry has a passkey, but the passkey username differs from the normal username, return the normal username
+    auto username = entry->resolveMultiplePlaceholders(entry->username());
+    auto passkeyUsername = passkeyUtils()->getUsernameFromEntry(entry);
+    if (entry->hasPasskey()) {
+        res["login"] = username != passkeyUsername ? username : passkeyUsername;
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp]: This ternary operator doesn't make sense. If they are equal than returning either username or passkeyUsername would result in the same outcome. If they are unequal then you return the username. So just return the username.

Looking at the code change in general, you always just return the username.

I think you need to write a test case against this behavior to validate the desired outcome.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/browser/BrowserService.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/browser/BrowserService.cpp]: In other words, you need to better define when you actually want to return the passkeyUsername and use that as your branching condition.

Comment (varjolintu) [reply src/browser/BrowserService.cpp]: Hmm. I guess you are right. It should be enough to just always return the username. `KPEX_PASSKEY_USERNAME` is used for the authentication anyway, and the original reason we added the username in a passkey entry in a first place was just for filtering.

**Review by droidmonkey — APPROVED** [review]
