### PR TITLE
Correct issues with system tray icon

### LINKED ISSUE #5780: Show a System Tray Tooltip when hovered
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC on Windows 10 does not show any System Tray Tooltips. It stands out slightly awkwardly from the other system tray icons because all other systray icons show a basic tooltip.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Hover mouse over KeePassXC icon in system tray

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should show a tooltip for the icon in system tray on Windows.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC is not showing any system tray tooltip.

## Context (Screenshot Example)
[NOTE]: # ( Give us any additional information you may have. )
KeePassXC-systray-tooltips

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 (Version 20H2) Build 19042.662
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Thank you for your time. Cheers!

### LINKED ISSUE #5943: [2.6.3] Try Icon sometimes not appear if KeePassXC automatically started with system.
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use the Option "Automatically startup with system"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A nice try icon

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

No try icon
## Context
[NOTE]: # ( Give us any additional information you may have. )
If I quite the app and start it manually, the tray icon appears.

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: EndeavourOS
CPU-Architektur: x86_64
Kernel: linux 5.10.7-zen1-1-zen

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- libgcrypt 1.8.7
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux / EndeavourOS
Desktop Env: XFCE 4.16
Windowing System: X11

### PR DESCRIPTION
**Pull request by droidmonkey**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
* Close #5780 - Show window title as system tray icon tooltip
* Fix #5943 - Try to show system tray icon up to 5 times, waiting 5 seconds between attempts, if the system tray is not available. This works around observed startup issues on Linux.
* Change function of "isTrayIconEnabled()" to return true if the tray icon is created and visible. This may correct some long standing bugs with the window hiding forever unexpectedly.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows and XFCE

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/MainWindow.cpp [hunk 1]
```diff
@@ -1281,40 +1279,46 @@ void MainWindow::updateTrayIcon()
...
-        } else if (m_ui->tabWidget->hasLockableDatabases()) {
+        if (m_ui->tabWidget->hasLockableDatabases()) {
             m_trayIcon->setIcon(resources()->trayIconUnlocked());
         } else {
             m_trayIcon->setIcon(resources()->trayIconLocked());
         }
-    } else {
-        QApplication::setQuitOnLastWindowClosed(true);
 
+        m_trayIcon->setToolTip(windowTitle().replace("[*]", isWindowModified() ? "*" : ""));
```
Comment (phoerious) [inline src/gui/MainWindow.cpp:1302]: Can we somehow construct the tooltip from the original raw title + an asterisk? Updating the existing title will replace any asterisks appearing in the database name. We should never read anything back from the UI.

File: src/gui/MainWindow.cpp [hunk 2]
```diff
@@ -1281,40 +1279,46 @@ void MainWindow::updateTrayIcon()
...
+        m_trayIcon->show();
+
+        if (!isTrayIconEnabled() || !QSystemTrayIcon::isSystemTrayAvailable()) {
+            // Try to show tray icon after 5 seconds, try 5 times
+            // This can happen if KeePassXC starts before the system tray is available
```
Comment (phoerious) [inline src/gui/MainWindow.cpp:1307]: I wonder if there are DBus signals we can listen for.

File: src/gui/MainWindow.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/gui/MainWindow.cpp:1302]: That is the explicit placeholder for the modified indicator. It's a stupid qt convention and they keep the placeholder intact for some reason.

File: src/gui/MainWindow.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/gui/MainWindow.cpp:1307]: That is Qt's job which it is failing at doing (that's actually their bug as reported). This works and isn't too bothersome.

File: src/gui/MainWindow.cpp (hunk 1 above)
Comment (phoerious) [reply src/gui/MainWindow.cpp:1302]: Hmm. I really don't like it, but so be it.

File: src/gui/MainWindow.cpp (hunk 2 above)
Comment (phoerious) [reply src/gui/MainWindow.cpp:1307]: It's definitely Qt's job to do it right, but we might find a more elegant workaround in the future perhaps.

**Review by phoerious — APPROVED** [review]

File: src/gui/MainWindow.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/gui/MainWindow.cpp:1307]: Is agree to that
