### PR TITLE
Fixes #199 : Disable buttonGenerate when no classes.

### LINKED ISSUE #199: Crash clicking generate with all character ranges disabled
## Expected Behavior
Don't crash

## Current Behavior
Crashes

## Possible Solution
Disable generate when no ranges enabled

## Steps to Reproduce (for bugs)
1. Tap the die
2. turn off A-Z, a-z, 0-9, /*_...
3. Tap generate

## Your Environment
* KeePassXC 2.1
* macOS

### PR DESCRIPTION
**Pull request by louib**
## Description

The presence of at least 1 character class was not verified before generating a new password, resulting in the following line https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/PasswordGenerator.cpp#L52 crashing the program.

Note that the validity was checked when calling `PasswordGeneratorWidget::regeneratePassword`, but was not checked when calling `PasswordGeneratorWidget::generatePassword`. The `Generate` button is now disabled if the generator is in an invalid state.

Even though now we should never call `PasswordGeneratorWidget::generatePassword` with an invalid password generator, I added the `isValid()` verification for robustness and for consistency with `regeneratePassword`.

## Motivation and Context
Fixes #199

## How Has This Been Tested?
Unit tests + manual tests (on MacOs).

## Screenshots (if appropriate):
Generate button is enabled when at least 1 character class : 
screen shot 2017-01-26 at 6 32 31 pm

Generate button is disabled when no class selected :
screen shot 2017-01-26 at 6 32 52 pm

At some point it could be useful to add an error message stating why the `Generate` button is disabled.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

File: src/gui/PasswordGeneratorWidget.cpp [hunk 1]
```diff
@@ -279,5 +281,12 @@ void PasswordGeneratorWidget::updateGenerator()
     m_generator->setCharClasses(classes);
     m_generator->setFlags(flags);
 
+    if (m_generator->isValid()) {
+        m_ui->buttonGenerate->setEnabled(true);
+    }
+    else {
```
Comment (phoerious) [inline src/gui/PasswordGeneratorWidget.cpp]: Although much of the existing code uses this style, it is actually against both the Qt coding standard and my personal taste. I'd suggest removing the newline before else.

**Comment by phoerious** [comment]
Oh, and one more thing: could you apply this fix on top of the release/2.1.1 branch please instead of develop? Thanks!

**Comment by louib** [comment]
Not sure about clearing the password field. Would that also imply disable the `Apply` button?
I'll rebase on release/2.1.1!

**Comment by phoerious** [comment]
Yes it would. My main intention was to remove the confusion that the password isn't updating anymore, even if you move the slider.

**Comment by phoerious** [comment]
Huh? No need to close this yet.

**Comment by louib** [comment]
@phoerious my bad, I thought changing the base branch screwed up the PR. I was about to cherry-pick the changes locally.

**Comment by phoerious** [comment]
No, as long as it hasn't been merged yet, you can do what you want to the base branch and it will still work.

Any thoughts on the password field? If you want to add a commit for that, I'll wait, otherwise, I'd just merge this as is. Your call.

**Comment by phoerious** [comment]
After you properly rebased and force-pushed, that is. Right now I would merge in the whole develop history.
