### PR TITLE
TouchID support refactoring

### LINKED ISSUE #7695: Quick unlock with apple watch not working
## Overview
I am not able to use the quick unlock feature with an apple watch (support introduced in KeepassXC 2.7.0)
I am using a MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports, Intel version) with OSX Monterey 12.3 and an Apple Watch Series 7 with watchOS 8.5, both with the same apple id.

Note that I am able to login into my mac with the apple watch and to unlock other applications (e.g., bitwarden).

## Steps to Reproduce
1. Wear your apple watch (make sure it is unlocked)
2. Open a database using its password
3. Lock the database
4. Click "Unlock Database"

## Expected Behavior
After clicking "Unlock Database", I should receive a prompt/notification on the apple watch to unlock the database.

## Actual Behavior
- With macbook lid open: after clicking "Unlock Database", KeePassXC asks for touch id and no notification is shown on the apple watch.
- With macbook lid closed (I am using only an external monitor):
    - Database initially opened with its password when lid was open: after clicking "Unlock Database", KeePassXC shows an error stating "Failed to authenticate with touch id".
    - Database initially opened with its password when lid was closed: KeePassXC does not show the "Unlock Database" button and asks for the database password again.

## Context
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.3
CPU architecture: x86_64
Kernel: darwin 21.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

Operating System: macOS

### PR DESCRIPTION
**Pull request by yowidin**
TouchID and Apple Watch support is now detected both at compile time and runtime.

We need both runtime and compile time checks to solve the following problems:
- Not all flags are available in all OS versions, so we have to check it at compile time
- Requesting Biometry/TouchID when to fingerprint sensor is available will result in runtime error. Same probably goes for Apple Watch.

Should fix #7695:

## Testing strategy
- Manual tests on an iMac (12.3) with an Apple Watch.
- Manual tests on a MacBook (12.3) with both TouchID and Apple Watch with either open or closed lid and using either the watch or the fingerprint sensor.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ Refactor (significant modification to existing code)

### CODE REVIEW

File: src/touchid/TouchID.h [hunk 1]
```diff
@@ -21,22 +21,17 @@ class TouchID
     bool storeKey(const QString& databasePath, const QByteArray& passwordKey);
     bool getKey(const QString& databasePath, QByteArray& passwordKey) const;
     bool containsKey(const QString& databasePath) const;
-    bool isAvailable();
     void reset(const QString& databasePath = "");
 
+    static bool isAvailable();
+    static bool isWatchAvailable();
+    static bool isTouchIdAvailable();
```
Comment (michaelk83) [inline src/touchid/TouchID.h]: `isAvailable()` should not be static, since the same is needed in Windows Hello (see [source](https://github.com/keepassxreboot/keepassxc/blob/develop/src/winhello/WindowsHello.h)) and later in the Linux equivalent. Once they're abstracted to a common interface as was planned, `isAvailable()` needs to be in that interface. It would be hardware and OS agnostic from that point of view, with the details handled by each implementation.

`isWatchAvailable()` is one of those implementation details that are specific to macOS. Probably shouldn't be public.

From the application side, it shouldn't care whether the authentication happens with the watch or a fingerprint reader. It just needs to store and read the key, when that's possible.

Comment (yowidin) [reply src/touchid/TouchID.h]: > From the application side, it shouldn't care whether the authentication happens with the watch or a fingerprint reader. It just needs to store and read the key, when that's possible.

I think it's always better to communicate as much information to the user as possible, otherwise it's really hard to debug the authentication issues. At the moment I, as a Mac user have no clue why quick unlock doesn't work, which methods are available, is it a OS problem or KeePassXC problem etc. 

1Password does a bit better job. They explicitly communicate that unlock is impossible with the laptop lid being  closed, watch being out of range etc. 🤷‍♂️

Comment (droidmonkey) [reply src/touchid/TouchID.h]: I agree, if the specific errors are made available by the api then we should show them. Windows hello doesn't provide much of anything.

Comment (michaelk83) [reply src/touchid/TouchID.h]: That's usually what exceptions are for. As long as the calling code can catch the exception and display the error message, that part is independent from the class interface.

What I meant by "the application shouldn't care" is that it shouldn't need to explicitly check which hardware is available and use different code paths for each case. It would just call `getKey()` (or whatever), and let the implementation worry about the details. Then catch any error and display the message (also without worrying about what it says).

**Review by droidmonkey — APPROVED** [review]
