### PR TITLE
CLI: Restore the original codepage on windows

### LINKED ISSUE #11465: On Windows keepassxc-cli.exe changes the code page to 65001 but does not restore it.
## Overview
When calling keepassxc-cli.exe on Windows it changes the code page to 65001.
And when calling powershell.exe, the font changes from Consolas to Raster Fonts.
Version 2.7.3 is OK, but versions 2.7.4 and later change the code page and the console font.

## Steps to Reproduce
1. Open Command Prompt.
2. Set console font to Consolas, size 16.
3. Type: `powershell.exe dir C:\Windows\System32\cmd.exe`
4. Console font doesn't change.
5. Type: `"C:\Program Files\KeePassXC\keepassxc-cli.exe" -v`
6. Console font doesn't change.
7. Type: `powershell.exe dir C:\Windows\System32\cmd.exe`
8. Console font changes to Raster Fonts, size 8x12.

## Expected Behavior
Console font does not change.

## Actual Behavior
Console font changes from Consolas, size 16 to Raster Fonts, size 8x12.

## Context
Default code page is 850, not 437.
The `chcp.com` command returns 850.
The Command Prompt font is set to Consolas, size 16.

KeePassXC - 2.7.4 and later

Operating System: Windows

Additional info when running inside PowerShell.

```
# Compile a helper type that calls the WinAPI functions.
Add-Type -Namespace Util -Name WinApi -MemberDefinition @'
    [DllImport("Kernel32.dll")]
    public static extern uint GetACP();
    [DllImport("Kernel32.dll")]
    public static extern uint GetOEMCP();
    [DllImport("Kernel32.dll")]
    public static extern uint GetConsoleCP();
    [DllImport("Kernel32.dll")]
    public static extern uint GetConsoleOutputCP();
'@
[Util.WinAPI]::GetACP()			# Returns 1252
[Util.WinAPI]::GetOEMCP()		# Returns 850
[Util.WinAPI]::GetConsoleCP()		# Returns 850
[Util.WinAPI]::GetConsoleOutputCP()	# Returns 850
 & 'C:\Program Files\KeePassXC\keepassxc-cli.exe' -v	# Returns 2.7.9
[Util.WinAPI]::GetACP()			# Returns 1252
[Util.WinAPI]::GetOEMCP()		# Returns 850
[Util.WinAPI]::GetConsoleCP()		# Returns 65001
[Util.WinAPI]::GetConsoleOutputCP()	# Returns 850

```

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #11465

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/cli/Utils.cpp [hunk 1]
```diff
@@ -43,6 +43,11 @@ namespace Utils
     QTextStream STDIN;
     QTextStream DEVNULL;
 
+#ifdef Q_OS_WIN
+    UINT origCodePage = GetConsoleCP();
+    UINT origOutputCodePage = GetConsoleOutputCP();
+#endif
```
Comment (phoerious) [inline src/cli/Utils.cpp]: Shouldn't this be done in the init function rather than global scope?

**Comment by droidmonkey** [comment]
@phoerious  ready for re-review

**Review by phoerious — APPROVED** [review]
