### PR TITLE
Fix two problems with URL wildcard matching

### LINKED ISSUE #12255: KeePassXC doesn't properly validate wildcards in domains leading to potential autofill on phishing websites
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

In Version 2.7.10 keepass ignores a dot after a wildcard and offers to autofill on any domain following *domain.tld if *.domain.tld is set Additional Url.

### Steps to Reproduce

1. Create a new entry in keepassxc with username and password
2. Insert _*.thub.com_ in the Addional URLs section of the entry
3. Navigate a keepassxc capable browser to github.com

### Expected Versus Actual Behavior

Expected Behaviour:
No offer to autofill is made as the additional url is for a different domain

Actual Behaviour:
(Tested on Firefox 140.0.2) the browser integration offers to to enter the login data

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.7.10
Revision: b342be4

Qt 5.15.17
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.15.4-arch2-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.8.1
```

### Operating System

Linux

### Linux Desktop Environment

i3

### Linux Windowing System

X11

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #12255
* Periods were not being escaped in the url string before being used in a regex resulting in matching 'any character' between domain parts
* Wildcards entered as `*.` were being replaced with simply `*` resulting in unexpected matches to occur. Fixing this has a side effect of `https://*.github.com` NOT matching `https://github.com` which should be the expected behavior. Users can enter both url's if they desire to match the primary and all sub domains or leave out the wildcard entirely to use normal matching behavior.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and include helpful comments. )
Updated unit tests to conform with new expected behavior

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -1572,11 +1572,11 @@ bool BrowserService::handleURLWithWildcards(const QUrl& entryQUrl, const QString
         }
 
         // Escape illegal characters
-        auto re = firstPart.replace(QRegularExpression(R"(([!\^\$\+\-\(\)@<>]))"), "\\\\1");
+        auto re = Tools::escapeRegex(firstPart);
 
         if (hostnameUsed) {
             // Replace all host parts with wildcards
-            re = re.replace(QString("%1.").arg(UrlTools::URL_WILDCARD), "(.*?)");
+            re = re.replace(QString("%1.").arg(UrlTools::URL_WILDCARD), "(.*?)\\.");
```
Comment (varjolintu) [inline src/browser/BrowserService.cpp:1579]: Doing just this breaks the compatibility with the URLs that have now been removed from the tests. If we still want to match the URLs with or without subdomains, one way to do that is to make the first wildcard optional if it only contains the host:
```
if (re.startsWith(QString("%1\\.%2").arg(UrlTools::URL_WILDCARD, Tools::escapeRegex(secondPart)))) {
    re.replace(0, UrlTools::URL_WILDCARD.length()+2, "(?:.*?\\.)?");
}
```

Or something similar. Otherwise URL `https://*.github.com/*` will match `https://login.github.com/path` but not `https://github.com/path`. But if we want to make this less complex, I'm ok with the new restriction.

File: tests/TestBrowser.cpp [hunk 2]
```diff
@@ -433,13 +433,12 @@ void TestBrowser::testSearchEntriesWithWildcardURLs()
...
     auto result = m_browserService->searchEntries(
         db, "https://github.com/login_page/second", "https://github.com/login_page/second");
-    QCOMPARE(result.length(), 6);
+    QCOMPARE(result.length(), 5);
     QCOMPARE(firstUrl(result[0]), QString("https://github.com/login_page/*"));
     QCOMPARE(firstUrl(result[1]), QString("https://github.com/*/second"));
     QCOMPARE(firstUrl(result[2]), QString("https://github.com/*"));
     QCOMPARE(firstUrl(result[3]), QString("http://github.com/*"));
     QCOMPARE(firstUrl(result[4]), QString("github.com/*"));
-    QCOMPARE(firstUrl(result[5]), QString("https://*.github.com/*"));
```
Comment (varjolintu) [inline tests/TestBrowser.cpp:442]: Maybe we should add the ` "*.thub.com",` to the URL list to make sure it is not matched.

File: src/browser/BrowserService.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/browser/BrowserService.cpp:1579]: Because of all the weird edge cases with urls, I want to keep this simple, and the user can enter two url patterns if they want this entry to match all subdomains. Technically, just adding `https://github.com/path` will match that and all subdomains of github without any wildcards needed. That is our original behavior.

File: tests/TestBrowser.cpp (hunk 2 above)
Comment (droidmonkey) [reply tests/TestBrowser.cpp:442]: Good idea

**Review by varjolintu — APPROVED** [review]
