### PR TITLE
Enhance update checker

### LINKED ISSUE #2819: "Check for updates" popup steals the focus
## Expected Behavior
I open a database, start typing my passphrase, type my passphrase entirely, validate and start using the password manager

## Current Behavior
I open a database, start typing my passphrase, get all my keypresses eaten after the third by the "Would you like KeePassXC to check for updates on startup?" popup.

## Possible Solution
Do not steal the focus from the "Password" field.
DO. NOT. USE. POPUPS.

## Steps to Reproduce
1. Upgrade to brand new v2.4.0 after having used v2.3.4 for months
2. Open a kdbx file
3. Start typing your passphrase because the focus is conveniently set on this fiedl when the application starts up
4. Try to be polite

## Context
Normal usage.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - v2.4.0
Revision: the released one

Libraries:
- A LOT OF THEM

Operating system: Linux
CPU architecture: x86_64
Kernel: 4.14.irrelevant

Enabled extensions:
- Dunno

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Reduce initial update check notification to 500 ms to prevent inappropriately stealing focus from user
* Add build flag WITH_XC_UPDATECHECK which defaults to ON
* Update checks are resolved every 7 days instead of every time the application is started
* Better checks for beta builds; ignore snapshots
* Increase test cases

Fixes #2819 

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested manually and updated existing test cases

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

File: src/updatecheck/UpdateChecker.cpp [hunk 1]
```diff
@@ -84,47 +89,59 @@ void UpdateChecker::fetchFinished()
...
+bool UpdateChecker::compareVersions(const QString& localVersion, const QString& remoteVersion)
 {
+    // Quick full-string equivalence check
     if (localVersion == remoteVersion) {
-        return false; // Currently using updated version
+        return false;
     }
 
-    QRegularExpression verRegex("^(\\d+(\\.\\d+){0,2})(-\\w+)?$", QRegularExpression::CaseInsensitiveOption);
+    QRegularExpression verRegex(R"(^((?:\d+\.?){3})(-\w+?)?(\d+)?$)");
```
Comment (phoerious) [inline src/updatecheck/UpdateChecker.cpp]: This regex looks a bit weird. Why not

```
^((?:\d+\.){2}\d+)-(\w+?)(\d+)?$
```
This matches the version number more accurately and by not capturing the hyphen you can use exact matching instead of `contains()` for betas and snapshots. You could even capture each of the version number components individually instead of splitting them afterwards.

Comment (droidmonkey) [reply src/updatecheck/UpdateChecker.cpp]: if you do not make the hyphen optional then a plain version number (2.4.0) will not match. I was considering making a group for each digit, but we are really splitting hairs here.

Comment (phoerious) [reply src/updatecheck/UpdateChecker.cpp]: The hyphen can be made optional by putting it all in a non-capturing group:
```
^((?:\d+\.){2}\d+)(?:-(\w+?)(\d+))?$
```

Comment (droidmonkey) [reply src/updatecheck/UpdateChecker.cpp]: Changes made
