### PR TITLE
Fix issues with Hardware Key auto detection

### LINKED ISSUE #10656: KeePassXC can't communicate with YubiKey (wrong serial)
## Overview
I have a new YubiKey 5C Nano (firmware 5.4.3). I have copied my keepass-database HMAC challenge to the new YubiKey. When I plug the YubiKey and try to login to my database, KeePassXC reports the wrong serial number for the hardware key and cannot interface with the hardware key.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. With YubiKey connected enter database password and attempt to unlock.
2. The YubiKey is detected on the password unlock screen, but displays a wrong serial number.
3. Receive error: "Error while reading the database: Unable to calculate database key: Could not find interface for hardware key with serial number [WRONG SERIAL NUMBER]"
4. Additionally: clicking the Refresh Hardware Keys changes the reported hardware key serial number.

## Expected Behavior
Login without difficulty.

## Actual Behavior
Wrong YubiKey serial number, database remains locked.

## Context
[NOTE]: # ( Give us any additional information you may have. )
The new YubiKey is attached directly to the Macbook Air. KeePassXC does not run under a virtual machine. Installed from Homebrew. Several other YubiKeys work correctly on the same computer. The affected YubiKey works correctly on the same computer with other applications (PGP) and also with KeePass-databases on an Android phone with Keepass2Android v. 1.10-pre. The affected YubiKey is the only one connected to the Mac at the time of testing.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 13.6
CPU architecture: x86_64
Kernel: darwin 22.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]:
Operating System: macOS

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fix #10656 - Add a small delay when before auto-polling hardware keys to all them to settle immediately after plugging in. This resolves an issue where the key's serial number could not be resolved due to hardware timeout.
* Also fix use of uninitialized variable if polling serial number fails for whatever reason.

* Fix typo in macOS key registration code

* Prevent registering duplicate listeners on window focus. These were not de-registered because we didn't trigger on unfocus. Show/Hide are sufficient triggers to add and remove listeners.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows with multiple keys. The serial number issue was most prevalent with Yubikey NEO and was immediately and fully resolved with the proposed fixes. There is no degradation to user experience.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/DatabaseOpenWidget.cpp [hunk 1]
```diff
@@ -171,8 +171,7 @@ bool DatabaseOpenWidget::event(QEvent* event)
     bool ret = DialogyWidget::event(event);
 
     switch (event->type()) {
-    case QEvent::Show:
-    case QEvent::WindowActivate: {
+    case QEvent::Show: {
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp]: Window activate is important. The window can already be visible, but not in focus/active, e.g., after Alt-Tab, mouse focus, or after screen unlock. I added this on purpose, because my testing showed that Show is not enough. Even WindowActivate does not cover all cases where we want to trigger this, but it's close enough. Keeping WindowActivate is particularly important for updating the quick unlock state.

File: src/gui/DatabaseOpenWidget.cpp [hunk 2]
```diff
@@ -512,7 +511,10 @@ void DatabaseOpenWidget::pollHardwareKey(bool manualTrigger)
     m_pollingHardwareKey = true;
     m_manualHardwareKeyRefresh = manualTrigger;
 
-    YubiKey::instance()->findValidKeysAsync();
+    // Add a delay, if this is an automatic trigger, to allow the USB device to settle as
+    // the device may not report a valid serial number immediately after plugging in
+    int delay = manualTrigger ? 0 : 1000;
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp]: I think 1000 is way too much. It adds visible delay, which will cause confusion and frustration.

**Review by phoerious — CHANGES_REQUESTED** [review]

File: src/gui/DatabaseOpenWidget.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: Then we should just trigger a polling on window activate and not a registration.

File: src/gui/DatabaseOpenWidget.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: Disagree, I tested this and saw no difference in delay. The polling itself takes several seconds. 500 ms would be the floor for this.

Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: But it will add a flat 1000ms on top before it even starts. I would prefer to reduce it to 500ms. The polling for devices is basically instant. What takes a second or so is the test challenge to see which slots are configured.

File: src/gui/DatabaseOpenWidget.cpp (hunk 1 above)
Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: What do you mean by registration? We could skip the polling on Show, but for consistency, I would prefer to poll everywhere. Overlapping polls would be cancelled anyway.

Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: You end up registering a new set of listeners every tike the window is activated before this change.

Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: Ah, that's what you mean. Yeah, I suppose that's left over from the first implementation when you could register only one trigger. Just skip the registration on WindowActivate, but still poll and, first of all, update the quick unlock state.

**Comment by droidmonkey** [comment]
@phoerious  ready for final

**Review by phoerious — APPROVED** [review]
