### PR TITLE
Fix Best-Matching ..again

### LINKED ISSUE #5299: 2.6.1: browser does not find entry
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When using KeePassXC 2.6.1 the browser module in Firefox 79 claims it can not find an entry. 2.6.0 works fine on the same site.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install 2.6.1
2. Visit website
3. Click on Browser modul

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Browser module recognizes website and pre-fills username and password field

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I get a notification saying "Error! No login found" (text might be slightly different...) 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: Not sure, I just went back to 2.6.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
It was still broken. And actually the change for passing a full URL from the extension fixed the issue without any extra handling in the BrowserService.cpp.

Fixes #5299.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Added some more tests, and tested it also manually. Double verification will be needed. This should be the final fix for this. Really.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Is this ready for review?

**Comment by varjolintu** [comment]
@droidmonkey Yes.

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -925,60 +928,75 @@ int BrowserService::sortPriority(const Entry* entry,
...
+        if (url.scheme().isEmpty()) {
+            url.setScheme("https");
+        }
 
-    // Add the empty path to the URL if it's missing
-    if (url.path().isEmpty() && !url.hasFragment() && !url.hasQuery()) {
-        url.setPath("/");
-    }
+        // Add the empty path to the URL if it's missing
+        if (url.path().isEmpty() && !url.hasFragment() && !url.hasQuery()) {
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp:938]: Wouldn't we want to add the empty path regardless of Fragment and Query also being present? Not sure how these matter or what the intent is here. At least a comment explaining it would be nice.

File: src/browser/BrowserService.cpp [hunk 2]
```diff
@@ -925,60 +928,75 @@ int BrowserService::sortPriority(const Entry* entry,
                                  const QString& baseSubmitUrl,
                                  const QString& fullUrl) const
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp:929]: I don't like the parameters of this function. We should be passing a list of URL's (not the entry itself) and the desired match URL only. Slicing and dicing the desired match URL should happen within the function. The function basically relies on the caller to do the right thing to make this function work properly.

File: src/browser/BrowserService.cpp (hunk 1 above)
Comment (varjolintu) [reply src/browser/BrowserService.cpp:938]: Sure. I can add a comment. The path is appended because URL's passed from the extension always has a `/` as a path. Entry URL's doesn't require it, but we still want to match both cases.

File: src/browser/BrowserService.cpp (hunk 2 above)
Comment (varjolintu) [reply src/browser/BrowserService.cpp:929]: True. Passing the list could also include the Additional URL's.

File: src/browser/BrowserService.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/browser/BrowserService.cpp:938]: Yah but we are not adding the empty path if there is a fragment or query. For example: `https://example.com#anchor` would not add the empty path to the end.

Comment (varjolintu) [reply src/browser/BrowserService.cpp:938]: AFAIK those URL's will have the path already set.

File: src/browser/BrowserService.cpp (hunk 2 above)
Comment (varjolintu) [reply src/browser/BrowserService.cpp]: Pushed the fix. `submitUrl` needed to be passed also because we make comparisons to that too.

**Review by droidmonkey — APPROVED** [review]
Fixed remaining issues with Qt < 5.11
