### PR TITLE
Don't rely on AppleInterfaceStyle for theme switching

### LINKED ISSUE #7615: KeePassXC doesn't properly switch between light and dark appearance on macOS
## Overview
I've experienced a problem with KeePassXC on Macs (currently macOS 12) with the appearance set to change automatically.  If I run KeePassXC during the day (light appearance) and keep it running until after the appearance switches to dark, then the next morning (light again) KeePassXC will display with a mix of light and dark elements.

## Steps to Reproduce
1. Turn on automatic appearance switching on your Mac (macOS 10.15 or higher required)
2. Run KeePassXC during the day (light appearance) and leave it running until after the appearance switches to dark.
3. Shut down the Mac.
4. The next morning (light appearance) boot the Mac and open KeePassXC.  The interface will be a mix of light and dark elements.

## Expected Behavior
KeePassXC will switch between light and dark appearances flawlessly.

## Actual Behavior
The interface is a mix of light and dark elements when going to light appearance after KeePassXC has been running during the day and into the night, and then again the next morning.

## Context
This has happened since automatic appearance switching support was added in KeePassXC 2.6.4.
I've been able to work around the issue by manually switching my Mac appearance to "Light", then back to "Auto".

KeePassXC - VERSION 2.7.0
Revision: d7a9ef4

Operating System: macOS

Screen Shot 2022-03-23 at 09 07 31
Screen Shot 2022-03-23 at 09 07 57

### PR DESCRIPTION
**Pull request by opa334**
Fixes #7615

I discovered that in very specific conditions (when interface style is on automatic and the switch happens while the Mac is turned off, as outlined in the original issue), the `AppleInterfaceStyle` preference value in `.GlobalPreferences` is wrong. I worked around this issue by instead relying on the proper system API to get the appearance state.

Additionally there was a second issue, originally the code was registering for the `AppleInterfaceThemeChangedNotification` to know when the appearance changed, unfortunately this event fires before the system API returns the new appearance state, so I had to switch it to registering a KVO on the `effectiveAppearance` property as done in [Apple sample code](https://developer.apple.com/documentation/uikit/appearance_customization/supporting_dark_mode_in_your_interface?language=objc).

## Screenshots
Before:
before

After:
after

## Testing strategy
Reproduce the specific conditions outlined above and open the old build and the build with this change after another (you will see one looks wrong and one looks right). Instead of reproducing the conditions (very time consuming), you can also manually give the `AppleInterfaceStyle` key the wrong value: `defaults write NSGlobalDomain AppleInterfaceStyle -string "<Dark/Light>"`. (Note that you have to use defaults, manually writing this key using a plist editor does not work).

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Has a bug report been submitted to Apple regarding their breaking their own api contract with the policy not changing values?

**Comment by opa334** [comment]
> Has a bug report been submitted to Apple regarding their breaking their own api contract with the policy not changing values?

Not yet, I'm not too familiar with how bug reporting to Apple works 😅. This change is still needed to work around the issue on older macOS versions either way.

**Comment by opa334** [comment]
Well before reporting it, I made sure to test it on Ventura RC2 in a VM first and it seems like the issue has already been fixed, at least I wasn't able to reproduce it

File: src/gui/osutils/macutils/AppKitImpl.mm [hunk 1]
```diff
@@ -67,14 +64,37 @@ - (void) didDeactivateApplicationObserver:(NSNotification*) notification
...
+                      ofObject:(id)object
+                        change:(NSDictionary<NSKeyValueChangeKey,id> *)change
+                       context:(void *)context
 {
-    Q_UNUSED(notification);
-    if (m_appkit) {
-        emit m_appkit->interfaceThemeChanged();
+    Q_UNUSED(object);
+    Q_UNUSED(change);
+    Q_UNUSED(context);
```
Comment (phoerious) [inline src/gui/osutils/macutils/AppKitImpl.mm]: Q_UNUSED already inserts a ; at the end.

File: src/gui/osutils/macutils/AppKitImpl.mm [hunk 2]
```diff
@@ -67,14 +64,37 @@ - (void) didDeactivateApplicationObserver:(NSNotification*) notification
...
+    if ([keyPath isEqualToString:@"effectiveAppearance"]) {
+        //
+        // Light / dark theme toggled
+        //
```
Comment (phoerious) [inline src/gui/osutils/macutils/AppKitImpl.mm]: Please remove the extra lines.

File: src/gui/osutils/macutils/AppKitImpl.mm [hunk 3]
```diff
@@ -67,14 +64,37 @@ - (void) didDeactivateApplicationObserver:(NSNotification*) notification
...
+            if(@available(macOS 11.0, *))
+            {
+                // Not sure why exactly this call is needed, but Apple sample code uses it so it's best to use it here too
+                [NSApp.effectiveAppearance performAsCurrentDrawingAppearance:emitBlock];
+            }
+            else
+#endif
+            {
+                emitBlock();
+            }
```
Comment (phoerious) [inline src/gui/osutils/macutils/AppKitImpl.mm]: Opening braces should be on the same line, space after if.

File: src/gui/osutils/macutils/AppKitImpl.mm [hunk 4]
```diff
@@ -67,14 +64,37 @@ - (void) didDeactivateApplicationObserver:(NSNotification*) notification
...
+        // Light / dark theme toggled
+        //
+        if (m_appkit) {
+
+            void (^emitBlock)(void) = ^
+            {
+                emit m_appkit->interfaceThemeChanged();
+            };
+
+#if __clang_major__ >= 9 && MAC_OS_X_VERSION_MIN_REQUIRED >= 101000
```
Comment (phoerious) [inline src/gui/osutils/macutils/AppKitImpl.mm]: I think you can remove these. We don't support macOS 10.1 anymore.

**Review by phoerious — DISMISSED** [review]

**Comment by opa334** [comment]
Applied the requested changes, let me know if there is anything else.

**Comment by opa334** [comment]
Actually this is not fixed in Ventura, just wasn't able to replicate it in a VM I assume.

**Review by droidmonkey — APPROVED** [review]

**Comment by ghost** [comment]
By the way, #9423 also *does* happen to me on Big Sur. (Latest update: 11.7.7, intel arch, system theme *is* set to automatic).
