### PR TITLE
Passkeys: Fix compatibility with StrongBox

### LINKED ISSUE #10414: KeepassXC doesn't recognize existing passkey from Strongbox
## Overview
I am using Keepassxc for Windows and Strongbox for Mac and iOS. I have stored some passkeys in Strongbox before (I'll be referencing to my passkey use for the website "ebay"). Yesterday I downloaded v.2.7.7 of keepassxc, with the implementation of passkeys. 
Unfortunately Keepassxc does not recognize any previously set passkeys from Strongbox and vice versa. If I have set a passkey with strongbox, keepassxc won't accept the passkey and asks me if I want to overwrite the one for that entry (ebay). If I hit yes, I'm able to log in with keepassxc, but not with strongbox anymore.

I'll continue calling keepassxc simply kp and strongbox sb.

## Steps to Reproduce
1. Set up a passkey for any entry that can use a passkey with kp or sb
2. Sync both instances so the passkey is accessible on sb and kp ( here the key will be stored in "advanced" and "additional properties")
3. Try to log in using the passkey with the opposite software / operating system the passkey was created with (created on sb try to log in with kp)

## Expected Behavior
1. The passkey should be recognised and valid for either operating system or software used to create the passkey.
2. The login should work with one key, created on either software

## Actual Behavior
1. The login on kp does not work with the one created from sb (and the other way around)
2. The Error notes that the passkey is not recocnized.
4. I get prompted if I want to use passkey on keepassxc and I have the option to override the existing passkey.
5. Once I do that, I can’t use the passkey on strongbox (macos) anymore and get promted if I want to override the existing one.

## Context
I have found a Workaround, as I noticed, that Kp does not store the passkey directly with the entry that contains the password and username, but rather as a separate entry itself. 

## Workaround

1. When I create a passkey on kp first, I can on only create a new entry entirely and cant safe it to my existing entry which holds username and password
2. One I do that, I have two entries: Ebay (username and password) and Ebay (passkey)
3. If I go back to strongbox, I can create a passkey for the existing entry Ebay (username and password)
4. That way, the Ebay (username password) entry uses the strongbox passkey and the Ebay (passkey) uses the keepassxc passkey.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - v.2.7.7
KeepassXC Browser Extension: v.1.9.0.1

Operating System: Windows & macOS

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Adds an older version of Credential Id and username attributes to check it against StrongBox's implementation. If user created a passkey using much older test implementation with KeePassXC, a passkey might hold the same attributes.

Fixes #10414.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by droidmonkey — APPROVED** [review]

File: src/browser/PasskeyUtils.cpp [hunk 1]
```diff
@@ -350,3 +350,27 @@ QStringList PasskeyUtils::getAllowedCredentialsFromAssertionOptions(const QJsonO
...
+QString PasskeyUtils::getUsernameFromEntry(const Entry* entry) const
+{
+    if (!entry) {
+        return {};
+    }
+
+    return entry->attributes()->hasKey(BrowserPasskeys::KPXC_PASSKEY_USERNAME)
+               ? entry->attributes()->value(BrowserPasskeys::KPXC_PASSKEY_USERNAME)
+               : entry->attributes()->value(BrowserPasskeys::KPEX_PASSKEY_USERNAME);
+}
```
Comment (droidmonkey) [inline src/browser/PasskeyUtils.cpp]: Need EOF newline pls

**Review by droidmonkey — APPROVED** [review]
