### PR TITLE
Fix multiple TOTP issues, resolves #1360

### LINKED ISSUE #1360: Segmentation fault when deleting entry with TOTP Seed
## Expected Behavior
No seg fault, entry is deleted as expected.

## Current Behavior
seg fault.

## Steps to Reproduce (for bugs)
1. Create an entry with a `TOTP Seed`
2. Save database
3. Delete the entry (will send to the recycle bin by default)
4. Save database
4. Right click the recycle bin and click `Empty recycle bin`
5. Seg fault

## Debug Info
KeePassXC - Version 2.2.4
Revision: 6476b6b

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Ubuntu 16.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.10.0-42-generic

Enabled extensions:
- Auto-Type

@TheZ3ro I believe it might have to do with the new details view, which I guess has a recurring job to update the totp code. Is it possible that the totp refreshing job wakes up to a deleted entry?

### PR DESCRIPTION
**Pull request by phoerious**
This PR resolves resolves #1360

## Description

1. Fix crash when deleting TOTP entry
2. Fix memory leak when selecting TOTP entries
3. Fix TOTP update timeout on DetailsWidget
4. Fix TOTP settings attributes not being applied before first call to totpSeed()

## Motivation and Context
1. maintained a TOTP update timer which wasn't deleted when the entry was deleted.
2. used to create a new QTimer instance every time a TOTP entry was selected without deleting the old one
3. was too fast by a factor of 100
4. caused TotpDialog to always use the standard settings on first invocation instead of the actual entry settings

## How has this been tested?

Manually and by running existing unit tests.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/DetailsWidget.cpp [hunk 1]
```diff
@@ -154,13 +153,13 @@ void DetailsWidget::getSelectedEntry(Entry* selectedEntry)
     if (m_currentEntry->hasTotp()) {
         m_step = m_currentEntry->totpStep();
 
-        if (nullptr != m_timer) {
-            m_timer->stop();
+        if (m_timer) {
+            delete m_timer;
         }
-        m_timer = new QTimer(this);
+        m_timer = new QTimer(selectedEntry);
```
Comment (adolfogc) [inline src/gui/DetailsWidget.cpp]: Nice solution to the problem.
