### PR TITLE
Enhance Tags / Saved Searches

### LINKED ISSUE #3963: Future: View count of entries in each Group
It can be near Groups. It isn't unneeded future, for example I need to understand how many entries are not in my second base on another device witch I don't want sync via cloud.

### LINKED ISSUE #8036: Column sorting is not saved after showing expired entries
## Overview
I sort entries by Title. However, it is not kept after relaunching the app.

Before restarting the app:
image

After restarting the app:
image

## Steps to Reproduce
1. Start the app
2. Open a group with entries.
3. Click on a column header to sort by that column.
4. Lock the database and exit or just immediately exit.
5. Open the app again. Go to the same group.

## Expected Behavior
Entries are sorted.

## Actual Behavior
Entries are not sorted.

## Context
Checked the suggestion from https://github.com/keepassxreboot/keepassxc/issues/7686#issuecomment-1079905231 for `~/Library/Caches/KeePassXC/keepassxc.ini` as I'm on Mac. But, it is not applicable as it is not on a RAM disk.
Tried removing `keepassxc.ini` but that didn't help either.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.3
CPU architecture: arm64
Kernel: darwin 21.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

### LINKED ISSUE #8277: Set and unset tags from several entries at once
## Summary

I would like to be able to delete tags from several entries at once.

## Examples

I do not have any picture to show some ideas:

1. From the block "Database Tags", or in the preview panel of an entry, to be able to right on any tag and select "Delete this tag from all entries".
2. Menubar > Database Settings > Maintenance > A new view with a list of all the tags used, with possibility to delete them from all entries (and rename the tags eventually?)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I am asking for this feature because, since I upgraded to the [version 2.7.0](https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.0), where the tags functionality has been added, _almost all_ my entries got automatically flagged with tags while I never wanted that.
I am not saying this feature is not useful (I want to use tags) but 1) the tags I have now were not created by me and 2) the set of entries that were modified with tags is not correct.
I do not understand how the creation of these tags was based on.

Thank you.

### LINKED ISSUE #8352: Tab navigation doesn't respect removed panels by the user
## Overview
Using tab to switch focus between elements of the GUI doesn't work as expected if I remove the database tags pane. Pressing <tab> in the group pane moves focus somewhere I can't see, presumable the now invisible database tags pane. Similarly, pressing <Shift+Tab> in the Database-Entry List also moves focus off-screen.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click on one of the database groups to move focus there
2. Press <tab> to verify that focus is moved to database pane, pressing tab again moves to database entries.
3. Remove database tags pane by dragging the upper border of it as far down as possible.
4. Click on one of the database groups to move focus there
5. Press <tab> once. Now it is not visible, where the focus is.
6. Press <tab> again to move to database entries.

## Expected Behavior
Pressing tab once from database group pane while database tags pane is removed should move focus directly to database entries.  Step 5. should not happen.

## Actual Behavior
Pressing tab once from database group pane moves focus to invisible location, presumably to the nonexistant database tags. Pressing again allows to go to database entries.

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Linux
Desktop Env: i3
Windowing System: X11

### PR DESCRIPTION
**Pull request by droidmonkey**
**Enhance Tags UX**
* Rename "Database Tags" to "Searches and Tags"
* Separate searching for all entries and resetting the search
* Support selecting multiple tags to search against
* Fix using escaped quotes in search terms
* Make tag searching more precise
* Support `is:expired-#` to search for entries expiring within # days. Exclude recycled entries from expired search.
* Don't list tags from entries that are recycled
* Force hide tag auto-completion menu when tag editing widget is hidden. On rare occasions the focus out signal is not called when the tag view is hidden (entry edit is closed), this resolves that problem.
* Remove spaces from before and after tags to prevent seemingly duplicate tags from being created.
* Also fix some awkward signal/slot dances that were setup over time with the entry view and preview widget.

**Add search saving and recall**
* Add ability to save searches and recall them from the "Searches and Tags" view
* Add ability to remove a tag from all entries from the "Searches and Tags" view
* Cleanup tag handling and widgets

**Allow changing tags for multiple entries through context menu**
* Closes #8277 - show context menu with currently available tags in database and checks those that are set on one or more selected entries. When a tag is selected it is either set or unset on all entries depending on its checked state.

**Other Improvements**
* Fix #8036 - use search interface to display expiring entries on first unlock.
* Fix #8352 - Correctly adjust for missing panels when tabbing around the Database Widget
* Closes #3963 - Show current entry count in status bar
* Improve various icons in context menus

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image

Save Searches!
image

Remove Searches and Tags!
image

New icons!
image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
note: looks like I need to fix the entry count display on unlock again...

**Comment by michaelk83** [comment]
~~"Reset View" is unclear. Maybe "Reset Search"? What does this do, and how is it different from "All Entries"?~~

> Support `is:expired-#` to search for entries expiring within # days.

There are a few other bits in #7791 that are related to this. Though some of it can wait for a separate PR, I guess.

**Comment by michaelk83** [comment]
> "Reset View" is unclear. Maybe "Reset Search"? What does this do, and how is it different from "All Entries"?

[Found it](https://github.com/keepassxreboot/keepassxc/pull/8435/files#diff-4614fe5e04e22ca136c9a966c7a7163b30baef9410bb847035e802022bf2603cR26):
```cpp
m_presetTags << qMakePair(QString(""), tr("Reset View")) << qMakePair(QString("*"), tr("All Entries"))
```

Hmm.. "Reset Search" somewhat makes sense here, but how about "All (global)" and "All (current view)"?

**Comment by droidmonkey** [comment]
"Clear Search" would make sense as well.

I will untag the expired entry view issue since it's a multiparter

**Comment by droidmonkey** [comment]
@michaelk83 I went a little crazy and added a bunch of fun stuff, check it out again

**Comment by michaelk83** [comment]
(sorry for the delay)

I don't see the "Expiring in 3 days" and "Multiple tags" in the code. Are those just searches you've saved manually? The other 4 are enough by default, I think.

"Expiring in 3 days" and "Expired" will end up the same thing once #7791 is done.

The rest LGTM, though I haven't looked at the code much. I like the new "Searches and Tags" header and the little save button. Will need to update the docs for the new features.

File: src/gui/DatabaseWidget.cpp [hunk 1]
```diff
@@ -1449,6 +1432,32 @@ void DatabaseWidget::search(const QString& searchtext)
...
+        return;
+    }
+
+    // Pull the existing searches and prepend an empty string to allow
+    // the user to input a new search name without seeing the first one
+    QStringList searches(m_db->metadata()->savedSearches().keys());
+    searches.prepend("");
+
+    auto name = QInputDialog::getItem(
+        this, tr("Saved Search"), tr("Enter a unique name or overwrite an existing search from the list:"), searches);
```
Comment (phoerious) [inline src/gui/DatabaseWidget.cpp]: Can we make this an inline edit in the list of saved searches? We shouldn't be using 90's-style UI patterns.

File: src/core/Entry.cpp [hunk 2]
```diff
@@ -654,7 +651,28 @@ void Entry::setOverrideUrl(const QString& url)
...
+
+void Entry::addTag(const QString& tag)
+{
+    auto taglist = m_data.tags;
+    if (!taglist.contains(tag)) {
+        taglist.append(tag);
+        std::sort(taglist.begin(), taglist.end());
+        set(m_data.tags, taglist);
+    }
+}
```
Comment (phoerious) [inline src/core/Entry.cpp]: I think we should trim leading and trailing white space from (new) tag names. I think you do that in the tag edit GUI, but it may make more sense to do it here. If a database already contains multiple tags that differ only in surrounding white space, we should treat it as the same tag anyway.

**Comment by droidmonkey** [comment]
Yes, expiring in 3 days is a saved search

File: src/gui/DatabaseWidget.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: This is used on the first save of a search from the search bar. I am not going to change that pattern. You cannot rename a search.

File: src/core/Entry.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/core/Entry.cpp]: Yes good point we should do some more data cleansing in this function.

File: src/gui/DatabaseWidget.cpp (hunk 1 above)
Comment (phoerious) [reply src/gui/DatabaseWidget.cpp]: Sure, but I would add an inline edit field to the tag list whose contents are saved on enter or discarded if left blank. That would be a lot smoother. I just hate the modal popup.

Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: There are two problems solved with the modal popup:
1. When you press the save button on the far right, having a new line appear in the Searches and Tags view is undiscoverable and easily missed. The modal popup provides feedback and centrality to the feature.
2. The modal popup lets you choose an existing saved search from the list to overwrite. This is incredibly helpful if you want to tweak your search and keep the same name without typing it over again.

I would consider editing the name of a saved search from the Searches and Tags view, but that's about it. Same with tags, could bulk-edit the name of tag from that view as well which could be useful.

Comment (phoerious) [reply src/gui/DatabaseWidget.cpp]: Editing should definitely be done in-line. For creating, I'm on the fence. Every modal popup creates another point of conflict with database locking and its generally being quite obtrusive and old-school.

The locality issue is a valid concern, but that applies also to the added entry after you press Save. To solve these locality problems, you could maybe instead add a + button to the tag list, which shows a context menu that let's you create different kinds of tags, including saving the current search. It would be a little less discoverable, but it would solve those issues. An existing search could be updated by right-clicking and choosing "update search". In the grand scheme, I would actually prefer that, since it adds a central point where tags and searches are added and edited instead of having different actions all over the place. Then we could also implement things like adding tags to entries by drag and drop etc.

Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: I agree but that sounds like a great improvement for a future update. I am out of time for this one and it works great as is. Don't let perfect be the enemy of good enough.

Comment (phoerious) [reply src/gui/DatabaseWidget.cpp]: Nothing is more permanent than a temporary solution. 😉
Would the modal pop-up block the database lock timer?

Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: Yes it would and I can fix that easily, I am willing to do that work

Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: Done!

**Review by phoerious — APPROVED** [review]

**Comment by jamilraichouni** [comment]
> Not important but worth mentioning:
> When using the macos GUI in English it states `2 Entry(s)` for instance. But it must be `x Entries` if x > 1.
> So in the case of the english word `Entry` you cannot cover singular and plural by appending the suffix `(s)`. That works for `User` -> `User(s)` and many other english words but not in the given case or for `1 Baby` and `x Babies` etc.

Moved my comment to https://github.com/keepassxreboot/keepassxc/issues/3963#issuecomment-1291728546
