### PR TITLE
Fix broken safe saves across file systems

### LINKED ISSUE #2888: KeepassXC deletes database file after unsafe save on different file system
## Expected Behavior
I want my datafiles save on a google drive for business (Drive File Stream) folder.

## Current Behavior
I've my keepass file on a google drive for business virtual drive (Drive File Stream) in my mac (updated to latest version). When I started with keepassxc 2.4 this morning, it told me that it needed to move my browser settings into the database settings (i clicked yes). Afterwards I got an error message that it couldn't save the file ("Writing the database failed, cross device link"). Afterwards my keepass file was gone.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. Add a pre keepass 2.4 (with browser settings) file to a google drive for business folder
2. open it, click yes to the browser migration question
3. observe: the file is gone

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Fix #2888
* Qt has an undocumented rename implementation for QTemporaryFile that does not fallback to the copy implementation. Forcing the use of QFile::rename(...) allows for this fallback and protects against cross-device link errors.

* Improve behaviors when the database fails to save properly.
  * Mark database dirty if saving fails
  * Restore database file from backup if unsafe save fails between deleting database file and copying temporary file into place
  * Improve error message display for opening and saving database files
  * Do not automatically retry saving after failure. This prevents deletion of the backup database file and improves user awareness of issues.

This was tested against databases with various extensions and forced failure modes.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Tested using VeraCrypt container.

2.4.0 -> database is deleted and cross-link error thrown
This PR -> database is saved correctly and backup file created

File: src/core/Database.cpp [hunk 1]
```diff
@@ -241,20 +241,12 @@ bool Database::save(const QString& filePath, QString* error, bool atomic, bool b
...
             QFile::remove(filePath);
-#ifdef Q_OS_LINUX
-            // workaround to make this workaround work, see: https://bugreports.qt.io/browse/QTBUG-64008
-            if (tempFile.copy(filePath)) {
-                // successfully saved database file
-                return true;
-            }
-#else
-            if (tempFile.rename(filePath)) {
+            if (tempFile.QFile::rename(filePath)) {
```
Comment (jankatins) [inline src/core/Database.cpp]: A comment why this is necessary might be wise for the next coder touching this stuff?

File: src/core/Database.cpp [hunk 2]
```diff
@@ -241,20 +241,16 @@ bool Database::save(const QString& filePath, QString* error, bool atomic, bool b
...
-                // successfully saved database file
-                return true;
-            }
-#else
-            if (tempFile.rename(filePath)) {
+
+            // Note: call into the QFile rename instead of QTemporaryFile
+            // due to an undocumented difference in how the function handles
+            // errors. This prevents errors when saving across file systems.
+            if (tempFile.QFile::rename(filePath)) {
```
Comment (phoerious) [inline src/core/Database.cpp]: Perhaps add the name of the temporary file to the error message so users can find it again if everything fails?

**Comment by droidmonkey** [comment]
Added a lot better handling of failed saving in the latest commit

File: src/core/Database.cpp [hunk 3]
```diff
@@ -241,27 +242,30 @@ bool Database::save(const QString& filePath, QString* error, bool atomic, bool b
...
+                // successfully saved the database
                 tempFile.setAutoRemove(false);
                 setFilePath(filePath);
                 return true;
+            } else {
+                // restore the database from the backup
+                if (backup) {
```
Comment (phoerious) [inline src/core/Database.cpp]: else if?

File: src/gui/DatabaseWidget.cpp [hunk 4]
```diff
@@ -1527,21 +1529,20 @@ bool DatabaseWidget::save(int attempt)
...
+        m_saveAttempts = 0;
         return true;
     }
 
-    if (attempt >= 0 && attempt <= 2) {
-        return save(attempt + 1);
-    }
-
-    if (attempt > 2 && useAtomicSaves) {
+    if (m_saveAttempts > 2 && useAtomicSaves) {
```
Comment (phoerious) [inline src/gui/DatabaseWidget.cpp]: You are missing the part where you are actually retrying. This code is never executed unless the user retries himself. Is that intentional? I guess it would make sense this way. I would prefer the logic reversed, though. Show error and return false if saving failed and m_saveAttempts is less than 3. Otherwise continue with whatever recovery logic we have.

File: src/core/Database.cpp [hunk 5]
```diff
@@ -241,27 +242,30 @@ bool Database::save(const QString& filePath, QString* error, bool atomic, bool b
...
+                    restoreDatabase(filePath);
```
Comment (phoerious) [inline src/core/Database.cpp]: This needs a check if database backups are enabled. If not, we can only disable autoremove and display the name of the temporary savefile instead.

File: src/gui/DatabaseWidget.cpp (hunk 4 above)
Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: Yes that is the new intention. The old method automatically tried saving 3 times in a row using recursive calls.

Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: The way the logic is programmed now is optimal. You want to intervene before getting to the final error message to try and disable the save safes after the third attempt. The block is never shown if atomic saves are already disabled. Reversing the logic will require code duplication or more complicated if/else blocks.

Comment (phoerious) [reply src/gui/DatabaseWidget.cpp]: Alright. I'm fine with that.
