### PR TITLE
Various bug fixes and minor enhancements

### LINKED ISSUE #1536: Open other database URL entry
## Expected Behavior
On Windows Original "KeePass" Variant you could make a link to another Keepass database file with
kdbx://C:\database.kbdx. If you double click that entry's URL it would open the database file. (Even is password protected, the password would come from the entry and would be passed in the openening process silently.
It also worked for password+keychain protection, but that didnt come right out of the box. (But I think I have the settings on my windows maschine still and could share it)
 
## Current Behavior
This feature isnt implemented to my knowledge.

## Context
With the implementation of this feature you could have seperated keepass database files for each customer in a company for instance. A "master" keepass file would be created with link entries to the customers keepass files. 1 entry = 1 customer = 1 keepass file.
If that keepass file is on an smb share for instance, it would be easy to revoke or give access to a keepass database file per user or per group. If you double click that entry and have ro/rw rights to that file, keepassxc will open that file (in a new window/tab of keepassxc).

Operating system: Mac OS High Sierra (other systems not checked)

### LINKED ISSUE #2078: AutoOpen Feature should allow usage of referenced fields
## Expected Behavior
A Item in the "AutoOpen" folder with password reference to another item from a different folder should be allowed.

## Current Behavior
The AutoOpen feature tries the reference string as password, which won't work.

## Possible Solution
Allow unserialization of reference strings for fields for items within "AutoOpen" folder.

## Steps to Reproduce (for bugs)
1. Create 2 keepass files protected with a password.
2. Open keepass file 1 and create a new entry in the root folder, with URL ```file://<where keepass file 2 is>``` and password
3. Clone that entry and check that the cloned item should use references for username and password
4. Create folder "AutoOpen" under root folder
5. Move that cloned entry with the references to that folder
6. Close all open databases
7. Open keepass file 1.
8. The AutoOpen feature will trigger but will be unable to open keepass file 2 for you, since the password (the reference string) will be interpreted as password, which is wrong.

## Context
See related issues
#1259
maybe 
#1536

Line in question (possible)
https://github.com/keepassxreboot/keepassxc/blob/0f604aa8c7ce47ce504f5a9d72acd9871802bebd/src/gui/DatabaseTabWidget.cpp#L631
(will use whatever is in the password field, without checking against references)

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### LINKED ISSUE #2493: Don't error out when duplicate attachments are found
## Expected Behavior

Database should open

## Current Behavior

Database won't open in KeePassXC on MacOS 10.14.1 with "Duplicate attachment found" error

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

We are using the Database over smb access on several macOS Computer. Opening the database in other programs like KeeWeb or MacPass is working fine. Only KeePassXC is causing this problem.
How can we solve this issue? We also exported the DB to .xml from KeeWeb but searching in a DB with over 100 pw is causing headaches :)

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### LINKED ISSUE #2871: Add ifDevice feature to Auto-Open
## Summary
KeeAutoExec functionality has been updated for Keepass2 and Keepass2Android. I suggest that the KeepassXC implementation is updated also to keep best compatibility.

## Context
KeeAutoExec functionality has been added (https://github.com/keepassxreboot/keepassxc/issues/477), but KeeAutoExec has sinced received an update which I have requested and discussed with Dominic in https://sourceforge.net/p/keepass/discussion/329220/thread/509d35a111/?limit=250. (Note: I am the author of KP2A).

The main update is introducing support for an IfDevice field which allows to select which entries should be opened on which devices. This makes sense for local files and also provides good support for mobile apps where paths e.g. to Dropbox files look different. The feature is implemented in Keepass2Android's current beta (https://play.google.com/apps/testing/keepass2android.keepass2android) which will soon be released to stable.
Would be great if KeepassXC would support the IfDevice extension.

## Desired Behavior
If an AutoOpen entry has a field "IfDevice", this field should be respected. Otherwise I am expecting people to complain if they add child databases in Keepass2Android which have the IfDevice field set because they should be restricted to the Android device.

### LINKED ISSUE #3706: Check for updates should consider checking weekly while running
## Summary
There's an option to `Check for updates at application startup once per week`, but if I leave KeePassXC running for a month, it seems like it won't tell me that I'm out of date.

## Desired Behavior
In addition to checking at startup if it hasn't been checked in a week, schedule a new check for a week later to be run if the app is still running at that point (and to be repeated a week after that...).

## Context
I (and many others) leave certain apps running for extended periods of time. Currently, Chrome.app has a white up arrow in a green circle telling me that I'm out of date. That will eventually turn to Yellow/Amber and later Red if I wait long enough (it definitely happens for some colleagues).

### LINKED ISSUE #4060: TOTP secrets not saved if set up from within entry
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
TOTP secrets saved

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
TOTP secrets not saved if set up from within entry

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create new entry or open any previously created
2. From WITHIN entry do Set up for TOPT
3. Switch to Advanced(on the left) to see that "OTP" attribute NOT presented.
4. You still can get TOTP code fine as until close/reopen DB.
5. After reopen DB TOTP fully cleaned.

The only way it works correct(save secrets) if set up TOTP for entry from the main grid.
1. Select entry (not drill down)
2. Setup TOPT via right click menu or main menu.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.2.0

### LINKED ISSUE #4413: KeeShare hits assert when choosing "Not This Time" to trust dialog
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

### LINKED ISSUE #4751: Portable Snapshot seems to write data in %AppData%
## Overview
After using the portable snapshot build, the settings in KeePassXC 2.5.4 are messed up (changes are saved immediately, browser-integration is turned off, etc).

## Steps to Reproduce
1. Install KeePassXC 2.5.4 in Windows 10 Pro to the default folder (C:\Program Files\KeePassXC)
2. Start KeePassXC and change some settings
3. Exit KeePassXC
4. Download the portable snapshot build KeePassXC-2.6.0-snapshot-Win64.zip from 15.05.2020
5. Extract the zip file to any folder (I extracted it in C:\Temp\KeePassXC - Snapshot)
6. Start the snapshot build, change the theme to "dark" and close it
7. Start KeePassXC 2.5.4 and check if the settings have changed

**Note:**
After this problem occurred, I posted this issue **without retesting** it.
Tell me if I should retest it or **if you need my settings files** (to check if the snapshot build really wrote in %AppData%).

## Expected Behavior
The **portable** version should never write any data in %AppData%

## Debug Info
KeePassXC - Version 2.6.0-snapshot
Build Type: Snapshot
Revision: 287e822

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

### LINKED ISSUE #4765: Copy paste bug in BaseStyle.cpp
Probably second occurrence of `colors[S_text]` should be removed

https://github.com/keepassxreboot/keepassxc/blob/26ea2742591da815e16608406e5bda7a39c793f5/src/gui/styles/base/BaseStyle.cpp#L398-L400

### LINKED ISSUE #4766: Option pointer but may be nullptr in BaseStyle.cpp
In line 4624 `option` pointer is used but in 4628 is checked if is null

https://github.com/keepassxreboot/keepassxc/blob/26ea2742591da815e16608406e5bda7a39c793f5/src/gui/styles/base/BaseStyle.cpp#L4624-L4628

### LINKED ISSUE #4809: Cannot save new database to SMB share.
## Overview

I cannot save a new kdbx file to a SMB share. I do have write access to the location.

(When I save it locally and then move it to the SMB share, I can open the file in KeePassXC and also save it.)

## Steps to Reproduce

1. Create a new database.
2. Attempt to save the database to an SMB share.

## Expected Behavior

It should work.

## Actual Behavior

> Writing the database failed: The system cannot find the path specified.

image

## Context

```
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
```

### PR DESCRIPTION
**Pull request by droidmonkey**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
**General Fixes:**
* Fix issues when Config options were renamed
* Fix compile issues when using clang 10
* Rearrange database menu icons and import database menu icons
* Set minimum size of MainWindow to 800 to prevent search bar from hiding
* Fix not saving password generator options when closing the standalone generator
* Add headers to health check reports
* Don't show hidden content dots when notes are hidden but empty.

* Fix saving new database files in SMB shares on Windows, fixes #4809

* Gracefully handle duplicate attachments :
Instead of bailing out with an error, prepend a random string to the name of duplicate attachment records. This prevents data loss from other programs that mishandled KDBX XML writing. Fixes #2493

* Properly handle blocked import of signed KeeShare database, fixes #4413

**Fix resolving resources when running from build directory**
* Copy wordlists to build dir share folder
* Change resource path resolution to only test the provided directory, not finding a specific file

**Fix theming with Qt 5.15**
* Fixes #4765, Fixes #4766

**Update edit entry widget when backing entry changes**
* Fixes #4060
* Also fix not emitting entryModified() when history is truncated. This possibly fixes other crashes with apply button when the history is truncated and then the history page is shown with a deleted entry.

**Prevent overwriting of portable config on update**
* Move portable configuration files into a config subfolder from the executable. This prevents overwriting the stored config when the application is updated in-place.
* Use .portable file to signal a portable app
* Fix #4751

**Improve AutoOpen**
* Add support for 'ifDevice' feature, closes #2871
* Resolve placeholders for username and password to support references, fixes #2078
* Add support for open databases from an entry when the url starts with 'kdbx://'. Uses the same syntax as AutoOpen. Closes #1536.

**Check for updates every 7 days while running**
* Check every hour to see if another update check should be performed. Nothing actually happens unless 7 days has elapsed since the last update check.
* Fixes #3706

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image

image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows, Linux, and macOS

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
@phoerious last code PR for 2.6.0! Ready for you.

File: src/core/Resources.cpp [hunk 1]
```diff
@@ -224,30 +224,31 @@ Resources::Resources()
...
+    trySetResourceDir(appDirPath + QStringLiteral("/share"));
 #endif
 
     if (m_dataPath.isEmpty()) {
         // Last ditch check if we are running from inside the src or test build directory
-        testResourceDir(appDirPath + QStringLiteral("/../../share"))
-            || testResourceDir(appDirPath + QStringLiteral("/../share"))
-            || testResourceDir(appDirPath + QStringLiteral("/../../../share"));
+        trySetResourceDir(appDirPath + QStringLiteral("/../share"))
+            || trySetResourceDir(appDirPath + QStringLiteral("/../../share"));
```
Comment (phoerious) [inline src/core/Resources.cpp:239]: Could also be a format expression. Causes a bit more runtime overhead, but is a bit more explicit what the final string looks like.

File: src/core/Translator.cpp [hunk 2]
```diff
@@ -117,40 +104,32 @@ bool Translator::installQtTranslator(const QStringList& languages, const QString
...
+            if (langcode == "la") {
+                // langcode "la" (Latin) is translated into "C" by QLocale::languageToString()
+                languageStr = "Latin";
             }
+            QString countryStr;
+            if (langcode.contains("_")) {
+                countryStr = QString(" (%1)").arg(QLocale::countryToString(locale.country()));
+            }
+
+            QPair<QString, QString> language(langcode, languageStr + countryStr);
```
Comment (phoerious) [inline src/core/Translator.cpp:131]: Why define a new variable that isn't used anywhere else? Just append it to `languageStr`.

File: src/crypto/ssh/bcrypt_pbkdf.cpp [hunk 3]
```diff
@@ -82,7 +82,7 @@ bcrypt_hash(const quint8* sha2pass, const quint8* sha2salt, quint8* out)
         cdata[i] = Blowfish_stream2word(ciphertext, sizeof(ciphertext),
             &j);
     for (i = 0; i < 64; i++)
-        blf_enc(&state, cdata, sizeof(cdata) / sizeof(uint64_t));
+        blf_enc(&state, cdata, BCRYPT_WORDS / 2);
```
Comment (phoerious) [inline src/crypto/ssh/bcrypt_pbkdf.cpp:85]: Any reason to make this less explicit? The result is the same.

File: src/format/KdbxXmlReader.cpp [hunk 4]
```diff
@@ -875,11 +875,13 @@ QPair<QString, QString> KdbxXmlReader::parseEntryBinary(Entry* entry)
...
 
     if (keySet && valueSet) {
-        if (entry->attachments()->hasKey(key)) {
-            raiseError(tr("Duplicate attachment found"));
-        } else {
-            entry->attachments()->set(key, value);
+        if (entry->attachments()->hasKey(key) && entry->attachments()->value(key) != value) {
+            // NOTE: This only impacts KDBX 3.x databases
+            // Prepend a random string to the key to make it unique and prevent data loss
+            key = key.prepend(QUuid::createUuid().toString().mid(1, 8) + QStringLiteral("_"));
```
Comment (phoerious) [inline src/format/KdbxXmlReader.cpp:881]: I'd append it and I wouldn't use QStringLiteral just for a `"_"` literal. This code also doesn't necessarily guarantee unique keys. That would need another check if the generated key already exists.

File: src/gui/Application.cpp [hunk 5]
```diff
@@ -162,6 +142,31 @@ Application::~Application()
...
+    } else if (appTheme == "light") {
+        setStyle(new LightStyle);
+    } else if (appTheme == "dark") {
+        setStyle(new DarkStyle);
+        m_darkTheme = true;
+    } else {
+        // Classic mode, only check for dark theme when not on Windows
+#ifndef Q_OS_WIN
+        m_darkTheme = osUtils->isDarkMode();
+#endif
```
Comment (phoerious) [inline src/gui/Application.cpp:164]: I just needed a moment to remember why we are ifdefing this on Windows. You should add a note about Qt not supporting Windows dark mode (yet). I should have documented that better when I wrote this line.

File: src/gui/DatabaseWidget.cpp [hunk 6]
```diff
@@ -2021,39 +2024,70 @@ void DatabaseWidget::processAutoOpen()
...
 
-        if (databaseUrl.startsWith("file://")) {
-            QUrl url(databaseUrl);
-            filepath.setFile(url.toLocalFile());
-        } else {
-            filepath.setFile(databaseUrl);
-            if (filepath.isRelative()) {
-                QFileInfo currentpath(m_db->filePath());
-                filepath.setFile(currentpath.absoluteDir(), databaseUrl);
+        auto ifDevice = entry->attribute("ifDevice");
```
Comment (phoerious) [inline src/gui/DatabaseWidget.cpp:2028]: This needs documentation and should be implemented for SSHAgent as well.

File: src/gui/DatabaseWidget.cpp [hunk 7]
```diff
@@ -2021,39 +2024,70 @@ void DatabaseWidget::processAutoOpen()
...
+        if (!ifDevice.isEmpty()) {
+            bool found = false;
```
Comment (phoerious) [inline src/gui/DatabaseWidget.cpp:2030]: Variable should be called `loadDb` or `doLoadDb`.

File: src/gui/styles/dark/DarkStyle.cpp [hunk 8]
```diff
@@ -23,8 +23,9 @@
 #include <QMenuBar>
 #include <QToolBar>
 
-void DarkStyle::polish(QPalette& palette)
+QPalette DarkStyle::standardPalette() const
 {
+    auto palette = BaseStyle::standardPalette();
     palette.setColor(QPalette::Active, QPalette::Window, QStringLiteral("#3B3B3D"));
     palette.setColor(QPalette::Inactive, QPalette::Window, QStringLiteral("#404042"));
     palette.setColor(QPalette::Disabled, QPalette::Window, QStringLiteral("#424242"));
```
Comment (phoerious) [inline src/gui/styles/dark/DarkStyle.cpp:31]: Since you're at it, you should replace all these QStringLiterals with `QRgb` hex numbers like `QRgb(0xABCDEF)`.

File: src/crypto/ssh/bcrypt_pbkdf.cpp (hunk 3 above)
Comment (droidmonkey) [reply src/crypto/ssh/bcrypt_pbkdf.cpp:85]: Clang 10 marks it as a warning and thus won't compile

File: src/format/KdbxXmlReader.cpp (hunk 4 above)
Comment (droidmonkey) [reply src/format/KdbxXmlReader.cpp:881]: It's a rare, onetime occurrence if ever. Appending causes the attachment to be unopenable because it overrides the extension

File: src/crypto/ssh/bcrypt_pbkdf.cpp (hunk 3 above)
Comment (phoerious) [reply src/crypto/ssh/bcrypt_pbkdf.cpp:85]: Which warning is that? Suspicious sizeof / sizeof? What about changing `sizeof(uint64_t)` to `sizeof(uint32_t) / 2`? or `8` or something?

File: src/format/KdbxXmlReader.cpp (hunk 4 above)
Comment (phoerious) [reply src/format/KdbxXmlReader.cpp:881]: It's rare, but my OCD keeps kicking in. I don't want to risk data loss to avoid data loss, even if the chances are reduced.

File: src/crypto/ssh/bcrypt_pbkdf.cpp (hunk 3 above)
Comment (droidmonkey) [reply src/crypto/ssh/bcrypt_pbkdf.cpp:85]: I generally hate determining array length with sizeof. In this case it makes little sense to do that anyway, the variable the functions asks for is "blocks" which are sequential pairs in the array.

File: src/format/KdbxXmlReader.cpp (hunk 4 above)
Comment (droidmonkey) [reply src/format/KdbxXmlReader.cpp:881]: 8 chars from a uuid is very unique when used almost never in the same entry. This isn't a global problem, it's per entry.

Comment (droidmonkey) [reply src/format/KdbxXmlReader.cpp:881]: Plus this only impacts kdbx 3 which I think we should make as deprecated.

Comment (phoerious) [reply src/format/KdbxXmlReader.cpp:881]: If its just per entry and not global, I can perhaps restrain and gag myself. But my feet are still itching.

File: src/core/Resources.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/core/Resources.cpp:239]: eh for this purpose its clear

File: src/gui/DatabaseWidget.cpp (hunk 6 above)
Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp:2028]: We'll add a section for "Opening Databases within Databases" in the Ascii Docs to cover both AutoOpen and this new feature.
