### PR TITLE
Asynchronous Browser Access Request dialog

### LINKED ISSUE #5765: Denied access not remembered
## Expected Behavior

When KeePassXC Browser asks to allow access and I deny it with the checkbox "Remember this" (or whatever it is called in English) checked I don't want the add-on asking for access every time.

## Current Behavior

I always get asked to permit access to entries where I denied access and checked the checkbox to not bother me anymore.

## Possible Solution

Well, remember being denied access.

## Steps to Reproduce (for bugs)

1. Create an entry matching a site
2. Visit this site
3. Deny access to the entry
4. Close tab, continue at 2.

## Debug info

KeePassXC -2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Mac
Browser: Chrome/Firefox

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Modifies the Access Control Dialog to work asynchronously, similar to the new Password Generator popup. The old/current implementation can break message sync between KeePassXC and the extension if another request for the dialog is retrieved. This can be only fixed when database is locked and reopened, which is not very user friendly.

This PR fixes the following issues:
-  When another dialog request is sent, an error is returned to the extension. The dialog must be closed before further intercation with browser is possible.
- Fixes the message sync with browser extension when multiple access requests are retrieved.
- Fixes the message sync if user switches tab to another page when the dialog is visible.
- Fixes accessing the dialog (and message sync) when using multiple browsers and one of them requests the dialog.

Fixes #5765.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually. Needs https://github.com/keepassxreboot/keepassxc-browser/pull/1684 for testing.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
What happens when another selection request is triggered with an existing selection dialog still visible?  Do we show another one or reject the current and show a new? Could we cause a situation where you could spam access request dialogs being opened?

**Comment by varjolintu** [comment]
> What happens when another selection request is triggered with an existing selection dialog still visible? Do we show another one or reject the current and show a new? Could we cause a situation where you could spam access request dialogs being opened?

The new request is rejected. It's expected that user responds to the one that's already active.

File: src/browser/BrowserAction.cpp [hunk 1]
```diff
@@ -263,21 +264,31 @@ QJsonObject BrowserAction::handleGetLogins(const QJsonObject& json, const QStrin
...
+    }
 
-    return buildResponse(action, message, newNonce);
+    browserService()->findEntries(socket,
+                                  incrementedNonce,
+                                  m_clientPublicKey,
+                                  m_secretKey,
+                                  id,
+                                  hash,
+                                  requestId,
```
Comment (droidmonkey) [inline src/browser/BrowserAction.cpp:285]: Just a note: we might want to create a general "Request Struct" that has all this info baked into it and we can pass around to various functions that know what to do with the elements. Would reduce the variable jumble.

**Review by droidmonkey — APPROVED** [review]
