### PR TITLE
Bitwarden and 1PUX importer improvements

### LINKED ISSUE #10368: Wrong otp secrets when importing from 1pux file
## Overview
When importing data from 1pux file, keepassxc import otp string like this 
`otpauth://totp/credential:email?secret=otpauthtotpcredentialemailsecretACTUAL_SECRET&period=30&digits=6&issuer=issuer_name`
and this leads to wrong otp codes

## Steps to Reproduce
1. Export 1pux file from 1password that contains credential with totp
2. Import 1pux file into KeepassXc 2.7.7
3. Check otp field in Advanced tab

## Expected Behavior
The line in the otp field should be identical to that in 1password

## Actual Behavior
The otp line from 1password appears in the secret option in the keepassxc otp line

## Debug Information
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.3
CPU architecture: arm64
Kernel: darwin 23.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

Operating System: macOS

### LINKED ISSUE #10380: New bitwarden import function does not work for exported Organization Vaults
## Overview
The new import function for Bitwarden JSON works properly for personal Vaults (encrypted or unencrypted json) but does not work for Organizational Vault, neither unencrypted nor encrypted.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. From Browser: export organizational vault to file (NOT Personal Vault), unencrypted
2. Import Database in KeepassXC
3. Choose Bitwarden (.json)
4. Choose previously exported json file (from organizational vault
5. Choose New or Existing DB (doesn't matter)
6. Dialogbox for import assistant shows 0 entries

## Expected Behavior
Finding and importing all entries from organizational vault export

## Actual Behavior
No entries are found, therefore nothing is imported

## Context
My assumption is that import assistant can only handle personal vaults due to different json formats/variables.
Personal Vault has:

- folders 
- items

Organizational Valut has:
- collections
- items

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: 2.7.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

### LINKED ISSUE #10400: TOTP and Argon2Id support missing from Bitwarden import
## Summary
- Currently the import function only seems to support protected vault exports that use the PBKDF2 derivation function. Trying to import vault exports that use the Argon2Id derivation function will return the error "Failed to decrypt json file: Wrong password"
- Also, for successful imports, it looks like the TOTP field is not imported, resulting in information loss during the import.

## Context
Some people might store their TOTPs in Bitwarden vaults or use the Argon2Id derivation function. Not supporting those features would mean that they would not be able to import their Bitwarden vaults using this method.

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #10400
  - Support TOTP entries with bare secrets instead of otpauth urls for Bitwarden. Vice-versa for 1PUX (Fixes https://github.com/keepassxreboot/keepassxc/issues/10368).
  - Support Bitwarden Argon2id encryption scheme

* Fixes #10380 - Support Bitwarden organization collections

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested with provided samples, added test case for Bitwarden Argon2id

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/format/OPUXReader.cpp [hunk 1]
```diff
@@ -126,9 +126,13 @@ namespace
...
                 const auto key = valueMap.firstKey();
                 if (key == "totp") {
-                    // Build otpauth url
-                    QUrl otpurl(QString("otpauth://totp/%1:%2?secret=%3")
-                                    .arg(entry->title(), entry->username(), valueMap.value(key).toString()));
+                    auto totp = valueMap.value(key).toString();
+                    if (!totp.startsWith("otpauth://")) {
+                        // Build otpauth url
+                        QUrl url(
+                            QString("otpauth://totp/%1:%2?secret=%3").arg(entry->title(), entry->username(), totp));
```
Comment (phoerious) [inline src/format/OPUXReader.cpp]: I think we might have to url encode the parameters just to be safe.

Comment (droidmonkey) [reply src/format/OPUXReader.cpp]: good catch

Comment (droidmonkey) [reply src/format/OPUXReader.cpp]: all fixed (both 1PUX and Bitwarden)

**Review by phoerious — APPROVED** [review]
