### PR TITLE
Fix various bugs when returning credentials

### LINKED ISSUE #5765: Denied access not remembered
## Expected Behavior

When KeePassXC Browser asks to allow access and I deny it with the checkbox "Remember this" (or whatever it is called in English) checked I don't want the add-on asking for access every time.

## Current Behavior

I always get asked to permit access to entries where I denied access and checked the checkbox to not bother me anymore.

## Possible Solution

Well, remember being denied access.

## Steps to Reproduce (for bugs)

1. Create an entry matching a site
2. Visit this site
3. Deny access to the entry
4. Close tab, continue at 2.

## Debug info

KeePassXC -2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Mac
Browser: Chrome/Firefox

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Fixes two minor bugs with the Browser Integration:
- "No logins found" should be only returned when none are actually found. If Access Confirm Dialog is shown and all entries are denied, no error is returned, but zero users instead.
- If "Remember" checkbox is used with Deny, that setting is now working properly.

Fixes #5765.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -314,7 +314,7 @@ QString BrowserService::getCurrentTotp(const QString& uuid)
     return {};
 }
 
-QJsonArray
+QPair<bool, QJsonArray>
 BrowserService::findEntries(const EntryParameters& entryParameters, const StringPairList& keyList, const bool httpAuth)
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp]: since this function is so complex, would you rather pass in a `bool* accepted` and use that as your indicator? Set it to false at the top of the function (if non-null) and only set to true at the bottom. The problem with returning a QPair<bool, ...> is that I have no idea what the bool represents and how to handle it. Not a big deal for internal code, but it just isn't good practice and C++ offers no good solutions like Rust has.

I also think "httpAuth" should be embedded in EntryParameters

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/browser/BrowserService.cpp (hunk 1 above)
Comment (varjolintu) [reply src/browser/BrowserService.cpp]: This is exactly what I was also thinking about. Using `QPair` is pretty ugly here. Maybe the extra parameter could be a little bit more clear.

Comment (droidmonkey) [reply src/browser/BrowserService.cpp]: especially if you move httpauth into EntryParameters

File: src/browser/BrowserAction.cpp [hunk 2]
```diff
@@ -240,14 +240,16 @@ QJsonObject BrowserAction::handleGetLogins(const QJsonObject& json, const QStrin
     entryParameters.dbid = id;
     entryParameters.hash = browserRequest.hash;
     entryParameters.siteUrl = siteUrl;
-    entryParameters.formUrl = formUrl;
```
Comment (droidmonkey) [inline src/browser/BrowserAction.cpp:243]: Did you intend to remove this line?

Comment (varjolintu) [reply src/browser/BrowserAction.cpp:243]: Nope. For some reason it was removed in the original PR. Setting it back.

File: src/browser/BrowserService.cpp [hunk 3]
```diff
@@ -383,24 +383,25 @@ BrowserService::findEntries(const EntryParameters& entryParameters, const String
...
-    QJsonArray result;
-    for (auto* entry : pwEntries) {
-        result.append(prepareEntry(entry));
+    QJsonArray entries;
+    for (auto* entry : allowedEntries) {
+        entries.append(prepareEntry(entry));
     }
 
-    return result;
+    *accepted = true;
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp]: Need to check for nullptr

File: src/browser/BrowserService.cpp [hunk 4]
```diff
@@ -315,36 +315,36 @@ QString BrowserService::getCurrentTotp(const QString& uuid)
 }
 
 QJsonArray
-BrowserService::findEntries(const EntryParameters& entryParameters, const StringPairList& keyList, const bool httpAuth)
+BrowserService::findEntries(const EntryParameters& entryParameters, const StringPairList& keyList, bool* accepted)
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp]: I recommend starting the function with a nullptr check and setting `accepted` to false. That way if the user sets it to true or is reusing a previous variable you don't get false positives.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

**Comment by droidmonkey** [comment]
Sorry did a more thorough review

File: src/browser/BrowserService.cpp (hunk 4 above)
Comment (varjolintu) [reply src/browser/BrowserService.cpp]: Btw, maybe we should cleanup other functions like that also? `KeePass2RandomStream::randomBytes()` as a good example. None of those are checking a null pointer.

**Comment by varjolintu** [comment]
> Sorry did a more thorough review

Good points! Thanks.

File: src/browser/BrowserService.cpp (hunk 4 above)
Comment (droidmonkey) [reply src/browser/BrowserService.cpp]: Yikes, we should. Nothing has exploded.. yet.. since those are internal functions. I don't take any chances with Browser since it is handling external data feeds and could be prime for injection attacks.

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
This will have to wait for 2.8.0 since it relies on the major browser refactor
