### PR TITLE
Show all url schemas in entry view

### LINKED ISSUE #1424: URL not shown in entry table if scheme is not http/https
A minor glitch. Created an entry in keepassxc for an ftp site:
```
Title: FreeBSD ftp
Username: ftpuser
Password: ******
URL: ftp://ftp.freebsd.org/
```
This item appears with an empty URL on the password listing. Anything but http/https shows a blank URL on the password listing.

## Expected Behavior
Strip spaces from urls when saved, support any protocol scheme

## Current Behavior
Only http/https URLs are shown, url is not stripped

## Steps to Reproduce (for bugs)
1. Start keepassxc, open password database
2. CTRL+N
3. Insert sample data above and save
4. Password listing shows the new item but url field is empty

Operating system: Ubuntu 17.10
Browser: Firefox 59.0b3
Proxy used: YES

## Debug Info
KeePassXC - Version 2.2.4
Revision: 83f1a53

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-31-generic

Enabled extensions:
- Auto-Type
- Browser Integration

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

Fixes #1424

Note: There is still bad behavior in the details view when you have a cmd:// url it will attempt to open a url that is embedded in the command. This is a holdover for icon downloading and can be corrected once icon downloading has the ability to specify arbitrary urls.

## How has this been tested?

Manually

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by TheZ3ro** [comment]
Do we want to display the full content of the URL field?

By removing the call to `resolveUrl` an url like `cmd://firefox https://keepassxc.org` will display the full command, with resolveUrl instead will return only `https://keepassxc.org`

The other PR use this second approach #1489

**Comment by droidmonkey** [comment]
I forgot about that other PR. That one is just a bandaid to the larger problem. We were erroneously filtering and modifying the URL for display (entry->displayUrl()). This one moves us closer to better behavior and cleaner interfaces. As I noted in the description, there still exists some ugly behavior that is dependent on the icon download code.

**Comment by tobiasboyd** [comment]
Will this show, for example, `ssh://some.example.com` along w/ http and https URLs?

**Comment by droidmonkey** [comment]
@tobiasboyd sorry for the delay, yes this PR displays SSH, HTTP, every url correctly.

File: src/gui/DatabaseWidget.cpp [hunk 1]
```diff
@@ -617,23 +617,19 @@ void DatabaseWidget::openUrl()
 
 void DatabaseWidget::openUrlForEntry(Entry* entry)
 {
-    QString urlString = entry->resolveMultiplePlaceholders(entry->url());
-    if (urlString.isEmpty()) {
-        return;
-    }
-
-    if (urlString.startsWith("cmd://")) {
+    if (entry->url().startsWith("cmd://")) {
```
Comment (TheZ3ro) [inline src/gui/DatabaseWidget.cpp]: We should call resolvePlaceholders before this check (like it was done before)

Example scenario:
The current entry has the url set to `{REF:A@I:<uuid>}` (a reference to another url field)
The other entry has the url field set to `cmd://firefox https://github.com`

In the current entry this check will be false (but should be true since the referred url does contains `cmd://`) and the url will be treated like a http url and the `github.com` link will be opened in the default browser (wrong behavior)

In the other entry the url will be correctly treated like a cmd and the execution alert below will be executed

**Comment by droidmonkey** [comment]
I moved this to v2.3.4 since it is a relatively minor change

File: src/gui/DatabaseWidget.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: Done!

**Comment by droidmonkey** [comment]
I reverted the removal and also fixed an issue with not validating user input when generating UUID's.

**Comment by droidmonkey** [comment]
ping @TheZ3ro
