### PR TITLE
Lock database on switching user in macOS

### LINKED ISSUE #2642: Database does not lock on switching user in macOS
## Summary
If you have KeePass configured to "Lock databases when session is locked or lid is closed" in KeePassXC Security Preferences checked, then I would also expect KeePassXC to lock databases when a "SwitchUser" occurs. That does not happen. Instead, the databases are left open, as if the user was still the active user.

I believe this is a security situation equivalent to locking a session or putting the device to sleep.

## Expected Behavior
When a database is open, and a user does a "SwitchUser" (e.g., /System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend ) I would expect KeePass to lock all open databases.

## Current Behavior
Currently, databases are left open.

## Possible Solution
KeePassXC should detect when a SwitchUser occurs, and if the option to lock the databases on a SwitchUser is enabled, then the databases should be locked.

This problem should be fixed as it leaves the database open when the user is in a condition approximately equivalent to being in Sleep mode.

## Steps to Reproduce
1. Open a database in KeePassXC
2. In a terminal window, enter /System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend
3. Login to a different user
4. Do stuff as that other user
5. Either logout of that other user or enter the SwitchUser command, above
6. Login to the original user with the open KeePass database(s) and observe they are still open

## Context
I see this as a security issue for which there should be a KeePassXC Security Preference to lock databases when switching users (this should be a separate option than the "session is locked" option, because there are circumstances where you would want to leave the databases open as a matter of convenience, albeit insecure)

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Using MacOS 2.3.4

MacOS 10.12.6 (16G1510)
MacBook Pro (Retina, 15-inch, Mid 2014)

Enabled extensions:
- EXTENSIONS -- None

### PR DESCRIPTION
**Pull request by varjolintu**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )
Locks all databases when switching user in macOS.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
Fixes #2642.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested manually with quick user switching.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/DatabaseTabWidget.cpp [hunk 1]
```diff
@@ -63,6 +63,10 @@ DatabaseTabWidget::DatabaseTabWidget(QWidget* parent)
     connect(autoType(), SIGNAL(autotypePerformed()), SLOT(relockPendingDatabase()));
     connect(autoType(), SIGNAL(autotypeRejected()), SLOT(relockPendingDatabase()));
     // clang-format on
+
+#ifdef Q_OS_MACOS
+    macUtils()->setDatabaseTabWidget(this);
```
Comment (droidmonkey) [inline src/gui/DatabaseTabWidget.cpp]: I do not like a util function holding onto a long-lived pointer. I would rather the MacUtils class have a signal that the DatabaseTabWidget can connect to the lock database slot. When the notification comes in, it emits the signal.

Comment (varjolintu) [reply src/gui/DatabaseTabWidget.cpp]: That's what I first tried but the linker has troubles finding the signal. I'm giving it a second try and see if I can solve it.

Comment (varjolintu) [reply src/gui/DatabaseTabWidget.cpp]: Got it. The `AppKit.h` header must be included in the makefile.
