### PR TITLE
Handle tilde with custom browser paths

### LINKED ISSUE #6542: Issues with Browser Integration-Advanced dialogue
## Overview
Five related issues - solving one may also solve one or more others with different implications

## Steps to Reproduce
1. Open Settings
2. Select Browser Integration
3. Open Advanced Tab
4. Check the Use Custom Browser Config Location Button

a) the hint given in the config location box shows
`~/.custom/config/Mozilla/native-messaging-hosts`
This is unlikely to be correct - more likely to be `~/.config/...`

b) entering a location starting with `~/` is not correctly parsed.
Instead of mapping `~/` to the current user home directory it *creates* a folder called `~` in the users home directory.
So the example in the hint creates a new folder `/home/roger/~/.custom/config/Mozilla/native-messaging-hosts`

In order for the correct location to be used the full path from root must be entered - this conflicts with the information given in the hint. eg on Ubuntu `/home/roger/.config/microsoft-edge-beta/NativeMessagingHosts/` works ok

c) The dropdown selector for Browser type (Firefox | Chromium) doesn't appear to do anything

d) The [ Browse... ] button starts from `/usr/bin` instead of a more likely location for the `native-messaging-hosts` folder
eg `~/.config` where "~" is the user home directory.

e) There is no indication that a custom location has already been set

## Expected Behavior
 a) The hint should either be `eg: ~/.config/[BrowserName]/native-messaging-hosts/` if `~` is going to be parsed correctly 
or give `eg /home/[Username]/.config/[BrowserName]/native-messaging-hosts/` as the hint if the "~" is not going to map to the user home directory

b) either `~/` in the Config location should be parsed or the hint shouldn't imply that it can be used. It should not simply create a new folder in the user home directory unless it is going to be used by keepassxc and the browser

c) If there are really only two possible Browser types then there should be some way of showing what is different between them. Different browsers of by Chromium will use their own separate config folders and it should be possible to have separate custom config locations for each separate browser of type Chromium

d) the browse button could more usefully start from `~/.config` (where `~` actually is the user home directory!)

e) it would be helpful if custom locations have already been set, then these could be listed under the location entry box together with the browser name.

## Actual Behaviour
See above

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-72-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: /Linux/ (ubuntu 20.04.2)
Desktop Env: Gnome
Windowing System: X11/

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Handle `~/` as a home directory with Custom Proxy and Custom Browser path. The full path is still stored to the configuration, so this only affects to the UI side.

Fixes https://github.com/keepassxreboot/keepassxc/issues/6542.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/browser/BrowserSettings.cpp [hunk 1]
```diff
@@ -514,3 +517,13 @@ void BrowserSettings::updateBinaryPaths()
...
+
+QString BrowserSettings::replaceHomePath(QString location)
+{
+    auto homePath = QDir::homePath();
+    if (location.startsWith(homePath)) {
+        location.replace(homePath, "~");
+    }
+
+    return location;
+}
```
Comment (droidmonkey) [inline src/browser/BrowserSettings.cpp]: You are missing the ~ to absolute dir code branch. The ~ path is stored in config and used in the browser code. This is the opposite of your description. This should also only occur on Linux systems.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/browser/BrowserSettings.cpp (hunk 1 above)
Comment (varjolintu) [reply src/browser/BrowserSettings.cpp]: Hmm? Gotta double check this one.

Comment (varjolintu) [reply src/browser/BrowserSettings.cpp]: Fixed the brain fart.

**Review by droidmonkey — APPROVED** [review]
