### PR TITLE
Fix crash when using Windows Hello in a Remote Desktop session

### LINKED ISSUE #7890: Windows hello crash when on remote desktop
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Login to keepassXC 
2. Enter hello pin
3. Lock the database so unlock shows
4. Connect to device with remote desktop and press unlock 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
For it to either ask for a password again or say it's invalid. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Program just closing. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - v2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

### PR DESCRIPTION
**Pull request by Gibstick**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

Summary: This change fixes #7890 by catching a previously uncaught exception, and adds fallback behaviour when quick-unlock fails.

Windows Hello can suddenly become unavailable with a permission denied exception. According to https://github.com/keepassxreboot/keepassxc/issues/7890#issuecomment-1099221593:

1. Unlock a database with Windows Hello enabled
2. Lock the database
3. Connect to the machine in a remote desktop session
4. Attempt to use Windows Hello to unlock the database by clicking the big button with the fingerprint icon

Note that this might not be the only way to trigger this. For example, one could disable Windows Hello and probably end up with the same crash.

So far I've been calling this "Windows Hello", but I'm not too familiar with the Windows APIs, so I'm not sure if `KeyCredentialManager.RequestCreateAsync Method` is technically Windows Hello. In any case, it comes up as a crash in the Windows Hello flow. It crashes because of an uncaught exception being returned, and it seems the error is by design because of extra restrictions Microsoft wanted to place on remote desktop sessions.

In the second commit, I made a quick attempt to improve the overall experience by falling back to the other unlock methods if quick unlock fails for any reason. This is a bigger change than just preventing the crash, so I'm open to feedback, including simply removing the second commit from this PR if it's contentious. This fallback behaviour I implemented was suggested in the original issue report and I think it's sensible.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

image
Clicking "Unlock Database" in a remote desktop session used to crash, now it doesn't.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

I tested this by using the reproduction steps in the linked issue #7890, using a real RDP session. I first reliably reproduced the crash on an unmodified build, and then verified that my fix stopped the crashes.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Dang I didn't put enough in the try/catch block. BTW this behavior is undocumented in the winrt documentation.

**Comment by Gibstick** [comment]
Yeah no worries, I couldn't find anything about it either. 

I neglected to consider all platforms in `buildDatabaseKey` and I'll be pushing up a fix for that soon.

File: src/gui/DatabaseOpenWidget.cpp [hunk 1]
```diff
@@ -251,6 +251,7 @@ void DatabaseOpenWidget::openDatabase()
     const auto databaseKey = buildDatabaseKey();
     if (!databaseKey) {
         setUserInteractionLock(false);
+        resetQuickUnlock();
```
Comment (droidmonkey) [inline src/gui/DatabaseOpenWidget.cpp]: I believe this will even reset quick unlock when you merely canceled the interaction. To me that is not a desired behavior. We should capture when an explicit error occurs with quick unlock then reset on that case alone.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/gui/DatabaseOpenWidget.cpp (hunk 1 above)
Comment (Gibstick) [reply src/gui/DatabaseOpenWidget.cpp]: Yes, that's right. As a shortcut for testing I've been clicking cancel in the Windows Hello dialog, and indeed it will reset in that case. I agree this isn't the best and I'll try to detect errors here, or try to detect cancellation, or something.

Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: I personally hate this widget / class. It was on my list for a complete code overhaul.

Comment (Gibstick) [reply src/gui/DatabaseOpenWidget.cpp]: I pushed a commit adding a bunch of plumbing for detecting an explicit cancellation, and not resetting in that case. However, my changes might have done more harm than good, especially since I'm only piling onto tech debt. I'm totally fine with just backing out all commits in this PR except for the first.

**Comment by droidmonkey** [comment]
You seem to have taken a very complex route to solve the problem cancel vs error problem. It would have been easier to either emit a "canceled()" signal or an error signal. In fact our current way of handling errors is incorrect and not thread safe. If another thread were to start a Windows Hello interaction then the error may get swallowed up.

**Comment by Gibstick** [comment]
Good to know that signals exist, I'll redo it 😅

**Comment by deluxghost** [comment]
May I ask, what will happen after unlocking by fallback method in remote session? Do I still need to reopen keepassxc to re-enable fingerprint unlock in local session?

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
I figured out an elegant solution and also used the nice error messages that were going to waste!
