### PR TITLE
SSH Agent: Update available attachments immediately

### LINKED ISSUE #1668: SSH Agent: Attachment list only updates after saving the entry
## Expected Behavior
When adding/removing attachments, those updates should be reflected in the list of attachments available for SSH Agent.

## Current Behavior
The updates are not visible until clicking saving (hitting OK or Apply).

## Possible Solution
Update as soon as attachments are added/removed.

## Steps to Reproduce (for bugs)
1. Create entry with SSH Agent enabled
2. Add attachment
3. Check Attachment drop-down list: It's still empty.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17112

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### PR DESCRIPTION
**Pull request by luzat**
## Description
The list of available attachments for SSH agent is now updated
immediately when adding or removing file attachments.

## Motivation and context
When adding or removing attachments, the list of available attachments was previously only updated after hitting `Apply` or `OK`.

Closes #1668.

## How has this been tested?
Built on Linux, ran tests and tried adding and removing files with previously empty and non-empty lists. Also checked if removing a selected file would lead to an error.

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Please rebase onto ```release/2.3.2```

**Comment by luzat** [comment]
Not sure if I am doing this right: rebasing from `develop` onto `release/2.3.x` introduces all these other commits to the PR. Anything that I should change with regards to git usage?

**Comment by hifi** [comment]
Use the edit button next to the PR title to change the base branch. It's under the title in edit mode.

**Comment by droidmonkey** [comment]
The command line version is: ```git rebase release/2.3.2``` when you have your fix-agent-attachments checked out.

**Comment by luzat** [comment]
Rebasing (and pushing) alone - which is what I did before - did not seem to update the state of where I want it to be merged here. `rebase` **and** changing the base branch helped. This makes sense, but I wasn't aware of the option to change the base branch here previously.

File: src/gui/entry/EditEntryWidget.cpp [hunk 1]
```diff
@@ -281,6 +281,8 @@ void EditEntryWidget::setupSSHAgent()
     connect(m_sshAgentUi->decryptButton, SIGNAL(clicked()), SLOT(decryptPrivateKey()));
     connect(m_sshAgentUi->copyToClipboardButton, SIGNAL(clicked()), SLOT(copyPublicKey()));
 
+    connect(m_advancedUi->attachmentsWidget->entryAttachments(), SIGNAL(modified()), SLOT(updateAttachments()));
```
Comment (yan12125) [inline src/gui/entry/EditEntryWidget.cpp]: updateAttachments() should be updateSSHAgentAttachments()? I got the following error on the latest git:
```
QObject::connect: No such slot EditEntryWidget::updateAttachments()
QObject::connect:  (receiver name: 'EditWidget')
QObject::connect: No such slot EditEntryWidget::updateAttachments()
QObject::connect:  (receiver name: 'EditWidget')
```

Comment (luzat) [reply src/gui/entry/EditEntryWidget.cpp]: Confirmed and fixed. Must have forgotten to add the final version to the commit. Now works and does not give the error message and updates as expected.
