### PR TITLE
Enhanced search ui keypress actions

### LINKED ISSUE #163: Icons gone when compiling in Release mode
## Expected Behavior
All icons should be shown independently of compile mode.

## Current Behavior
When compiling KeePassXC in Release mode, all icons that are not standard system icons are gone.

## Possible Solution
Make sure `FilePath::m_dataPath` is correctly set in Release mode, otherwise icons are expected under /icons

## Steps to Reproduce (for bugs)
Compile KeePassX in release mode and start the application.

## Your Environment

* KeePassXC version/commit used: 9dadafe20a2a9c7878b4505c1aa4097c87b955f4
* Qt version (e.g. Qt 5.3): 5.7.1
* Compiler (e.g. Clang++3.6.0): Clang++ 3.9.1
* Operating System and version: Arch Linux

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

* Pressing down arrow will always focus on entry view
* Pressing enter opens currently selected entry
* Pressing CTRL+F focuses and selects search text

Also fixes #163 

Originally inspired by @knu

## Motivation and Context
While the PR #67 was a great improvement, my "Control+F and type a word" workflow had stopped working since then.
Most popular browsers and editors do this so you can always do a fresh search every time you invoke the "Find" action, so I think KeePassXC should, too.

## How Has This Been Tested?
The new behavior is covered by the new assertions added to the GUI test.

## Types of changes
- :negative_squared_cross_mark: Bug fix (non-breaking change which fixes an issue)
- :white_check_mark: New feature (non-breaking change which adds functionality)
- :negative_squared_cross_mark: Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- :white_check_mark: I have read the **CONTRIBUTING** document. [REQUIRED]
- :white_check_mark: My code follows the code style of this project. [REQUIRED]
- :white_check_mark: All new and existing tests passed. [REQUIRED]
- :negative_squared_cross_mark: My change requires a change to the documentation.
- :negative_squared_cross_mark: I have updated the documentation accordingly.
- :white_check_mark: I have added tests to cover my changes.

### CODE REVIEW

File: src/gui/SearchWidget.cpp [hunk 1]
```diff
@@ -76,14 +75,9 @@ bool SearchWidget::eventFilter(QObject *obj, QEvent *event)
...
         else if (keyEvent->matches(QKeySequence::MoveToNextLine)) {
-            // If Down is pressed at EOL in the search edit, move
-            // the focus to the entry view.
-            QLineEdit* searchEdit = m_ui->searchEdit;
-            if (!searchEdit->hasSelectedText() &&
-                searchEdit->cursorPosition() == searchEdit->text().length()) {
-                emit downPressed();
-                return true;
-            }
+            // If Down is pressed move the focus to the entry view.
```
Comment (knu) [inline src/gui/SearchWidget.cpp]: Down is the key for moving the cursor to the EOL on macOS, so I'm afraid rebinding the key to another function may cause user inconvenience.

Comment (droidmonkey) [inline src/gui/SearchWidget.cpp]: Isn't that what "END" is for?? I am not a Mac user and did not know this...

Perhaps this can be removed as a feature when compiled on Mac.

Comment (knu) [inline src/gui/SearchWidget.cpp]: There's no home/end keys on laptop (MacBook) keyboards, so while Control+A/E, Command+Left/Right combos work for that purpose I believe many users are used to just use Up/Down to move to BOL/EOL because they don't require modifier keys.

Comment (knu) [inline src/gui/SearchWidget.cpp]: On macOS, the cursor is considered to be positioned at EOL when the whole text is selected, so simply deleting the first condition (59962dd) would do the job.

Comment (TheZ3ro) [inline src/gui/SearchWidget.cpp]: On most of applications on GNU/Linux the Up/Down is used to going at EOL. On QLineEdit this behaviour isn't followed by default so on GNU/Linux you have to use Ctrl+Right.

I think pressing Down in the middle of the text is not meant to be used as "set focus on entryView" but instead for placing pointer to EOL. 
When pointer is at EOL we can change the focus to entryView

Comment (droidmonkey) [inline src/gui/SearchWidget.cpp]: Fair enough, easy to implement

**Comment by knu** [comment]
Just for the record, as I [commented](https://github.com/keepassxreboot/keepassxc/pull/139#issuecomment-270555173) in #139, I'd expect that a search text would be selected also when focused by Shift+Tab/Tab and that's why I created a SearchEdit widget.  I won't insist strongly, though.  I just wish QLineEdit had the select-on-focus functionality built in.

**Comment by droidmonkey** [comment]
I think that behavior is still possible without a custom widget. I will investigate.

**Comment by knu** [comment]
Thanks for your effort.

I have one more thing to improve the UI.  Can we get the "Delete" button back that used to be there in the search text edit?  The search bar now always persists but there is no way to dismiss a search with one click or even two.

**Comment by droidmonkey** [comment]
@knu when I use tab or shift+tab to change focus, the EditText widget correctly selects all the text. I am not sure what is not working for you? Can you better describe the issue?

**Comment by knu** [comment]
@droidmonkey True, I've confirmed myself that the auto-selection works just as excepted with this current implementation.  Thanks!

**Comment by phoerious** [comment]
I didn't know that Ctrl+F was broken somehow. It always worked fine for me (that's why I personally don't really need the search bar to be always visible).
The changes look fine to me, but the GUI tests have to be fixed.

**Comment by droidmonkey** [comment]
I've implemented all the fixes to the searchui (see screenshot). Just need to figure out why Travis is barfing and this is ready for merge.

keepassxc_search_ui

**Comment by phoerious** [comment]
Tests look fine for me now, not sure why Travis is still whining.
However the "clear text" button is super pixelated.

screenshot_20170115_023138

**Comment by phoerious** [comment]
Ah, I see. The second time I ran the test, I got this:

```
FAIL!  : TestGui::testSearch() QTestLib: This test case check ("(((searchTextEdit->hasFocus())))") failed because the requested timeout (5000 ms) was too short, 10150 ms would have been sufficient this time.
   Loc: [/home/janek/keepassxc/tests/gui/TestGui.cpp(398)]
```

Looks totally random to me.

**Comment by phoerious** [comment]
I did some research in the meantime. The pixelated clear button is a bug in Qt which hasn't been fixed in over two years: https://bugreports.qt.io/browse/QTBUG-39517

File: src/core/FilePath.cpp [hunk 2]
```diff
@@ -211,6 +211,9 @@ FilePath::FilePath()
     else if (testSetDir(appDirPath + "/share")) {
     }
 #endif
+    // Last ditch test when running in the build directory (mainly for travis tests)
+    else if (testSetDir(QString(KEEPASSX_SOURCE_DIR) + "/share")) {
```
Comment (TheZ3ro) [inline src/core/FilePath.cpp]: Why adding this duplicate of QT_DEBUG?
On Travis if you are building with the Release flag you need first to run `make install` to install icons and assets and then run tests/guitest. (I've reported this some commit ago but went unnoticed)
This is just a "bad" workaround to make things works.

Comment (phoerious) [inline src/core/FilePath.cpp]: Well, in Debug mode, this is always evaluated as the first option. In Release mode, this path only exists in development environments, though. Checking other paths first is not a bad idea since it saves quite some file checks.

Comment (TheZ3ro) [inline src/core/FilePath.cpp]: If you have KeePassXC already (correctly) installed on your system you don't need to re-run `make install`. Travis on the other hand make a new environment for every run so you have to add a `make install` for building the Release tests.

Alternatively you can direcly remove the QT_DEBUG part and leave the last elseif part so you don't duplicate things (but this doesn't even make sense in the first place as a workaround if things are done in the right way)

Comment (phoerious) [inline src/core/FilePath.cpp]: No, it doesn't work that way. KEEPASSX_PREFIX_DIR isn't correctly set and I prefer to keep my stable KeePassXC and my development KeePassXC separate. Sure, I could make install my dev version to some other place, but then I also have to remember to do it every time something changes in the data dir. Things like that can cost you hours of your time when you can't find out, why something is not working the way it is supposed to. ;-)

Removing th QT_DEBUG stuff from the beginning may work, but if you have a different version of KeePassXC installed in KEEPASSX_PREFIX_DIR this might cause conflicts. I would prefer to always check KEEPASSX_SOURCE_DIR first for Debug builds.

Comment (TheZ3ro) [inline src/core/FilePath.cpp]: Actually, Travis tests are meant to run on Debug build (before this commit https://github.com/keepassxreboot/keepassxc/commit/dee331d52d5df5b8b282eb8cfa7cbbc39ea77a62 they were) and the Release build should be used only by end users that want to install it or when building a release.
So the problem with icons and prefix shouldn't be there in the first place.

If you want to have multiple workspace for various dev/stable KeePassXC version you can do the following:
When compiling with **Debug** option: no problem, will load resource from SOURCE folder.
When compiling with **Release** option: install keepassxc to a destination folder with `make install DESTDIR=./dist` and execute that executable, not the one from `./build/src`

Those are my 2 cents, leaving this here won't hurt anyone but really it's useless.

Comment (droidmonkey) [inline src/core/FilePath.cpp]: Wow didnt even remember that i flopped it from debug to release! In either case both builds are now tested in travis which is good because they are built differently.
