### PR TITLE
Various fixes to database settings

### LINKED ISSUE #10558: KDF parameters missing units in Encryption Settings
## Overview
In Database Settings -> Security -> Encryption Settings, the units for memory usage (MiB) and parallelism (threads) only show after I disable and re-enable Advanced settings. Also, both default to 1 when units are not shown (compared to 64 MiB and 4 threads with units shown). My database currently uses AES-KDF, which I wanted to change to Argon2id.

## Steps to Reproduce
Version A:
1. have Advanced Settings on
2. open database
3. Database -> Database Security -> Encryption Settings
4. change KDF from AES-KDF to Argon2id
5. units don't show
6. disable and re-enable Advanced Settings
7. units show

Version B:
1. have Advanced Settings off
2. open database
3. Database -> Database Security -> Encryption Settings
4. enable Advanced Settings
5. change KDF from AES-KDF to Argon2id
6. units don't show
7. disable and re-enable Advanced Settings
8. units show

## Expected Behavior
I would expect to see memory usage "64 MiB" and parallelism "4 threads" (or some other values, but including units) every time, including steps 5/6 above.

## Actual Behavior
I see memory usage "1" and parallelism "1". Units are missing and the suggested values are the minimum possible, not some (I guess) recommended values.

## Context
The database currently uses AES-KDF, which I want to change. I'm using KeePassXC from the Arch Linux [package](https://archlinux.org/packages/extra/x86_64/keepassxc/).

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.13
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.6.23-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: i3
Windowing System: X11

### LINKED ISSUE #10723: "Weak password" warning incorrectly shown after adding (or removing) a key file from database
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I set up a new database file for testing purposes initially without using a key file. My master password was generated with KeePassXC using 10 random words from the default word list to ensure very strong entropy. Later I decide to create and add a key file to the database, and when I went to save changes and click "OK" at the bottom I get an incorrect prompt saying my master password is too weak, which I know is false.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. From menu at the top of the application: go to Database > Database Security
2. Add a key file if one does not already exist and save changes, Removing a key file and saving changes also triggers this bug.

Additional information that may help in reproducing:
- Encryption Algorithm was set to ChaCha20 during database creation phase, all other settings were left at default values.
- Master password was generated from within KeePassXC's default word list, the master password only contains words, no symbols (besides spaces separating the words), no numbers. 10 words in length.
- The key file was generated using KeePassXC.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
If the master password is known to be -without a doubt- very strong then there is not supposed to be a "weak password" prompt when saving changes after adding or removing a key file from the database.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After adding or removing a key file from the database and saving changes, a prompt incorrectly shows up saying my password is weak.

## Context
[NOTE]: # ( Give us any additional information you may have. )
KeePassXC_OqnP0GPcif

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Home - (23H2, OS Build 22631.3527)

### PR DESCRIPTION
**Pull request by droidmonkey**
Changes are split across 3 commits intentionally.

* Use SHA256 hash of the file path of the database to generate a UUID when using the KDBX3 format. This restores the original behavior of using the file path as the quick unlock lookup key.

* Fixes https://github.com/keepassxreboot/keepassxc/issues/10558
* Fixes https://github.com/keepassxreboot/keepassxc/issues/10723 - only display password strength warning when actively editing the password
* Also improve behavior of minimum quality warning
* Improve behavior and handling of password changes with the database settings dialog
* Prevents loss of newly entered password when toggling between elements in the settings page
* On error, switch to tab that prevents saving database settings for easier correction

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested extensively manually and added unit tests

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp [hunk 1]
```diff
@@ -177,31 +177,32 @@ bool DatabaseSettingsWidgetDatabaseKey::save()
...
-        static_cast<PasswordHealth::Quality>(config()->get(Config::Security_DatabasePasswordMinimumQuality).toInt());
-    if (!m_passwordEditWidget->isEmpty() && m_passwordEditWidget->getPasswordQuality() < minQuality) {
-        MessageBox::critical(this,
-                             tr("Weak password"),
-                             tr("You must enter a stronger password to protect your database."),
-                             MessageBox::Ok,
-                             MessageBox::Ok);
-        return false;
+        // Show warning if database password is weak or poor
+        if (m_passwordEditWidget->getPasswordQuality() < PasswordHealth::Quality::Good) {
```
Comment (phoerious) [inline src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp:195]: I think you need to take into account whether this is a normal password or a passphrase.

File: src/gui/databasekey/PasswordEditWidget.cpp [hunk 2]
```diff
@@ -103,16 +105,6 @@ void PasswordEditWidget::initComponent()
...
 
-void PasswordEditWidget::hideEvent(QHideEvent* event)
-{
-    if (!isVisible() && m_compUi->enterPasswordEdit) {
-        m_compUi->enterPasswordEdit->setText("");
-        m_compUi->repeatPasswordEdit->setText("");
-    }
-
-    QWidget::hideEvent(event);
-}
```
Comment (phoerious) [inline src/gui/databasekey/PasswordEditWidget.cpp:114]: This was added on purpose in cb2900f5a98b3774b9dfaa4c6ead4f1a3b18c6fc and it also triggers on events such as window minimisation (at least tray minimisation). I'm unsure whether we should actually remove this. We should at least fix the password clear timer.

File: src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp:195]: Hmmmm, that's an interesting point, but I'm not sure how to proceed

File: src/gui/databasekey/PasswordEditWidget.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/gui/databasekey/PasswordEditWidget.cpp:114]: In my testing, this caused data loss when switching between the tabs on the security page. I decided to compromise by doing the clearing only when the user explicitly cancels the action to change the password. Remember, this isn't the actual password "yet".

Comment (droidmonkey) [reply src/gui/databasekey/PasswordEditWidget.cpp:114]: I made some improvements to the clearing process when you "cancel" the database settings. Might need to do the same on save too. The workflow in the code for all this is very convoluted.

File: src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp:195]: Going to table that for now, technically a long passphrase rates as excellent:

image

Three words rates weak, which I would expect:

image

**Comment by droidmonkey** [comment]
Ready for another review @phoerious

**Review by phoerious — APPROVED** [review]
