### PR TITLE
Fix sorting of advanced attribute list

### LINKED ISSUE #6175: Sort advanced attribute list using locale aware sort
## Overview
Additional Attributes are sorted by string ascii values, resulting in 10 coming before 2.

This results in strange behavior like the KP2A URL fields in the Browser integration tab being ordered oddly. When adding a 10th Additional URL, the new line will appear after the 1st entry and before the 2nd, not at the end of the list as you'd expect.

Example of the new KP2A_URL_# fields sorted badly

## Steps to Reproduce
1. Create 10 "Additional URLs" on an entry.
2. Note that the 10th is added before the 2nd entry in the list.
3. Flip to the Advanced tab and see why.

## Expected Behavior
10 should appear at the end of the list.

## Actual Behavior
10 appears after 1 and before 2.

## Context
Note that this also happens in Windows and should happen on every platform.

KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: Flatpak

Qt 5.15.2
Debugging mode is disabled.

Operating system: KDE Flatpak runtime (System: Ubuntu 20.04.2 LTS)
CPU architecture: x86_64
Kernel: linux 5.8.0-43-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.8.7

Desktop Env: Gnome
Windowing System: X11

### PR DESCRIPTION
**Pull request by marco-langer**
Sort advanced attribute list using locale aware sort.

Fixes #6175

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
1. Add an entry to a database
2. Go to "Edit entry" -> "Advanced"
3. Add some additional attributes via the "Add" button. E.g.: "Test1", "Test12", "Test2"
4. The additional attributes should be sorted now as "Test1", "Test2", "Test12"

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/entry/EntryAttributesModel.cpp [hunk 1]
```diff
@@ -19,6 +19,18 @@
 
 #include "core/EntryAttributes.h"
 
+#include <QCollator>
+
+namespace
+{
+    void sortLocaleAware(QList<QString>& strings)
+    {
+        QCollator collator;
```
Comment (droidmonkey) [inline src/gui/entry/EntryAttributesModel.cpp]: Need to instantiste QCollator once, it's a very expensive (time wise) class to create

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/gui/entry/EntryAttributesModel.cpp (hunk 1 above)
Comment (marco-langer) [reply src/gui/entry/EntryAttributesModel.cpp]: Thanks for the feedback!

Considering that this PR is from 2023 and I haven't worked on it since then: Do you think it is worth it to continue with this PR? I remember that I opened the PR, however some CI pipeline failed and I put it back to draft mode. Haven't had a look into it since then.

I could try to rebase the branch onto dev and implement your feedback if you think the PR is worth it, otherwise I could withdraw it given the long inactivity time.

Comment (droidmonkey) [reply src/gui/entry/EntryAttributesModel.cpp]: I can handle the rebase.

**Review by droidmonkey — APPROVED** [review]
