### PR TITLE
Fix checking subdomains

### LINKED ISSUE #2291: URL matching seems to be partially broken since v2.3.4
Starting with version 2.3.4, URL matching fails in several cases where it was working fine for years.

Examples:
1. Entry with address 'aol.com' now doesn't match 'https://www.aol.com' in the browser.
2. Entry with address 'http://aol.com' now doesn't match 'https://www.aol.com' in the browser (URL matching is disabled in settings.

I would like to see the previous behavior restored, where:
1. URL scheme in the entry was optional
2. Subdomains were omittable and matching was based on shortest match

For years, I was storing addresses without URL scheme and subdomains.
Entry with address: "aol.com" would match addresses as:
1. http://www.aol.com
2. https://auth-1234.aol.com/user_1234.cgi
3. https://auth-1234.www.aol.com/cgi/user.cgi

The issue manifests itself using "Browser Integration" plugin connected to Chrome with KeePassXC-Browser v1.2.0.

Enviroment details:
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.5 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-34-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### PR DESCRIPTION
**Pull request by varjolintu**
Fix checking subdomains when retrieving credentials.

## Description
After title matching was removed with release 2.3.4 the subdomain handling broke. Base domain of the URL will be used for EntrySearcher instead of hostname.

With this fix:
- Entry URL `https://google.com`: matches `https://*.google.com`, does not match `http://*.google.com`
- Entry URL `google.com` with scheme matching off: matches `*://*.google.com`
- Entry URL `https://accounts.google.com`: matches `https://accounts.google.com`, does not match with `https://*.google.com`
- Entry URL `accounts.google.com` with scheme matching off: matches `*://accounts.google.com`

## Motivation and context
Fixes https://github.com/keepassxreboot/keepassxc-browser/issues/283.
Fixes #2291
~~~Depends on https://github.com/keepassxreboot/keepassxc/pull/2232.~~~

## How has this been tested?
Manually, and with local tests.

## Types of changes
<!--- What types of changes does your code introduce? -->
<!--- Please remove all lines which don't apply. -->
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
<!--- Please go over all the following points. -->
<!--- Again, remove any lines which don't apply. -->
<!--- Pull Requests that don't fulfill all [REQUIRED] requisites are likely -->
<!--- to be sent back to you for correction or will be rejected.  -->
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -779,6 +781,20 @@ bool BrowserService::removeFirstDomain(QString& hostname)
...
+{
+    QUrl qurl = QUrl::fromUserInput(url);
+    QString hostname = qurl.host();
+
+    if (hostname.isEmpty() || hostname.indexOf(qurl.topLevelDomain()) < 0) {
+        return {};
+    }
+
+    hostname.chop(qurl.topLevelDomain().length());
+    return hostname.split('.').last().append(qurl.topLevelDomain());
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp]: These two lines need to be broken up and comments added. Took me a while to figure out what was going on.

File: src/browser/BrowserService.cpp [hunk 2]
```diff
@@ -779,6 +781,20 @@ bool BrowserService::removeFirstDomain(QString& hostname)
     return false;
 }
 
+// Gets the base domain of URL, e.g. https://another.example.co.uk -> example.co.uk
+QString BrowserService::baseDomain(const QString& url) const
+{
+    QUrl qurl = QUrl::fromUserInput(url);
+    QString hostname = qurl.host();
+
+    if (hostname.isEmpty() || hostname.indexOf(qurl.topLevelDomain()) < 0) {
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp]: Recommend changing the second term to ```!hostname.contains(qurl.topLevelDomain())``` for clarity.

File: src/browser/BrowserService.cpp [hunk 3]
```diff
@@ -388,14 +388,16 @@ QList<Entry*> BrowserService::searchEntries(Database* db, const QString& hostnam
         return entries;
     }
 
-    for (Entry* entry : EntrySearcher().search(hostname, rootGroup, Qt::CaseInsensitive)) {
+    QString base = baseDomain(hostname);
+    for (Entry* entry : EntrySearcher().search(base, rootGroup, Qt::CaseInsensitive)) {
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp]: Just replace "base" with "baseDomain(hostname)", no need for a temp variable with a questionable name.

**Comment by varjolintu** [comment]
Issues fixed & PR rebased.

**Comment by pillarsdotnet** [comment]
After being annoyed at the bug for a couple weeks, I found this PR, recompiled my copy, and ran it for a couple days. Got two console errors; the first popped up immediately and the second some time later:

<code>
bobvin@T560:~/github/keepassxc/build$ keepassxc
QObject::startTimer: Timers cannot have negative intervals
"Maximum depth of replacement has been reached. Entry uuid: {ae9f0413-cf2e-aa93-ac9c-76cb8b9c5986}"
</code>

**Comment by varjolintu** [comment]
@pillarsdotnet Those errors are not related to this PR. The first one I have seen multiple times, the second is caused by placeholder resolver.

File: src/browser/BrowserService.cpp [hunk 4]
```diff
@@ -780,6 +780,25 @@ bool BrowserService::removeFirstDomain(QString& hostname)
     return false;
 }
 
+// Gets the base domain of URL, e.g. https://another.example.co.uk -> example.co.uk
```
Comment (phoerious) [inline src/browser/BrowserService.cpp]: Nitpick: why is this not a proper docblock?

**Comment by pahhur** [comment]
Ok, I place my question and thoughts about the non-working matching algorithm here,
meaning those that maybe haven't been discussed yet.

---

Consider, you have a special link, the user wants to open.
Let's say, the link is **xyz.de/login**

xyz is an international company with locale support on their web sites.

If you call **xyz.de/login**, you get the german site, no matter if you are in Germany, or elsewhere.
The address is remapped by them to **de.xyz.com/login**. That's why the typical german user would specify **xyz.de/login** in the URL field (Yes he could specify de.xyz.com/login, too, but that is not the typical use case. The non-technical user even might not understand that the URL for him has been changed in the background. Furthermore, the webmaster of site xyz might be using a different nomen clatura for that in the next month, and instead of de.xyz.com, then germany.xyz.com would be used, while the original link of xyz.de/login would still work)

If you call **xyz.com/login**, you get the international site or a local site in the language of the country where you are. The link is remapped to something like **www.xyz.com/login**, **www.xyz.co.uk/login", or **no.xyz.com/login** (Norway)

Thus, if the (german) keepassxc user wants to open the correct site for him, he has to specify the **.de** link. However, for the credentials to be provided correctly by keepassxc, the field must have a value of **xyz.com** right now.

Also consider that the user is not always able to change any language settings when in an internet cafe in a foreign country, or might be using a VPN.

Examples of sites with such a behaviour are linkedin, or xing.

Maybe it would be a good idea to separate the field in two. One field for the URL to open, and one optional field for the mapper, in case the mapping cannot be derived from the first URL.

---
I dont know if this point is a good idea

    * Entry URL `https://accounts.google.com`: matches `https://accounts.google.com`, does not match with `https://*.google.com`

for the websites sometimes load balance their requests. Thus a request for

accounts.xyz.com

would sometimes be changed by them to

accounts1.xyz.com
accounts2.xyz.com
accounts3.xyz.com
accounts5.xyz.com
accounts99.xyz.com

If you apply your rule (saying *.xyz.com will not match), then there is no chance for the user to specify a URL that is matching at all.

**Comment by droidmonkey** [comment]
This is what cloned entries are for. You can clone the original one and change the URL to a redirect page or alternative login domain. The latter example you provided is increasingly rare due to modern load balancing being handled by smart dns routing instead of multiple sub domains.
