### PR TITLE
Set correct case for DB file path on open (fix for #7139)

### LINKED ISSUE #7139: Database filename case shouldn't be changed on save (after opening it from the command line)
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
This is weird issue, but I think it could potentially be quite nasty, e.g. when syncing the database file between case sensitive and insensitive systems. What happens is that if you open a database file from the command line, KeePassXC will remember the filename case as it was input in the command. Then, when you save changes to the database, the original case will be overwritten with the other one. I don't think this is intended, is it?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new database called `TEST.kdbx`.
2. Open the newly created database using the command line, but using a different case, e.g. `keepassxc test.kdbx`. Obviously, this will only work in case insensitive systems like Windows.
3. Make a change to the database, then save it.
4. The database filename has now been renamed from `TEST.kdbx` to `test.kdbx`.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The database file case should remain as it was in the original file, i.e. it shouldn't follow the one used in the command line when starting KeePassXC.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The database file case changes to the one used in the command line argument.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: N/A
Windowing System: N/A

### PR DESCRIPTION
**Pull request by mckeema**
Fixes #7139. On database open, if OS is Windows, find correct case for database filename by searching through database parent folder. If found, overwrite internal database file path with corrected file path so that, on database modification, database is not saved under a new name. For example, if your database is DB.kdbx and you open db.kdbx on the Windows command line, then add a new entry and save your database, DB.kdbx is maintained as the filename. Previously, DB.kdbx would be overwritten with db.kdbx on save.

## Screenshots
Old behavior:

https://user-images.githubusercontent.com/40369019/145335172-a7daf37d-e870-4bc1-8349-bbd9870056ab.mp4

New behavior:

https://user-images.githubusercontent.com/40369019/145335185-67632cff-53da-4b5c-abaa-3f2ab5c91652.mp4

## Testing strategy
I tested the change manually, as you can see in the video included above. I also ran `make test`.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/core/Database.cpp [hunk 1]
```diff
@@ -32,6 +32,8 @@
 #include <QTemporaryFile>
 #include <QTimer>
 
+#include <iostream>
```
Comment (droidmonkey) [inline src/core/Database.cpp]: What is this for?

Comment (mckeema) [reply src/core/Database.cpp]: My bad. That was for testing, it shouldn't be there. I will remove it.

**Comment by droidmonkey** [comment]
Does QFileInfo(path).absoluteFilePath() return the correct case?

**Comment by mckeema** [comment]
> Does QFileInfo(path).absoluteFilePath() return the correct case?

~~It does. I'm not sure why that didn't occur to me. I'll make that change in a bit.~~

Scratch that, I manually closed the database and tried again. For a database called TEST.kdbx opened as test.kdbx, QFileInfo(filePath).absoluteFilePath() returns test.kdbx. It must've just reopened my last used database on the first try.

**Comment by mckeema** [comment]
~~Regardless, the Windows build is still failing it seems. It built fine on my end and passed the local tests, so I'm not yet sure why that's happening.~~

Fixed. Just had to format the code.

File: src/core/Database.cpp [hunk 2]
```diff
@@ -154,6 +154,20 @@ bool Database::open(const QString& filePath, QSharedPointer<const CompositeKey>
     setFilePath(filePath);
     dbFile.close();
 
+#ifdef Q_OS_WIN
+    // Get correct case for Windows filename (fixes #7139)
+    QFileInfo fileInfo(filePath);
+    QDir dir = fileInfo.dir();
+    QFileInfoList files = dir.entryInfoList();
```
Comment (benjarobin) [inline src/core/Database.cpp]: This could be simplified a bit (since by default `entryList()` matches with case insensitive)
```
    QStringList files = dir.entryList(QStringList{fileInfo.fileName()}, QDir::Files);
    if (files.size() > 0) {
        setFilePath(files.at(0));
    }
```

**Comment by droidmonkey** [comment]
Can we simplify the code any further? I don't like the brute force search approach.

**Comment by benjarobin** [comment]
@droidmonkey Well, I also do not like it... If you want to "simplify" it, there is this solution: https://docs.microsoft.com/en-us/windows/win32/memory/obtaining-a-file-name-from-a-file-handle?redirectedfrom=MSDN

**Comment by droidmonkey** [comment]
You could use FindFirstFile Windows API: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilea#examples

Then extract the filename from the data structure.

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
I switched over to the native Windows function, moved the code closest to the source of input error (main.cpp), and cleaned up some old code.
