### PR TITLE
Significantly improve performance when saving and opening databases

### LINKED ISSUE #4249: App refuses to close after running for long period of time
Sometimes I am unable to close KeepassXC. Seems to be when I have Hibernated the PC then restarted it, Not unlocked after restart. Shutdown by right-click in tray icon and select Quit. Process hangs and has to be terminated via Task Manager. Problem appeared in 2.5.1 and all subsequent releases so I'm running 2.3.4. I'm running the Portable version - don't know if that makes any difference.
Doesn't always happen but it is very annoying when it does.
Windows 10 .
By the way - the 2.5.3 release says it's 2.5.1 on the 'About' pop-up.

### LINKED ISSUE #4289: Crashes when saving
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Database should be saved when new entry is added.
I would like to add that I have autosave and browser integration enabled.

## Current Behavior
The whole KeePassXC window is greyed out - Asterix next to database name indicates that it hasn't been saved. Unable to save, close or exit application. Only way is to use taksmanager to kill it and start it again.
When that happens the app is still usable, i.e. I am able to search.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Start KeepassXC
2. In Firefox (or any other supported browser) go to a website and enter logon details - when prompted by KeePass plugin click add new entry to database
3. App crashes

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ Refactor (significant modification to existing code)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Fix crash when switching tabs while unlocking

* Prevent destruction of FileWatcher while calculating checksums
  * Only perform async checksum calculations when triggered by timer (prevents random GUI freezes)
  * Use mutex to block object destruction while an async checksum is being calculated

* Fix crashes on database save
  * Add saving mutex to database class to prevent re-entrant saving
  * Prevent saving multiple times to the same file if the database is not marked as modified
  * Prevent locking the database while saving. This also prevents closing the application and database tab while saving.

* Dynamically determine database validity
  * Check that the database composite key exists, has sub-keys associated with it, and the root group exists.

* Move database open to AsyncTask
  * Wrap key transformation in AsyncTask when reading a database. Significantly reduces user interface lockup.

Fixes #4249 
Fixes #4289

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows 10. I used a long encryption time and artificial wait introduced in the FileWatcher checksum calculation to guarantee triggering a crash in the original code (`Tools::wait(2000)`). Fixes were introduced until the crashes could not be reproduced. 

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

File: src/core/Database.cpp [hunk 1]
```diff
@@ -159,6 +159,11 @@ bool Database::open(const QString& filePath, QSharedPointer<const CompositeKey>
     return true;
 }
 
+bool Database::isSaving()
+{
+    return !m_saveMutex.tryLock();
```
Comment (phoerious) [inline src/core/Database.cpp]: What happens if tryLock() is successful? There should be a release call right after this statement.

File: src/core/FileWatcher.cpp [hunk 2]
```diff
@@ -43,6 +43,13 @@ FileWatcher::FileWatcher(QObject* parent)
     m_fileIgnoreDelayTimer.setSingleShot(true);
 }
 
+FileWatcher::~FileWatcher()
+{
+    // Prevent destroying the file watcher while performing async operations
+    m_mutex.lock();
+    m_mutex.unlock();
```
Comment (phoerious) [inline src/core/FileWatcher.cpp]: Mind blown... :boom: 🤯

File: src/core/FileWatcher.cpp [hunk 3]
```diff
@@ -121,32 +128,33 @@ void FileWatcher::checkFileChanged()
     m_ignoreFileChange = true;
 
     // Only trigger the change notice if there is a checksum mismatch
-    auto checksum = calculateChecksum();
+    m_mutex.lock();
```
Comment (phoerious) [inline src/core/FileWatcher.cpp]: Why not use a QMutexLocker here?

File: src/gui/DatabaseOpenWidget.cpp [hunk 4]
```diff
@@ -212,7 +215,34 @@ void DatabaseOpenWidget::openDatabase()
...
+
+        if (m_ui->messageWidget->isVisible()) {
+            m_ui->messageWidget->animatedHide();
+        }
+
+        emit dialogFinished(true);
+        m_isOpeningDatabase = false;
+        clearForms();
+    } else {
+        m_isOpeningDatabase = false;
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp]: Shouldn't this be a Mutex then as well?

File: src/gui/DatabaseWidget.cpp [hunk 5]
```diff
@@ -1379,6 +1379,12 @@ bool DatabaseWidget::lock()
         return true;
     }
 
+    // Don't try to lock the database while saving, doing so
+    // would result in data loss and/or crashing
+    if (m_db->isSaving()) {
+        return false;
+    }
```
Comment (phoerious) [inline src/gui/DatabaseWidget.cpp]: Is this the correct behaviour? To me it would make more sense to defer (or reschedule) further execution to when isSaving() returns false (without blocking the event loop).

Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: I tried that and it causes a deadlock because you are in a single thread that cannot unwind itself.

File: src/core/Database.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/core/Database.cpp]: Correct this is an error. We may have to shift to a Boolean here.

File: src/core/FileWatcher.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/core/FileWatcher.cpp]: Curious, do you know a better way to prevent destruction?

File: src/core/FileWatcher.cpp (hunk 3 above)
Comment (droidmonkey) [reply src/core/FileWatcher.cpp]: Since there is only on code path I decided not to allocate a new variable for this purpose.

File: src/gui/DatabaseOpenWidget.cpp (hunk 4 above)
Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: Perhaps, I'm second guessing the use of mutex

File: src/core/FileWatcher.cpp (hunk 2 above)
Comment (phoerious) [reply src/core/FileWatcher.cpp]: Except for preventing that the object itself goes out of scope? No.

File: src/core/FileWatcher.cpp (hunk 3 above)
Comment (phoerious) [reply src/core/FileWatcher.cpp]: That may not be so in the future. Better be safe than sorry.

File: src/gui/DatabaseWidget.cpp (hunk 5 above)
Comment (phoerious) [reply src/gui/DatabaseWidget.cpp]: This should cause a deadlock if you do not release the lock in isSaving() in any case. However, scheduling reentry using a timer should not result in any deadlocks.

File: src/core/Database.cpp (hunk 1 above)
Comment (phoerious) [reply src/core/Database.cpp]: You could simply add m_saveMutex.unlock() afterwards.

File: src/core/FileWatcher.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/core/FileWatcher.cpp]: We actively delete it in the database releaseData function!

File: src/gui/DatabaseWidget.cpp (hunk 5 above)
Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: I'll draw a diagram of the problem, it is what is causing the majority of crashes.

**Comment by droidmonkey** [comment]
I cleaned up the fixes. Need to introduce setting `m_initialized` in Database class for more circumstances rather than just opening the database. Perhaps `isInitialized()` can determine that state dynamically based on a set of criteria.

**Comment by droidmonkey** [comment]
This is ready for a re-review

File: src/cli/Create.cpp [hunk 6]
```diff
@@ -121,6 +121,7 @@ int Create::execute(const QStringList& arguments)
 
     QSharedPointer<Database> db(new Database);
     db->setKey(key);
+    db->setInitialized(true);
```
Comment (phoerious) [inline src/cli/Create.cpp]: I like the explicit initialisation, but couldn't be determine this automatically somehow based on a set of criteria? It seems rather error-prone to me to rely on the user to call this function.

Comment (droidmonkey) [reply src/cli/Create.cpp]: I had the same thought as well

Comment (phoerious) [reply src/cli/Create.cpp]: Then we should go with that.

Comment (droidmonkey) [reply src/cli/Create.cpp]: Done

File: src/core/Database.cpp [hunk 7]
```diff
@@ -466,22 +488,14 @@ void Database::setReadOnly(bool readOnly)
...
-    return m_initialized;
-}
-
-/**
- * @param initialized true to mark database as initialized
- */
-void Database::setInitialized(bool initialized)
-{
-    m_initialized = initialized;
+    return m_data.key && !m_data.key->isEmpty() && m_rootGroup;
```
Comment (phoerious) [inline src/core/Database.cpp]: You forgot the metadata

Comment (droidmonkey) [reply src/core/Database.cpp]: Metadata is always a valid pointer.

Comment (phoerious) [reply src/core/Database.cpp]: Alright.

**Comment by Cyrix240** [comment]
Sorry if this is not the place to say this, the issues I would maybe comment on have been closed or merged into this (i think.) I have been experiencing the crash on database save on 2 different PCs and on different versions of keepass. 

On my main PC (relatively modern, ssd, etc.) I get the issue maybe once a month on 2.5.4, not hat big a deal for me to kill it and start again.

On my mothers PC (Core2duo, slow HDD) it would happen consistently after just a save or 2, i tried updating this PC to the snapshot version with no change in behavior. 

However on both computers the behavior seems to go away completely if browser integration is disabled.

I also saw mention of turning off the minimize on close setting, but that had no effect on either machine or version.

happy to provide and further info if i can.

**Comment by droidmonkey** [comment]
We have heard that browser integration is to blame for the random freezes/crashes. It's hard to pinpoint the issue without debug logs.

**Comment by Cyrix240** [comment]
Is that something i could send you? All i could find relating to debug in the app is the info tab in the about dialog box but that doesn't seem like much info, so i assume there is something else. 

here it is either way: 
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1903
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

I'd be happy to send other logs along if you can point me to where/how to get them.

**Comment by droidmonkey** [comment]
What you can do is see if a snapshot build that includes the fixes from this PR still crashes on your mother's PC. We (the development team) have not been able to reproduce these crashes at all in the past year. You can download a snapshot build at https://snapshot.keepassxc.org. We don't recommend using it permanently, just to test.

**Comment by Cyrix240** [comment]
The snapshot as of 4/20 still crashes on moms PC, no noticeable difference.

**Comment by droidmonkey** [comment]
OK great, we are working some fixes that may work. You will be our Guinea pig if you don't mind

**Comment by Cyrix240** [comment]
happy to help.
