### PR TITLE
Properly block modified signal during Database destruction

### LINKED ISSUE #6393: Mutex Deadlock Crash in Secret Service
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
@Aetf This was reported by a user on IRC. They experienced a crash on close of KeePassXC with self-built develop branch with the latest Secret Service code.

"And I'm using two databases while the second one gets opened by AutoOpen. When closing KeePassXC, it hangs due to an dead-lock:"

```
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f50fc1ebea5 in QtLinuxFutex::_q_futex (val3=0, addr2=0x0, val2=0, val=3, op=0, addr=0x561b00bbe1d8) at thread/qfutex_p.h:116
#2  QtLinuxFutex::futexWait<QBasicAtomicPointer<QMutexData> > (expectedValue=0x3, futex=...) at thread/qfutex_p.h:135
#3  lockInternal_helper<false> (timeout=-1, elapsedTimer=0x0, d_ptr=...) at thread/qmutex_linux.cpp:142
#4  QBasicMutex::lockInternal (this=0x561b00bbe1d8) at thread/qmutex_linux.cpp:159
#5  0x00007f50fc1ec08a in QMutex::lock (this=<optimized out>) at thread/qmutex.cpp:235
#6  0x0000561afdcb603a in QMutexLocker::QMutexLocker (this=0x7fff6bbceca0, m=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h:233
#7  0x0000561afdcb3246 in Database::releaseData (this=0x561b00bbe120) at /home/joerg/git/keepassxc/src/core/Database.cpp:426
#8  0x0000561afdcb47b2 in Database::~Database (this=0x561b00bbe120, __in_chrg=<optimized out>) at /home/joerg/git/keepassxc/src/core/Database.cpp:75
#9  0x0000561afde0bdd9 in QtSharedPointer::ExternalRefCountData::destroy (this=0x561b00bbe110) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:149
#10 QSharedPointer<Database>::deref (dd=0x561b00bbe110) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:458
#11 QSharedPointer<Database>::deref (this=0x7fff6bbced40) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:453
#12 QSharedPointer<Database>::~QSharedPointer (this=0x7fff6bbced40, __in_chrg=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:310
#13 operator() (__closure=0x561affce0e20) at /home/joerg/git/keepassxc/src/fdosecrets/objects/Service.cpp:162
#14 QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, FdoSecrets::Service::monitorDatabaseExposedGroup(DatabaseWidget*)::<lambda()> >::call (arg=<optimized out>, f=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:146
#15 QtPrivate::Functor<FdoSecrets::Service::monitorDatabaseExposedGroup(DatabaseWidget*)::<lambda()>, 0>::call<QtPrivate::List<>, void> (arg=<optimized out>, f=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:256
#16 QtPrivate::QFunctorSlotObject<FdoSecrets::Service::monitorDatabaseExposedGroup(DatabaseWidget*)::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=0x561affce0e10, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:443
#17 0x00007f50fc403546 in QtPrivate::QSlotObjectBase::call (a=0x7fff6bbcee30, r=0x561b000cd500, this=0x561affce0e10) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#18 doActivate<false> (sender=0x561b00970580, signal_index=3, argv=0x7fff6bbcee30, argv@entry=0x0) at kernel/qobject.cpp:3886
#19 0x00007f50fc3fc8a0 in QMetaObject::activate (sender=<optimized out>, m=m@entry=0x561afdf66640 <CustomData::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0) at kernel/qobject.cpp:3946
#20 0x0000561afdc95710 in CustomData::customDataModified (this=<optimized out>) at /home/joerg/git/keepassxc/build/src/keepassx_core_autogen/TAC5DWH4SE/moc_CustomData.cpp:244
#21 0x0000561afdcaf8cf in CustomData::clear (this=<optimized out>) at /home/joerg/git/keepassxc/src/core/CustomData.cpp:156
#22 0x0000561afdcd3e4d in Metadata::clear (this=<optimized out>) at /home/joerg/git/keepassxc/src/core/Metadata.cpp:72
#23 0x0000561afdcb34af in Database::releaseData (this=0x561b00bbe120) at /home/joerg/git/keepassxc/src/core/Database.cpp:440
#24 0x0000561afdcb47b2 in Database::~Database (this=0x561b00bbe120, __in_chrg=<optimized out>) at /home/joerg/git/keepassxc/src/core/Database.cpp:75
#25 0x0000561afdd28071 in QtSharedPointer::ExternalRefCountData::destroy (this=0x561b00bbe110) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:149
#26 QSharedPointer<Database>::deref (dd=0x561b00bbe110) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:458
#27 QSharedPointer<Database>::deref (this=0x561b001b89a0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:453
#28 QSharedPointer<Database>::~QSharedPointer (this=0x561b001b89a0, __in_chrg=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:310
#29 DatabaseWidget::~DatabaseWidget (this=0x561b001b8970, __in_chrg=<optimized out>) at /home/joerg/git/keepassxc/src/gui/DatabaseWidget.cpp:235
#30 0x0000561afdd280c9 in DatabaseWidget::~DatabaseWidget (this=0x561b001b8970, __in_chrg=<optimized out>) at /home/joerg/git/keepassxc/src/gui/DatabaseWidget.cpp:238
#31 0x00007f50fc3f8d4f in QObject::event (this=this@entry=0x561b001b8970, e=e@entry=0x561b01c7dd70) at kernel/qobject.cpp:1301
#32 0x00007f50fcf5beb9 in QWidget::event (this=this@entry=0x561b001b8970, event=event@entry=0x561b01c7dd70) at kernel/qwidget.cpp:9080
#33 0x00007f50fd00441e in QFrame::event (this=0x561b001b8970, e=0x561b01c7dd70) at widgets/qframe.cpp:550
#34 0x00007f50fcf1c15f in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x561b001b8970, e=0x561b01c7dd70) at kernel/qapplication.cpp:3632
#35 0x00007f50fc3ccf6a in QCoreApplication::notifyInternal2 (receiver=0x561b001b8970, event=0x561b01c7dd70) at kernel/qcoreapplication.cpp:1063
#36 0x00007f50fc3cf9a1 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=52, data=0x561aff953ae0) at kernel/qcoreapplication.cpp:1817
#37 0x00007f50fc3d3bb8 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:86
#38 0x00007f50fc799bdc in QGuiApplication::exec () at kernel/qguiapplication.cpp:1867
#39 0x00007f50fcf1c0d5 in QApplication::exec () at kernel/qapplication.cpp:2824
#40 0x0000561afdc43ccc in main (argc=<optimized out>, argv=<optimized out>) at /home/joerg/git/keepassxc/src/main.cpp:174
```

### PR DESCRIPTION
**Pull request by Aetf**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Fixes #6393, another attempt.

- Explicitly clear `m_db` in DatabaseWidget
- Introduce `ModifiableObject` to manage all objects that can emit modified signals. Properly block the signal from all sub-objects during Database destruction

While at it, also some cosmetic changes in the neighboring lines:

- Use QScopedPointer for `m_entrySearcher` in `DatabaseWidget`
- Convert neighboring lines to new signal/slot syntax

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Added unit test for modified signals not firing when they are blocked.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ Refactor (significant modification to existing code)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Oooh sexy idea!!

**Comment by Aetf** [comment]
@droidmonkey Ready for review. The CI failure seems unrelated & the tests pass locally.

File: src/core/ModifiableObject.cpp [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+ *
+ *  You should have received a copy of the GNU General Public License
+ *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+#include "ModifiableObject.h"
+
+namespace
+{
+    template <typename T> T findParent(const QObject* obj)
```
Comment (xvallspl) [inline src/core/ModifiableObject.cpp:22]: Are we calling findParent with any type other than ModifiableObject *?

**Comment by droidmonkey** [comment]
Awesome thank you for this! I'll review by the weekend.

**Review by droidmonkey — APPROVED** [review]
1 minor change
