### PR TITLE
Significantly enhance hardware key robustness

### LINKED ISSUE #1050: Add ability to use more than one connected Yubikey
## Expected Behavior

Multiple Yubikey's connected to the system would be polled and made available to KeePassXC.

Also, the YubiKey would only be "held" during active Challenge/Response actions.

## Current Behavior

Only the first connected Yubikey is used and the Yubikey is held open for the duration of KeePassXC running regardless of whether it is being used or not.

### LINKED ISSUE #1088: Global Auto-type when minimized to tray in Windows + Yubikey: no prompt to touch the key (appears stalled)
Starting with KeepassXC on Windows minimized to tray and locked. I use keepassxc with Yubikey challenge/response, configured to wait for a "touch" before responding.

Then invoking auto-type with ctrl-alt-a, keepassxc displays a password prompt
The prompt includes the Challenge/response option selected, and the yubikey detected, all as expected.

After entering the password and hitting enter, windows displays the circular throbber and keepassXC appears stalled, there is no prompt anywhere asking to touch the key.

After touching the key, all proceeds as normal. 

## Expected Behavior
There should be a prompt somewhere (inline / blue ribbon message?) asking to touch the key, same as what happens when opening up keepassxc for the first time.
"Please touch the button in your YubiKey!"

## Current Behavior
After invoking auto-type and entering the password, keepassXC appears to stall forever 

## Possible Solution
add an inline prompt in a blue ribbon prompting to touch the key, as is done when keepassxc is first invoked.
Message: "Please touch the button in your YubiKey!"

## Steps to Reproduce (for bugs)
1. On windows 7 64bits, start keepassXC, open your yubikey-protected database, and then minimize keepasXC to tray ensuring it's locked
2. then invoke global autotype (ctrl alt a)
3.In the prompt, enter the correct password and hit enter
4.... see the windows throbber spinning, and nothing happens.
Now if you touch your yubikey, the DB will open normally

## Context
N/A

## Debug Info
KeePassXC - Version 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### LINKED ISSUE #1215: Yubikey remains "open" after use preventing other applications to use it
If you are using a Yubikey with KeePassXC, the Yubico OTP in Slot 1 isn't available.

## Expected Behavior

Normally you also can use OTP generation from slot 1, when you press a button.

## Current Behavior

Slot 1 isn't functional.

## Possible Solution

As a workaround it helps to unplugged the Yubikey.

## Steps to Reproduce (for bugs)

1. Use Yubikey
2. Press the button 

## Context

With the Keepass extension it was possible to use both functionalities.

## Debug Info

KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.5.1
- libgcrypt 1.7.6

Operating system: Ubuntu 16.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-101-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### LINKED ISSUE #1869: Prompt to insert yubikey if missing on autoreload
I've tested the "Tools-Settings->General->Automatically reload the database when modified externally"

## Expected Behavior
On my Ubuntu box, KeePassXC 3.2.1, correctly detects a change made by KeePassXC 3.2.1 on Windows.

I use OwnCloud to synchronise between the two hosts. OwnCloud detects the change and automatically overwrites the old file on the host(s) where there was no changes made.

## Current Behavior
On my Windows box, a similar change to the file made on the Linux box, isn't detected.

And I just double checked it again, the file is synchronizing correctly from Linux to Windows box. Timestamp and size is updated. KeePassXC on Windows still don't reload.

## Possible Solution
KeepassXC on Windows should detect the change.

However, when, I did this, I first changed the database on Ubuntu, Windows didn't detect this, then I changed the database on Windows (without reloading). When I then made the change on Windows, the Ubuntu box picked up the change, but did NOT merge the file, with the one it had in memory. Thus the change on the Ubuntu box was lost (if it wasn't because I also enabled the "Backup database file before saving" and then did a manual merge).

## Steps to Reproduce (for bugs)
Change file on one host
Wait and see if host2 (Windows) detects the changed file

## Context
I wish to be able to use only one KDBX file across numerous devices. I use:
"Safely save database files"
"Backup database file before saving"
"Automatically save after every change"
"Automatically reload the database when modified externally"

It would be awesome, if KeePassXC would maintain a user defined number of timestamped/named backups (in case OwnCloud connection fails while doing simultaneous changes on the two hosts).

And it would be even more awesome, if the default action was to "merge" when doing an "Automatic reload".

Also, one smaller issue, is that the "merge" or "synchronize" behavior has changed, compared to KeePass 2. In KeePass 2, you would not be prompted for password / keyfile, if only they were the same, when doing a synchronize. In XC it seems to default to prompting regardless of this being identical.

Except from this, big kudos for some lovely and long awaited improvements over the original KeePass 2 and KeePassX. And I also sent a little donation.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### LINKED ISSUE #3087: Yubikey is listed twice in combobox
## Expected Behavior

When configuring Yubikey Challenge-Response, my single attached Yubikey is only listed once in the combo box to choose the Yubikey from.

## Current Behavior

My single Yubikey is listed twice in the combo box (with exactly the same string incl. the same slot number).

## Possible Solution

None.

## Steps to Reproduce
1. Launch KeePassXC.
2. Create a new database.
3. Accept defaults, then "Add additional protection", then "Add Yubikey Challenge-Response".
4. Wait for the discovery of Yubikeys to finish.

## Context

N/A

## Debug Info

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

### LINKED ISSUE #4065: Yubikey is not detected if already plugged
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A yubikey should be detected if it's plugged in.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The yubikey is not detected if it's already plugged in before launching the KeePassXC.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Insert yubikey
2. Launch KeePassXC
3. Try to unlock the database or 'refresh' for the keys.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.1

Operating system: Arch Linux
CPU architecture: 64
Kernel: 5.4.6

### LINKED ISSUE #4400: Unlocking database with Onlykey is a hit and miss
## Expected Behavior
When KeepassXC says "Please touch the button on your YubiKey!" I expect the database to open if I touch a button on the Onlykey and have typed the correct password. 

## Current Behavior
I sometimes get this error: "Error while reading the database: Unable to calculate master key".  I have verified thoroughly that I got my password typed right. There seems to be some timing issue: press too fast and it won't work, press too late and it won't work either. 

## Steps to Reproduce

1. Plug-in the Onlykey in a USB-port and unlock it
2. Open KeepassXC and enter your password as usual
3. Hit enter and touch a button on the Onlykey when requested

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ Refactor (significant modification to existing code)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Significantly improve user experience when using hardware keys on databases in both GUI and CLI modes. Prevent locking up the YubiKey USB interface for prolonged periods of time. Allows for other apps to use the key concurrently with KeePassXC.

* Improve messages displayed to user when finding keys and when user interaction is required. Output specific error messages when handling hardware keys during database read/write.

* Only poll for keys when previously used or upon user request. Prevent continuously polling keys when accessing the UI such as switching tabs and minimize/maximize.

* Add support for using multiple hardware keys simultaneously. Keys are identified by their serial number which prevents using the wrong key during open and save operations.

* Fixes #4400
* Fixes #4065
* Fixes #1050
* Fixes #1215
* Fixes #3087
* Fixes #1088
* Fixes #1869

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
Coming soon

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Updated YubiKey test and CLI test.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
This is ready for review!

File: src/cli/Command.cpp [hunk 1]
```diff
@@ -121,7 +122,15 @@ QString Command::getDescriptionLine()
 
 QString Command::getHelpText()
 {
-    return buildParser(this)->helpText().replace("[options]", name + " [options]");
+    auto help = buildParser(this)->helpText();
+    // Fix spacing of options parameter
+    help.replace("[options]", name + " [options]");
+    // Remove application directory from command line example
+    auto appname = QFileInfo(QCoreApplication::applicationFilePath()).fileName();
+    auto regex = QRegularExpression(QString(" .*%1").arg(QRegularExpression::escape(appname)));
```
Comment (phoerious) [inline src/cli/Command.cpp:130]: QStringLiteral.

File: src/gui/DatabaseOpenWidget.cpp [hunk 2]
```diff
@@ -315,34 +317,32 @@ QSharedPointer<CompositeKey> DatabaseOpenWidget::databaseKey()
...
-        bool blocking = comboPayload & 1;
-        int slot = comboPayload >> 1;
-        auto crKey = QSharedPointer<YkChallengeResponseKey>(new YkChallengeResponseKey(slot, blocking));
+        auto slot = m_ui->comboChallengeResponse->itemData(selectionIndex).value<YubiKeySlot>();
+        auto crKey = QSharedPointer<YkChallengeResponseKey>(new YkChallengeResponseKey(slot));
         masterKey->addChallengeResponseKey(crKey);
-        lastChallengeResponse[m_filename] = true;
+
+        // Qt doesn't read custom types in settings so stuff into a QString
+        lastChallengeResponse.insert(m_filename, QString("%1:%2").arg(slot.first).arg(slot.second));
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp:345]: QStringLiteral.

File: src/gui/DatabaseOpenWidget.cpp [hunk 3]
```diff
@@ -400,45 +400,62 @@ void DatabaseOpenWidget::handleKeyFileComboChanged()
...
 
-void DatabaseOpenWidget::pollYubikey()
+void DatabaseOpenWidget::pollHardwareKey()
 {
+    if (m_yubiKeyBeingPolled) {
+        return;
+    }
+
+    m_ui->comboChallengeResponse->clear();
+    m_ui->comboChallengeResponse->addItem(tr("Detecting Hardware Keys..."));
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp:410]: Should be a real ellipsis, not three dots.

File: src/gui/DatabaseOpenWidget.cpp [hunk 4]
```diff
@@ -400,45 +400,62 @@ void DatabaseOpenWidget::handleKeyFileComboChanged()
...
+
     m_ui->buttonRedetectYubikey->setEnabled(false);
     m_ui->comboChallengeResponse->setEnabled(false);
-    m_ui->comboChallengeResponse->clear();
-    m_ui->comboChallengeResponse->addItem(tr("Select slot..."), -1);
     m_ui->yubikeyProgress->setVisible(true);
+    m_yubiKeyBeingPolled = true;
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp:415]: Perhaps rename this and variable as well?

File: src/gui/DatabaseOpenWidget.cpp [hunk 5]
```diff
@@ -400,45 +400,62 @@ void DatabaseOpenWidget::handleKeyFileComboChanged()
...
+    m_ui->buttonRedetectYubikey->setEnabled(true);
+    m_ui->yubikeyProgress->setVisible(false);
+    m_yubiKeyBeingPolled = false;
 
+    if (!found) {
+        m_ui->comboChallengeResponse->addItem(tr("No Hardware Keys Detected"));
+        m_ui->comboChallengeResponse->setEnabled(false);
+        return;
+    } else {
+        m_ui->comboChallengeResponse->addItem(tr("Select Hardware Key..."));
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp:432]: Should this really be title casing?

File: src/gui/masterkey/YubiKeyEditWidget.cpp [hunk 6]
```diff
@@ -105,72 +98,36 @@ void YubiKeyEditWidget::pollYubikey()
 
     m_isDetected = false;
     m_compUi->comboChallengeResponse->clear();
+    m_compUi->comboChallengeResponse->addItem(tr("Detecting Hardware Keys..."));
```
Comment (phoerious) [inline src/gui/masterkey/YubiKeyEditWidget.cpp:101]: Ellipsis.

File: src/gui/masterkey/YubiKeyEditWidget.cpp [hunk 7]
```diff
@@ -105,72 +98,36 @@ void YubiKeyEditWidget::pollYubikey()
...
-#endif
-}
 
-bool YubiKeyEditWidget::createCrKey(QSharedPointer<YkChallengeResponseKey>& key, bool testChallenge) const
-{
-    Q_ASSERT(m_compEditWidget);
-    if (!m_isDetected || !m_compEditWidget) {
-        return false;
+    if (!found) {
+        m_compUi->comboChallengeResponse->addItem(tr("No Hardware Keys Detected"));
```
Comment (phoerious) [inline src/gui/masterkey/YubiKeyEditWidget.cpp:121]: Title casing?

File: src/keys/YkChallengeResponseKey.cpp [hunk 8]
```diff
@@ -63,60 +57,25 @@ QByteArray YkChallengeResponseKey::rawKey() const
...
-            sodium_memzero(key.data(), static_cast<std::size_t>(key.capacity()));
-            return true;
+    m_error.clear();
+    QByteArray key;
+    auto result =
+        AsyncTask::runAndWaitForFuture([&] { return YubiKey::instance()->challenge(m_keySlot, challenge, key); });
+
+    if (result == YubiKey::SUCCESS) {
+        if (m_key) {
+            gcry_free(m_key);
```
Comment (phoerious) [inline src/keys/YkChallengeResponseKey.cpp:69]: I'm not so much a fan of scattered non-RAII frees like this. I prefer we reuse existing (or extended) PasswordKey logic here.

File: src/keys/YkChallengeResponseKey.cpp [hunk 9]
```diff
@@ -63,60 +57,25 @@ QByteArray YkChallengeResponseKey::rawKey() const
...
-    YubiKey::instance()->getSerial(serial);
-
-    return fmt.arg(YubiKey::instance()->getVendorName(),
-                   QString::number(serial),
-                   QString::number(m_slot),
-                   (m_blocking) ? QObject::tr("Press") : QObject::tr("Passive"));
-}
+        m_keySize = static_cast<std::size_t>(key.size());
+        m_key = static_cast<char*>(gcry_malloc_secure(m_keySize));
+        std::memcpy(m_key, key.data(), m_keySize);
```
Comment (phoerious) [inline src/keys/YkChallengeResponseKey.cpp:73]: See above.

File: src/keys/YkChallengeResponseKeyCLI.cpp [hunk 10]
```diff
@@ -23,49 +23,33 @@
...
 {
+    connect(YubiKey::instance(), SIGNAL(userInteractionRequest()), SLOT(showInteractionMessage()));
 }
 
-QByteArray YkChallengeResponseKeyCLI::rawKey() const
+void YkChallengeResponseKeyCLI::showInteractionMessage()
 {
-    return m_key;
+    QTextStream out(m_out, QIODevice::WriteOnly);
+    out << m_interactionMessage << endl << endl;
```
Comment (phoerious) [inline src/keys/YkChallengeResponseKeyCLI.cpp:43]: Don't use `endl` twice, replace with `'\n' << endl` or `"\n\n" << flush`.

File: src/keys/drivers/YubiKey.cpp [hunk 11]
```diff
@@ -30,17 +30,95 @@
...
+    {
+        unsigned int serial;
+        yk_get_serial(key, 1, 0, &serial);
+        return serial;
+    }
+
+    YK_KEY* openKeySerial(unsigned int serial)
+    {
+        bool onlykey;
+        for (int i = 0, j = 0; i + j < 4;) {
```
Comment (phoerious) [inline src/keys/drivers/YubiKey.cpp:83]: Where does this magic 4 come from? Should be a named constexpr.

File: src/keys/drivers/YubiKey.cpp [hunk 12]
```diff
@@ -54,161 +132,162 @@ YubiKey* YubiKey::instance()
...
-        m_yk_void = nullptr;
-        yk_release();
-        m_mutex.unlock();
-        return false;
-    }
+        // Remove all known keys
+        m_foundKeys.clear();
+
+        // Try to detect up to 4 connected hardware keys
+        for (int i = 0, j = 0; i + j < 4;) {
```
Comment (phoerious) [inline src/keys/drivers/YubiKey.cpp:157]: Same here.

File: src/keys/drivers/YubiKey.cpp [hunk 13]
```diff
@@ -54,161 +132,162 @@ YubiKey* YubiKey::instance()
...
+            bool onlyKey = false;
+            auto* yk_key = openKey(i, j, &onlyKey);
+            Tools::wait(50);
```
Comment (phoerious) [inline src/keys/drivers/YubiKey.cpp:160]: What are we waiting for here? This looks an awful lot like "no idea what's happening here, let's just hope this is enough to not fail randomly on some persons's machine". Isn't there a better solution?

File: src/keys/drivers/YubiKey.cpp [hunk 14]
```diff
@@ -54,161 +132,162 @@ YubiKey* YubiKey::instance()
...
+
+                auto chall = randomGen()->randomArray(1);
+                QByteArray resp;
+                QList<QPair<int, QString>> ykSlots;
+                for (int slot = 1; slot <= 2; ++slot) {
+                    auto config = (i == 1 ? CONFIG1_VALID : CONFIG2_VALID);
+                    if (ykds_touch_level(st) & config) {
+                        // Don't actually challenge a YubiKey Neo or below, they always require button press
+                        // if it is enabled for the slot resulting in failed detection
+                        if (pid <= 0x0116) {
```
Comment (phoerious) [inline src/keys/drivers/YubiKey.cpp:183]: 1) Magic number should be named constexpr (can be local).

2) Skipping the challenge results in both slots being detected as being configured for HMAC-SHA1 on my NEO, even though only one is. The other one is configured for OpenPGP. If I select that slot, KeePassXC will try to challenge it and then bails out with a timeout error. That's not how this should work and looks quite dangerous to me (particularly during master key setup).

File: tests/TestYkChallengeResponseKey.cpp [hunk 15]
```diff
@@ -19,82 +19,69 @@
...
+        }
     }
 
-    /* Key used for later testing */
-    if (!m_key) {
-        m_key.reset(new YkChallengeResponseKey(slot, blocking));
+    if (passiveKey.first == 0) {
+        /* Testing active mode in unit tests is unreasonable */
+        QSKIP("No YubiKey contains a slot in passive mode.");
     }
```
Comment (phoerious) [inline tests/TestYkChallengeResponseKey.cpp:80]: This check fails for my NEO.

File: src/keys/YkChallengeResponseKey.cpp (hunk 8 above)
Comment (droidmonkey) [reply src/keys/YkChallengeResponseKey.cpp:69]: This was moved code

Comment (phoerious) [reply src/keys/YkChallengeResponseKey.cpp:69]: Then I take the blame for not refactoring that in the first place. :-D

File: src/keys/drivers/YubiKey.cpp (hunk 11 above)
Comment (droidmonkey) [reply src/keys/drivers/YubiKey.cpp:83]: From my magical limit I set! Agree with constexpr

File: src/keys/drivers/YubiKey.cpp (hunk 13 above)
Comment (droidmonkey) [reply src/keys/drivers/YubiKey.cpp:160]: There isn't, removing these waits causes sporadic issues reading from the keys. This one *may* be able to be removed since I excluded yubikey neo from the CR testing.

File: src/keys/drivers/YubiKey.cpp (hunk 14 above)
Comment (droidmonkey) [reply src/keys/drivers/YubiKey.cpp:183]: It's not dangerous because you cannot possibly get past the master key setup unless challenge response is setup correctly. The checks done in this function do not work with the NEO because of a firmware problem. The NEO does not cancel the CR action properly if "press" is enabled resulting in it waiting for a press when none will come. To add insult to injury, the NEO firmware also does not populate the touch status properly so I can't even  check if touch is enabled on a slot. The NEO is a fucking mess and I recommend just throwing it away and get a YK 4 or 5.

Comment (phoerious) [reply src/keys/drivers/YubiKey.cpp:183]: It has served me well so far and I don't really want to buy a new one for no apparent reason. Having the other slot enabled all of a sudden is super ugly and annoying.
And what's dangerous is not the setup wizard, it's the master key change. When I tested it, I could change the master key and the error occurred only after that. I did not test what would have happened had closed the database in this state, but it certainly looks to me like a recipe for disaster or at least something that is hard to test yet easy to fuck up massively.

Comment (droidmonkey) [reply src/keys/drivers/YubiKey.cpp:183]: I'll look into that further.

File: src/keys/drivers/YubiKey.cpp (hunk 13 above)
Comment (asvc) [reply src/keys/drivers/YubiKey.cpp:160]: > since I excluded yubikey neo from the CR testing

Will this be of any problem for "Neo" users? Just curious if I need to replace mine beforehand.

File: src/keys/drivers/YubiKey.cpp (hunk 14 above)
Comment (asvc) [reply src/keys/drivers/YubiKey.cpp:183]: > The NEO is a fucking mess and I recommend just throwing it away and get a YK 4 or 5.

Now I have noticed this... Ordering a replacement.

File: src/gui/DatabaseOpenWidget.cpp (hunk 3 above)
Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp:410]: We have several places in the code where we should convert to ellipses.

File: src/keys/YkChallengeResponseKey.cpp (hunk 8 above)
Comment (droidmonkey) [reply src/keys/YkChallengeResponseKey.cpp:69]: I am not a fan of that logic and have seen it in the code. I prefer a properly named container like "SecureBuffer" which would encapsulate this behavior. Then PasswordKey would use that buffer but we don't sprinkle specific use case classes like PasswordKey around the world.

**Comment by droidmonkey** [comment]
I made the requested changes. I don't want to include the PasswordKey change in this PR, I think we need to do that on a more global refactor. Also, tests now pass using a NEO :wink:

**Comment by phoerious** [comment]
Still failing for me:

```
FAIL!  : TestYubiKeyChallengeResponse::testDetectDevices() 'displayName.contains("Challenge Response - Slot")' returned
FALSE. ()
D:\Documents\KeePassXC\keepassxc\tests\TestYkChallengeResponseKey.cpp(52) : failure location
SKIP   : TestYubiKeyChallengeResponse::testKeyChallenge() No YubiKey contains a slot in passive mode.
D:\Documents\KeePassXC\keepassxc\tests\TestYkChallengeResponseKey.cpp(79) : failure location****
```

It's also still showing both slots as configured.

**Comment by droidmonkey** [comment]
Tests fixed and rebased

**Comment by onlykey** [comment]
Has anyone had any issues with Yubikey since this change? Asking because we have a user saying that OnlyKey works fine with this but now they are having issue with Yubikey on Linux - https://github.com/trustcrypto/OnlyKey-Firmware/issues/98#issuecomment-640928678

**Comment by droidmonkey** [comment]
I tested extensively with both OK and YK keys. I have a YK Neo and YK 4 and both work flawlessly. Perhaps this is a Linux problem? If someone else can replicate I will be concerned.
