### PR TITLE
Fix focus loss when using Auto-Type from locked database

### LINKED ISSUE #10439: 2.7.7: Auto-Type doesn't use correct window when database needs to be unlocked
## Overview
Installed KeePassXC 2.7.7 on Windows 10 and was unable to use the **Global Auto-Type shortcut** to auto-type passwords into website in Chrome. When typing master password into KeePassXC focus slips from username field in Chrome

## Steps to Reproduce
1. launch Chrome
2. visit website with login (e.g. bank)
3. place cursor in username field
4. type Global Auto-Type shortcut
5. enter master password
6. all passwords are shown
7. search for correct password
8. press enter
9. username/password are not entered into webpage

## Expected Behavior
Only passwords whose Auto-Type settings match should be listed.
Username/password is entered into username and password fields based on auto-type sequence

## Actual Behavior
In most instances all passwords are listed and correct username/password must be searched for
After finding correct username/password entry entry and hitting enter, username and password fields are not filled in as focus is no longer on username field

## Context
Every webiste I tried for which I have a login via Chrome

KeePassXC - 2.7.7
Revision: latest as of 3-13-2024
Reverted to Version 2.7.6 Revision: dd21def to restore functionality

Operating System: Microsoft Windows 10 Home
Version 10.0.19045 Build 19045
Windows default UI

Chrome Version 122.0.6261.129 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #10439

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested manually

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/autotype/AutoType.cpp [hunk 1]
```diff
@@ -339,20 +339,22 @@ void AutoType::executeAutoTypeActions(const Entry* entry,
...
-    m_windowTitleForGlobal.clear();
+        // Last action failed to complete, cancel the rest of the sequence
+        if (failed) {
+            break;
+        }
+    }
 
-    emit autotypePerformed();
+    resetAutoTypeState();
     m_inAutoType.unlock();
```
Comment (phoerious) [inline src/autotype/AutoType.cpp:356]: This could be a QMutexLocker.

**Review by phoerious — APPROVED** [review]

File: src/autotype/AutoType.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/autotype/AutoType.cpp:356]: QMutexLocker doesn't let you test for a lock, we test if it is already locked and bail out if it is instead of blocking.
