### PR TITLE
Fix annoyances with access control dialog

### LINKED ISSUE #4639: Browser access confirmation dialog pops up on tab change
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
This only happens while currently on a website that requires confirmation of credentials. When a new database tab is selected, the browser access confirmation dialog pops up, steals focus, and regardless of whether Allow or Deny is chosen KeePassXC minimizes.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to a website that requires credential access confirmation
2. Open multiple databases
3. Switch between database tabs

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Merely switching database tabs will not re-trigger a credential access confirmation. This should only happen when the user refreshes the page, clicks "Reload" in the extension popup menu, or requests credentials from the KPXC icon on the page.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Access confirmation is triggered every time.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Occurs in 2.6.0-develop

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Changes made:
- When "Search from all databases" is enabled, access control dialog is not executed when switching between open databases. Switching from locked to to open again, the dialog will be shown.
- Do not hide the application main window when switching databases when the access control dialog is visible. Switching to another tab rejects the dialog.

Fixes #4639.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -803,10 +804,15 @@ QList<Entry*> BrowserService::confirmEntries(QList<Entry*>& pwEntriesToConfirm,
         return {};
     }
 
+    bool bDatabaseChanged = false;
     m_dialogActive = true;
     BrowserAccessControlDialog accessControlDialog;
 
     connect(m_dbTabWidget, SIGNAL(databaseLocked(DatabaseWidget*)), &accessControlDialog, SLOT(reject()));
+    connect(
+        m_dbTabWidget, &DatabaseTabWidget::activateDatabaseChanged, [&bDatabaseChanged]() { bDatabaseChanged = true; });
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp:813]: I'm surprised this doesn't cause a crash. bDatabaseChanged will be deallocated as soon as this function returns. Also when using lambda functions in connect statements we should always include the "context" which in this case would be `this` right before the lambda. This ensures the lambda function is disconnected if the context is destroyed.

Comment (varjolintu) [reply src/browser/BrowserService.cpp:813]: Did I understood this correctly: it's enough if I change this to: `connect(
        m_dbTabWidget, &DatabaseTabWidget::activateDatabaseChanged, this, [&bDatabaseChanged]() { bDatabaseChanged = true; });` ?
