### PR TITLE
Save to canonical path when dealing with symlinks

### LINKED ISSUE #3435: Linked database file become a regular file
I make a link to an database file. If I open the database through the linked file, then modify and save the database, the link is gone and a regular file saved over the link.

## Expected Behavior
The link to the original file is remaining as a link.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The link to the original file saved as a regular file (copy of the original one).

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create a link to the original file.
createlink4file

2. Open the database through this link. Edit something and save the database.
3. The link file is gone, and the copy of the original file is created at the link path.
aftereditlink4file

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
The original KeePass 2.42.1 program don't do that.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3

Operating system: Manjaro Linux
CPU architecture: 64bit
Kernel: 4.19.62-1-MANJARO
neofetch

Enabled extensions:
- None

I do not speak English well. Sorry about that.

### PR DESCRIPTION
**Pull request by brainplot**
Symlinks and Windows shortcuts are now handled correctly when atomic save is disabled.

## Type of change
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
The `save` routine is passed the canonical path when a symlink or Windows shortcut is used as the database path. Previously it overwrote the symlink with a regular file. Fixes #3435.

## Testing strategy
I tested my changes manually by opening a symlink to a dummy database I created for the purpose.
I also ran all the existing tests to make sure nothing broke.

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/core/Database.cpp [hunk 1]
```diff
@@ -179,8 +179,8 @@ bool Database::save(QString* error, bool atomic, bool backup)
         }
         return false;
     }
-
-    return save(m_data.filePath, error, atomic, backup);
+    const QFileInfo info(m_data.filePath);
+    return save(info.isSymLink() ? info.symLinkTarget() : m_data.filePath, error, atomic, backup);
```
Comment (droidmonkey) [inline src/core/Database.cpp]: You want to use `QFileInfo::canonicalFilePath()` because it returns a blank string if the file does not exist and is a no-op for actual files. See https://doc.qt.io/qt-5/qfileinfo.html#canonicalFilePath

No need to check if the file is a symlink either.

Comment (droidmonkey) [reply src/core/Database.cpp]: However, you will want to make this change in the other save function since that is called by DatabaseWidget. I actually have a pending branch I did to fix this issue and hadn't pushed it yet.

**Comment by brainplot** [comment]
I made the changes. I hope it's fine now. If it's now I'll leave it to you, since you only need to push your branch with the fix. Sorry for stepping on your toes :)

**Comment by droidmonkey** [comment]
Hmmmm this method I proposed might break save as to a new file

**Comment by brainplot** [comment]
Should be okay now, unless something slipped by during my tests. I let `canonicalFilePath` be a reference to the resolved path only if it already exists.

Note: I left `const` out in an attempt to keep the line shorter. It will get automatically inferred by the compiler but I can add it back in if deemed better for clarity :)

**Comment by droidmonkey** [comment]
Looks exactly like my code branch with your fix, A+!

**Comment by droidmonkey** [comment]
Looks exactly like my code branch with your fix, A+!
