### PR TITLE
Fix db history when adding new db

### LINKED ISSUE #8375: Newly created database does not get added to history / recent databases
## Overview

A newly created database does not get added to history / recent databases.

## Steps to Reproduce

* Database -> New database
* ... fill in all relevant details ...
* save to "~/mydatabase.kdbx"
* Database -> Close database

## Expected Behavior

"~/mydatabase.kdbx" shows up in the recent databases list, both in the listview and in the Database -> Recent databases menu.

## Actual Behavior

"~/mydatabase.kdbx" has no entry in the history / recent databases

## Context

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.5
Debugging mode is disabled.

Operating system: Fedora Linux 36 (Thirty Six)
CPU architecture: x86_64
Kernel: linux 5.18.17-200.fc36.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

### PR DESCRIPTION
**Pull request by dmaslenko**
Fixes #8375 bug when just created new db was not reflected in the db history (recent files).

Now on a successfully created file it emits a signal to the parent widget to update the last dbs list.

### Start the app and check how many recent files you have --> Create a new `test` DB
welcome-with-one-recent-db

### Close the just created DB
close-db

### Verify the recent files on the welcome page
welcome-with-two-recent-db

### Verify the updated app ini file
app-config

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by dmaslenko** [comment]
I am still checking how it can be covered by GUI tests...

File: src/gui/DatabaseWidget.cpp [hunk 1]
```diff
@@ -216,6 +216,7 @@ DatabaseWidget::DatabaseWidget(QSharedPointer<Database> db, QWidget* parent)
     connect(m_csvImportWizard, SIGNAL(importFinished(bool)), SLOT(csvImportFinished(bool)));
     connect(this, SIGNAL(currentChanged(int)), SLOT(emitCurrentModeChanged()));
     connect(this, SIGNAL(requestGlobalAutoType(const QString&)), parent, SLOT(performGlobalAutoType(const QString&)));
+    connect(this, SIGNAL(updateLastDatabases(const QString&)), parent, SLOT(updateLastDatabases(const QString&)));
```
Comment (droidmonkey) [inline src/gui/DatabaseWidget.cpp]: This is an anti-pattern. You should always connect from parent to child, not child to parent. This should be in DatabaseTabWidget

File: src/gui/DatabaseWidget.h [hunk 2]
```diff
@@ -153,6 +153,7 @@ class DatabaseWidget : public QStackedWidget
     void clearSearch();
     void requestGlobalAutoType(const QString& search);
     void requestSearch(const QString& search);
+    void updateLastDatabases(const QString& search);
```
Comment (droidmonkey) [inline src/gui/DatabaseWidget.h]: No need to introduce a new signal, just use databaseSaved.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

**Comment by droidmonkey** [comment]
It doesn't need gui tests, more trouble than it's worth

File: src/gui/DatabaseWidget.cpp (hunk 1 above)
Comment (dmaslenko) [reply src/gui/DatabaseWidget.cpp]: I just followed the above example, line 218.
Ok, I moved the `connect` to the `DatabaseTabWidget` class.
Actually this solution does not work, for some reason the `filePath` is empty. May be I missed something?

File: src/gui/DatabaseWidget.h (hunk 2 above)
Comment (dmaslenko) [reply src/gui/DatabaseWidget.h]: In this case I need to introduce `void updateLastDatabases(int index)` which will call the `void updateLastDatabases(const QString& filePath);` with the current file path.
```c++
void DatabaseTabWidget::updateLastDatabases(int index) {
    if (index == -1) {
        index = currentIndex();
    }

    auto filePath = databaseWidgetFromIndex(index)->database()->filePath();
    // FIXME: the filePath is empty here

    updateLastDatabases(filePath);
}
```
But this solution does not work:
empty-file-name-in-history

File: src/gui/DatabaseTabWidget.cpp [hunk 3]
```diff
@@ -829,6 +830,17 @@ void DatabaseTabWidget::updateLastDatabases(const QString& filename)
     }
 }
 
+void DatabaseTabWidget::updateLastDatabases(int index) {
+    if (index == -1) {
```
Comment (droidmonkey) [inline src/gui/DatabaseTabWidget.cpp]: You'll want to check that the index is out of range entirely, so index < 0 || index >= count()

You also need to check that you have a count at all, if there are no database widgets you should just return. 

You can also do this by trying to get the database widget by index, of nullptr then try `currentDatabaseWidget` if nullptr return, otherwise check for a file name and if present continue with the function.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/gui/DatabaseTabWidget.cpp (hunk 3 above)
Comment (dmaslenko) [reply src/gui/DatabaseTabWidget.cpp]: Thank you for ideas, I will try...

Comment (dmaslenko) [reply src/gui/DatabaseTabWidget.cpp]: Check my latest update, I found an example without `index` and as for me it looks more concise. Let me know if a variant with `index` is better.
Also I found a reason why it did not work yesterday: in the `Database` class I changed the order of `setFilePath()` and `markAsClean()`. Now it works.

**Review by droidmonkey — APPROVED** [review]

File: src/gui/DatabaseTabWidget.cpp (hunk 3 above)
Comment (droidmonkey) [reply src/gui/DatabaseTabWidget.cpp]: That is a good catch with the mark as clean! 

The code is very elegant now, great work

**Comment by dmaslenko** [comment]
I decided to add a unit test for `saveAs()` method to verify the expected signal was emitted and a file was created.

**Comment by dmaslenko** [comment]
Wondering why TeamCity builds are pending?

**Comment by droidmonkey** [comment]
We have been having a lot of issues with team city controlling the kubernetes based agents

**Review by droidmonkey — APPROVED** [review]
