### PR TITLE
SSH Agent: Reset settings when KeeAgent.settings is removed

### LINKED ISSUE #4020: SSH Agent settings added to entry when not needed
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeeAgent.settings should only be added to an entry when there are settings to store, as in a key is set up to be used.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
KeeAgent.settings are added to an entry on some occasions.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Don't add KeeAgent.settings if it does not exist and the key is not set up (i.e. chosen attachment or path are empty).

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Enable SSH Agent
2. Restart the program
3. Create a new entry and add an attachment.
    * Also works when editing an existing entry.
4. Save it by pressing `Ok`.
5. Notice that KeeAgent.settings is present but not required

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
The impact of this issue is minor at best. I noticed it when I opened my database on my phone and looked at an entry where I added an attachment.
The ~1.4 KB the file adds to the entry is not large but it could add up for a larger database and could become noticeable when syncing it on a mobile client.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.1
Revision: 0fd8836

Libraries:
-  libgcrypt 1.8.5

Operating system: Windows 10 (10.0)
CPU architecture:  x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

### LINKED ISSUE #4594: SSH Agent: Hidden KeeAgent settings flags prevent removing agent settings from entry
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Removing KeeAgent.settings attachment by hand should allow the user to reset the settings on-the-fly.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Hidden non-default KeeAgent settings can prevent the attachment from being removed. It's also rather annoying you need to manually reset each setting.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

a. Add a button on SSH Agent page on entry settings to "Reset" settings (force KeeAgentSettings defaults)
b. Hook attachment management in a way that when the user deletes KeeAgent.settings file by hand it will also reset the settings page and all hidden flags if present

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create KeeAgent.settings from KeePass that has save to temp file checked
2. Open entry in KeePassXC
3. Try to delete KeeAgent.settings or reset the settings by hand
4. Attachment persists

### PR DESCRIPTION
**Pull request by hifi**
Fixes #4594
Fixes #4020 

[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Testing strategy
Manual clicking in the UI. Seems to work as intended.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

File: src/sshagent/KeeAgentSettings.cpp [hunk 1]
```diff
@@ -50,6 +50,15 @@ bool KeeAgentSettings::isDefault() const
     return (*this == defaultSettings);
 }
 
+/**
+ * Reset this instance to default settings
+ */
+void KeeAgentSettings::reset()
+{
+    KeeAgentSettings defaultSettings;
+    *this = defaultSettings;
```
Comment (droidmonkey) [inline src/sshagent/KeeAgentSettings.cpp:59]: I am not a fan of this method of resetting.

Comment (hifi) [reply src/sshagent/KeeAgentSettings.cpp]: Did exactly this now.
