### PR TITLE
Fix autotype syntax to support custom attributes

### LINKED ISSUE #1546: Spaces in additional attribute not working for autotype
## Expected Behavior

In 2.2.4 I had an additional attribute with a space in it like `SOME NAME` and it worked when using it for autotype sequence using something like `{S:SOME NAME}`.

## Current Behavior

In 2.3.0 Autotype sequences with attributes like `{S:SOME NAME}` containing spaces gives the error `The Syntax of your Auto-type statement is incorrect` (whereas `{S:SOMENAME}` gives no error). Not sure if this is new behavior in 2.3.0 (using KDBX4) but just something I wanted to ask about in case it's a bug.

Operating system: Windows

### PR DESCRIPTION
**Pull request by TheZ3ro**
## Description

Fix #1546 
Extend the Autotype Syntax to Custom Fields/Attributes

## How has this been tested?

Manually and with tests

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ I have added tests to cover my changes.

### CODE REVIEW

File: tests/TestAutoType.cpp [hunk 1]
```diff
@@ -277,6 +277,15 @@ void TestAutoType::testAutoTypeSyntaxChecks()
 
     QCOMPARE(true, AutoType::checkSyntax("{NUMPAD1 3}"));
 
+    QCOMPARE(true, AutoType::checkSyntax("{S:SPECIALTOKEN}"));
```
Comment (phoerious) [inline tests/TestAutoType.cpp]: You should use Q_ASSERT, not QCOMPARE.

Comment (TheZ3ro) [reply tests/TestAutoType.cpp]: I would say QVERIFY

Comment (phoerious) [reply tests/TestAutoType.cpp]: Yes, I meant QVERIFY.
