### PR TITLE
Preserve group/entry focus when replacing db.

### LINKED ISSUE #144: Saving database resets the current folder to Root
If you edit an entry and hit Control+S to save the database, the current focus gets moved to the first entry in the Root folder.

## Expected Behavior
The current focus (folder or entry) should stay so you can keep working there.

KeePassX 2.0.3 does not change the current entry or folder.

## Current Behavior
The focus will be moved to the first entry in the Root folder.

## Steps to Reproduce (for bugs)
1. Set focus on an entry that is not at the top, not in the Root folder 
2. Hit Control+S to save the database
3. The focus will be moved to the first entry in the Root folder

## Your Environment
* KeePassXC from the latest develop branch (ff6d78244bdb5b70839b211eb57827ce2c1f31d6)
* Qt 5.6.2: 
* Apple LLVM version 8.0.0 (clang-800.0.42.1)
* macOS 10.11.6

### PR DESCRIPTION
**Pull request by louib**
## Description

The group and entry focus was lost when saving a new entry because of the autoreload feature.
I added the `restoreGroupEntryFocus`. While testing, I realized the entry focus was also lost when locking / unlocking the db (the group focus was preserved though), so I added that to the locking / unlocking also.

## Motivation and Context
Fixes #144 

## How Has This Been Tested?
Unit tests + tested manually that the bug was fixed on MacOS.
I did **not** test with linux yet (I will!)

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

File: src/gui/DatabaseWidget.cpp [hunk 1]
```diff
@@ -1061,6 +1075,37 @@ QStringList DatabaseWidget::customEntryAttributes() const
     return entry->attributes()->customKeys();
 }
 
+/*
+ * Restores the focus on the group and entry that was focused
+ * before the database was locked or reloaded.
+ */
+void DatabaseWidget::restoreGroupEntryFocus(Uuid groupUuid, Uuid entryUuid)
+{
+    Group* restoredGroup;
```
Comment (droidmonkey) [inline src/gui/DatabaseWidget.cpp]: This should be explicitly set to nullptr

File: src/gui/DatabaseWidget.cpp [hunk 2]
```diff
@@ -1061,6 +1075,37 @@ QStringList DatabaseWidget::customEntryAttributes() const
...
+    const QList<Group*> groups = m_db->rootGroup()->groupsRecursive(true);
+    for (Group* group : groups) {
+        if (group->uuid() == groupUuid) {
+            restoredGroup = group;
+            break;
+        }
+    }
+
+    if (!restoredGroup) {
```
Comment (droidmonkey) [inline src/gui/DatabaseWidget.cpp]: preferably this should be ```if (restoredGroup != nullptr)``` followed by the remainder of the function instead of an "early out" negative test for cleaner code.

**Comment by louib** [comment]
@droidmonkey thanks for the review! I also tested on Linux to make sure everything is working fine.

**Comment by droidmonkey** [comment]
Excellent work!

**Comment by phoerious** [comment]
I think this should be backported to 2.1.2.
