### PR TITLE
Turn search reset off by default

### LINKED ISSUE #9145: Turn search reset off by default
## Overview

If I use the search function to find an item, after a short while (a minute?) the undone and results are unfiltered (e.g.: as if I'd never done the search).

## Steps to Reproduce
1. Search for anything that filters out some entries.
2. Wait.
3. Search is undone.

## Expected Behavior

The application should retain it's state and not reset.

## Actual Behavior

The application loses it's state after a short while. I always feel like I have to "rush" for it to not lose what I'm doing.

## Context

The behavior is much on iPhone (and I think Android?), where the OS kills applications in the background after a while, which results in applications losing their state. This is a bug due to a technical limitation, not an actual feature, but KPXC seems to do the same on Linux desktop.

```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Linux 6.1.12-0-edge
CPU architecture: x86_64
Kernel: linux 6.1.12-0-edge

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

### PR DESCRIPTION
**Pull request by WhyNotHugo**
This is more user friendly, especially to newcomers.

Fixes: https://github.com/keepassxreboot/keepassxc/issues/9145

## Type of change

- ✅ Breaking change (causes existing functionality to change)

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Do you want me to add a CHANGELOG entry, or do those get added all at once before the release?

**Comment by droidmonkey** [comment]
We make change log at end

File: src/core/Config.cpp [hunk 1]
```diff
@@ -127,7 +127,7 @@ static const QHash<Config::ConfigKey, ConfigDirective> configStrings = {
     // Security
     {Config::Security_ClearClipboard, {QS("Security/ClearClipboard"), Roaming, true}},
     {Config::Security_ClearClipboardTimeout, {QS("Security/ClearClipboardTimeout"), Roaming, 10}},
-    {Config::Security_ClearSearch, {QS("Security/ClearSearch"), Roaming, true}},
+    {Config::Security_ClearSearch, {QS("Security/ClearSearch"), Roaming, false}},
```
Comment (dmaslenko) [inline src/core/Config.cpp:130]: Wondering, why no failed GUI tests where this option is selected by default?
Probably we don't have a test with default values and test configs are predefined.
SelectedClearSearchOption

Comment (droidmonkey) [reply src/core/Config.cpp:130]: The gui tests are brittle enough. I don't care to test  things like that, especially non-critical features.

**Review by droidmonkey — APPROVED** [review]
