### PR TITLE
Reduce delay when searching entries in Auto-Type select dialog

### LINKED ISSUE #7596: Auto-Type window filtering has a delay since 2.7.0
## Overview
Before 2.7.0 I used to press my Auto-Type shortcut, which opened the Auto-Type window. To select a common entry I just pressed one letter on the keyboard to have that entry selected/filtered in the Auto-Type window. I immediately pressed enter after pressing the key to filter the values and it worked well. Now when typing (in order to filter) there is a delay.

## Steps to Reproduce
1. Have multiple Entries that would show up on a window of your choice when pressing the Auto-Type shortcut
2. Press the Auto-Type shortcut in the window of your choice
3. Type letters to filter the entries in the Auto-Type window
4. See the delay
5. You can't press immediately Enter after typing your filter letter/string because of the delay you would select the wrong entry

## Expected Behavior
I can just do this in the fastest possible way without a delay that causes me to select the wrong entry if I am too fast:
1. Press Auto-Type shortcut
2. Press keys to filter the Auto-Type entries
3. Press Enter

## Actual Behavior
I have to wait when doing the step 2 in "Expected behaviour" because of the delay.

## Context
came with 2.7.0

```
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.16.16-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

Operating System: Linux
Desktop Env: [dwm](https://dwm.suckless.org/)
Windowing System: X11

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fix #7596

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by pauschuu — APPROVED** [review]
Looks good to me.
Built and tested on my system, works.

File: src/autotype/AutoTypeSelectDialog.cpp [hunk 1]
```diff
@@ -71,7 +71,7 @@ AutoTypeSelectDialog::AutoTypeSelectDialog(QWidget* parent)
 
     m_ui->searchCheckBox->setShortcut(Qt::CTRL + Qt::Key_F);
     connect(m_ui->searchCheckBox, &QCheckBox::toggled, this, [this](bool checked) {
-        Q_UNUSED(checked);
+        m_searchTimer.setInterval(checked ? 150 : 0);
```
Comment (hifi) [inline src/autotype/AutoTypeSelectDialog.cpp]: This logic needs to be duplicated in `AutoTypeSelectDialog::setMatches` because it prevents the signal from being fired on initial setup when the dialog is opened to prevent double search.

**Review by hifi — CHANGES_REQUESTED** [review]
Found one issue, need to make the delay a shared const as well.

File: src/autotype/AutoTypeSelectDialog.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/autotype/AutoTypeSelectDialog.cpp]: Doesn't the signal get blocked in setMatches and an explicit call to perform search is made?

Comment (hifi) [reply src/autotype/AutoTypeSelectDialog.cpp]: Yes, but doesn't that also mean that it call setInterval when the check is grayed out but checked?

Comment (droidmonkey) [reply src/autotype/AutoTypeSelectDialog.cpp]: Good point

**Review by hifi — APPROVED** [review]
Ship it :+1:
