### PR TITLE
Correct latent single instance lock file preventing launch

### LINKED ISSUE #893: Startup fails with error message "Another instance of KeePassXC is already running"
Keepassrc does not start, only shows "Another instance of KeePassXC is already running" although there is no keepassrc process and even no configs in ./config/ (no keepassxcrc etc.)

## Expected Behavior
Successful startup

## Debug Info
Information for package keepassxc:
----------------------------------
Repository     : Security                         
Name           : keepassxc                        
Version        : 2.2.0-14.2                       
Arch           : x86_64                           
Vendor         : obs://build.opensuse.org/security
Installed Size : 6.8 MiB                          
Installed      : Yes                              
Status         : up-to-date                       
Source package : keepassxc-2.2.0-14.2.src         
Summary        : Qt5-based Password Manager 

Libraries:
- LIBS

Operating system: OpenSUSE leap 42.2, 
CPU architecture: 64 bit
Kernel: 4.4.79-18.26-default
plasmashell 5.8.6

Enabled extensions:
- EXTENSIONS

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

* Fixes #893, if connection to the listen server fails three times, the lock file is removed and a new listen server is started.

I also took the opportunity to bring this code into alignment with the coding standards for variable naming.

## Motivation and context

This issue has been reported 4 times since release of 2.2.0.

## How has this been tested?

Manually

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/Application.cpp [hunk 1]
```diff
@@ -99,56 +99,68 @@ Application::Application(int& argc, char** argv)
...
                     client.abort();
+                    m_alreadyRunning = true;
                     break;
                 }
             }
+
+            if (!m_alreadyRunning) {
+                // If we get here then the original instance is likely dead
+                // forceably reset the lock file
+                m_lockFile->removeStaleLockFile();
```
Comment (louib) [inline src/gui/Application.cpp]: @droidmonkey Maybe we could add a `qDebug` or `qWarn` here? Might be useful for debugging purposes.

Comment (droidmonkey) [reply src/gui/Application.cpp]: Good idea, I'll add that tonight

**Comment by droidmonkey** [comment]
Consistency in the code and i think it reads better. Bouncing between Kotlin and C++ I can never remember what is immutable and whst isn't.
