### PR TITLE
Fix Copy Password button when text is selected

### LINKED ISSUE #10734: Password is not copied when other text is selected in KeePassXC
## Overview
image
Looks like with selected text "Copy username" and "Copy URL" buttons works correctly, but not "Copy password" button.

## Steps to Reproduce
For the attached screenshot:
1. Select _Description_ from **Notes**.
2. Click "Copy password" button.

## Expected Behavior
The password value is copied (here "Password").

## Actual Behavior
The selected text is copied (here "Description").

## Context
```
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```

### PR DESCRIPTION
**Pull request by c4rlo**
When the user chooses to copy the password for an entry to the clipboard, previously there was logic to check if text was selected, and if so, that text was instead copied to the clipboard. That made sense if (a) the user invoked the Copy Password action via its keyboard shortcut, and (b) that keyboard shortcut was configured (as per default) to be Ctrl-C, i.e. the same as the system action for copy-to-clipboard.

However, it made no sense if the user invoked that action in some other way, for example by clicking the corresponding toolbar button.

It also made no sense in the case that the Copy Password action had some other keyboard shortcut assigned. Also, if some other action had Ctrl-C assigned, the logic would not kick in then.

Fix all of the above by modifying the keyboard shortcut logic to intervene precisely in the case where a shortcut is pressed that matches the system copy-to-clipboard shortcut; only in that case do we now check if text is selected and if so copy that to the clipboard instead of the action we would otherwise take.

Fixes #10734.

## Testing strategy

Added test to `TestGui.cpp`. Also confirmed via manual testing.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Love it, glad to use the new action collection too! I really couldn't figure out a fix to this, too focused on the toolbar action and not the keyboard shortcut.

File: src/gui/MainWindow.cpp [hunk 1]
```diff
@@ -2166,33 +2073,94 @@ void MainWindow::initActionCollection()
...
 
-    // All other actions with default shortcuts
-    ac->setDefaultShortcut(m_ui->actionDatabaseNew, Qt::CTRL + Qt::SHIFT + Qt::Key_N);
-    ac->setDefaultShortcut(m_ui->actionDatabaseSettings, Qt::CTRL + Qt::SHIFT + Qt::Key_Comma);
-    ac->setDefaultShortcut(m_ui->actionReports, Qt::CTRL + Qt::SHIFT + Qt::Key_R);
-    ac->setDefaultShortcut(m_ui->actionLockDatabase, Qt::CTRL + Qt::Key_L);
-    ac->setDefaultShortcut(m_ui->actionLockAllDatabases, Qt::CTRL + Qt::SHIFT + Qt::Key_L);
-    ac->setDefaultShortcut(m_ui->actionEntryEdit, Qt::CTRL + Qt::Key_E);
-    ac->setDefaultShortcut(m_ui->actionEntryDelete, Qt::CTRL + Qt::Key_D);
-    ac->setDefaultShortcut(m_ui->actionEntryDelete, Qt::Key_Delete);
```
Comment (c4rlo) [inline src/gui/MainWindow.cpp]: The second of these was overriding the first one, so only the Delete key was actually in effect. At this point I'm not sure what the desired behaviour is, so I've left this to only have the Delete key assigned to this action. I'm thinking this makes sense since the shortcut config UI only supports assigning a single shortcut to each action.

**Comment by c4rlo** [comment]
I actually have a slightly simpler approach now, based on `QObject::installEventFilter()`. Moving this back to Draft while I consider it.

**Comment by c4rlo** [comment]
Ok, this is ready for review now. I've undone all the refactoring and kept this more focused.

**Comment by c4rlo** [comment]
The macOS CI failure seems like some kind of test flakeyness, unrelated to this change. I have created #10901 to address that.

**Review by droidmonkey — APPROVED** [review]
