### PR TITLE
Fix: Disable 'Remove' button in Plugin Data when no row is selected

### LINKED ISSUE #12891: "Properties" -> "Plugin Data" -> "Remove" button enabled on first show with no rows selected
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

Image

Image

Image

KeePassXC - Version 2.7.11

### Steps to Reproduce

Select a key file
Click on a table area without data
Click elsewhere

### Expected Versus Actual Behavior

If not activated (images 1 and 3), it should behave in the same way. IMO grayed out.

### KeePassXC Debug Information

```Text

```

### Operating System

Windows

### Linux Desktop Environment

None

### Linux Windowing System

None

### PR DESCRIPTION
**Pull request by pranmya**
## Overview
Fixed a UI consistency issue in the "Properties" tab of the entry editor. Previously, the "Remove" button in the Plugin Data section was enabled by default if any data existed, even if no specific row was selected.

## Changes
- Modified `EditWidgetProperties::update()` in `src/gui/EditWidgetProperties.cpp`.
- Updated the logic to check for an active selection in `customDataTable` instead of just checking if the underlying data container is non-empty.
- This ensures the "Remove" button remains disabled until the user explicitly selects a row to delete.

## Screenshots
[Paste your "Before" and "After" screenshots here by dragging them into the box]

## Testing strategy
- **Manual Verification:** Built the application on Windows 11 with Qt 5.15.18 and verified that the button state now correctly reflects the selection state.
- **Persistence:** Verified the button correctly re-disables after a successful deletion or when the selection is cleared.
- **Regression:** Ran `ctest` to ensure no core logic was affected (95% pass rate, failures were unrelated to this UI change).

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)
- Fixes #12891
remove_active
remove_inactive

### CODE REVIEW

File: src/gui/EditWidgetProperties.cpp [hunk 1]
```diff
@@ -116,6 +116,7 @@ void EditWidgetProperties::update()
             m_customDataModel->appendRow(QList<QStandardItem*>()
                                          << new QStandardItem(key) << new QStandardItem(m_customData->value(key)));
         }
-        m_ui->removeCustomDataButton->setEnabled(!m_customData->isEmpty());
+        //m_ui->removeCustomDataButton->setEnabled(!m_customData->isEmpty());
+        m_ui->removeCustomDataButton->setEnabled(!m_ui->customDataTable->selectionModel()->selectedIndexes().isEmpty());
```
Comment (droidmonkey) [inline src/gui/EditWidgetProperties.cpp]: should just use `m_ui->customDataTable->selectionModel()->hasSelection()` and also do not include commented out code.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/gui/EditWidgetProperties.cpp (hunk 1 above)
Comment (pranmya) [reply src/gui/EditWidgetProperties.cpp]: I've updated the code to use .hasSelection() and removed the commented-out lines as suggested. Verified the fix locally on Windows 11. Thanks for the review!

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
Thanks!

**Comment by phoerious** [comment]
This was merged directly into 2.7.x. Do we need to forward-port it to develop?
