### PR TITLE
Fix: Sanitize username to prevent single-instance detection failure

### LINKED ISSUE #12049: Single instance detection doesn't work when USER env var is a non-standard value
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

The Option "Start only a single instance of KeePassXC" does not work. Even if I enabled it, I can start a second, third etc. session.

I think it's because on my computer there exists an environment variable "USER" with a stupid value (like "/../../ABC123/user/..") and this takes priority over the environment variable "USERNAME". As a result the ".lock"-File can not be created. 

Unfortunately the "USER"-Variable is needed by an important other application, so i can not delete it.

My proposal ist to insert something like this to "gui\Application.cpp":
#if defined (Q_OS_WIN)
    QString userName = qgetenv("USERNAME");
#else
    QString userName = qgetenv("USER");
    if (userName.isEmpty()) {
        userName = qgetenv("USERNAME");
    }
#endif

This way the behaviour only changes on Windows. Linux, MaxOS and others are not affected.

### Steps to Reproduce

1. Create an environment variable "USER" with value like "/../../ABC123/user/.." at user level
2. Start KeePassXC
3. Start KeePassXC again
4. search for %temp%\keepassxc-%username%.lock"

### Expected Versus Actual Behavior

If I enable the option "Start only a single instance of KeePassXC" only one instane of KeePassXC should run. All other starts should bring up this instance.

### KeePassXC Debug Information

```Text

```

### Operating System

Windows

### Linux Desktop Environment

None

### Linux Windowing System

None

### PR DESCRIPTION
**Pull request by sshekhar563**
Fixes #12049 

The single-instance detection feature fails on systems where the environment variable used for the username (USER or USERNAME) contains characters that are invalid in filenames (e.g., /, \).

This prevents the .lock file from being created, which causes the application to allow multiple instances to run simultaneously, even when the option is disabled.

Solution:

This PR resolves the issue by sanitizing the username string before it is used to construct the lock file identifier. It uses a regular expression to find and replace all invalid filename characters with an underscore (_).

This approach is more robust as it protects against invalid characters from any source, ensuring the lock file can always be created.

### CODE REVIEW

File: src/gui/Application.cpp [hunk 1]
```diff
@@ -63,10 +63,20 @@ Application::Application(int& argc, char** argv)
...
+    }
+#else
     QString userName = qgetenv("USER");
     if (userName.isEmpty()) {
         userName = qgetenv("USERNAME");
     }
+#endif
+
+userName.replace('/', '_');
+userName.replace('\\', '_');
```
Comment (droidmonkey) [inline src/gui/Application.cpp]: This is insufficient, we should remove all characters that are not allowed in file names. https://stackoverflow.com/a/31976060

**Review by droidmonkey — CHANGES_REQUESTED** [review]

**Comment by sshekhar563** [comment]
Hi @droidmonkey , I’ve applied the requested changes
Please review the updates at your convenience and let me know if anything else is needed. Thanks!

**Review by droidmonkey — APPROVED** [review]
