### PR TITLE
Fix health check reused password count tooltip (#13075)

### LINKED ISSUE #13075: Health Check reused password count discrepancy
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

When hovering over a Health Check entry of a password that is used 20 times, all 20 entries are displayed _plus_ an ellipsis (...) which incorrectly indicates more passwords.

Image

This minor issue could be confusing for new users with a few heavily-reused passwords.

### Steps to Reproduce

1. Open a database.
2. Have a password used exactly 20 times.
3. Open Health Check.
4. Hover over one of the reused entries.
5. See 20 entries + an incorrect extra ellipsis.

### Expected Versus Actual Behavior

Expected: Ellipsis is shown when a password is used _more than 20_ times.

Actual: Ellipsis is shown when a password is used _20 or more_ times, including exactly 20.

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.7.11
Revision: 01e5b6e

Qt 5.15.18
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.18.9-arch1-2

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.10.0
```

### Operating System

Linux

### Linux Desktop Environment

Other

### Linux Windowing System

Wayland

### PR DESCRIPTION
**Pull request by JCira-OSU**
Fixes #13075
Removed if-break check from detail display loop; moved entry display limit to the loop definition.
Added specific check (after loop) if >20 duplicates before showing ellipsis.

## Screenshots
Current release build:
image

Build with changes applied (with 20 entries sharing password):
image

Build with changes applied (with 21 entries sharing password):
image

## Testing strategy
Manual.
1. Opened test database
2. Create 19 entries sharing the same password
3. Add 20th entry, check for ellipsis
4. Add 21st entry, check for ellipsis

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/core/PasswordHealth.cpp [hunk 1]
```diff
@@ -151,12 +151,11 @@ QSharedPointer<PasswordHealth> HealthChecker::evaluate(const Entry* entry) const
...
+        for (int i = 0; i < (count < 20 ? count : 20); ++i) {
             health->addScoreDetails(used[i]);
-            if (i == 19) {
-                health->addScoreDetails("…");
-                break;
-            }
+        }
+        if (count > 20) {
+            health->addScoreDetails("...");
         }
```
Comment (droidmonkey) [inline src/core/PasswordHealth.cpp]: The easier (less code) fix is to move the i == 19 check above the addscoredetails line and changing it to i==20, then the loop will break properly.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

**Comment by JCira-OSU** [comment]
I made the change you suggested.  But, out of curiosity, isn't it more efficient to move the check after the loop?

**Comment by droidmonkey** [comment]
The loop will only ever run up to 20 times, efficiency is certainly not a problem here. Code clarity is more important.

**Review by droidmonkey — APPROVED** [review]
