### PR TITLE
Fix setting window title as modified

### LINKED ISSUE #11540: Window title change indicator (`*`) not updated in time
## Overview

Unless you click the "Password Generator" or "Settings" button to enter other interfaces, the modification status indicator in the window title will not be updated in time. Either after modification or after saving.

https://github.com/user-attachments/assets/f02ac3f7-b47b-4157-a941-03d26076f4a5

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
When creating a new entry to database, the window title does not include an asterisk character. When going to Settings / Password generator, the title appears correctly.

Fixes #11540

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually. Switching tab to a closed database, or Settings / Password generator removes the asterisk character from the title.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by varjolintu** [comment]
Noticed that this fix works, but Qt gives a warning to the console: `QWidget::setWindowModified: The window title does not contain a '[*]' placeholder`. If we want to get rid of that warning too, another solution must be found.

Even if `MainWindow::updateWindowTitle()` has `isModified` set to `false`, in some cases the title will still include the asterisk character.

File: src/gui/MainWindow.cpp [hunk 1]
```diff
@@ -1033,8 +1033,8 @@ void MainWindow::updateWindowTitle()
 
     if (stackedWidgetIndex == DatabaseTabScreen && tabWidgetIndex != -1) {
         customWindowTitlePart = m_ui->tabWidget->tabName(tabWidgetIndex);
-        if (isModified) {
-            // remove asterisk '*' from title
+        if (!isModified) {
+            // Remove asterisk '*' from title
             customWindowTitlePart.remove(customWindowTitlePart.size() - 1, 1);
```
Comment (droidmonkey) [inline src/gui/MainWindow.cpp:1037]: This line is not good because it assumes an asterisk is the very last character.

File: src/gui/MainWindow.cpp [hunk 2]
```diff
@@ -1033,8 +1033,8 @@ void MainWindow::updateWindowTitle()
...
         }
         m_ui->actionDatabaseSave->setEnabled(m_ui->tabWidget->canSave(tabWidgetIndex));
```
Comment (droidmonkey) [inline src/gui/MainWindow.cpp:1039]: This should be handled within the action state function instead of here.

**Comment by droidmonkey** [comment]
https://doc.qt.io/qt-5/qwidget.html#windowModified-prop

> The window title must contain a "[*]" placeholder, which indicates where the '*' should appear. Normally, it should appear right after the file name (e.g., "document1.txt[*] - Text Editor"). **If the window isn't modified, the placeholder is simply removed.**

The placeholder should be in the window title no matter what.

File: src/gui/MainWindow.cpp (hunk 1 above)
Comment (varjolintu) [reply src/gui/MainWindow.cpp:1037]: Yes, I have already changed this to `.replace()` in my test branch. That line also removed the last `]` in some cases even without this change.

Comment (droidmonkey) [reply src/gui/MainWindow.cpp:1037]: Perhaps an adjustment to the tab widget function is in order as well, I briefly looked at it and seemed too much

Comment (varjolintu) [reply src/gui/MainWindow.cpp:1037]: Seems that we need a new can after the worms are all out.

File: src/gui/MainWindow.cpp (hunk 2 above)
Comment (varjolintu) [reply src/gui/MainWindow.cpp:1039]: Where? This might be actually needed because the tab name has been set with the asterisk. If that is not removed, the window title placeholder will show `**`.

**Comment by varjolintu** [comment]
I made a simple fix for this where the title is set to the placeholder first, and then to the actual one. It was the only way I could find to go around this (I'm pretty sure it's some kind of Qt bug). Also tried the title setter as a signal/slot (tried both: settings modified and/or setting the title), but that didn't solve the issue either.

**Comment by droidmonkey** [comment]
Is this ready to go?

**Comment by varjolintu** [comment]
> Is this ready to go?

Yes. If everything works for you as well.

File: src/gui/MainWindow.cpp [hunk 3]
```diff
@@ -1034,8 +1034,8 @@ void MainWindow::updateWindowTitle()
     if (stackedWidgetIndex == DatabaseTabScreen && tabWidgetIndex != -1) {
         customWindowTitlePart = m_ui->tabWidget->tabName(tabWidgetIndex);
         if (isModified) {
-            // remove asterisk '*' from title
-            customWindowTitlePart.remove(customWindowTitlePart.size() - 1, 1);
+            // Remove asterisk '*' from title
+            customWindowTitlePart.replace("*", "");
```
Comment (droidmonkey) [inline src/gui/MainWindow.cpp]: This will technically remove all asterisks in the tab name entirely which may be totally valid if the database name has them like `**MY DATABASE**`. The previous code was actually "right" but relied on DatabaseTabWidget doing what we expect.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/gui/MainWindow.cpp (hunk 3 above)
Comment (varjolintu) [reply src/gui/MainWindow.cpp]: Didn't though about that kind of naming scenario. I'll modify this to a regex, or whatever suits the best.

**Review by droidmonkey — APPROVED** [review]
