### PR TITLE
Fix wrong horizontal QR code resizing

### LINKED ISSUE #8944: QR code is stretched horizontally within its window
## Overview
Resizing the QR code display window horizontally distorts the QR code itself, i.e. it's not square anymore.

## Steps to Reproduce
1. Select "TOTP / Show QR Code" from the context menu of an entry.
2. Resize the window horizontally.

## Expected Behavior
The QR code should always be square, centered and as large as possible within the limits of its allocated window are. (If the window is resized _vertically_, the program behaves correctly.)

## Actual Behavior
The QR code is stretched horizontally, covering the whole width of the window. Scanning it with a smartphone camera will not work correctly.

## Context
KeePassXC - Version 2.7.4
Revision: 63b2394
Qt 5.15.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

### PR DESCRIPTION
**Pull request by dmaslenko**
Fixes #8944 issue when the QR code was wrongly resized horizontally

### Before
stratched-qr-code

### After
fixed-qr-code-centered

## Testing strategy
- Have an entry with defined TOTP.
- Open the QR code window and try to stretch it.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by phoerious — APPROVED** [review]
Thanks! Looks good to me.

**Comment by droidmonkey** [comment]
This doesn't solve the problem because the QR Code remains the same size. The point of resizing the window is to get a bigger qr code.

**Comment by phoerious** [comment]
Do we need that? IMHO we could even make the window a fixed size.

**Comment by droidmonkey** [comment]
I don't disagree. Perhaps the real problem is initial sizing of the qrcode is not dpi dependent, although it works great on my 4k screen so not sure what's the matter.

**Comment by phoerious** [comment]
Proportional resizing would be fine as well, I don't really care.

**Comment by dmaslenko** [comment]
I am still working to find a solution to center it or stop me here :)
scalable-qr-code-not-centered

**Comment by dmaslenko** [comment]
The next commit allows to scale and center the QR code. It looks like:
Screencast from 01-28-2023 03 13 26 PM

Let me check if UI test is possible here...

**Comment by droidmonkey** [comment]
You could test by setting the dialog size and checking that the size of the qr svg is bigger and still square.

File: src/gui/SquareSvgWidget.h [hunk 1]
```diff
@@ -18,16 +18,20 @@
...
 
+#include <QLayout>
 #include <QSvgWidget>
 
 class SquareSvgWidget : public QSvgWidget
 {
 public:
-    SquareSvgWidget() = default;
+    explicit SquareSvgWidget(QWidget* parent)
+        : QSvgWidget(parent){};
```
Comment (droidmonkey) [inline src/gui/SquareSvgWidget.h]: Our convention is to have the constructor definition in the cpp file

File: src/gui/SquareSvgWidget.cpp [hunk 2]
```diff
@@ -26,3 +28,21 @@ int SquareSvgWidget::heightForWidth(int width) const
...
+// The overridden logic allows to keep the SVG image as square and centered by width and height.
+void SquareSvgWidget::resizeEvent(QResizeEvent*)
+{
+    Q_ASSERT(parentWidget());
+    auto containerRect = parentWidget()->contentsRect();
+
+    auto containerWidth = containerRect.width();
+    auto containerHeight = containerRect.height();
+
+    auto squareSize = std::min(containerWidth, containerHeight);
```
Comment (droidmonkey) [inline src/gui/SquareSvgWidget.cpp]: use `qMin` to avoid importing cmath

File: src/gui/SquareSvgWidget.cpp [hunk 3]
```diff
@@ -16,6 +16,8 @@
  */
 
 #include "SquareSvgWidget.h"
+#include "QResizeEvent"
```
Comment (droidmonkey) [inline src/gui/SquareSvgWidget.cpp]: Needs to be placed in `< >`

File: src/gui/SquareSvgWidget.h [hunk 4]
```diff
@@ -18,16 +18,20 @@
 #ifndef KEEPASSX_SquareSvgWidget_H
 #define KEEPASSX_SquareSvgWidget_H
 
+#include <QLayout>
```
Comment (droidmonkey) [inline src/gui/SquareSvgWidget.h]: I don't think this is needed

File: src/gui/TotpExportSettingsDialog.cpp [hunk 5]
```diff
@@ -29,25 +29,28 @@
...
 #include <QPushButton>
 #include <QShortcut>
+#include <QStackedWidget>
 
 TotpExportSettingsDialog::TotpExportSettingsDialog(DatabaseWidget* parent, Entry* entry)
     : QDialog(parent)
     , m_timer(new QTimer(this))
     , m_verticalLayout(new QVBoxLayout())
-    , m_totpSvgWidget(new SquareSvgWidget())
+    , m_totpSvgContainerWidget(new QStackedWidget())
```
Comment (droidmonkey) [inline src/gui/TotpExportSettingsDialog.cpp:38]: Why are you using a stacked widget?

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/gui/SquareSvgWidget.h (hunk 1 above)
Comment (dmaslenko) [reply src/gui/SquareSvgWidget.h]: Sure, thank you, fixed.

File: src/gui/SquareSvgWidget.cpp (hunk 2 above)
Comment (dmaslenko) [reply src/gui/SquareSvgWidget.cpp]: Sure, thank you, fixed.

File: src/gui/SquareSvgWidget.cpp (hunk 3 above)
Comment (dmaslenko) [reply src/gui/SquareSvgWidget.cpp]: My bad, fixed.

File: src/gui/SquareSvgWidget.h (hunk 4 above)
Comment (dmaslenko) [reply src/gui/SquareSvgWidget.h]: It was left after my expriments. Fixed.

File: src/gui/TotpExportSettingsDialog.cpp (hunk 5 above)
Comment (dmaslenko) [reply src/gui/TotpExportSettingsDialog.cpp:38]: I was looking for Frame based widget that can include other widget(s). Only stacked widget I found anong standard QT ones.

Comment (droidmonkey) [reply src/gui/TotpExportSettingsDialog.cpp:38]: You don't need to wrap it in a frame, it's part of a layout. You really just need to get the sizeHint() of the svg widget after a resize and then force it to be square. The size hint returns the size the layout wants it to be.

File: src/gui/SquareSvgWidget.cpp [hunk 6]
```diff
@@ -26,3 +33,21 @@ int SquareSvgWidget::heightForWidth(int width) const
 {
     return width;
 }
+
+// The overridden logic allows to keep the SVG image as square and centered by width and height.
+void SquareSvgWidget::resizeEvent(QResizeEvent*)
+{
+    Q_ASSERT(parentWidget());
+    auto containerRect = parentWidget()->contentsRect();
```
Comment (droidmonkey) [inline src/gui/SquareSvgWidget.cpp]: Do a null check here, there is no guarantee the widget will have a parent and you will instacrash here if it doesn't. Assert only gets hit in debug build

**Review by droidmonkey — CHANGES_REQUESTED** [review]

**Comment by dmaslenko** [comment]
Hm, seems I rebased my branch incorrectlly.

File: src/gui/SquareSvgWidget.cpp (hunk 6 above)
Comment (dmaslenko) [reply src/gui/SquareSvgWidget.cpp]: Sure, added the checking for null.

**Comment by dmaslenko** [comment]
Added a test for QR code: `open -> check the initial shape for square -> resize -> check the shape again`.
In general the TOTP tests look like this (with temporary small delays between steps, not committed):
test-totp

**Review by droidmonkey — APPROVED** [review]
