### PR TITLE
Fix double warning display for database open

### LINKED ISSUE #741: File not found warning immediately replaced when key file not found
When a key file is not found at the path specified, a less than helpful dialogue is shown:
```
Unable to open the database.
Wrong key or database file is corrupt.
```

## Expected Behavior

A dialogue showing that the key file was not found.
```
Can't open key file:
No such file or directory
```

## Current Behavior

Currently the dialogue that should be shown is flashed for about a quarter of a second and then replaced with:
```
Unable to open the database.
Wrong key or database file is corrupt.
```
It is very easy to miss the actual cause of the failure because of this.

## Possible Solution

The first error (file not found) should trump the second. This suggests to me that an ENOENT error condition is being ignored and keepassxc is forging ahead and failing again.

## Steps to Reproduce (for bugs)

1. Create a database with a password and key file.
2. Attempt to open the database with a bad path to the key file.

## Context

Was looking into replacing keepassx for the reasons that this fork exists.

## Debug Info

KeePassXC - 2.2.0 / 7580c385da58329ef29e0d026b1ac0720cbcccf2
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0  / 7580c385da58329ef29e0d026b1ac0720cbcccf2

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Ubuntu 16.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-81-generic

Enabled extensions:
- Auto-Type

### PR DESCRIPTION
**Pull request by louib**
Second attempt to fix #741, after https://github.com/keepassxreboot/keepassxc/pull/744
Rebased on `2.2.2`.

## How has this been tested?
Locally, by opening a database with a keyfile, and testing the error message when providing an invalid path.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/DatabaseOpenWidget.cpp [hunk 1]
```diff
@@ -174,28 +177,29 @@ void DatabaseOpenWidget::openDatabase()
...
     }
+
+    delete masterKey;
 }
 
-CompositeKey DatabaseOpenWidget::databaseKey()
+CompositeKey* DatabaseOpenWidget::databaseKey()
 {
-    CompositeKey masterKey;
+    CompositeKey* masterKey = new CompositeKey();
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp]: Shouldn't this be a smart pointer of some sort? Right now I don't see you deleting this instance anywhere.

Comment (louib) [reply src/gui/DatabaseOpenWidget.cpp]: It could be, yeah. It's deleted line 215 if the key is invalid, otherwise it's deleted at the end of `openDatabase()`

Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: Im in favor of using smart/scoped pointers for these key components from here on out.

Comment (louib) [reply src/gui/DatabaseOpenWidget.cpp]: @droidmonkey @droidmonkey now using a QScopedPointer in `openDatabase()`

Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: You should use and return a QSharedPointer here, not a QScopedPointer. With a QScopedPointer you have no idea when the object will be deleted and it may as well be deleted never or twice.

**Comment by droidmonkey** [comment]
@louib @phoerious is this ready for merging?

**Comment by phoerious** [comment]
As I said, I would prefer a QSharedPointer instead of a QScopedPointer as the ownership of pointers as return values is unclear otherwise.

**Comment by louib** [comment]
Thanks for that @phoerious!
