### PR TITLE
Fix multiple issues with entry keyboard shortcuts

### LINKED ISSUE #1588: Right click context menu doesn't show keyboard shortcuts anymore
## Expected Behavior
I expected right click context menu to show keyboard shortcuts like it used to do in 2.2.4.

## Current Behavior
Keyboard shortcuts are not shown in the right click context menu in 2.3.0, only in the "Entries" dropdown at the top.

## Context
To be honest I'm not sure if this change is intended or not, but I didn't see anything about it in #1305 or anywhere else.

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### LINKED ISSUE #2031: shortcut to hide/unhide usernames and passwords
is there any shortcut to hide/unhide the usernames and passwords like in keepass2 ? 

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-22-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

### LINKED ISSUE #2096: Add keyboard shortcut to search bar background text
Add in the `Entries` menu group a "Search password / item (CTRL+F)" item to let users know there's a shortcut to jump into the search form without using the mouse (I've discovered this shortcut by chance because of muscle memory).

## Expected Behavior
Add a "Search password (CTRL+F)" item in the `Entries` menu group

## Current Behavior
The CTRL+F shortcut works, the search feature too, but they're not "documented" in the menu

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-24-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### LINKED ISSUE #2166: Add reveal password button to details pane
BUG: I have checked and unchecked (with keepassxc restarts) the Preference >> Security setting "Show passwords in cleartext by default", but nothing seems to change: The passwords are always hidden (black dots) in the overall database view, and the passwords are always shown in the preview pane underneath. I would like to show the passwords in the main database view

SUGGESTION: I suggest there be a global check box to ALWAYS show passwords in the window (both in the database view AND the preview pane) or NEVER. To have passwords visible in one place but not in another in the same window seems strange to me.

Thanks,
Mike

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### LINKED ISSUE #2266: Allow to temporarily show individual passwords
I'd like to have the possibility to quickly view an individual password in clear text.
Use case is usually that I want to manually enter a password somewhere, but are not sure which. I want to quickly check.

## Expected Behavior
Select a password entry, and with a single click show me the password.

## Current Behavior
Current options are:
* Show all in clear text - not what I want (apart from that it doesn't seem to work...)
* uncheck "Hide passwords in preview panel" - closer, but the problem is that I'd always have to manually close the panel, as otherwise one entry is always selected and the respective password is always visible...
    * the preview panel could be made autohide, but don't think that is what I want either, as it would also hide the notes for instance...
* open the edit dialog: double click the entry, go all the way to the right to hit the small eye icon, cancel - tedious

## Possible Solution
What I imagine for instance could be to show the eye button right next to the dotted password in the preview panel. Plus automatically hide the password again after 10s or so. (Actually, there is not really a use to show a couple of black dots in the preview panel ... ;) So they could be made useful by allowing to turn them into clear text)

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### LINKED ISSUE #2403: CTRL+V after searching doesn't start autotype anymore
## Expected Behavior
In earlier versions, it was possible to search for an entry using the search bar, and directly start autotype when the respective entry is selected. This doesn't work in 2.3.4 anymore.

## Current Behavior
Instead, CTRL+V works as 'paste' and pastes the current clipboard content into the search field. 

## Possible Solution
I understand that using CTRL+V in a text input field can be expected to paste text. However, this change breaks accustomed user flow. A possible solution would be user-configurable shortcuts. See also https://xkcd.com/1172/ ;)

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Fedora 29 (Twenty Nine)
CPU architecture: x86_64
Kernel: linux 4.18.14-300.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

* Cleanup entry change notification with entryview focus in/out
* Change Open URL shortcut to CTRL+SHIFT+U to conform with an "action"
including SHIFT
* Change Copy URL shortcut to CTRL+U to conform with "copy" without
SHIFT
* Entry specific toolbar and menu items are disabled unless the entry
row has focus (prevents unintended actions)
* Reword security setting for password visibility in entry edit view
* Shortcut to hide/unhide usernames (CTRL+SHIFT+B)

* Fix #1588 - show keyboard shortcuts in context menu
* Fix #2403 - Change auto-type shortcut to CTRL + SHIFT + V
* Fix #2096 - Add (CTRL+F) to search bar background
* Fix #2031 & Fix #2266 - shortcut to hide/unhide passwords (CTRL+SHIFT+C)
* Fix #2166 - Add reveal password button to entry preview

## Motivation and context

The previous way these interactions were handled was rather fragile and required 3 different signal/slot interactions between 3-4 objects.

## How has this been tested?

Manually and unit tests

## Screenshots (if appropriate):
entries_menu

preview_panel_passtoggle

security_options

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Sorry ignore this, I need to fix some stuff

**Comment by droidmonkey** [comment]
Ready for review!

**Comment by droidmonkey** [comment]
@weslly good catch, updated and tried to make the gui tests even more reliable...

File: src/gui/SearchWidget.cpp [hunk 1]
```diff
@@ -41,9 +41,11 @@ SearchWidget::SearchWidget(QWidget* parent)
     connect(m_searchTimer, SIGNAL(timeout()), this, SLOT(startSearch()));
     connect(this, SIGNAL(escapePressed()), m_ui->searchEdit, SLOT(clear()));
 
-    new QShortcut(Qt::CTRL + Qt::Key_F, this, SLOT(searchFocus()), nullptr, Qt::ApplicationShortcut);
+    new QShortcut(QKeySequence::Find, this, SLOT(searchFocus()), nullptr, Qt::ApplicationShortcut);
     new QShortcut(Qt::Key_Escape, m_ui->searchEdit, SLOT(clear()), nullptr, Qt::ApplicationShortcut);
 
+    m_ui->searchEdit->setPlaceholderText(tr("Search (%1)...", "Search placeholder text, %1 is the keyboard shortcut")
+                                            .arg(QKeySequence(QKeySequence::Find).toString(), QKeySequence::NativeText));
```
Comment (weslly) [inline src/gui/SearchWidget.cpp]: @droidmonkey Still returning CTRL 

`QKeySequence::NativeText` should be an argument of `.toString()` instead of `tr().arg()`.

Comment (droidmonkey) [reply src/gui/SearchWidget.cpp]: Fixed, I made a stupid undo right before commit.

Comment (droidmonkey) [reply src/gui/SearchWidget.cpp]: Man I am striking out today! Good catch 😢
