### PR TITLE
Return keyboard focus after saving database edits

### LINKED ISSUE #4157: Entry list loses focus after entry edit
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
ok
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
open keepassxc, program starts
login
arow down arow down: (fokus now in the list of entries)
ctrl+e: entry opens, edit the titel or anything other
alt + o (save and close of the entry)
arow down or up: focus jumps from one entry to the next, with ctrl+e open is working

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
open keepassxc, program starts
login
arow down arow down: (fokus now in the list of entries)
ctrl+e: entry opens, edit the titel or anything other
alt + o (save and close of the entry)
arow down or up: focus has been lost in the list of entries. ctrl+e open is not working. only with shift+tab the focus is back in the list and can be opened with ctrl+e or browsed with the up and down arrow.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
after saving, make sure, the focus is back in the list of entries.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. n a
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
the issue affected me in the way of disrupting my workflow when working just with the keyboard only. the bug forces me, to make additional mouse operations or press shift+tab to regain control of the focus in the list of entries. 

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION
KeePassXC - Version 2.5.2
Revision: 62cda9d
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.0.0-37-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

Libraries:
- LIBS

Operating system: n a
CPU architecture: ARCH na
Kernel: KERNEL na

Enabled extensions:
- EXTENSIONS
na

### PR DESCRIPTION
**Pull request by sigmaupsilon**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
Prior to when a database is saved after an edit, the Group and Entry Views are disabled which causes a loss in keyboard focus. This change sets the focus to Entry View after the views are re-enabled.

Fixes #4157 

## Testing strategy
All unit tests as well as manual testing.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/gui/DatabaseWidget.cpp [hunk 1]
```diff
@@ -1671,6 +1671,8 @@ bool DatabaseWidget::save()
     m_entryView->setDisabled(false);
     m_groupView->setDisabled(false);
 
+    m_entryView->setFocus();
```
Comment (droidmonkey) [inline src/gui/DatabaseWidget.cpp]: This is not the right thing to do because the entryview may not have had focus prior to saving. You should store the focus widget before disabling (`auto focusWidget = qApp->focusWidget()`) then restore the focus when enabled again `if (focusWidget) { focusWidget->setFocus(); }`

**Comment by sigmaupsilon** [comment]
I'm not sure why the GUI tests are failing, I'm getting similar errors as [here](https://github.com/keepassxreboot/keepassxc/pull/4227)
