### PR TITLE
Several improvements to tags editing

### LINKED ISSUE #7528: Pasting a new tag into the tag field don't work
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Can't paste into the tag field for adding a new tag

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Copy a string to the clipboard (right click, ctrl+c)
2. Try to paste ist into the tag field (right click, ctrl+v)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Tag should be added, at least a info when the string ist invalid for a Tag

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happen, pasting ist not working. Context Menu doesn't appear

## Context
[NOTE]: # ( Give us any additional information you may have. )
- Tested strings: 
  - test
  - test test
  - test-test
  - 1

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0-beta1
Download from the release page

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19044

### LINKED ISSUE #7602: Words with spaces used for tags get split into multiple tags
## Overview
I have a DB created with the original KeePass on Windows that have multiple words as tags but when I open that DB with KeePassXC, I get multiple tags, split by the spaces. Also, if I try to write a new tag in KeePassXC, the moment I hit the space button, it decides to start a new tag.

## Steps to Reproduce
1. Open a DB with tags with spaces or directly edit already existing entry in KeePassXC
2. Start typing multiple-word tag, separated with spaces

## Expected Behavior
Spaces should be allowed in tags. At least not break already existing tags with spaces, done with other KeePass programs

## Actual Behavior
Tags get broken into multiple separate words, split by the spaces. For example a tag "this is tag" will be created as 3 separate tags: "this", "is", "tag", instead of just one.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Pop!_OS 21.10
CPU architecture: x86_64
Kernel: linux 5.16.11-76051611-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Mutter

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fix #7602 - Allow spaces in tag names
* Fix #7528 - Allow pasting text into the tags field. Text is split by comma creating tags for each section of text. If there are no commas then the pasted text becomes a tag.
* Fix tags editing not causing the entry to be marked as modified.

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on windows.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by phoerious — APPROVED** [review]

**Comment by droidmonkey** [comment]
Fixed the gui test

File: src/gui/tag/TagsEdit.cpp [hunk 1]
```diff
@@ -797,6 +799,15 @@ void TagsEdit::keyPressEvent(QKeyEvent* event)
     } else if (event == QKeySequence::SelectNextChar) {
         impl->moveCursor(impl->text_layout.nextCursorPosition(impl->cursor), true);
         event->accept();
+    } else if (event == QKeySequence::Paste) {
+        auto clipboard = QApplication::clipboard();
+        if (clipboard) {
+            for (auto tagtext : clipboard->text().split(",")) {
```
Comment (michaelk83) [inline src/gui/tag/TagsEdit.cpp:805]: Shouldn't this use the same regex as when editing manually, the one on `Entry.cpp` line 195?
Also, what happens when you paste a tag that was already added (or enter a duplicate tag manually, for that matter)?

Comment (droidmonkey) [reply src/gui/tag/TagsEdit.cpp:805]: Tags don't duplicate so non issue. I am just trying to get this out the door right now. This needs far more work to synch the various pieces. Not doing that right now. (aka this is good enough for now)

**Review by phoerious — APPROVED** [review]
