### PR TITLE
Raise error if challenge-response failed during KDBX4 key transformation

### LINKED ISSUE #1656: KDBX4 Allows Yubikey Auth Removal
When using a KDBX 4 DB (Argon2 or AES-KDF does not matter), Yubikey auth can be removed by editing and saving an entry, while the Yubikey is unplugged.

## Expected Behavior
Similar to KDBX 3.1 an error message should be displayed when the Yubikey is unplugged.

## Current Behavior
The database is saved with challenge-response disabled.

## Steps to Reproduce (for bugs)
1. Create a new DB, with password and challenge-response
2. Create e new entry and save
3. Change key derivation function to KDBX 4 (does not matter whether Argon2 or AES-KDF is used)
4. Unplug Yubikey
5. Open entry, change password
6. Save entry
7. Close DB
8. Open DB with password only

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.6-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### PR DESCRIPTION
**Pull request by phoerious**
## Description

Fail with an error when challenge-response failed during key transformation instead of silently discarding the key component.

Resolves #1656.

## Motivation and context

Saving a KDBX 3.1 file failed with an error message when challenge-response failed (e.g. YubiKey wasn't inserted). KDBX 4 silently discarded the key component. This is a user error which we should prevent.

## How has this been tested?

Saving a KDBX 4 file fails when I unplug my YubiKey.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/keys/CompositeKey.cpp [hunk 1]
```diff
@@ -97,19 +97,27 @@ QByteArray CompositeKey::rawKey() const
  * as a challenge to acquire their key contribution.
  *
  * @param transformSeed transform seed to challenge or nullptr to exclude challenge-response components
+ * @param ok true if challenges were successful and all key components could be added to the composite key
  * @return key hash
  */
-QByteArray CompositeKey::rawKey(const QByteArray* transformSeed) const
```
Comment (droidmonkey) [inline src/keys/CompositeKey.cpp]: Honestly I would rather we return bool and have a QByteArray& result input. This style makes coding very janky. It also is completely different then how the transformKey function is written.

**Comment by TheZ3ro** [comment]
Instead of `ok` I would call that variable `complete`. 
`ok` seems too generic to me

File: src/keys/CompositeKey.cpp (hunk 1 above)
Comment (phoerious) [reply src/keys/CompositeKey.cpp]: We have both styles.

Comment (phoerious) [reply src/keys/CompositeKey.cpp]: Actually, I would prefer to leave it as-is. The abstract Key class has a pure-virtual rawKey() function which returns the raw key as byte array. This function is just an overload and should behave similarly. Changing both requires a lot of (unnecessary) code changes and changing only this one makes it inconsistent. Also I think needing lvalues for the actual key is more annoying than (optionally) needing an lvalue for the `ok` value (@TheZ3ro `ok` is the name we use everywhere else for this kind of stuff).

Comment (droidmonkey) [reply src/keys/CompositeKey.cpp]: Defer the api change to 2.4
