### PR TITLE
FdoSecrets: implement unlock before search

### LINKED ISSUE #4443: Block and ask for unlock when applications query the secret service
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When app launch and the database is locked, keepassxc would popup and ask for unlock.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When app launch and the database is locked, the app fails to get password, therefore asking user to enter it again (or ask to re-authenticate in case of nextcloud), keepassxc sit in silence.
Then, when the application trys to save it, keepassxc then ask user to unlock, and stores a duplicate entry.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Make querying password acts the same as saving password in this case.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. setup secret service
2. expose a database group
2. launch a application that uses secret service, and save a password
3. lock database
4. re-launch that application again

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
It causes nextcloud to ask for auth everytime system boots up, and my mail client sometimes can't get password when keepassxc is locked.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.3
Revision: f8c962b

Libraries:
- Qt 5.14.1
- libgcrypt 1.8.5

Operating system: Arch Linux
CPU architecture: Arch Linux
Kernel: 5.5.9-arch1-2

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

### LINKED ISSUE #6942: Secret Service will not be able to return any entries if the exposed group has search disabled
## Overview
If the exposed group has searching disabled, then apps will not be able to look for secrets.

## Steps to Reproduce
1. Create a new group called "Keyring", with "Search" set to "Disabled".
2. Enable Secret Service and expose "Keyring".
3. Run `secret-tool store --label=test attr test` and enter any password.
4. Run `secret-tool lookup attr test`

## Expected Behavior
The entered password is returned.

## Actual Behavior
Nothing is returned, `secret-tool` exit with status code 1 (entry not found).

## Context
KeePassXC - Version 2.6.6

Qt 5.15.2
Debugging mode is disabled.

Operating system: Gentoo/Linux
CPU architecture: x86_64
Kernel: linux 5.14.6-zen1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

### PR DESCRIPTION
**Pull request by Aetf**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Resolves #4443. While at it, also fixes #6942.

Right now this is based on #6915. But I'll rebase once that is merged.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Added unit test also tested manually

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by Aetf** [comment]
Update: added guards for prompts to run concurrently.

---

While haven't tested it yet, but I realize using a nested event loop for the blocking call isn't the best approach. What if another dbus call happens while KPXC sits in the nested loop? If the other call is for unrelated parts, it is probably fine because there won't be any other nesting.
But what if the other call also results in unlocking the same database?

Actually, that's a problem in general: what will happen while one database is being unlocked asynchronously, and another client requests to unlock the same database.

I need to think more about this. The solution is probably to remember database unlocking is in progress, and for any new requests, submit to the old prompt signal rather than create a new unlock dialog.

Changing to WIP for now.

**Comment by Aetf** [comment]
Ready for review (or probably wait after #6915 so the history is cleaner) @droidmonkey

**Comment by michaelk83** [comment]
So you're going with just an internal blocking prompt, without all the `IsLocked` / `InteractiveAuthorizationRequired` stuff?

**Comment by Aetf** [comment]
> So you're going with just an internal blocking prompt, without all the `IsLocked` / `InteractiveAuthorizationRequired` stuff?

Yes. I view this as a workaround to increase compatibility.

The proper fix should be done in the spec, either returning `InteractiveAuthorizationRequired` error, or returning a prompt object just like other methods. IMHO returning a prompt object is better and consistent with the rest of the spec, though.

**Comment by droidmonkey** [comment]
Rebased and squashed. Ready for review @Aetf ?

**Comment by Aetf** [comment]
Somehow I can't reproduce the test failure `TestGuiFdoSecrets::testServiceUnlockItems` locally. But let me try to reproduce in the CI docker environment.

**Comment by Aetf** [comment]
Found the root cause of test failure. Ready to review. @droidmonkey

File: src/gui/DatabaseWidget.h [hunk 1]
```diff
@@ -163,7 +163,8 @@ public slots:
     void createEntry();
     void cloneEntry();
     void deleteSelectedEntries();
-    void deleteEntries(QList<Entry*> entries, bool confirm = true);
+    // return the number of entries deleted
+    size_t deleteEntries(QList<Entry*> entries, bool confirm = true);
```
Comment (droidmonkey) [inline src/gui/DatabaseWidget.h]: I don't like re-using this function call from within FDO Secrets plugin. Perhaps the GuiTools deleteEntriesResolvedReferences should be called directly from the FDO Secrets. Then you don't need to modify the signature of the DatabaseWidgets.

File: src/gui/entry/EditEntryWidget.cpp [hunk 2]
```diff
@@ -68,20 +68,20 @@ EditEntryWidget::EditEntryWidget(QWidget* parent)
...
 #ifdef WITH_XC_BROWSER
     , m_browserSettingsChanged(false)
-    , m_browserWidget(new QWidget())
+    , m_browserWidget(new QWidget(this))
     , m_additionalURLsDataModel(new EntryURLModel(this))
 #endif
-    , m_editWidgetProperties(new EditWidgetProperties())
-    , m_historyWidget(new QWidget())
+    , m_editWidgetProperties(new EditWidgetProperties(this))
+    , m_historyWidget(new QWidget(this))
```
Comment (droidmonkey) [inline src/gui/entry/EditEntryWidget.cpp:85]: Why was this code changed? Parenting is handled in the addPage call.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/gui/entry/EditEntryWidget.cpp (hunk 2 above)
Comment (Aetf) [reply src/gui/entry/EditEntryWidget.cpp:85]: This reduces some LSAN noise when the unit test fails and `addPage` isn't called. Not a big deal outside of tests. I can drop this if you don't like it.

File: src/gui/DatabaseWidget.h (hunk 1 above)
Comment (Aetf) [reply src/gui/DatabaseWidget.h]: I thought about this. My only concern is the additional handling of selection and previewView in DatabaseWidgets. What if the user is viewing the exposed group while some backend clients delete some entries?

Comment (Aetf) [reply src/gui/DatabaseWidget.h]: (Or probably entryView should be fixed to react to entry delete signal and update selection and preview itself?)

File: src/gui/entry/EditEntryWidget.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/gui/entry/EditEntryWidget.cpp:85]: Just unrelated to the FDO code, you can keep it since it doesn't change anything.

File: src/gui/DatabaseWidget.h (hunk 1 above)
Comment (droidmonkey) [reply src/gui/DatabaseWidget.h]: I think the latter is the better solution. The GUI should "repair itself" automatically when the backend data changes. Can fix this in a different PR.

Comment (Aetf) [reply src/gui/DatabaseWidget.h]: Updated to directly use GuiTools. Will create a separate PR fixing the DatabaseWidget.

**Comment by Aetf** [comment]
@droidmonkey updated this per comments. I also created #7041 to clean up deleteEntries.

**Review by droidmonkey — APPROVED** [review]
