### PR TITLE
Use QClipboard::clear() instead of setting blank text

### LINKED ISSUE #9121: KeePassXC freezes KDE Plasma panel on exit
I'm using Arch Linux with KDE Plasma 5.26.5. When I close KeePassXC 2.7.4 - Flatpak version - (with it configured to be immediately closed, without going to the tray), my bottom panel freezes for ~2-3 seconds. First time I thought it was a KDE bug, but I noticed it always & only happens with KeePassXC. IDK if it happens with other DEs, distros or package types.

**Edit:** It does not freeze the panel when exiting the application via the Database > Exit menu.

## Steps to Reproduce
1. Open KeePassXC Flatpak in Arch Linux
2. Close it
3. That's it

## Expected Behavior
Just not freeze.

## Actual Behavior
It freezes for ~2-3 seconds.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

Operating System: Arch Linux
Desktop Env: KDE
Windowing System: X11

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #9121 and #4498 and #4105

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows, CI tests all platforms

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/Clipboard.cpp [hunk 1]
```diff
@@ -99,7 +99,8 @@ void Clipboard::clearCopiedText()
 
     if (m_lastCopied == clipboard->text(QClipboard::Clipboard)
         || m_lastCopied == clipboard->text(QClipboard::Selection)) {
-        setText("", false);
```
Comment (michaelk83) [inline src/gui/Clipboard.cpp:102]: May want to leave this as a fallback on systems where `clear()` doesn't work. https://github.com/keepassxreboot/keepassxc/issues/6101#issuecomment-1376948784

Comment (droidmonkey) [reply src/gui/Clipboard.cpp:102]: I'm afraid that if I do that we will still have the problem with the exit hanging. There is no supported system that doesn't support clear() at this point

Comment (droidmonkey) [reply src/gui/Clipboard.cpp:102]: I tested this and the delay on quit was still present if I included the `setText("", false);` line before the clear calls. So I will not be keeping this line in as it would defeat the whole purpose of this PR.

**Review by phoerious — APPROVED** [review]
