### PR TITLE
Correct opening files from command line

### LINKED ISSUE #2877: Password is checked when unlocking the database
## Expected Behavior
By checking "Rememver last key filed and security dongles", it should remember that I only use key file without password.

## Current Behavior
In KeePassXC 2.4.0, Password field is always checked on the unlocking page. Thus I have to uncheck it every time since I only use key file. This is also not how it behaves in previous versions.

## Possible Solution
N/A

## Steps to Reproduce
1. Set a database with key file only
2. Check "Rememver last key filed and security dongles"
3. Try to open the database

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Fix #2877 - password is unchecked by default
* Smarter activation of key components based on contents of text entry fields
* Prevent multiple copies of the same database from opening when the canonicalFileName != fileName

Ported fixes from #2805 
* When removing portions of the master key, the key is marked dirty for saving
* Properly clear password and other fields in edit entry widget and password widgets

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested using Windows Cmd Shell and MSYS2.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

File: src/gui/masterkey/PasswordEditWidget.cpp [hunk 1]
```diff
@@ -92,6 +92,15 @@ void PasswordEditWidget::initComponentEditWidget(QWidget* widget)
     m_compUi->enterPasswordEdit->setFocus();
 }
 
+void PasswordEditWidget::hideEvent(QHideEvent* event)
+{
+    if (!isVisible() && m_compUi->enterPasswordEdit) {
+        m_compUi->enterPasswordEdit->setText("");
```
Comment (louib) [inline src/gui/masterkey/PasswordEditWidget.cpp]: @droidmonkey shouldn't we also clear the `repeatPasswordEdit`??

File: src/gui/DatabaseOpenWidget.cpp [hunk 2]
```diff
@@ -174,13 +173,8 @@ QSharedPointer<Database> DatabaseOpenWidget::database()
...
 {
-    if (!pw.isEmpty()) {
-        m_ui->editPassword->setText(pw);
-    }
-    if (!keyFile.isEmpty()) {
-        m_ui->comboKeyFile->setEditText(keyFile);
-    }
-
+    m_ui->editPassword->setText(pw);
+    m_ui->comboKeyFile->setEditText(keyFile);
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp]: I don't like that the field is cleared immediately after hitting enter. That restores the old annoying behaviour where you cannot fix typos without retypting the whole thing. What we should do, however, is reset the display mode to bullets as soon as enter is pressed. This is the same behaviour that KeePass2Android has.

File: src/gui/DatabaseOpenWidget.cpp [hunk 3]
```diff
@@ -372,6 +369,7 @@ void DatabaseOpenWidget::pollYubikey()
     m_ui->checkChallengeResponse->setChecked(false);
     m_ui->comboChallengeResponse->setEnabled(false);
     m_ui->comboChallengeResponse->clear();
+    m_ui->comboChallengeResponse->addItem(tr("-- SELECT --"), -1);
```
Comment (phoerious) [inline src/gui/DatabaseOpenWidget.cpp]: Do we really need the checkboxes after all this?

File: src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp [hunk 4]
```diff
@@ -103,7 +100,9 @@ void DatabaseSettingsWidgetMasterKey::load(QSharedPointer<Database> db)
 
     setAdditionalKeyOptionsVisible(hasAdditionalKeys);
 
-    m_isDirty = isDirty;
+    connect(m_passwordEditWidget->findChild<QPushButton*>("removeButton"), SIGNAL(clicked()), SLOT(markDirty()));
+    connect(m_keyFileEditWidget->findChild<QPushButton*>("removeButton"), SIGNAL(clicked()), SLOT(markDirty()));
+    connect(m_yubiKeyEditWidget->findChild<QPushButton*>("removeButton"), SIGNAL(clicked()), SLOT(markDirty()));
```
Comment (phoerious) [inline src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp]: What about the change button? I'm also generally not sure if this approach works, because components are initialised lazily. A remove button may not exist until it's been shown for the first time. connect() won't complain, but it won't work either.

File: src/gui/DatabaseOpenWidget.cpp (hunk 3 above)
Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: Technically we do because people could have an "empty password" as their password. This is possible in KeePass2.

File: src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp (hunk 4 above)
Comment (droidmonkey) [reply src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp]: You wrote this code 😉

File: src/gui/DatabaseOpenWidget.cpp (hunk 2 above)
Comment (droidmonkey) [reply src/gui/DatabaseOpenWidget.cpp]: You wrote this code :wink:

Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: I wrote it so that it won't clear out the field after enter anymore. That's what we had before. ;-)

File: src/gui/DatabaseOpenWidget.cpp (hunk 3 above)
Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: Forgot about that. I actually consider that a conceptual bug in KeePass. But so be it.

File: src/gui/DatabaseOpenWidget.cpp (hunk 2 above)
Comment (phoerious) [reply src/gui/DatabaseOpenWidget.cpp]: Ah, nvm. I misread. I thought this was resetting the field to empty. We should still reset the display mode, though. That's something I noticed was missing.

File: src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp (hunk 4 above)
Comment (phoerious) [reply src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp]: Did I? I guess it works then. 😛

Comment (droidmonkey) [reply src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp]: I tested it with my "all key types" test database. I don't like that the ui doesn't fully initialize because it creates runtime bugs like you mentioned (and the crash bug that is in 2.4.0). Can we fix that behavior?

Comment (phoerious) [reply src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp]: I don't think we can. That's Qt-internal stuff.

Comment (phoerious) [reply src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp]: We could try that.

Comment (phoerious) [reply src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp]: Actually, we cannot. setupUi is only available for widgets created with uic. I remember I had similar issues with initial vertical layout calculation, which I tried to solve in the updateSize() method. Now I also remember that I do initialise the remove and add pages (which is why this snippet should work), but not the dynamic widget. I'll try and see if I can make that work for that as well and if I find a better method than manipulating layout policies.

Comment (phoerious) [reply src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp]: Update: I found a solution. The reason was actually not that Qt didn't initialise the component but that we didn't do it unless the QStackedWidget changed its index. I have submitted an additional commit that fixes that and also resets the password field echo mode to bullets on database open (we had that, but there was a weird if statement around it that didn't make sense).
