### PR TITLE
Revert Auto-Type change that caused race condition

### LINKED ISSUE #12723: Auto-Type sometimes does not working after upgrade to 2.7.11
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

The Auto-Type is not working after upgrade to 2.7.11.
KeePassXC is installed from Ubuntu repo.

### Steps to Reproduce

Open a terminal.
SSH to a server.
Go to KeePassXC (v.2.7.11) and try to use Auto-Type (PASSWORD/ENTER)
Nothing happens

### Expected Versus Actual Behavior

The password injected into the terminal windows as previously.

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.7.11
Revision: 6a2ed32

Qt 5.15.13
Debugging mode is disabled.

Operating system: Linux Mint 22.2
CPU architecture: x86_64
Kernel: linux 6.8.0-87-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

### Operating System

Linux

### Linux Desktop Environment

Gnome

### Linux Windowing System

X11

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #12723

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and include helpful comments. )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/autotype/AutoType.cpp [hunk 1]
```diff
@@ -543,16 +548,16 @@ AutoType::parseSequence(const QString& entrySequence, const Entry* entry, QStrin
     }
 
     const int maxTypeDelay = 500;
-    const int maxWaitDelay = 10000;
     const int maxRepetition = 100;
+
     int currentTypingDelay = qBound(0, config()->get(Config::AutoTypeDelay).toInt(), maxTypeDelay);
-    int cumulativeDelay = qBound(0, config()->get(Config::AutoTypeStartDelay).toInt(), maxWaitDelay);
+    // Take into account the initial delay which is added before any actions are performed
+    int cumulativeDelay = qBound(s_minWaitDelay, config()->get(Config::AutoTypeStartDelay).toInt(), s_maxWaitDelay);
```
Comment (phoerious) [inline src/autotype/AutoType.cpp:555]: Can you store this in a variable above? Even if the calculation is unlikely to change, we should not have this complex expressions in two places when it must evaluate to exactly the same result always. Looks like a bug-to-be to me otherwise.

**Comment by phoerious** [comment]
Oh, we're having this random test failure again:
```
FAIL!  : TestTools::testBackupFilePatternSubstitution(Complex custom time pattern) Compared values are not the same
   Actual   (Tools::substituteBackupFilePath(pattern, dbFilePath)): "./25/KeePassXC_20251126_041909.old.kdbx"
   Expected (expectedSubstitution)                                : "./25/KeePassXC_20251126_041908.old.kdbx"
```
https://ci.keepassxc.org/buildConfiguration/KeePassXC_UbuntuLinux/276042?showLog=276039_1608_1499&logFilter=debug&logView=flowAware

This seems to be happening when the second lapses during the generation of the test pattern matrix and the actual test execution: https://github.com/keepassxreboot/keepassxc/blob/967dc5937f1f69e601f7aecbc600ef9027cc5043/tests/TestTools.cpp#L157

My recommended fix would be simply to remove the second from the pattern. This could still happen at the minute mark, but it's way less likely.

**Review by phoerious — APPROVED** [review]

**Comment by d03j** [comment]
confirm this fixed autotype not working on openSUSE KDE X11. Thanks.

**Comment by stefan123t** [comment]
@phoerious and @droidmonkey this made my life so much better :heart: ! 
Many thanks for fixing this regression :hugs::hugs::hugs: !!!
