### PR TITLE
Fix bugs introduced by database refactor #2491

### LINKED ISSUE #2502: Passwords are leaked under certain circumstances
## Expected Behavior
After databases are unlocked, knowledge of the master password is always required (if configured) to unlock databases.

## Current Behavior
Under certain circumstances (see steps to reproduce), the field for the master password contains exactly the master password after the database is locked, so the authentication process is bypassed and saved passwords are leaked.

## Possible Solution
This issue does not exist before today. I guess it's related to https://github.com/keepassxreboot/keepassxc/commit/d612cad09a4f1cd8ef9bf6be8bf90b75248ecfef (Refactor Database and Database widgets).

## Steps to Reproduce (for bugs)
1. In Settings -> Security -> Lock databases after inactivity of, set the value to a short time (e.g., 10 seconds) for easier issue reproduction.
2. In Settings -> General, enable "Minimize instead of app exit", "Show a system tray icon" and "Hide window to system tray when minimized".
3. Create a test database, keep it unlocked and minimize the KeePassXC main window.
4. Wait for 10 seconds for the database to be locked.
5. Click on the tray icon. The main window appears again. However, the master password field contains the correct password, so hitting OK unlocks the database.

## Context
Minimize KeePassXC to the system tray and wait for databases to be locked is part of my daily workflow.

## Debug Info
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
修訂： d612cad

函式庫：
- Qt 5.12.0
- libgcrypt 1.8.4

作業系統：Arch Linux
處裡器架構：x86_64
核心：linux 4.19.3-arch1-2-ARCH

已啟用的擴充元件：
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey

### PR DESCRIPTION
**Pull request by phoerious**
## Description

Fixes bugs introduced by the refactoring of our database classes (#2491).

Resolves #2502 by making sure that password fields are cleared when they are hidden.
Resolves issues no. 1 and 3 of #2499 by fixing conditions and reworking connected signals and tracking of added keys in our SSH agent feature.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)
## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/sshagent/SSHAgent.cpp [hunk 1]
```diff
@@ -222,120 +241,121 @@ bool SSHAgent::removeIdentity(OpenSSHKey& key)
...
-    }
-
-    return true;
+    return sendMessage(requestData, responseData);
 }
 
-void SSHAgent::removeIdentityAtLock(const OpenSSHKey& key, const QUuid& uuid)
+/**
+ * Change "remove identity on lock" setting for a key already added to the agent.
+ * Will to nothing if the key has not been added to the agent.
```
Comment (PF93mc8y7erq92qTmTjJBysALa) [inline src/sshagent/SSHAgent.cpp]: will do nothing

File: src/sshagent/SSHAgent.cpp [hunk 2]
```diff
@@ -201,9 +211,18 @@ bool SSHAgent::addIdentity(OpenSSHKey& key, quint32 lifetime, bool confirm)
         return false;
     }
 
+    OpenSSHKey keyCopy = key;
+    keyCopy.clearPrivate();
+    m_addedKeys[keyCopy] = removeOnLock;
```
Comment (PF93mc8y7erq92qTmTjJBysALa) [inline src/sshagent/SSHAgent.cpp]: Previously, in 2.3.4, only those keys with the option "remove at lock" were removed from the ssh agent upon closing keepassxc.
see #2980
