### PR TITLE
fix showing any notes in an entry without notes (Fixes #6461)

### LINKED ISSUE #6461: hidden notes reappear when you select a entry without notes
## Overview
if you hide your notes via settings/security and view a entry with notes in it you have to click to see the note. When you then go to a entry without notes and click on it you see the notes of the other entry. This doesnt happen when you go to a entry with a note in it. Also do entrys without notes then keep the eye and dot's for notes, this stays then on all entrys without notes until you click to see a note without entry.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. go to settings/security/hide notes by standart
2. go to a entry with notes in it, click on the eye to see it
3. click directly to another entry without notes in it and you see the notes of the other entry
4. click on other entrys without notes and you will still see the last note.
5. click on the eye on other entry without notes and the last note will disappear
6. now the "fake dots" of all entrys without notes also disappear
7. once you just click on a entry with notes, the "fake dots" reappear on entrys without notes

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
- when you leave a entry with hidden notes they shouldnt reappear  somewhere else
- entrys without notes should not show any "fake dots" or even not the eye for seeing notes

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

### PR DESCRIPTION
**Pull request by xvallspl**
Fixes Issue #6461

Entries without notes were not clearing the notes field in the entry preview widget. I'm not clearing them either, but making the field invisible (it will get overwritten by next entry with notes).

## Screenshots

(gif)

screenshot

## Testing strategy
Manual testing

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by droidmonkey — APPROVED** [review]

File: src/gui/EntryPreviewWidget.cpp [hunk 1]
```diff
@@ -240,13 +240,19 @@ void EntryPreviewWidget::updateEntryGeneralTab()
...
+        m_ui->entryNotesTextEdit->setVisible(true);
+        if (config()->get(Config::Security_HideNotes).toBool()) {
+            setEntryNotesVisible(false);
+            m_ui->toggleEntryNotesButton->setVisible(!m_ui->entryNotesTextEdit->toPlainText().isEmpty());
+            m_ui->toggleEntryNotesButton->setChecked(false);
+        } else {
+            setEntryNotesVisible(true);
+            m_ui->toggleEntryNotesButton->setVisible(false);
+        }
     }
```
Comment (michaelk83) [inline src/gui/EntryPreviewWidget.cpp:256]: I'm not familiar with the rest of KPXC's code, nor with Qt yet, but just taking these lines on their own, this looks messy. A bunch of branching code setting multiple inter-dependent state in a complex manner. This screams "bugs!" at me.

1. First, why not actually clear the notes member in the model by default, when it's initialized? Or *always* load the notes from the entry, so that here it would get overwritten by an empty string? That's a more sensible solution to me than this UI hack.
1. Related to that, having two different ways to check if the notes are empty (lines 243 and 250) feels wrong. I understand these check slightly different things, but if the above point is fixed, then the 2nd form (line 250) should work for both (and can be checked once).
1. From line 250, `m_ui->entryNotesTextEdit`, it appears this can be editable in some cases? If so, then you shouldn't be hiding the edit box just because it's initially empty (line 244). Or, if it's never editable here, then why is this an edit box and not a label?
1. (For that matter, if it's editable, why are the "edit" and "view" views not separated to begin with? Though I realize that separating them is beyond the scope of this PR.)
1. Ignoring the above, if you go ahead with this UI approach, I would at least rearrange the code to reduce the branching complexity. How about this:
    1. Check the two conditions in advance, and put their results in boolean variables, `isNotesEmpty` and `isHideNotes`.
    1. Set each boolean state exactly once, passing the correct combination of conditions to the boolean parameter. For example, `m_ui->toggleEntryNotesButton->setVisible(isHideNotes && !isNotesEmpty);`. This would clearly spell out what the compound condition is for each state.
1. Finally, this could really use some unit tests, if possible (if there already are, then at least for the new bug scenario). And ideally they should be written *before* changing the actual code.

I realize @droidmonkey has already approved this PR, and it's not my place to overrule, but these are just some points to consider.

Comment (droidmonkey) [reply src/gui/EntryPreviewWidget.cpp:256]: There are a lot of quirks with this dialog to make it work and function the way it does. It's not clean, welcome to gui programming.

Comment (michaelk83) [reply src/gui/EntryPreviewWidget.cpp:256]: Then how about point 5, at least? I think that would be cleaner still.

Comment (droidmonkey) [reply src/gui/EntryPreviewWidget.cpp:256]: Reasonable yes

File: src/gui/EntryPreviewWidget.cpp [hunk 2]
```diff
@@ -240,14 +240,13 @@ void EntryPreviewWidget::updateEntryGeneralTab()
...
-    } else {
-        setEntryNotesVisible(true);
-        m_ui->toggleEntryNotesButton->setVisible(false);
-    }
+    auto hasNotes = !m_currentEntry->notes().isEmpty();
+    auto hideNotes = config()->get(Config::Security_HideNotes).toBool();
+
+    m_ui->entryNotesTextEdit->setVisible(hasNotes);
+    setEntryNotesVisible(hasNotes && !hideNotes);
+    m_ui->toggleEntryNotesButton->setVisible(hasNotes && hideNotes && !m_ui->entryNotesTextEdit->toPlainText().isEmpty());
```
Comment (michaelk83) [inline src/gui/EntryPreviewWidget.cpp:248]: Can ` && !m_ui->entryNotesTextEdit->toPlainText().isEmpty()` be part of `hasNotes` (line 243), or would that break line 246?

If you always initialize `entryNotesTextEdit` with the notes from the current entry, then it'll get reset to an empty string, and then only one of `entryNotesTextEdit->toPlainText().isEmpty()` or `m_currentEntry->notes().isEmpty()` should be enough (and you won't have to hide the text edit either).

File: src/gui/EntryPreviewWidget.cpp [hunk 3]
```diff
@@ -240,14 +240,13 @@ void EntryPreviewWidget::updateEntryGeneralTab()
...
+    m_ui->toggleEntryNotesButton->setChecked(!(hasNotes && hideNotes));
```
Comment (michaelk83) [inline src/gui/EntryPreviewWidget.cpp:249]: This can probably just be set to `false` until the user clicks it.

Comment (xvallspl) [reply src/gui/EntryPreviewWidget.cpp:249]: correct, thanks

File: src/gui/EntryPreviewWidget.cpp (hunk 2 above)
Comment (xvallspl) [reply src/gui/EntryPreviewWidget.cpp:248]: > Can && !m_ui->entryNotesTextEdit->toPlainText().isEmpty() be part of hasNotes (line 243), or would that break line 246?

It would break

> If you always initialize entryNotesTextEdit with the notes from the current entry, then it'll get reset to an empty string, and then only one of entryNotesTextEdit->toPlainText().isEmpty() or m_currentEntry->notes().isEmpty() should be enough (and you won't have to hide the text edit either).

That would be the ideal case, but I was trying to change the code as little as possible to fix this bug ASAP 🙃 . That would require changing the setEntryNotesVisible and the setNotesVisible (which is also called by group functionality) functions. There is some work that could be done to simplify things but I'm not sure it is in the scope of this PR.

**Comment by michaelk83** [comment]
The updated code looks much nicer. Thanks!

**Review by droidmonkey — APPROVED** [review]
