### PR TITLE
Fix edit entry header entity encoding

### LINKED ISSUE #679: HTML Entities are double encoded in entry detail view
## Expected Behavior

Display text with ampersands as eg, `AT&T`

## Current Behavior

Display text with ampersands as `AT&amp;T`
screen shot 2017-06-26 at 10 50 57 am

## Steps to Reproduce (for bugs)

1. Create password entry
2. Insert a name with an ampersand
3. close detail pane
4. reopen detail pane

## Your Environment

KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.6.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### PR DESCRIPTION
**Pull request by weslly**
## Description
Close #679

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

File: src/gui/EditWidget.cpp [hunk 1]
```diff
@@ -36,6 +36,7 @@ EditWidget::EditWidget(QWidget* parent)
     headerLabelFont.setBold(true);
     headerLabelFont.setPointSize(headerLabelFont.pointSize() + 2);
     headlineLabel()->setFont(headerLabelFont);
+    headlineLabel()->setTextFormat(Qt::RichText);
```
Comment (phoerious) [inline src/gui/EditWidget.cpp]: Wrong way round.  Set text format to PlainText and remove HTML escaping in EditEntryWidget.cpp, lines 283-291.

We have more instances where we added HTML escaping (see #236). Thinking about this more, that was the wrong solution, though. Correct solution would be doing the above: use PlainText instead of explicit HTML escaping.
