### PR TITLE
SSH Agent: Fix handling of encrypted RSA keys

### LINKED ISSUE #1560: SSH Agent: Encrypted RSA keys can't be removed from agent
There are major issues with encrypted RSA keys that were thrown in very late in the development cycle.

This is a high priority fix for 2.3.1.

## Expected Behavior

Encrypted RSA keys are completely decrypted before doing any public key operations. This is an oversight as new OpenSSH style keys (ED25519 for default but also RSA, DSA etc.) have public key information available without decryption and it was implemented first.

## Current Behavior

RSA keys are not decrypted when doing public key operations which cause the following bugs:
 - **Removing such key from agent through KeePassXC is not working**
    - Manual removal button does not work
    - Automatic removal does not work, this is a big security issue
 - Fingerprint and public key are invalid before key is manually decrypted
 - Fingerprint is never updated to the correct one after decryption

## Possible Solution

The UI needs some refactoring to do decryption when needed. Removing key from agent needs small refactors to keep the public key data of a decrypted key in memory.

## Workaround for users
1. If you are embedding a key file inside your database you can decrypt it before attaching the file as it provides no added security
2. If you are decrypting an external key on your filesystem you can convert it to the new OpenSSH format with `ssh-keygen -o -p -f id_rsa`, this also improves the encryption of your private key on disk

## Steps to Reproduce (for bugs)

1. Use encrypted non-OpenSSH format RSA key (default ssh-keygen format) with KeePassXC
2. Try adding to agent (works)
3. Try removing from agent (doesn't)
4. Try remove-on-lock feature (doesn't)

### PR DESCRIPTION
**Pull request by hifi**
Fixes #1560

## Description
Multiple UI issues caused by not having public key available have been fixed as well. All old RSA keys are *always* decrypted for display now, there's no manual decrypt option available for such keys.

The changes also handle the edge case that should not happen that such key is loaded but not decrypted.

## How has this been tested?
Tested all kinds of keys in all kinds of situations by hand in the UI and automatic add/removal. Could not find any issues so far.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

File: src/sshagent/OpenSSHKey.cpp [hunk 1]
```diff
@@ -94,6 +94,10 @@ int OpenSSHKey::keyLength() const
 
 const QString OpenSSHKey::fingerprint() const
 {
+    if (m_publicData.isEmpty()) {
+        return "";
```
Comment (phoerious) [inline src/sshagent/OpenSSHKey.cpp]: Does this have to be an empty string or could you also return a null string {}?

File: src/sshagent/OpenSSHKey.cpp [hunk 2]
```diff
@@ -115,6 +119,10 @@ const QString OpenSSHKey::comment() const
 
 const QString OpenSSHKey::publicKey() const
 {
+    if (m_publicData.isEmpty()) {
+        return "";
```
Comment (phoerious) [inline src/sshagent/OpenSSHKey.cpp]: Same here.

**Comment by hifi** [comment]
Changed.

**Comment by hifi** [comment]
Done.

**Comment by phoerious** [comment]
Still out of date.
