### PR TITLE
Fix base domain matching

### LINKED ISSUE #4170: Domain matching not strict enough. xyz.com entry offered for abcxyz.com
## Expected Behavior

Only matching domains and superdomains (if that's the opposite of subdomains) should be offered. If I have an entry for example.com and an entry for otherexample.com, only the entry for otherexample.com should be offered when I visit otherexample.com.

## Current Behavior

If I have an entry for example.com and an entry for otherexample.com, both of these entries are offered when I visit otherexample.com.

## Possible Solution

I'm guessing the matching algorithm is just a bit too permissive. It should maybe check for slash or dot at the start of the match.

## Steps to Reproduce
1. Have password entries for a xyz.com and abcxyz.com
2. Go to abcxyz.com
3. See that KeepassXC offers both of those entries, not just the abcxyz.com one.

## Debug info

KeePassXC - 2.5.2
KeePassXC-Browser - 1.5.4
Operating system: Linux
Browser: Firefox

### PR DESCRIPTION
**Pull request by varjolintu**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

Adds base domain matching when handling URL matches. This prevents invalid matches to appear. In this case, for example an entry with `https://hub.com` would be returned for `https://github.com`.

Fixes #4170.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually. Tests are also updated.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ I have added tests to cover my changes.

### CODE REVIEW

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -1053,7 +1053,7 @@ bool BrowserService::handleURL(const QString& entryUrl, const QString& url, cons
     }
 
     // Filter to match hostname in URL field
-    if (siteQUrl.host().endsWith(entryQUrl.host())) {
+    if (siteQUrl.host().endsWith(entryQUrl.host()) && baseDomain(siteQUrl.host()) == baseDomain(entryQUrl.host())) {
```
Comment (phoerious) [inline src/browser/BrowserService.cpp]: Isn't this somewhat redundant?

Comment (varjolintu) [reply src/browser/BrowserService.cpp]: No. The subdomain matching is currently done with `endsWith` that can cause some extra matches appearing to the results. The baseDomain check ensusures the comparison is really made with the same host address. If you have a better proposition, I'll gladly take it.

Comment (phoerious) [reply src/browser/BrowserService.cpp]: I mean, isn't the endsWith check redundant when you have the stricter baseDomain check in place?

Comment (droidmonkey) [reply src/browser/BrowserService.cpp]: I find this comparison confusing because there is a lot of functions transforming the inputs to it. Needs to be simplified regardless or a comment on how it functions.

Comment (varjolintu) [reply src/browser/BrowserService.cpp]: Thanks for the feedback guys. I'll try to simplify the comparison.

Comment (varjolintu) [reply src/browser/BrowserService.cpp]: I made the baseDomain comparison as a separate if-sentence, so it's a little bit more clear.
