### PR TITLE
Browser: second fix for linked socket path

### LINKED ISSUE #8702: Browser connection is broken
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Commit 69f05d4c26f5afb0feb0892cc71a4a2aaded9518 broke the browser connection

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KPXC and open the database
2. Open a website which requests credentials
3. the credential dialogue doesn't open

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The credential dialogue should open

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.2-snapshot
Build Type: Snapshot
Revision: c5eaee

Qt 5.15.6
Debugging mode is enabled.

Operating system: Debian GNU/Linux bookworm/sid
CPU architecture: x86_64
Kernel: linux 6.0.0-2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Awesome
Windowing System: X11

## Patch

``` diff
commit c30bef7b2d9afa8997e5ebef28cbcfbe2b677e6a (HEAD -> master)
Author: Jörg Sommer <joerg@jo-so.de>
Date:   Sat Oct 29 17:12:33 2022 +0200
 
    Browser: Fix socket cleanup
    
    69f05d4c26f5afb0feb0892cc71a4a2aaded9518 removed the file at the new
    location and not the legacy location.
    
    Remove the duplicate slash in the link destination
    
    ```
    % readlink /run/user/1000/org.keepassxc.KeePassXC.BrowserServer
    /run/user/1000/app/org.keepassxc.KeePassXC//org.keepassxc.KeePassXC.BrowserServer
    ```
 
diff --git a/src/browser/BrowserShared.cpp b/src/browser/BrowserShared.cpp
index f5978274..d6801ce8 100644
--- a/src/browser/BrowserShared.cpp
+++ b/src/browser/BrowserShared.cpp
@@ -38,14 +38,15 @@ namespace BrowserShared
 
         // Put the socket in a dedicated directory.
         // This directory will be easily mountable by sandbox containers.
-        QString subPath = path + "/app/org.keepassxc.KeePassXC/";
+        QString subPath = path + "/app/org.keepassxc.KeePassXC";
         QDir().mkpath(subPath);
 
         QString socketPath = subPath + serverName;
 #ifndef KEEPASSXC_DIST_FLATPAK
-        QFile::remove(socketPath);
+        const auto oldSocketPath = path + serverName;
+        QFile::remove(oldSocketPath);
         // Create a symlink at the legacy location for backwards compatibility.
-        QFile::link(socketPath, path + serverName);
+        QFile::link(socketPath, oldSocketPath);
 #endif
 
         return socketPath;
```

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fix #8702

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Ubuntu with 2.70 upgraded to this commit

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
The only downside is that downgrading to anything less than 2.7.4 will break browser integration again. Maybe it is a good idea to remove this link when KeePassXC closes. @varjolintu thoughts? I am not overly concerned, but maybe adding to the troubleshooting guide for linux to manually delete the socket locations as a troubleshooting step.

File: src/browser/BrowserShared.cpp [hunk 1]
```diff
@@ -38,14 +38,15 @@ namespace BrowserShared
 
         // Put the socket in a dedicated directory.
         // This directory will be easily mountable by sandbox containers.
-        QString subPath = path + "/app/org.keepassxc.KeePassXC/";
+        QString subPath = path + "/app/org.keepassxc.KeePassXC";
```
Comment (phoerious) [inline src/browser/BrowserShared.cpp:41]: Why do we actually prefix the subdirectory path with `/app`?

Comment (droidmonkey) [reply src/browser/BrowserShared.cpp:41]: it's apparently a standard, this came out of a flatpak discussion... hence why flatpak only uses /app/{appid} path. The reason was also for apparmor in general, can allow access to this subdir without exposing the entire run directory and not being specific to keepassxc.

See #8030 for more

Comment (phoerious) [reply src/browser/BrowserShared.cpp:41]: But is the app part of it also a "standard"?

Comment (droidmonkey) [reply src/browser/BrowserShared.cpp:41]: from what I can tell, yes

Comment (phoerious) [reply src/browser/BrowserShared.cpp:41]: The only app subfolder I have in /run/user/1000 is ours and I cannot find anything in the XDG specs.

Comment (droidmonkey) [reply src/browser/BrowserShared.cpp:41]: I'm really unconcerned and don't want to change this again

Comment (phoerious) [reply src/browser/BrowserShared.cpp:41]: It's not very important, it just appears strange to me. I believe the only reason why there is "app" is to avoid clashes with our previous symlink, which is kind of irrelevant.

**Review by phoerious — APPROVED** [review]

**Comment by varjolintu** [comment]
@droidmonkey At least we've made sure the newer versions will work. I'll add a section about deleting the socket to the troubleshooting guide.
