### PR TITLE
Force clear clipboard on Wayland and Fix opening URL's in AppImage

### LINKED ISSUE #4498: Clipboard clearing not working when using Gnome on Wayland unless the window is focussed
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After the timeout for the clipboard clearing has expired, I expect the clipboard to be cleared - regardless of whether or not the KeepassXC window is focussed.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
If you don't have the KeepassXC window focussed when it attempts to clear the clipboard, it fails to do so. It does so without giving a warning, and focussing the window later doesn't clear the clipboard either. Having the window focussed when the timeout ends does clear the clipboard (as expected).

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
I don't know if there's a fix available, as I don't know anything about Wayland really.

If there is no fix available, maybe it's possible to give the user a warning message (or notification) that he has to focus the window to clear the clipboard, and then do so when focus is given to the KeepassXC window?

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install Fedora 31 (Workstation Edition)
2. Login using the default GNOME, which uses Wayland
3. Install KeepassXC using `dnf` (this will give you version 2.5.3)
4. Open a password database
5. Make sure the clear clipboard setting is enabled
6. Copy a password
7. Focus another window
8. Wait for the clear clipboard timeout to pass
9. Paste the password (this shouldn't be possible)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Because clearing the clipboard fails silently, and there is no indicator to show if the timeout has passed yet, there is always a bit of uncertainty if the clipboard is cleared or not. This is not a feeling I like to have around a password manager.

When starting GNOME on X11, the clipboard is cleared properly, hence I think it's a problem with the clearing on Wayland.

`keepassxc-cli clip` does work as expected under Wayland, also without the terminal focussed.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Fedora 31 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.5.10-200.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

### LINKED ISSUE #8721: Cannot open URL's from AppImage
Hello,
since last update (2.7.4), opening url from KeePassXC does not works anymore.
I use Appimage KeePassXC

Debian SID
Firefox 106
KeePassXC-Browser : 1.8.3.1

I made some tests : 
Opening URLs does not work with 2.7.3 and 2.7.4 appimage version
It works fine with the 2.7.1 appimage version

------------------------------------------------------------
Debug Info
KeePassXC - Version 2.7.4
Révision : 63b2394
Distribution : AppImage

Qt 5.15.2
Le mode débogage est désactivé.

Système d’exploitation : Debian GNU/Linux bookworm/sid
Architecture de l’unité centrale : x86_64
Noyau : linux 6.0.0-2-amd64

Extensions activées :
- Saisie automatique
- Intégration aux navigateurs
- Agent SSH
- KeeShare
- YubiKey
- Intégration à « Secret Service »

Bibliothèques cryptographiques :
- Botan 2.19.1
------------------------------------------------------------

Thanks for your help

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #4498
* Fixes #8721

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Welp the attempted AppImage fix _does not work_. Trying to call xdg-open directly didn't work. Trying again with QProcess::execute

File: src/gui/DatabaseWidget.cpp [hunk 1]
```diff
@@ -971,7 +971,11 @@ void DatabaseWidget::openUrlForEntry(Entry* entry)
     } else {
         QUrl url = QUrl::fromUserInput(entry->resolveMultiplePlaceholders(entry->url()));
         if (!url.isEmpty()) {
+#ifdef KEEPASSXC_DIST_APPIMAGE
+            QProcess::execute(QString("xdg-open %1").arg(url.toString(QUrl::FullyEncoded)));
```
Comment (phoerious) [inline src/gui/DatabaseWidget.cpp]:
```suggestion
            QProcess::execute("xdg-open", {url.toString(QUrl::FullyEncoded)});
```

File: src/gui/MainWindow.cpp [hunk 2]
```diff
@@ -1204,7 +1204,11 @@ void MainWindow::showUpdateCheckDialog()
 
 void MainWindow::customOpenUrl(QString url)
 {
+#ifdef KEEPASSXC_DIST_APPIMAGE
+    QProcess::execute(QString("xdg-open %1").arg(url));
```
Comment (phoerious) [inline src/gui/MainWindow.cpp]: Same.

**Review by phoerious — CHANGES_REQUESTED** [review]

**Review by phoerious — APPROVED** [review]
