### PR TITLE
Take delays into account when Auto-Type TOTP values

### LINKED ISSUE #12682: Auto-Type: Stale {TOTP} after {DELAY}
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

When Auto-Typing, if the `{TOTP}` value rolls over during a `{DELAY}` period, then the old `{TOTP}` value is typed instead of the current value.

(Ideally, services wouldn't take so long to load their TOTP entry form or would accept a slightly stale code, but such is life.)

### Steps to Reproduce

1. Create an entry that includes TOTP.
2. Set the Auto-Type sequence to `{DELAY 9000}{TOTP}`.
3. With less than 9 seconds remaining before the TOTP code rolls over, trigger the Auto-Type.

### Expected Versus Actual Behavior

**Expected:** current `{TOTP}` value is typed.
**Actual:** stale `{TOTP}` value from when Auto-Type was first triggered is typed.

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.7.10
Revision: b342be4

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```

### Operating System

Windows

### Linux Desktop Environment

None

### Linux Windowing System

None

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #12682

[NOTE]: # ( Describe your changes in detail. Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
[NOTE]: # ( If you used Generative AI to write the majority of your code, you must state this. )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and include helpful comments. )
Tested manually with short TOTP step and delays in auto-type

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/autotype/AutoType.cpp [hunk 1]
```diff
@@ -632,14 +635,18 @@ AutoType::parseSequence(const QString& entrySequence, const Entry* entry, QStrin
                 error = tr("Very long delay detected, max is %1: %2").arg(maxWaitDelay).arg(fullPlaceholder);
                 return {};
             }
+            cumulativeDelay += repeat;
```
Comment (phoerious) [inline src/autotype/AutoType.cpp:638]: `repeat` isn't really a repetition in this case, is it? This being just the parameter for {DELAY} is quite confusing and cumulativeDelay being additive rather than multiplicative makes it even more so. Maybe add at least a comment that `repeat` does not contain an actual repetition value here.

**Review by phoerious — APPROVED** [review]

File: src/autotype/AutoType.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/autotype/AutoType.cpp:638]: The variable itself is directly from the regex capture. Mostly used for repetition of commands (capture after an equals), but for delay it is used as the delay.

Comment (phoerious) [reply src/autotype/AutoType.cpp:638]: That's what I figured. But it isn't clear from the name and the regex is pretty opaque. It's not a must, but a comment would help clarify things.
