### PR TITLE
Ensure challenge-response key buffer is properly cleared.

### LINKED ISSUE #4041: Removing Hardware Key protection (YubiKey) from database results in "invalid credential" error
Removing Hardware Key protection (YubiKey) from a kdbx database results in "invalid credential" error when opening the database from that point onwards, after saving it. Database can then no longer be opened with or without yubikey present. 

This is the error: 

image

## Expected Behavior
KeePassXC should open the database with only a password, after the Hardware key protection has been removed and the database was saved. It should open without a YubiKey present. 

## Current Behavior
The KeePassXC database can not be opened after entering just the password. No matter if the YubiKey that was used before removing the additional protection is selected and plugged in or not. The error shown above occurs in both cases. The database can no longer be opened. 

## Steps to Reproduce
Create a new KeePassXC database. 
Set a password and also a YubiKey for additional protection. 
Lock the database. 
Unlock with password and YubiKey. 
Go to Database, Change Master Key, and remove the Yubikey protection. 
Save and close. 
Open KeePassXC and open the database again, enter the password. 
The YubiKey is still being populated in the Hardware Key pulldown list. 
KeePass will still prompt to Touch the YubiKey, after touching the YubiKey the above error shows. 

When entering the password and instead setting the pulldown list to "Select ...", thereby deselecting the yubikey, the above error also occurs. 

Now the strangest thing is that when opening a previously saved backup file of the database, that was saved with YubiKey protection still in place, without ever having attempted to remove the Yubikey protection, it can not be opened either, with the YubiKey being detected, but after touching the YubiKey the same error above is shown. 

This also happens when closing KeePassXC inbetween each database opening and closing, no difference. 

## Context
Now, even with the Yubikey being detected, it is not possible to open any database. 

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

### LINKED ISSUE #4146: KDBX 3.1 db gets corrupted after removing yubikey from security
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

The  KDBX3.1 db gets corrupted after adding and removing yubikey to security

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

8. the db can be opened with the password only

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

8. try to open db with password only - fails - INCORRECT

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

convert to kdbx4.0?

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )

1. create an empty db KDBX 3.1 with password protection
2. the db can be opened with the password - correct
3. the db cannot be opened with password + yubikey - correct
4. modify the db security by adding yubikey
5. the db can only be opened with password + yubikey - correct
6. remove yubikey from security options
7. try to open db with password + yubikey - fails - correct
8. try to open db with password only - fails - INCORRECT
9 the db cannot be opened any longer ( you lost your db I suppose)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Same behavior on Ubuntu 18.04.3

### PR DESCRIPTION
**Pull request by phoerious**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

The challenge-response key buffer is explicitly cleared before the key transformation if no such key is configured to ensure one is never injected into the hash even if the database had a challenge-response key previously.

This patch also adds extensive tests for verifying that a key change will not add any expired key material to the hash.

Fixes #4146
Fixes #4041

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
Removing a YubiKey from a KDBX 3.1 database caused the old response to be injected into the new master key. KDBX 4.0 was unaffected due to different CR key handling.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
New tests were added that test various key change scenarios to detect such problems. I verified that removing this fixes triggers a test failure. 

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Looking at the code this looks like an extremely well formed fix. I personally don't like the convoluted nature of how the master key is handled, but there is not much we can do about that for kdbx 3.1.

**Comment by phoerious** [comment]
Not without breaking compatibility, which is why the code is this convoluted in the first place.

File: tests/TestKeePass2Format.cpp [hunk 1]
```diff
@@ -566,6 +568,168 @@ void TestKeePass2Format::testKdbxDeviceFailure()
...
+
+    // only password
+    auto compositeKey2_1 = QSharedPointer<CompositeKey>::create();
+    compositeKey2_1->addKey(passwordKey1);
+    auto compositeKey2_2 = QSharedPointer<CompositeKey>::create();
+    compositeKey2_2->addKey(passwordKey2);
+
+    QTest::newRow("Change:   Password -> Empty Key") << compositeKey2_1 << compositeKey0;
+    QTest::newRow("Change:  Empty Key -> Password") << compositeKey0 << compositeKey2_1;
+    QTest::newRow("Change:   Full Key -> Password 1") << compositeKey1_1 << compositeKey2_1;
```
Comment (droidmonkey) [inline tests/TestKeePass2Format.cpp]: This test is redundant

File: tests/TestKeePass2Format.cpp [hunk 2]
```diff
@@ -566,6 +568,168 @@ void TestKeePass2Format::testKdbxDeviceFailure()
...
+    QTest::newRow("Change:   Full Key -> Password 2") << compositeKey1_1 << compositeKey2_2;
+    QTest::newRow("Change: Password 1 -> Full Key") << compositeKey2_1 << compositeKey1_1;
```
Comment (droidmonkey) [inline tests/TestKeePass2Format.cpp]: This test is redundant

File: tests/TestKeePass2Format.cpp [hunk 3]
```diff
@@ -566,6 +568,168 @@ void TestKeePass2Format::testKdbxDeviceFailure()
...
+
+    // only key file
+    auto compositeKey3_1 = QSharedPointer<CompositeKey>::create();
+    compositeKey3_1->addKey(fileKey1);
+    auto compositeKey3_2 = QSharedPointer<CompositeKey>::create();
+    compositeKey3_2->addKey(fileKey2);
+
+    QTest::newRow("Change:   Key File -> Empty Key") << compositeKey3_1 << compositeKey0;
+    QTest::newRow("Change:  Empty Key -> Key File") << compositeKey0 << compositeKey3_1;
+    QTest::newRow("Change:   Full Key -> Key File 1") << compositeKey1_1 << compositeKey3_1;
```
Comment (droidmonkey) [inline tests/TestKeePass2Format.cpp]: This test is redundant

File: tests/TestKeePass2Format.cpp [hunk 4]
```diff
@@ -566,6 +568,168 @@ void TestKeePass2Format::testKdbxDeviceFailure()
...
+    QTest::newRow("Change:   Full Key -> Key File 2") << compositeKey1_1 << compositeKey3_2;
+    QTest::newRow("Change: Key File 1 -> Full Key") << compositeKey3_1 << compositeKey1_1;
```
Comment (droidmonkey) [inline tests/TestKeePass2Format.cpp]: This test is redundant

File: tests/TestKeePass2Format.cpp [hunk 5]
```diff
@@ -566,6 +568,168 @@ void TestKeePass2Format::testKdbxDeviceFailure()
...
+
+    // only cr key
+    auto compositeKey4_1 = QSharedPointer<CompositeKey>::create();
+    compositeKey4_1->addChallengeResponseKey(crKey1);
+    auto compositeKey4_2 = QSharedPointer<CompositeKey>::create();
+    compositeKey4_2->addChallengeResponseKey(crKey2);
+
+    QTest::newRow("Change:    CR Key -> Empty Key") << compositeKey4_1 << compositeKey0;
+    QTest::newRow("Change: Empty Key -> CR Key") << compositeKey0 << compositeKey4_1;
+    QTest::newRow("Change:  Full Key -> CR Key 1") << compositeKey1_1 << compositeKey4_1;
```
Comment (droidmonkey) [inline tests/TestKeePass2Format.cpp]: This test is redundant

File: tests/TestKeePass2Format.cpp [hunk 6]
```diff
@@ -566,6 +568,168 @@ void TestKeePass2Format::testKdbxDeviceFailure()
...
+    QTest::newRow("Change:  Full Key -> CR Key 2") << compositeKey1_1 << compositeKey4_2;
+    QTest::newRow("Change:  CR Key 1 -> Full Key") << compositeKey4_1 << compositeKey1_1;
```
Comment (droidmonkey) [inline tests/TestKeePass2Format.cpp]: This test is redundant

**Comment by droidmonkey** [comment]
There are some redundant tests going from Full Key to Password 1 and Full Key to Password 2 (for example). Recommend reducing those to one.

**Comment by phoerious** [comment]
Those are testing what happens if you keep only the password and remove the rest, which is pretty much the opposite of the leave-on-out test. Of course, it's redundant in the sense that our code doesn't distinguish between keeping the password part of a composite key (password 1) and setting an entirely new key with only a password (password 2), but I added this just in case anything changes in the future. I want to avoid making any assumptions about implementation details in the tests. Better play dumb and test these things than get bitten by it later.

**Comment by droidmonkey** [comment]
Sounds good to me
