### PR TITLE
Warn user if deleting entries that are referenced.

### LINKED ISSUE #852: User should be warned before deleting entry with a UID that is being REF'd by another object
When the user clones a key and maintains a reference to the original, the key that uses a reference is displayed grayed out with "Ref: " prefixing the field. The original key appears normal, as it did before cloning. If the original key is deleted and moved to the "Recycle Bin" there is no issue and things continue to function. If the original key is deleted from the Recycle Bin the cloned field remains gray but the Ref is broken and the underlying syntax is shown. Any keys that REF'd that key are now useless. I propose that a warning would be useful here to ensure the user is okay with this potentially dangerous choice.

It is understandable to expect user caution to be enough protect from this breakage accidentally, but with a large number of objects, especially when nested in folders, it's not hard to imagine this happening without due diligence on the user's part to prevent it or notice the broken REF before saving the database.

At the very least, perhaps some documentation nudging users towards organizing ref'd objects in a thoughtful manner and preferring to delete ref clones over originals would be useful.

At the same time, it seems an easy thing to scan through the open database for.

## Expected Behavior
I expect that when deleting a file that other files currently REF a field from that a warning be displayed mentioning this fact and providing an opportunity to cancel the deletion in response.

## Current Behavior
The file gets deleted and any REFs silently break.

## Possible Solution
When the above situation occurs, it would be nice to give a chance for automatically redistributing the REF (fill-in the value so they are no longer ref'd, or choose one of them as the new value holder and re-REF any others to that one). This would need to happen for each REF'd field, as there could be multiple. 

## Steps to Reproduce (for bugs)
1. Add a new entry (Ctrl+N) named test with user/pass "123"
2. Clone entry (Ctrl+K) and check "Replace username and password with references" and hit OK
3. Select the original "test" entry and hit Delete entry (Ctrl+D) and hit Yes
4. Notice that "test - Clone"'s Username is still linked by the username showing as "Ref: 123"
5. Click "Recycle Bin" to go there
6. Select the original, now deleted "test" entry and hit Delete entry (Ctrl+D) and hit Yes
7. Click back to original location where steps were started from
8. Notice that "test - Clone"'s Username is broken by the username showing as "Ref: {REF:U@....}"

## Context
I was organizing some keys by Group and noticed that one key fit best in two groups, but duplicating the objects may result in them falling out of sync upon next password rotation. Therefore I felt the Refs feature would be perfect for this use case, but find it hard to determine which group should be the "master" group that the others REF.

While I can see solutions I can implement by care and convention, I want to trust my REF objects to always be up-to-date and in-sync with their REFs without having to concern myself with the very organizational details the REFs seemed meant to save me from.

## Debug Info

KeePassXC - 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 8.1 (6.3)
CPU architecture: x86_64
Kernel: winnt 6.3.9600

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### PR DESCRIPTION
**Pull request by wgml**
## Description
User is warned on deletion of entries referenced by other database entries. No warning is shown if all referencing entries are also being removed.

## Motivation and context

See #852.

## How has this been tested?
Built on top of `develop`, that is `2.3.1` with `gcc 7.3.0` on 64-bit Linux.

Ran tests, of which `testgui` failed. I checked logs for sanitizer output and compared with running same test on `develop` branch. In both cases, summary was:
`SUMMARY: AddressSanitizer: 110049 byte(s) leaked in 2162 allocation(s)`. 

## Types of changes

- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

File: src/core/Database.cpp [hunk 1]
```diff
@@ -199,6 +201,30 @@ Group* Database::findGroupRecursive(const Uuid& uuid, Group* group)
     return nullptr;
 }
 
+namespace {
+    QList<Entry*> resolveReferencesRecursive(const Uuid& uuid, const Group* group)
```
Comment (droidmonkey) [inline src/core/Database.cpp]: This function should be a member of the Database class. Also recommend overloading the Database::resolveReferences function with this one accepting a specific group.

File: src/core/Database.cpp [hunk 2]
```diff
@@ -199,6 +201,30 @@ Group* Database::findGroupRecursive(const Uuid& uuid, Group* group)
...
+    {
+        const QString usernameRef = Tools::usernameReference(uuid).toUpper();
+        const QString passwordRef = Tools::usernameReference(uuid).toUpper();
+        auto isReference = [&usernameRef, &passwordRef](const Entry* e) {
+            return e->username() == usernameRef || e->password() == passwordRef;
+        };
+
+        QList<Entry*> result;
+        std::copy_if(group->entries().begin(), group->entries().end(), std::back_inserter(result), isReference);
```
Comment (droidmonkey) [inline src/core/Database.cpp]: Please don't mix Qt and std. Recommend the following function call:
```auto result = QtConcurrent::blockingFiltered(group->entries(), isReference);```

File: src/core/Database.cpp [hunk 3]
```diff
@@ -199,6 +201,30 @@ Group* Database::findGroupRecursive(const Uuid& uuid, Group* group)
...
+
+        for (Group *child : group->children())
+            result += resolveReferencesRecursive(uuid, child);
```
Comment (droidmonkey) [inline src/core/Database.cpp]: Missing { and }

File: src/gui/DatabaseWidget.cpp [hunk 4]
```diff
@@ -473,26 +472,39 @@ void DatabaseWidget::deleteEntries()
...
     QList<Entry*> selectedEntries;
+    QMap<Entry*, int> referencesMap;
     for (const QModelIndex& index : selected) {
-        selectedEntries.append(m_entryView->entryFromIndex(index));
+        Entry* entry = m_entryView->entryFromIndex(index);
+        selectedEntries.append(entry);
+        QList<Entry*> references = m_db->resolveReferences(entry->uuid());
+        for (auto const& el : selectedEntries)
+            references.removeAll(el);
+        referencesMap.insert(entry, references.size());
```
Comment (droidmonkey) [inline src/gui/DatabaseWidget.cpp]: Instead of using a referencesMap and lumping everything into one message below, you should use this same loop to process the delete function for each selected entry. That way a user can choose to delete or not delete a particular selected entry "in the moment" and not have to cancel the whole operation and deselect a particular one. If there are no entries with references, no message should be shown beyond the "Are you sure you want to delete XX entries?"

File: src/gui/DatabaseWidget.cpp [hunk 5]
```diff
@@ -530,6 +548,19 @@ void DatabaseWidget::deleteEntries()
     }
 }
 
+QString DatabaseWidget::referencesMessage(QMap<Entry*, int> const& referencesMap)
```
Comment (droidmonkey) [inline src/gui/DatabaseWidget.cpp]: This function is unnecessary if you follow my implementation suggestion above.

File: src/gui/DatabaseWidget.cpp [hunk 6]
```diff
@@ -461,6 +461,22 @@ void DatabaseWidget::setupTotp()
     setupTotpDialog->open();
 }
 
+namespace {
+    void replaceReferencesWithValues(const QMap<Entry*, QList<Entry*>>& referencesMap)
```
Comment (droidmonkey) [inline src/gui/DatabaseWidget.cpp]: Add this function to the Database class.

**Comment by droidmonkey** [comment]
Before you go any further please address my comments. This is become more and more complicated.

**Comment by wgml** [comment]
Actually, I have one question - can there possibly be references to all fields of `Entry` in such context, or are we fine with taking care of password and username only?

**Comment by droidmonkey** [comment]
Title, Username, Password, URL, and Notes can be referenced

**Comment by wgml** [comment]
Then, this will get far more complicated that I expected. :expressionless:

File: src/gui/DatabaseWidget.cpp (hunk 4 above)
Comment (wgml) [reply src/gui/DatabaseWidget.cpp]: What should be the options available for references? `Replace`, `Ignore`, `Keep original`, `Cancel`? Depending on selected set of options, flow might get complicated as we will need to track underlying dependencies between every field that might be removed.

Comment (droidmonkey) [reply src/gui/DatabaseWidget.cpp]: Keep it simple: Copy Values, Delete All, Skip

File: src/gui/DatabaseWidget.cpp (hunk 5 above)
Comment (wgml) [reply src/gui/DatabaseWidget.cpp]: Agreed.

File: src/gui/DatabaseWidget.cpp (hunk 4 above)
Comment (wgml) [reply src/gui/DatabaseWidget.cpp]: `Delete all` is far from simple in implementation terms. 
I went with Replace / Ignore / Skip for now. What do you think?

**Comment by wgml** [comment]
I merged with `develop` branch to incorporate recent changes to prompts.
Currently, PR offers options to Replace/Ingore/Skip - implementing `Delete all` might be a bit more complicated and I suggest separating it into new PR.
CI seems to still fail because of
`/opt/qt53/include/QtGui/qopengl.h:110:12: fatal error: 'GL/gl.h' file not found`
but I don't think I am the one responsible.

**Comment by droidmonkey** [comment]
Please rebase on develop now that the code format was performed.

**Comment by wgml** [comment]
Done.

**Comment by droidmonkey** [comment]
Any reason why this was closed?

**Comment by wgml** [comment]
PR seemed to be stalled from my perspective. If it is still a candidate for a merge, feel free to reopen it.

**Comment by droidmonkey** [comment]
For future reference, if it's still open, we still want it.

File: src/core/Entry.cpp [hunk 7]
```diff
@@ -299,11 +300,25 @@ QString Entry::notes() const
...
+}
+
 bool Entry::isExpired() const
 {
     return m_data.timeInfo.expires() && m_data.timeInfo.expiryTime() < QDateTime::currentDateTimeUtc();
 }
 
+bool Entry::isAttributeReferenceOf(const QString& key, const Uuid& uuid) const
+{
+    if (!m_attributes->isReference(key))
```
Comment (TheZ3ro) [inline src/core/Entry.cpp]: codestyle: Add brackets around if

File: src/core/Entry.cpp [hunk 8]
```diff
@@ -315,6 +330,16 @@ bool Entry::hasReferences() const
     return false;
 }
 
+bool Entry::hasReferencesTo(const Uuid& uuid) const
+{
+    const QList<QString> keyList = EntryAttributes::DefaultAttributes;
+    for (const QString& key : keyList) {
+        if (isAttributeReferenceOf(key, uuid))
```
Comment (TheZ3ro) [inline src/core/Entry.cpp]: codestyle: Add brackets around if

File: src/core/Entry.cpp [hunk 9]
```diff
@@ -520,6 +545,16 @@ void Entry::setNotes(const QString& notes)
     m_attributes->set(EntryAttributes::NotesKey, notes, m_attributes->isProtected(EntryAttributes::NotesKey));
 }
 
+void Entry::setDefaultAttribute(const QString& attribute, const QString& value)
+{
+    Q_ASSERT(EntryAttributes::isDefaultAttribute(attribute));
+
+    if (!EntryAttributes::isDefaultAttribute(attribute))
```
Comment (TheZ3ro) [inline src/core/Entry.cpp]: See above

File: src/core/Tools.cpp [hunk 10]
```diff
@@ -346,4 +347,21 @@ namespace Tools
         return bSuccess;
     }
 
+QString reference(const Uuid& uuid, const QString& field)
+{
+    Q_ASSERT(EntryAttributes::DefaultAttributes.count(field) > 0);
+
+    if (field == EntryAttributes::TitleKey)
```
Comment (TheZ3ro) [inline src/core/Tools.cpp]: codestyle: Add brackets around if every if

**Comment by wgml** [comment]
I finally rebased that feature on top of develop. Most of the code was in conflict state by now.
I added missing braces, as @TheZ3ro suggested.

File: src/core/Entry.cpp (hunk 7 above)
Comment (wgml) [reply src/core/Entry.cpp]: done

**Comment by droidmonkey** [comment]
I rebased and made some modifications to streamline. My only concern with this PR is there may be a significant performance hit when deleting entries in large databases. There might be some more optimizations to make before merging.
