### PR TITLE
Fix crash when pressing home key on empty tags field

### LINKED ISSUE #11344: KeePassXC 2.7.9 crashes when pressing `Home`/`End` keyboard keys in the tag field on Linux
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
1. Open any entry (or create a new entry)
2. Focus on the tags field
3. Press <kbd>End</kbd> or <kbd>Home</kbd> keyboard keys
4. The app suddenly closes

## Expected Behavior
Pressing <kbd>Home</kbd> or <kbd>End</kbd> keys in the entry tag field should navigate to the first/last tag of the entry.

(Or, at least the app should not crash whenever those keys are pressed.)

## Actual Behavior
The app crashes.

On CLI, KeePassXC prints out the following error log when <kbd>Home</kbd> or <kbd>End</kbd> keys are pressed:

```
QWidget::setWindowModified: The window title does not contain a '[*]' placeholder
Segmentation fault
```

## Context

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.15
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.10.8-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.5.0

Operating System: ArchLinux
Desktop Env: no desktop environment (only using i3-gaps v4.23-4 tiling manager)
Windowing System: X11

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #11344 

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and include helpful comments. )
Pressing Home no longer produces crashes and all other functionality remains in tact.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/tag/TagsEdit.cpp [hunk 1]
```diff
@@ -338,9 +338,11 @@ struct TagsEdit::Impl
...
             std::count_if(tags.cbegin(), tags.cend(), [this](const auto& tag) { return tag.text == currentText(); });
         if (currentText().isEmpty() || occurrencesOfCurrentText > 1) {
-            tags.erase(std::next(tags.begin(), std::ptrdiff_t(editing_index)));
-            if (editing_index <= i) { // Do we shift positions after `i`?
-                --i;
+            if (tags.size() > 1) {
+                tags.erase(std::next(tags.begin(), std::ptrdiff_t(editing_index)));
+                if (editing_index <= i) { // Do we shift positions after `i`?
+                    --i;
+                }
```
Comment (phoerious) [inline src/gui/tag/TagsEdit.cpp]:
```suggestion
        if (tags.size() > 1 && (currentText().isEmpty() || occurrencesOfCurrentText > 1)) {
            tags.erase(std::next(tags.begin(), std::ptrdiff_t(editing_index)));
            if (editing_index <= i) { // Do we shift positions after `i`?
                --i;
            }
        }
```

Comment (droidmonkey) [reply src/gui/tag/TagsEdit.cpp]: @phoerious done

File: src/gui/tag/TagsEdit.cpp [hunk 2]
```diff
@@ -337,7 +337,7 @@ struct TagsEdit::Impl
         assert(i < tags.size());
         auto occurrencesOfCurrentText =
             std::count_if(tags.cbegin(), tags.cend(), [this](const auto& tag) { return tag.text == currentText(); });
-        if (currentText().isEmpty() || occurrencesOfCurrentText > 1) {
+        if (tags.size() > 1 && (currentText().isEmpty() || occurrencesOfCurrentText > 1)) {
```
Comment (w15eacre) [inline src/gui/tag/TagsEdit.cpp:340]: Suggest that if you change your if expression to:
```
if (occurrencesOfCurrentText > 1 || currentText().isEmpty()) {
...
}
```
It solves the problem because occurrencesOfCurrentText > 1 if and only if tag.size() > 1.

Comment (droidmonkey) [reply src/gui/tag/TagsEdit.cpp:340]: I'd rather be explicit about the requirement

**Review by phoerious — APPROVED** [review]
