### PR TITLE
Fix multiple TOTP issues

### LINKED ISSUE #6838: When creating or editing entry, Setup TOTP reset fields to original state
## Overview
When manually creating a new login with TOTP, on completion of the "setup TOTP" step it wipes other information entered previously.  Note this only happens with a new entry, if adding TOTP to an existing entry it does not happen.

## Steps to Reproduce
1. Start a new login entry
2. Enter title, username, password, URL
3. Click Entries -> TOTP -> Set up TOTP
4. Enter a TOTP code etc.
5. Click OK
6. Title through URL entered previously are wiped.

## Expected Behavior
Set up of TOTP should leave previous entries intact

## Actual Behavior
When the Set up TOTP step is complete and click on Ok (within the TOTP pop-up) the Title through URL entries are wiped

## Context
This only happens with a new entry, so when the Title through URL information is entered just before selecting Set up TOTP.  If Set up TOTP is used with an existing entry this does not occur.

[NOTE]:
KeePassXC - VERSION 2.6.6
Revision: REVISION 9c108b9

[NOTE]:
Operating System: Windows

### LINKED ISSUE #9847: TOTP generation with bare secret in otp property
## Summary
This is a little compatibility issue concerning TOTP handling of different KeePass clients.

## Examples
The attached ZIP contains a KDBX file, which demonstrates different ways of storing TOTP configurations for default RFC 6238 cases. The DB password is `HelloWorld`.

There are two entries with the same TOTP secret `JBSWY3DPEHPK3PXP` stored in the property `otp`.  

The first uses the format from KeePassXC: `otpauth://totp/TOTP%20KeePassXC:none?secret=JBSWY3DPEHPK3PXP&period=30&digits=6&issuer=TOTP%20KeePassXC`  

The second one uses the format from KeeWeb: `JBSWY3DPEHPK3PXP`

In KeeWeb, both entries show identical (correct) TOTP values.

In KeePassXC, the simple format produces a different (wrong) TOTP value. This is exactly the same value that is produced for the third entry, which also has the `otp` property, but with an empty value.

##  Suggested solution
I think there are two things that can be done here:
1. Don't generate TOTP at all if the secret is empty.
2. If the `otp` property doesn't contain a known format (eg. the correct form of `otpauth://` URL), assume the complete property value is the secret to be used with default RFC 6238 parameters.

[TOTPProblem.zip](https://github.com/keepassxreboot/keepassxc/files/12618751/TOTPProblem.zip)

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fix #9847 - don't provide TOTP values if settings are blank or completely wrong
* Fix #6838 - don't reset the ui when creating a new entry and applying TOTP to it
* Move totp source into the core folder

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Added test cases

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/entry/EditEntryWidget.cpp [hunk 1]
```diff
@@ -867,7 +875,7 @@ void EditEntryWidget::loadEntry(Entry* entry,
     m_create = create;
     m_history = history;
 
-    connect(m_entry, &Entry::modified, this, [this] { m_entryModifiedTimer.start(); });
+
```
Comment (phoerious) [inline src/gui/entry/EditEntryWidget.cpp]: Code formatter doesn't approve.

**Review by phoerious — APPROVED** [review]
