### PR TITLE
 Prevent clipboard history and cloud sync on Windows

### LINKED ISSUE #2358: Windows 10 October 2018 update breaks clipboard clearing feature
Microsoft introduced a new clipboard in the October 2018 update for Windows 10. Enabling said clipboard breaks KeePassXC's ability to clear the clipboard after copying something.

## Expected Behavior
Clipboard should be cleared after the period specified in settings.

## Current Behavior
Clipboard is never cleared. This is independent of whether cloud synchronisation of the clipboard is turned on or not.

## Steps to Reproduce (for bugs)
1. Open KeePassXC
2. Unlock the database
3. Copy anything e.g username, password
4. Wait for the period specified in Application Settings > Security > Clear clipboard after
5. Press Win+V, the clipboard still holds the copied text

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### PR DESCRIPTION
**Pull request by droidmonkey**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Fix #2358 

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows 10

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/gui/Clipboard.cpp [hunk 1]
```diff
@@ -59,7 +59,12 @@ void Clipboard::setText(const QString& text, bool clear)
     clipboard->setMimeData(mime, QClipboard::Clipboard);
 #else
     mime->setText(text);
+#ifdef Q_OS_LINUX
     mime->setData("x-kde-passwordManagerHint", QByteArrayLiteral("secret"));
+#endif
+#ifdef Q_OS_WIN
+    mime->setData("ExcludeClipboardContentFromMonitorProcessing", QByteArrayLiteral("1"));
+#endif
```
Comment (phoerious) [inline src/gui/Clipboard.cpp:67]: I would do if, elif, but it's no big deal.

**Review by phoerious — APPROVED** [review]

File: src/gui/Clipboard.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/gui/Clipboard.cpp:67]: Thought about that, I prefer the ifdef versus if defined(...). Personal preference
