### PR TITLE
Passkeys: Do not ask update with a new user handle

### LINKED ISSUE #10404: [Passkeys] Should not ask to update if new user handle
## Overview

In WebAuthn, the user handle (e.g. user.id) identifies the unique user account. An authenticator should only have a single credential per user handle, and can have multiple user handles for the same relying party

## Steps to Reproduce

1. Use WebAuthn.io to create a passkey
2. Accept the prompt in KeePassXC to create it
3. Refresh WebAuthn.io and create a new passkey (this will have a new user handle)
4. KeePassXC will ask you if you want to update the existing passkey

image

## Expected Behavior

1. Use WebAuthn.io to create a passkey
2. Accept the prompt in KeePassXC to create a new passkey
3. Refresh WebAuthn.io and create a new passkey (this will have a new user handle)
4. Accept the prompt in KeePassXC to create a new passkey

## Actual Behavior

When the user handle (user.id) is different, it should be a fresh passkey creation prompt, not an update.

## Context

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.4
CPU architecture: arm64
Kernel: darwin 23.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
When user is creating a new passkey, the KeePassXC's dialog should not ask for update if the user handle is not found.

Fixes #10404

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/browser/BrowserService.cpp [hunk 1]
```diff
@@ -1348,6 +1348,22 @@ QList<Entry*> BrowserService::getPasskeyEntries(const QString& rpId, const Strin
...
 
+// Returns all Passkey entries for the current Relying Party and identical user handle
+QList<Entry*> BrowserService::getPasskeyEntriesWithUserHandle(const QString& rpId,
+                                                              const QString& userId,
+                                                              const StringPairList& keyList)
+{
+    QList<Entry*> entries;
+    for (const auto& entry : searchEntries(rpId, "", keyList, true)) {
+        if (entry->hasPasskey() && entry->attributes()->value(BrowserPasskeys::KPEX_PASSKEY_RELYING_PARTY) == rpId
+            && entry->attributes()->value(BrowserPasskeys::KPEX_PASSKEY_USER_HANDLE) == userId) {
```
Comment (droidmonkey) [inline src/browser/BrowserService.cpp:1359]: Do we want to do a Qt::CaseInsensitive compare instead? May also want to trim the userId of prefix and suffix whitespace. Just thinking of some contingencies based on values users type in.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: src/browser/BrowserService.cpp (hunk 1 above)
Comment (varjolintu) [reply src/browser/BrowserService.cpp:1359]: These are values that users do not add by themselves.

Comment (droidmonkey) [reply src/browser/BrowserService.cpp:1359]: Ok gotcha, can ignore

**Review by droidmonkey — APPROVED** [review]
