### PR TITLE
Fix TOTP Segfault in DetailsWidget #1156

### LINKED ISSUE #1156: Segmentation fault opening database
## Expected Behavior
Open my database.

## Current Behavior
KeePassXC ends in segmentation fault when try to open database.

## Steps to Reproduce (for bugs)

Not very clean, only happens with my database, issue is with some entry.

## Context

With my database KeePassXC always ends in segmentation fault, creating a new database works, i've created a new database with same credentials of my database and then merge the old database with new on, KeePassXC continues to works without issue, but after close and reopen the new database same issue, crash on open database.

## Debug Info

KeePassXC - Versão 2.2.2
Revisão: e100ba8

Bibliotecas:
- Qt 5.9.2
- libgcrypt 1.8.1

Sistema operativo: Arch Linux
Arquitetura do CPU: x86_64
Kernel: linux 4.13.10-1-ck-core2

Extensões ativas:
- KeePassHTTP
- Auto-Type
- YubiKey

## Notes
No other patches applied, compiled only with develop branch.

Tried to do some debug with gdb:
```
[New Thread 0x7f8fa9138700 (LWP 28576)]
[New Thread 0x7f8fa8937700 (LWP 28577)]
[New Thread 0x7f8f9fde2700 (LWP 28762)]
[New Thread 0x7f8f9f5e1700 (LWP 28763)]
[New Thread 0x7f8f9ede0700 (LWP 28764)]
[New Thread 0x7f8f9d7b9700 (LWP 28765)]
[New Thread 0x7f8f9cfb8700 (LWP 28766)]
[New Thread 0x7f8f87fff700 (LWP 28767)]
[Thread 0x7f8f9d7b9700 (LWP 28765) exited]
[Thread 0x7f8f9cfb8700 (LWP 28766) exited]
[Thread 0x7f8f9f5e1700 (LWP 28763) exited]
[Thread 0x7f8f87fff700 (LWP 28767) exited]
[Thread 0x7f8f9fde2700 (LWP 28762) exited]

Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
0x00007f8fd1d02db0 in QTimer::stop() () from /usr/lib/libQt5Core.so.5
```

### PR DESCRIPTION
**Pull request by adolfogc**
## Description
This is a hot fix for #1156.

## Motivation and context
Please see #1156 for specifics of the bug here fixed.

## How has this been tested?
Manually on macOS.

## Screenshots (if appropriate):
N/A.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by adolfogc** [comment]
@TheZ3ro  Please review.

File: src/gui/DetailsWidget.cpp [hunk 1]
```diff
@@ -263,23 +264,21 @@ void DetailsWidget::getSelectedGroup(Group* selectedGroup)
 
 void DetailsWidget::updateTotp()
 {
-    if (m_locked) {
-        m_timer->stop();
-        return;
+    if (!m_locked) {
+        QString totpCode = m_currentEntry->totp();
+        QString firstHalf = totpCode.left(totpCode.size()/2);
```
Comment (louib) [inline src/gui/DetailsWidget.cpp]: @adolfogc can you add spaces around the operators please?

Comment (adolfogc) [reply src/gui/DetailsWidget.cpp]: Sure.

File: src/gui/DetailsWidget.cpp [hunk 2]
```diff
@@ -263,23 +264,21 @@ void DetailsWidget::getSelectedGroup(Group* selectedGroup)
 
 void DetailsWidget::updateTotp()
 {
-    if (m_locked) {
-        m_timer->stop();
```
Comment (louib) [inline src/gui/DetailsWidget.cpp]: @adolfogc so the problem was that the  `m_timer` here was null? Why not just `if (m_locked && m_timer)` instead? I'm just trying to understand why `m_timer` is no longer a member variable.

Comment (adolfogc) [reply src/gui/DetailsWidget.cpp]: @louib The bug is caused by `m_timer` being undefined at first, please note that it isn't initialized to `nullptr` by the constructor. I think the offending code is the following:

```cpp
void DetailsWidget::getSelectedEntry(Entry* selectedEntry) 
// ...
    if (m_currentEntry->hasTotp()) {
        m_ui->totpButton->show();
        updateTotp(); // <-- [BUG]
        // updateTotp/1 gets called before m_timer and m_entry have a valid reference

        m_step = m_currentEntry->totpStep();

        m_timer = new QTimer(this);
        connect(m_timer, SIGNAL(timeout()), this, SLOT(updateTotp()));
        m_timer->start(m_step * 10);
    }
// ...
}
```

At the moment, my reason for removing those lines was that, IMHO, they were doing nothing, since they affected just a single timer instance (the one associated with the last selected entry) of all the possible. If a previous entries were selected, a QTimer instance could still be active. This means there is another bug here. What happens if two entries have TOTP information. We select a first entry that has TOTP information, so a QTimer instance gets created and it will call `updateTotp/1` every time it timeouts.  We then select a second entry with TOTP information and another QTimer instance gets created, it will also call `updateTotp/1` when it timeouts periodically. The bug manifests itself when the timing is such that both instances timeout with an interval greater than 0 seconds between them, i.e., they don't coincide.

This can be fixed by keeping the `m_timer` instance and initializing it to `nullptr`

```cpp
DetailsWidget::DetailsWidget(QWidget* parent)
    : QWidget(parent)
    , m_ui(new Ui::DetailsWidget())
    , m_locked(false)
    , m_timer(nullptr)
    , m_currentEntry(nullptr)
    , m_currentGroup(nullptr)
    , m_attributesWidget(nullptr)
    , m_autotypeWidget(nullptr)
    , m_selectedTabEntry(0)
    , m_selectedTabGroup(0)
{
    // ...
}
```

Applying the following changes:

```cpp
void DetailsWidget::getSelectedEntry(Entry* selectedEntry) 
// ...
    if (m_currentEntry->hasTotp()) {
        m_step = m_currentEntry->totpStep();

        if(nullptr != m_timer) { // a previous timer exists
            m_timer->stop();  
        }

        m_timer = new QTimer(this);
        connect(m_timer, SIGNAL(timeout()), this, SLOT(updateTotp()));
        updateTotp();
        m_timer->start(m_step * 10);
        m_ui->totpButton->show();
    }
// ...
}
```

And also:

```cpp
void DetailsWidget::updateTotp()
{
    if (!m_locked) {
        QString totpCode = m_currentEntry->totp();
        QString firstHalf = totpCode.left(totpCode.size() / 2);
        QString secondHalf = totpCode.right(totpCode.size() / 2);
        m_ui->totpLabel->setText(firstHalf + " " + secondHalf);
    } else {
      if (nullptr != m_timer) { // <-- As per your suggestion
          m_timer->stop(); 
      }
    }
}
```

I'll push a commit with these changes.

**Comment by adolfogc** [comment]
@louib @TheZ3ro  Please review the new changes. I think there are two different bugs.

File: src/gui/DetailsWidget.cpp (hunk 2 above)
Comment (TheZ3ro) [reply src/gui/DetailsWidget.cpp]: At first I was using 1 QTimer for each entry but this was giving me problems since if you have multiple timer acting on the same Widget they where updating the DetailsWidget at different time making it unreliable (as you said), so I switched to 1 timer as member of DetailsWidget but I think I've missed something when testing this

**Comment by TheZ3ro** [comment]
The solution seems good. I need to test it tomorrow

**Comment by adolfogc** [comment]
@TheZ3ro I'll squash the commits into a single one.

File: src/gui/DetailsWidget.cpp [hunk 3]
```diff
@@ -263,23 +267,25 @@ void DetailsWidget::getSelectedGroup(Group* selectedGroup)
...
-        return;
+    if (!m_locked) {
+        QString totpCode = m_currentEntry->totp();
+        QString firstHalf = totpCode.left(totpCode.size() / 2);
+        QString secondHalf = totpCode.right(totpCode.size() / 2);
+        m_ui->totpLabel->setText(firstHalf + " " + secondHalf);
+    } else {
+      if (nullptr != m_timer) {
```
Comment (louib) [inline src/gui/DetailsWidget.cpp]: @adolfogc you can merge the else and the if here

File: src/gui/DetailsWidget.cpp [hunk 4]
```diff
@@ -136,14 +139,16 @@ void DetailsWidget::getSelectedEntry(Entry* selectedEntry)
     }
 
     if (m_currentEntry->hasTotp()) {
-        m_ui->totpButton->show();
-        updateTotp();
-
         m_step = m_currentEntry->totpStep();
 
+        if (nullptr != m_timer) {
+            m_timer->stop();
```
Comment (louib) [inline src/gui/DetailsWidget.cpp]: @adolfogc one last thing: shouldn't we also delete this timer before creating a new one?

Comment (adolfogc) [reply src/gui/DetailsWidget.cpp]: @louib This isn't necessary because its parent will delete it.

Reference:
>QObjects organize themselves in object trees. When you create a QObject with another object as parent, the object will automatically add itself to the parent's children() list. The parent takes ownership of the object; i.e., it will automatically delete its children in its destructor. You can look for an object by name and optionally type using findChild() or findChildren().

Source: http://doc.qt.io/qt-5/qobject.html

Comment (adolfogc) [reply src/gui/DetailsWidget.cpp]: @louib We can let its parent delete it or we could also delete it ourselves at that time to save some memory (given the possible lifetime of its parent). Is that what you meant?

Comment (louib) [reply src/gui/DetailsWidget.cpp]: @adolfogc didn't know about the destruction behaviour of `QObject`! It's your call then.

Comment (adolfogc) [reply src/gui/DetailsWidget.cpp]: @louib I prefer to let QObject take care of it.

Comment (droidmonkey) [reply src/gui/DetailsWidget.cpp]: Actually the m_timer has no parent! When you create it in the constructor you pass nullptr, you should pass "this" to establish the DetailsWidget as its parent.
