### PR TITLE
Fix crash when building history changes, add tags to history compare, fix minizip-ng compiling

### LINKED ISSUE #7603: Crash while editing x-ref entries
## Overview
Editing entries will result into crash. It does works for normal entries but entries with field refs & TOTP will result into crash 

## Steps to Reproduce
Edit entry with field cross-refs & TOTP

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.6
CPU architecture: x86_64
Kernel: darwin 20.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

### PR DESCRIPTION
**Pull request by droidmonkey**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
**Fix crash when building history changes**
* Replace rarely hit asserts with defined nullptr checks when replacing references without a group
* Fix #7603
* Replace TOTP history comparison with checking the actual TOTP output instead of a compiled string

**Add tags to history comparison**

**Fix compiling with minizip-ng**

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested minizip fixes on Fedora

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: src/keeshare/ShareExport.cpp [hunk 1]
```diff
@@ -29,6 +29,13 @@
 #include <botan/pubkey.h>
 #include <zip.h>
 
+// Compatibility with minizip-ng
+#ifdef MZ_VERSION_BUILD
+#undef Z_BEST_COMPRESSION
+#define Z_BEST_COMPRESSION MZ_COMPRESS_LEVEL_BEST
+#define zipOpenNewFileInZip64 zipOpenNewFileInZip_64
+#endif
+
```
Comment (phoerious) [inline src/keeshare/ShareExport.cpp]: In addition to redefining symbols, I think you should also change the include path to not obscure the `minizip/` prefix. Most of the headers have very generic names and some also exist in zlib iirc. Not including the directory name is asking for things to break sooner or later (and apparently, they are still broken on some systems).

**Review by phoerious — CHANGES_REQUESTED** [review]

File: src/keeshare/ShareExport.cpp (hunk 1 above)
Comment (droidmonkey) [reply src/keeshare/ShareExport.cpp]: Agreed will include that

Comment (droidmonkey) [reply src/keeshare/ShareExport.cpp]: Change has been made

**Review by phoerious — APPROVED** [review]
